src/io/flutter/logging/FlutterLogColors.java
src/io/flutter/logging/FlutterLogTree.java

Colors up for discussion and more presets to come.
FWIW, I tried right-align and it looked more odd to my eye:
Some spacing could maybe help?  Dunno.

color log categories

---

src/io/flutter/logging/FlutterLogTree.java

filter on level in filter text field

---

src/io/flutter/logging/FlutterLogTree.java

Follow-up from: https://github.com/flutter/flutter-intellij/pull/2687.

right align log categories

---

flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterProjectModel.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.form
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
src/io/flutter/module/settings/FlutterCreateParams.java
tool/plugin/compile.xml

Fixes #2099 
Reuses FlutterCreateParams from the IntelliJ wizard.

 Add checkbox for creating projects and modules offline

---

src/io/flutter/logging/FlutterLogTree.java

filter tree cleanup

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Only do Gradle sync for Flutter projects

---

flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
src/io/flutter/pub/PubRoot.java

Fixes #2701
Make module recognition more flexible in anticipation of removing the module template.

Fix 2701 and prepare for module removal

---

src/io/flutter/logging/FlutterLogTree.java

add simple key navigation to the logging view

---

src/io/flutter/inspector/FPSDisplay.java
src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/inspector/TreeScrollAnimator.java
src/io/flutter/inspector/WidgetPerfPanel.java
src/io/flutter/view/InspectorPerfTab.java

- fix a layout issue in the perf tab of the inspector - items could get too short when we run out of vertical space (cvt from use of a GridBagLayout to a VerticalLayout)
- address a few misc IntelliJ inspections
@jacob314

layout fixes to the perf tab

---

src/io/flutter/logging/FlutterLogEntry.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java

process and present log data

---

src/io/flutter/logging/FlutterLogView.java
src/io/flutter/utils/UIUtils.java
src/io/flutter/view/FlutterView.java

* fixed up some code duplication
* some language migrations
* added missing annotations
/cc @jacob314 @terrylucas

de-duping; language migrations

---

src/io/flutter/logging/FlutterLogPreferences.java
src/io/flutter/logging/FlutterLogView.java

Log pane splitter proportion persistence.

---

src/io/flutter/logging/FlutterLog.java

update channel enabled message

---

src/io/flutter/preview/DartElementPresentationUtil.java

- support mixins in the flutter outline view 
- partially address https://github.com/dart-lang/sdk/issues/34958
@scheglov

support mixins in the flutter outline view

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/DiagnosticsPathNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorSourceLocation.java

Read a few more fields to DiagnosticsNode json and wire up parent nodes

---

src/io/flutter/view/FlutterView.java

I'm working on some refactorings; these are some (very low priority) diffs to FlutterView.
@jacob314

misc changes in FlutterView.java

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

- change preference text to agree with the other settings
@stevemessick

change preference text to agree with the other settings

---

src/io/flutter/run/SdkFields.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java

@DanTup I think you are doing something similar for VSCode.

Turn on TrackWidgetCreation when the Flutter version is new enough.

---

AUTHORS

reference here. https://github.com/flutter/flutter-intellij/issues/2770

Add author. ChangJoo Park

---

src/io/flutter/view/FlutterView.java

Automatically fill in version numbers for Flutter Sdk, Flutter plugin, and IDE in the inspector feedback survey.
Issue: https://github.com/flutter/flutter-intellij/issues/1915

Auto populate version numbers in inspector feedback survey

---

third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/ObjRefConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/ScriptListConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/ScriptList.java

- rev the service protocol library to the latest spec
@terrylucas, this includes the lib that exposes `isolate.getInstances()` (I think you're currently calling this via a raw `invoke` call).

rev the service protocol library

---

src/io/flutter/view/FlutterView.java

overflow action button makeover

---

src/io/flutter/preview/PreviewView.java

Fixes https://github.com/flutter/flutter-intellij/issues/2423

Add 'Extract Widget' action to the context menu in 'Flutter Outline'.

---

src/io/flutter/run/FlutterDebugProcess.java

Related to: #2777 .
/cc @jacob314

moves observatory run actions into an overflow menu

---

CONTRIBUTING.md

Add additional instructions regarding when and how to open the project structure dialog.

Add instructions regarding the Project Structure dialog to CONTRIBUTING

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/actions/FlutterMakeHostAppEditableAction.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java

Adds new command: flutter make-host-app-editable
Fixes #2661 
@devoncarew

flutter make-host-app-editable

---

flutter-studio/src/io/flutter/profiler/FlutterStageView.java
flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
flutter-studio/src/io/flutter/profiler/FlutterStudioProfilersView.java

Updated so controls have the IntelliJ look and feel (fonts, etc.)

Updated to use IntelliJ derived UI controls.

---

src/io/flutter/FlutterConstants.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/preview/RenderHelper.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/FlutterApp.java
testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java

Fixes: #2682.
/cc @DanTup @devoncarew

Add reload reason analytics

---

src/io/flutter/FlutterConstants.java
src/io/flutter/preview/RenderHelper.java

Follow-up from https://github.com/flutter/flutter-intellij/pull/2812#issuecomment-438714341.
/cc @DanTup @devoncarew

update render reload analytics reason to “tool”

---

src/io/flutter/FlutterConstants.java

(used to validate project names)
/cc @scheglov @bwilkerson

update Dart keyword tokens

---

.idea/modules.xml
flutter-intellij.iml
src/io/flutter/settings/FlutterSettings.java

- update the pref. settings we track to include all current settings
@pq

track newer preference settings

---

.travis.yml
product-matrix.json
tool/plugin/test/plugin_test.dart

- build for 182.4323.46
- fix https://github.com/flutter/flutter-intellij/issues/2833
@stevemessick - this introduces another (IntelliJ specific) build

build for 182.4323.46

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

- tweak flutter attach action title (Keerti and I had some trouble finding it in the IntelliJ action dialog - we were looking for 'Flutter Attach')
- also contribute the action to the 'Run' top level menu

tweak flutter attach action title

---

CONTRIBUTING.md

add a contributors badge

---

src/io/flutter/inspector/FrameRenderingDisplay.java
src/io/flutter/inspector/WidgetPerfTipsPanel.java
src/io/flutter/perf/EditorPerfDecorations.java
src/io/flutter/perf/Icons.java
src/io/flutter/view/BoolServiceExtensionCheckbox.java
src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/InspectorPerfTab.java
src/io/flutter/view/WidgetPerfSummaryView.java
src/io/flutter/view/WidgetPerfTable.java

Use yellow icons.
Perf Panel tweaks around being clever about tweaking the layout depending on the aspect ratio and size.
Att a table

Add table showing performance tips and polish ui.

---

flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
flutter-studio/src/io/flutter/profiler/FlutterStudioProfilersView.java
flutter-studio/src/io/flutter/profiler/Memory.java

Added Accumulated Instances to detect memory leaks hooked to Reset.
Fixed hover background color and selection indicator (background color and bold font) in classes table.

Expose more information to help detect of memory leaks.

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

This turned out to be easier than I thought.
You can now navigate around in the inspector when paused at a breakpoint and the toolbar buttons now work reasonably when paused at a breakpoint.
Make calls on the Daemon protocol more robust. Previously Daemon protocol
requests would time out when paused at a breakpoint resulting in out
of sync UI. Added logic to wait to send Daemon requests until the debugger
is resumed which stops the requests from timing out.
Fixes https://github.com/flutter/flutter-intellij/issues/2706

Make the inspector work while the debugger is paused by switching to the

---

CHANGELOG.md
resources/META-INF/plugin.xml

I condensed #2769 to focus on user-visible changes. Happy to add more. We did quite a lot of user-visible work this cycle and I want to make sure everything is mentioned. (But I'm happy to use 'bug fixes' as a catch-all for crashes.)
@devoncarew @pq @jacob314 @terrylucas @kenzieschmoll 
Did I include all the contributors for this release?

Update change log for M31

---

src/io/flutter/view/FlutterView.java

- some additional code to try and remove the 'no running applications' empty content message from the Inspector
@jacob314 @pq @stevemessick

remove the empty content message

---

docs/testing.md

Instructions were out of order

---

.travis.yml
.travis_template.yml
tool/travis.sh

move url checking to its own bot

---

src/io/flutter/perf/EditorPerfDecorations.java
src/io/flutter/perf/PerfMetric.java
src/io/flutter/perf/PerfTipRule.java
src/io/flutter/perf/SlidingWindowStats.java
src/io/flutter/view/WidgetPerfTable.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

Addresses https://github.com/flutter/flutter-intellij/issues/2889

Rebuild stats wording tweaks.

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/perf/PerfTipRule.java
src/io/flutter/perf/WidgetPerfLinter.java

- minor change to how we populate perf urls; this will allow the IntelliJ 'unused property file entry' lint help us notice when we are / aren't using url entries
@jacob314

tweak to the perf urls

---

CHANGELOG.md
resources/META-INF/plugin.xml

Release 31.1

---

flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java
flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
tool/plugin/lib/plugin.dart

Show legend with proper line chart color or line style.
Legend displays the RSS value exposed under a flag (consider option to enable RSS stats).
Legend insert to not intersect with right side axis name.
Fix for Travis, AS 3.2 build.

Display legend again with line chart color/line style and last value.

---

src/io/flutter/sdk/FlutterCommand.java

- when running the `flutter doctor` command, use the `-v` flag

add verbose to flutter doctor

---

README.md

add proxy workaround notes

---

CHANGELOG.md
resources/META-INF/plugin.xml

Update change log with latest work for M31.2.
@devoncarew @pq @jacob314 @terrylucas @kenzieschmoll

Release 31.2

---

.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml

Commits project-level code style configuration (previously git ignored).
These should be the IDEA defaults.  I'm not attached to any details besides the fact that we converge on some agreement to avoid future churn.
Fixes #2922.
/cc @devoncarew @stevemessick @jacob314

commit project code style config

---

src/io/flutter/perf/FlutterWidgetPerfManager.java

- address an NPE in FlutterWidgetPerfManager.java
- fix https://github.com/flutter/flutter-intellij/issues/2961

address an NPE in FlutterWidgetPerfManager.java

---

README.md

update IDE versions

---

src/io/flutter/run/daemon/DaemonApi.java

- when an app terminates and there are pending commands, no longer complete them with exceptions
- fix https://github.com/flutter/flutter-intellij/issues/3049

don't use completeExceptionally

---

src/io/flutter/logging/FlutterLogPreferences.java
src/io/flutter/logging/FlutterLogView.java

Hides details pane when there is no associated data.
Fixes: #2947 

auto-hide details pane

---

src/io/flutter/module/settings/ProjectType.java
src/io/flutter/samples/FlutterSample.java
src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/index.json

Updates to latest index format.
* adds `sourceLocation`
* updates display label
Follow-up to add a popup with description details tracked in https://github.com/flutter/flutter-intellij/issues/3088.

update sample json format

---

src/io/flutter/server/vmService/ServiceExtensions.java

Bug fix- Enabled/Disabled text values were swapped for two extensions.

Fix enabled/disabled text for service extensions.

---

README.md

add proxy issue link

---

src/io/flutter/run/common/CommonTestConfigUtils.java

- don't use a groovy import (this doesn't compile well against Android Studio)
@stevemessick @DaveShuckerow

don't use a groovy import

---

src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
src/io/flutter/sdk/FlutterSdk.java

fix sample project creation

---

docs/testing.md

Minor change to the test script that brings its instructions in line with recent changes.

Make script match new behavior

---

docs/testing.md

Change button name in script

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/tree/AbstractEntryCellRender.java
src/io/flutter/logging/tree/CategoryCellRenderer.java

Fixes category cell rendering for light and darcula themes. 
* fixed background color
* fixed reload border rendering
/cc @stevemessick @jacob314

fix category cell rendering

---

src/io/flutter/logging/FlutterLogEntry.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/logging/tree/DataPanel.java

See: https://github.com/flutter/flutter-intellij/issues/3139.
/cc @jacob314 @stevemessick

link support for log data entries

---

src/io/flutter/run/bazelTest/BazelTestRunner.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

Bazel package roots start with :// not : .

Correct the bazel output for debugging bazel tests.

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

- mention 'Dart' in the plugin description
- fix https://github.com/flutter/flutter-intellij/issues/3149
@stevemessick

mention 'Dart' in the plugin description

---

src/io/flutter/actions/OpenEmulatorAction.java
src/io/flutter/actions/OpenInAndroidStudioAction.java
src/io/flutter/actions/OpenSimulatorAction.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/actions/RunProfileFlutterApp.java
src/io/flutter/actions/RunReleaseFlutterApp.java
src/io/flutter/perf/EditorPerfDecorations.java
src/io/flutter/run/FlutterPopFrameAction.java
src/io/flutter/run/OpenObservatoryAction.java
src/io/flutter/run/OpenTimelineViewAction.java
src/io/flutter/run/common/TestType.java
src/io/flutter/run/test/FlutterTestLineMarkerContributor.java
src/io/flutter/run/test/TestFields.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/utils/AnimatedIcon.java
src/io/flutter/view/FlutterViewMessages.java
src/io/flutter/view/HighlightedTable.java
src/io/flutter/view/OpenFlutterViewAction.java
testSrc/unit/io/flutter/run/bazel/BazelFieldsTest.java
testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestFieldsTest.java
testSrc/unit/io/flutter/testing/Testing.java

misc imports cleanup

---

src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/index.json

* looks for remote before falling back to local cache
* updates local cache to be consistent w/ current stable
/cc @stevemessick @DanTup

read samples from remote / update local cache

---

product-matrix.json

Fixed a version problem that prevented the plugin from loading into the canary build.
I can just TBR this one.

Fix version incompatibility

---

tool/plugin/lib/plugin.dart

Fix the Gradle sync error in AS 3.3.1
Fixes #3203

Fix Gradle sync error for 3.3.1

---

CHANGELOG.md
resources/META-INF/plugin.xml

Release 33.1

---

CHANGELOG.md
resources/META-INF/plugin.xml
resources/META-INF/pluginIcon.svg

Release 33

---

flutter-gui-tests/flutter-gui-tests.iml

Define a new module for GUI tests to run in IntelliJ (not Android Studio).

GUI tests module

---

src/io/flutter/samples/FlutterSampleManager.java

Unblocks: #3243. 
Fixes: #3237.

inline sample index reading

---

src/io/flutter/logging/tree/MessageCellRenderer.java
src/io/flutter/run/SdkRunConfig.java

* removed unused import
* suppressed warning (I've got a TODO already)

minor cleanup

---

src/io/flutter/logging/FlutterLogView.java

`AllIcons.General.Gear` is deprecated and slated for removal.

migrate to GearPlain

---

src/io/flutter/bazel/PluginConfig.java

- address a file handle leak
- fix https://github.com/flutter/flutter-intellij/issues/3263
@DaveShuckerow

address a file handle leak

---

src/io/flutter/bazel/PluginConfig.java

- add a comment to a recent change
@lambdabaa

add a comment to a recent change

---

src/io/flutter/editor/FlutterSaveActionsManager.java

This class was incorrectly referenced as FlutterFormatManager

Update a comment in FlutterSaveActionsManager

---

src/io/flutter/FlutterUtils.java

New method in FlutterUtils: this method checks for "dependencies: flutter_web" in a pubspec file.

New method in FlutterUtils: declaresFlutterWeb()

---

src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
src/io/flutter/run/bazelTest/BazelTestConfig.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.form
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestFieldsTest.java
testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java

This will make it possible to use new g3 features that @gamebox is working on.
Screenshot: ![Screenshot from 2019-03-18 16-02-54](https://user-images.githubusercontent.com/14947366/54569301-86aec200-4997-11e9-8de9-27f579394e13.png)

Add an additional args field to the bazel test run configuration

---

src/io/flutter/logging/FlutterLogTree.java

* restores tree path selection preservation
* adds reveal logic to programmatically selected nodes (used for error nodes)
/cc @stevemessick @jacob314

log tree path selection fixes

---

.gitignore
flutter-gui-tests/testSrc/io/flutter/tests/gui/InspectorTest.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/ProjectCreator.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/TestSuite.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterMessagesToolWindowFixture.kt

Launches a Flutter app in a GUI test.
Includes more deterministic pub sync, via pubspec.yaml editor.

Launch Flutter app in test

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/server/vmService/VMServiceManager.java

Here is the matching change for devtools:
https://github.com/flutter/devtools/commit/c458df0dd6254b0e89f86777479ac7da33dda713

Support package:flutter_web as well as package:flutter libraries.

---

.travis.yml
flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

The AS GUI test framework is in flux. I disabled that source (`testSrc`) directory; there's no way to make it compile right now.

Update build for M34

---

src/io/flutter/perf/DocumentFileLocationMapper.java

This fixes https://github.com/flutter/flutter-intellij/issues/2883

Fix widget names.

---

src/io/flutter/server/vmService/frame/DartVmServiceEvaluator.java

Matches https://github.com/JetBrains/intellij-plugins/commit/ce51ac028ff97ae0191b476e4d9a7bdecd629ca0
This fixes https://github.com/flutter/flutter-intellij/issues/2538

Fix NPE issue sometimes hit evaluating expressions.

---

src/io/flutter/server/vmService/frame/DartVmServiceValue.java

This is a similar piece of effort as [this one](https://github.com/JetBrains/intellij-plugins/pull/642) to IntelliJ Dart plugin.

Provides a better display if the variable has a `toStringDeep()` method defined.

---

CHANGELOG.md
resources/META-INF/plugin.xml

update changelog for M34

---

src/io/flutter/module/settings/ProjectType.java

- fix an npe when sample content generation is disabled
- fixes https://github.com/flutter/flutter-intellij/issues/3335

fix an npe when sample content generation is disabled

---

flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java
src/io/flutter/inspector/HeapState.java

- fix a series of NumberFormatExceptions
```
[io.flutter/java.lang.NumberFormatException] For input string: "-1,734"
```
@jacob314 @terrylucas 
(and thanks @lambdabaa - there were caught by our exception logging)

address a number of format exceptions

---

flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java

- address an array index out of bounds
```
[io.flutter/java.lang.ArrayIndexOutOfBoundsException] -1
```

address an array index out of bounds

---

src/io/flutter/view/InspectorPanel.java

Make the inspector easier to test

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/project/FlutterProjectModel.java
flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
tool/plugin/lib/plugin.dart

Update build for canary 11

---

testSrc/unit/io/flutter/inspector/FlutterWidgetTest.java

@jacob314 
Change constructor to resolve NPE.

Make FlutterWidgetTest run

---

testSrc/unit/io/flutter/dart/DartSyntaxTest.java

Fix DartSyntaxTest

---

testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java

@DaveShuckerow (not yours, I know)

Fix DaemonEventTest

---

testSrc/unit/io/flutter/utils/FileWatchTest.java

Fix FileWatchTest

---

src/io/flutter/dart/FlutterDartAnalysisServer.java

This fixes an issue where the outline view can temporarily show stale information after restarting the analyzer.

Update subscriptions after analysis server restart.

---

src/io/flutter/samples/FlutterSampleManager.java

remove unneeded logging

---

CHANGELOG.md
resources/META-INF/plugin.xml

@devoncarew @pq @kenzieschmoll @terrylucas @jacob314 @DaveShuckerow

M35 change log

---

.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

Build for canary 12

---

flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
src/io/flutter/module/settings/ProjectType.java

@pq 
Had to change sample management slightly to work with the Android Studio new project wizard. Shouldn't be too disruptive.
I noticed an empty sample list sometimes, probably due to slow network.

Update samples in AS NPW

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Relax project structure assumption in one place. There may be others that will need to be fixed as discovered.
Fixes #3412

Check android dir existence

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterPerfView.java

- remove the option to disable the memory view from the settings
@terrylucas

remove the option to disable the memory view from the settings

---

src/io/flutter/settings/FlutterSettings.java

- remove older code related to preview-dart-2

remove older code related to preview-dart-2

---

src/io/flutter/preview/DartElementPresentationUtil.java

- use a constant from the dart plugin (now that we depend on a recent enough version)

use a constant from the dart plugin

---

docs/testing.md

Fix typo in test script

---

testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java

Update test to match outupt

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogEntryParser.java

- support both the Logging and _Logging event
- fix https://github.com/flutter/flutter-intellij/issues/3419

support both the Logging and _Logging event

---

src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

This was part of the IDE's 'open source' service protocol extension.
Note, we should revise the implementation of `VmOpenSourceLocationListener` so that is doesn't create an independent connection to the VM.

remove an old DartVmServiceDebugProcess.java todo

---

flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java

Track API changes

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- remove the legacy track widget creation setting
@jacob314

remove the legacy track widget creation setting

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterUtils.java
src/io/flutter/actions/InstallSdkAction.java
src/io/flutter/module/settings/ProjectType.java
src/io/flutter/preview/PreviewArea.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/common/TestLineMarkerContributor.java

- update older todos
- fix imports
- some cleanup to `FlutterBundle.properties `

update older todos

---

CHANGELOG.md
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart

Preserving changes made in release_35.1.

Change log from 35.1 & plugin tool mod

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/FlutterMessages.java
src/io/flutter/analytics/Analytics.java
src/io/flutter/run/FlutterRunNotifications.java
src/io/flutter/survey/FlutterSurveyNotifications.java

Fixes: #3444.
/cc @DanTup @stevemessick @devoncarew

Q2 survey notifcation

---

src/io/flutter/editor/OutlineLocation.java
src/io/flutter/editor/WidgetIndentGuideDescriptor.java
src/io/flutter/editor/WidgetIndentsHighlightingPass.java
src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java

Fix synchronization bug.
Fix bug for outlines past end of line.
Fix bug for edits that lead to range markers coming to bad conclusions.

Fix two bugs for widget guide outlines.

---

src/io/flutter/FlutterErrorReportSubmitter.java

- fix an npe from the FlutterErrorReportSubmitter.java class
- fix https://github.com/flutter/flutter-intellij/issues/3464
In AS 3.5, the `OpenFileDescriptor.navigate` method doesn't like the use of the default project (`ProjectManager.getInstance().getDefaultProject()`) if we don't have a real project. When trying to report one exception, it instead throws another exception. We address this currently by at least not throwing the 2nd exception.

fix an npe from the FlutterErrorReportSubmitter.java class

---

src/io/flutter/editor/WidgetIndentsHighlightingPass.java

- remove a System.out.println in WidgetIndentsHighlightingPass.java

remove a println in WidgetIndentsHighlightingPass.java

---

src/io/flutter/run/daemon/DeviceDaemon.java

- mark the device daemon process as a background process
This address a log message in the IntelliJ log, which complains about background processes that haven't written to stdout in a while.

mark the device daemon process as a background process

---

.gitignore
.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

New:
- Android Studio: 3.4.1, 3.5 beta 3, 3.6 canary 1
- IntelliJ: 2019.1.3, 2019.2 eap
Continuing:
- IntelliJ: 2018.3, 2019.1.2

Update for new platform releases

---

CHANGELOG.md
resources/META-INF/plugin.xml

@pq @devoncarew @jacob314 @DaveShuckerow

Update change log for M36

---

tool/plugin/lib/plugin.dart

- tweak to the plugin.dart script (`FileSystemEntity.isDirectorySync` is slightly more idiomatic)
@stevemessick

tweak to the plugin.dart script

---

src/io/flutter/samples/FlutterSampleManager.java

Sample Manager fixes.
* avoids calling flutter_tools multiple times
* adds a process timeout
Fixes: #3496.

Sample Manager fixes.

---

src/io/flutter/samples/FlutterSampleManager.java

query on a backgroundable task

---

product-matrix.json
tool/plugin/lib/plugin.dart

Update for canary 2

---

src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/sdk/FlutterSdk.java

Fixes for re-runs of backgrounded tasks.
Manager-sharing.
Follow-ups for next milestone tracked: https://github.com/flutter/flutter-intellij/issues/3541.

moar sample manager fixes

---

src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

Revert change to focus project in debugger

---

src/io/flutter/samples/FlutterSampleManager.java

task run synchronization

---

flutter-intellij-community.iml
src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/utils/FlutterModuleUtils.java
src/io/flutter/view/InspectorColoredTreeCellRenderer.java

Compile with Java 11

---

flutter-intellij-community.iml

Need some module deps to compile the latest code for bazel.
@DaveShuckerow

Fix build errors

---

flutter-gui-tests/build.gradle
flutter-gui-tests/testSrc/io/flutter/tests/gui/TestSuite.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterInspectorFixture.kt

 Make integration tests runable

---

product-matrix.json
resources/META-INF/plugin.xml

This makes the plugin compatible with the g3 version of Android Studio

Revise Android Studio version down 

---

tool/plugin/lib/plugin.dart

- update the plugin tool to run tests via `./gradlew test`
@stevemessick

update the plugin tool to run tests via gradle

---

.travis.yml
.travis_template.yml

switch to open jdk

---

build.gradle

Disable flakey tests

---

build.gradle

Tests are too flakey to rely on

---

.travis.yml
.travis_template.yml

- disable xvfb to see if that fixes our bots

disable xvfb to see if that fixes our bots

---

src/io/flutter/editor/OutlineLocation.java

- fix an offset issue with the UI guides code (we could get startOffsets that were greater than endOffsets)
- fix https://github.com/flutter/flutter-intellij/issues/3572
@jacob314 
I'm less familiar with this code; this fix will avoid the error, but I don't know if we should back the fix up to the calling code.

fix an offset issue with the UI guides code

---

src/io/flutter/console/FlutterConsoleFilter.java
testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java

Fixes #3278 by making the file-URL of a test file linkable in the test result console.

Fix links for test URLs

---

flutter-gui-tests/build.gradle
flutter-gui-tests/testSrc/io/flutter/tests/gui/PerfTest.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/ProjectCreator.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/TestSuite.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterInspectorFixture.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterMessagesToolWindowFixture.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterPerfFixture.kt

@terrylucas @jacob314 
Put the performance view to work.
```bash
cd flutter-gui-tests
./gradlew -Dtest.single=TestSuite --info clean test
```

Performance view test

---

flutter-intellij-community.iml
testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java

The final check was failing. And the libraries needed to be added to the other *.iml file.

Fix devtool test

---

src/io/flutter/perf/FlutterWidgetPerfManager.java
src/io/flutter/run/daemon/FlutterApp.java

Check for null vm service manager

---

src/io/flutter/logging/FlutterLogEntryParser.java

- remove a todo in the logging code

remove a todo in the logging code

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

- adjust the text for the desktop/web device preference
@DanTup @jonahwilliams

adjust the text for the desktop/web device preference

---

product-matrix.json

@devoncarew @pq @DaveShuckerow

Adjust build for M37

---

flutter-intellij-community.iml
src/io/flutter/inspections/FlutterDependencyInspection.java
src/io/flutter/inspector/TreeScrollAnimator.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/perf/PerfTipRule.java
src/io/flutter/perf/ScriptManager.java
src/io/flutter/perf/WidgetPerfLinter.java
src/io/flutter/run/ObservatoryFile.java
src/io/flutter/run/PositionMapper.java
src/io/flutter/test/DartTestEventsConverterZ.java
src/io/flutter/view/MultiIconSimpleColoredComponent.java
src/io/flutter/view/WidgetPerfTable.java
src/io/flutter/vmService/DartVmServiceBreakpointHandler.java
src/io/flutter/vmService/DartVmServiceDebugProcess.java
src/io/flutter/vmService/IsolatesInfo.java
src/io/flutter/vmService/VMServiceManager.java
src/io/flutter/vmService/frame/DartVmServiceEvaluator.java
tool/plugin/lib/lint.dart

Less dependencies = healthier code.

Remove netty and gnu.trove imports

---

src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/vmService/frame/DartVmServiceValue.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/TimestampConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Instance.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceRef.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Timestamp.java

- rev the vm service protocol lib (done in the first commit)
- use the new InstanceRef.isNull() method; remove a todo

 use the new InstanceRef.isNull() method

---

src/io/flutter/console/FlutterConsoleFilter.java
testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java

- remove no longer used functionality related to restart warnings

remove no longer used functionality related to restart warnings

---

src/io/flutter/view/MultiIconSimpleColoredComponent.java

- use `TIntIntHashMap` in MultiIconSimpleColoredComponent.java
@DaveShuckerow

use TIntIntHashMap in MultiIconSimpleColoredComponent.java

---

src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/logging/FlutterErrorHelper.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/tree/CategoryCellRenderer.java
testSrc/unit/io/flutter/logging/FlutterErrorHelperTest.java

- send flutter.error analytics
- create and normalize an error code based on he Flutter.Error summary text
- some unrelated formatting in the logging package

send flutter.error analytics

---

src/io/flutter/editor/FliteredIndentsHighlightingPass.java
src/io/flutter/editor/OutlineLocation.java
src/io/flutter/editor/WidgetIndentGuideDescriptor.java
src/io/flutter/editor/WidgetIndentsHighlightingPass.java
src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java

- fix a ConcurrentModificationException (fix https://github.com/flutter/flutter-intellij/issues/3655)
- format some files

fix a ConcurrentModificationException

---

src/io/flutter/inspector/FlutterWidget.java
src/io/flutter/inspector/widgets.json

- update the widgets.json catalog file

update the widgets.json catalog file

---

src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- add a user preference to opt-into showing structured errors
- address part of https://github.com/flutter/flutter-intellij/issues/3680

add a user preference to opt-into showing structured errors

---

build.gradle
src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/run/daemon/FlutterApp.java
testSrc/unit/io/flutter/logging/FlutterConsoleLogManagerTest.java

- fix the logging tests (partial work for https://github.com/flutter/flutter-intellij/issues/3583)
These broke, but I didn't notice as travis didn't go red; we should really get all the test passing (w/o flakes), and re-enable breaking the build on test failures.

fix the logging tests

---

src/io/flutter/samples/FlutterSampleActionsPanel.java

- re-label `'samples'` to `'widget samples'`

re-label 'samples' to 'widget samples'

---

build.gradle
src/io/flutter/bazel/WorkspaceCache.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java
testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java

- re-enable tests on the bots
- disable two tests that were causing downstream test failures (tracking those disabled tests in https://github.com/flutter/flutter-intellij/issues/3583)

re-enable tests on the bots

---

flutter-gui-tests/build.gradle

Uses latest version of the GUI test framework.

Integration test update

---

src/io/flutter/console/FlutterConsoleFilter.java
testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java
testSrc/unit/io/flutter/testing/Testing.java

Fix logger npe

---

flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
tool/plugin/lib/plugin.dart

Fix break due to AS API change.

---

docs/testing.md

Add instructions to reproduce the problem fixed in #3722.

Update test script

---

src/io/flutter/editor/ActiveEditorsOutlineService.java

Fixes https://github.com/flutter/flutter-intellij/issues/3729

Fix bug causing ActiveEditorsOutlineService to never return outlines on Windows.

---

src/io/flutter/view/TogglePlatformAction.java

Fixes https://github.com/flutter/flutter-intellij/issues/3736.
Default to `unknown` for unknown and null values.

Fix NPE for target platform toggle.

---

src/io/flutter/run/common/CommonTestConfigUtils.java

Tolerate null elements in the outline visitor

---

CHANGELOG.md
resources/META-INF/plugin.xml

Update change log

---

src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/common/CommonTestConfigUtils.java
src/io/flutter/run/common/TestType.java
src/io/flutter/view/InspectorTreeMouseListener.java
src/io/flutter/view/InspectorTreeUI.java
testSrc/unit/io/flutter/editor/ActiveEditorsOutlineServiceTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
testSrc/unit/io/flutter/run/common/CommonTestConfigUtilsTest.java
testSrc/unit/io/flutter/testing/FakeActiveEditorsOutlineService.java

- organize imports
- format a few files
- remove some no longer used `SuppressWarnings` annotations

organize imports

---

src/io/flutter/actions/InstallSdkAction.java
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/run/common/CommonTestConfigUtils.java

- add todos related to synchronous execution on the EDT (see #3731)

add todos related to synchronous execution on the EDT

---

analysis_options.yaml
tool/grind.dart

- make part of the dart code use implicit-casts false

make part of the dart code use implicit-casts false

---

src/io/flutter/FlutterUtils.java

- optimize FlutterUtils.isInTestDir
- address some or most of https://github.com/flutter/flutter-intellij/issues/3766
`FlutterUtils.isInTestDir` is called very frequently by editors when rendering, and is called from the EDT. This may have been the cause of the bulk of the precent performance issues. From some profiling, `FlutterRunConfigurationProducer.getFlutterEntryFile()` is fairly slow; this PR re-writes `isInTestDir()` to not use it.

optimize FlutterUtils.isInTestDir

---

src/io/flutter/dart/FlutterDartAnalysisServer.java

- only parse analysis server events we're interested in
- fix https://github.com/flutter/flutter-intellij/issues/3765
cc @lambdabaa

only parse analysis server events we're interested in

---

src/io/flutter/FlutterUtils.java
src/io/flutter/pub/PubRoot.java

- cache the results of parsing the pubspec file
- fix https://github.com/flutter/flutter-intellij/issues/3767

cache the results of parsing the pubspec file

---

src/io/flutter/dart/FlutterDartAnalysisServer.java

- fix a regression in the Flutter Outline view (introduced in https://github.com/flutter/flutter-intellij/pull/3772)

fix a regression in the Flutter Outline view

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/logging/tree/MessageCellRenderer.java
src/io/flutter/perf/VmServiceWidgetPerfProvider.java
src/io/flutter/utils/AnimatedIcon.java
src/io/flutter/view/MultiIconSimpleColoredComponent.java

- address a few deprecation warnings
I'll let this build through on the bots to see if all supported platforms are happy with this change.

address deprecated warnings

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/project/DomainToPackageExpression.java
flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

There were a couple changes in the Android Studio API with 3.6 canary 6.

Adapt to API changes in ASc6

---

src/io/flutter/inspector/InspectorService.java

- follow up from https://github.com/flutter/flutter-intellij/pull/3786, work around an issue where package:dwds doesn't assign IDs to strings
@jacob314

flutter web inspector

---

flutter-intellij-community.iml
src/io/flutter/actions/OpenInAndroidStudioAction.java

Use full path to studio on windows

---

resources/liveTemplates/flutter_miscellaneous.xml

See: https://github.com/flutter/flutter-intellij/issues/3256

theme.of live template

---

resources/liveTemplates/flutter_miscellaneous.xml

Fixes: #3256 
/cc @stevemessick 
/fyi @feinstein

inherited theme.of live template

---

AUTHORS

See: https://github.com/flutter/flutter-intellij/pull/3761
/cc @stevemessick 
/fyi @frextrite

add @frextrite to Authors

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/editor/NativeEditorNotificationProvider.java

Closes #3708 
The changes should theoretically work though I was unable to test the changes due to some errors in setting-up my development environment. Working on fixing that.

Add Hide Notification hyperlink to Notification Panel

---

src/io/flutter/sdk/FlutterCreateAdditionalSettings.java

now supports opening of corresponding sample
Closes #3843

Fix open widget sample opening only counter sample app

---

src/io/flutter/sdk/FlutterSdk.java

- fix a ConcurrentModificationException in FlutterSdk.getFlutterSdk()
- fix https://github.com/flutter/flutter-intellij/issues/3855

fix a ConcurrentModificationException in FlutterSdk.getFlutterSdk()

---

.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/test/plugin_test.dart

- remove support for AS 3.4
@stevemessick @DaveShuckerow

remove support for AS 3.4

---

src/io/flutter/logging/FlutterErrorHelper.java
testSrc/unit/io/flutter/logging/FlutterErrorHelperTest.java

- more normalization of flutter error codes
Ensure that we normalize doubles as well as ints.
@jacob314

more normalization of flutter error codes

---

src/io/flutter/project/ProjectWatch.java
src/io/flutter/sdk/AbstractLibraryManager.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkManager.java

- replace some deprecated API calls with their non-deprecated equivalents

replace some deprecated API calls

---

src/io/flutter/inspector/FrameRenderingDisplay.java
src/io/flutter/vmService/FlutterFramesMonitor.java
src/io/flutter/vmService/ServiceExtensions.java
src/io/flutter/vmService/VMServiceManager.java

Query display refresh rate and use in Performance window.

---

src/io/flutter/preview/PreviewView.java

- rename the "Replace widget with its children" to "remove widget action"
- fix https://github.com/flutter/flutter-intellij/issues/3898
- remove the feedback button from the Flutter Outline view - this was added to get initial feedback on the view
- move an action (the show only widgets filter) to the 'title actions' toolbar for the view; this gives more horizontal space for the build method manipulation actions

rename the remove widget action

---

flutter-intellij.iml

- update the flutter-intellij.iml file w/ the latest libraries (`com.google.protobuf:protobuf-java`)

update flutter-intellij.iml w/ the latest libraries

---

src/io/flutter/vmService/VMServiceManager.java

Fail gracefully when calling getFlutterViewsList if current isolate is null.
Fixes https://github.com/flutter/flutter-intellij/issues/3925.

Fix NPE in when querying display refresh rate.

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml

Move the listener into the Android Studio version of the plugin.
Fixes #3938

Unhook Gradle listeners from IntelliJ

---

src/io/flutter/utils/math/Matrix4.java
src/io/flutter/utils/math/Quaternion.java
src/io/flutter/utils/math/Vector.java
src/io/flutter/utils/math/Vector2.java
src/io/flutter/utils/math/Vector3.java
src/io/flutter/utils/math/Vector4.java
src/io/flutter/utils/math/VectorUtil.java
testSrc/integration/io/flutter/utils/math/Matrix4Test.java
testSrc/integration/io/flutter/utils/math/TestUtils.java

Accessing this code from IntelliJ is convenient for visualizing transform matrixes stored as part of DiagnosticsNodes and other HotUI use cases.

Port package:vector_math package

---

product-matrix.json

- increase version range for as 3.6 beta 1
- fix https://github.com/flutter/flutter-intellij/issues/3972

increase version range for as 3.6 beta 1

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

- remove two reload and restart keybindings
- fix https://github.com/flutter/flutter-intellij/issues/3903

remove two reload and restart keybindings

---

src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/vmService/VMServiceManager.java

- remove support for the older `_Logging` event

remove support for the older _Logging event

---

src/io/flutter/preview/PreviewView.java

- rename two wrap with flutter actions
This is so we keep up-to-date w/ the analysis server's names; https://dart-review.googlesource.com/c/sdk/+/122025.
@scheglov

rename two wrap with flutter actions

---

src/io/flutter/view/FlutterView.java

- fix an npe in the feedback button
We shipped this view quite a while ago - this PR just removes the feedback button.
```
io.flutter.view.FlutterView$1.actionPerformed(), FlutterView.java:149
com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(), ActionUtil.java:261
com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(), ActionUtil.java:278
com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(), ActionButton.java:183
com.intellij.openapi.actionSystem.impl.ActionButton.performAction(), ActionButton.java:147
com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(), ActionButton.java:415
java.awt.Component.processEvent(), Component.java:6315
java.awt.Container.processEvent(), Container.java:2239 …
```

fix an npe in the feedback button

---

src/io/flutter/android/AndroidEmulator.java
src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/run/bazelTest/BazelTestFields.java

- address a few warnings about 'mostly idle daemon process'
- fix https://github.com/flutter/flutter-intellij/issues/3991
@DaveShuckerow

address a few warnings about 'mostly idle daemon process'

---

src/io/flutter/editor/FlutterPubspecNotificationProvider.java

- fix a project assert in the flutter editor notification
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of io/flutter/sdk/FlutterSdk.getFlutterSdk must not be null
at io.flutter.sdk.FlutterSdk.$$$reportNull$$$0(FlutterSdk.java)
at io.flutter.sdk.FlutterSdk.getFlutterSdk(FlutterSdk.java)
at io.flutter.editor.FlutterPubspecNotificationProvider$FlutterPubspecActionsPanel.runPackagesGet(FlutterPubspecNotificationProvider.java:108)
at io.flutter.editor.FlutterPubspecNotificationProvider$FlutterPubspecActionsPanel.lambda$new$0(Flutter...
```

fix a project assert in the flutter editor notification

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- hide the custom logging view setting
From analytics, 1.8% of people have this enabled.
@pq 
This will address https://github.com/flutter/flutter-intellij/issues/3952 (as well as the longer tail of issues - https://github.com/flutter/flutter-intellij/labels/logging).

hide the custom logging view setting

---

src/io/flutter/analytics/Analytics.java
testSrc/unit/io/flutter/analytics/AnalyticsTest.java

remove an unused method

---

testSrc/unit/io/flutter/analytics/AnalyticsTest.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

- re-enable our disabled tests
A trial run to see if our tests now pass; I'll cycle the bots a few times to make sure things aren't flakey.

re-enable our disabled tests

---

src/io/flutter/vmService/DartVmServiceDebugProcess.java

- additional follow up to https://github.com/flutter/flutter-intellij/pull/4008; remove an Observatory link handler from DartVmServiceDebugProcess.java
- remove an unused method

remove an Observatory link handler from DartVmServiceDebugProcess.java

---

product-matrix.json
tool/plugin/test/plugin_test.dart

Build the plugin for Android Developer Studio 4.0 canary 1.

Build for ADS4 canary 1

---

src/io/flutter/survey/FlutterSurveyNotifications.java

Fixes: #4027.
@DanTup @jayoung-lee: maybe double-check URLs and dates? :pray:

Q4 survey notification hooks

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

- fix an indent in the settings page

fix an indent in the settings page

---

flutter-studio/src/io/flutter/module/FlutterModuleModel.java

Inverse of most Windows path problems. URL needs a slash, not backslash.

Use slash on windows

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/editor/WidgetIndentsHighlightingPass.java

- fix a IndexOutOfBoundsException from WidgetIndentsHighlightingPass
- fix https://github.com/flutter/flutter-intellij/issues/4047 (`IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 283]`)

fix a IndexOutOfBoundsException from WidgetIndentsHighlightingPass

---

src/io/flutter/samples/FlutterSampleManager.java

check tempfile before reading

---

flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
src/io/flutter/sdk/AbstractLibraryManager.java
tool/plugin/lib/plugin.dart

Fix error from undefined macro

---

src/io/flutter/vmService/VMServiceManager.java

- fix an issue with an Disposable being already disposed
- fix https://github.com/flutter/flutter-intellij/issues/4057

fix an issue with an Disposable being already disposed

---

src/io/flutter/utils/AsyncRateLimiter.java

- prevent an exception related to use of a disposed Alarm
- fix https://github.com/flutter/flutter-intellij/issues/4070

prevent an exception related to use of a disposed Alarm

---

src/io/flutter/actions/RunFlutterAction.java

- add diagnostics for 'Runner must be specified' error
- related to https://github.com/flutter/flutter-intellij/issues/4067
We're seeing some 'Runner must be specified' errors in crash reporting, but it's not clear why they're happening. This change adds a bit more diagnostics in order to help us narrow down the problem.

add diagnostics for 'Runner must be specified' error

---

src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/inspector/HeapState.java
src/io/flutter/vmService/HeapMonitor.java

- dead code removal and misc cleanup to the `HeapMonitor` class

misc cleanup to the HeapMonitor class

---

src/io/flutter/console/FlutterConsole.java

- address an npe in FlutterConsole.java
```
at io.flutter.console.FlutterConsole.bringToFront(FlutterConsole.java:104)
at io.flutter.console.FlutterConsoles.lambda$null$0(FlutterConsoles.java:45)
at c.i.ui.content.impl.MessageViewImpl.runWhenInitialized(MessageViewImpl.java:53)
at io.flutter.console.FlutterConsoles.lambda$displayProcessLater$1(FlutterConsoles.java:42)
at c.i.o.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
at c.i.o.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvoca...
```

address an npe in FlutterConsole.java

---

src/io/flutter/view/TogglePlatformAction.java

- remove a System.out.print reference

remove a System.out.print reference

---

src/io/flutter/logging/FlutterConsoleLogManager.java

- fix a null assertion (`argument for @NotNull parameter 'text' of io/flutter/run/daemon/DaemonConsoleView.print must not be null`)
- fix https://github.com/flutter/flutter-intellij/issues/4073

fix a null assertion

---

src/io/flutter/vmService/VMServiceManager.java

- address a resource leak on shutdown
- correct a copy paste issue with a log instance

address a resource leak on shutdown

---

src/io/flutter/editor/WidgetIndentsHighlightingPass.java

- use `@NotNull` annotations and remove an if check where we can prove that a reference can't be nullable)

use @NotNull and remove an if check

---

src/io/flutter/vmService/VMServiceManager.java

- add more diagnostics for an error (WARN - ter.vmService.VMServiceManager - java.lang.RuntimeException: Method not found)
It may be that we're calling `_flutter.listViews` on an isolate, after we've identified the isolate as a flutter one, but before listViews is registered. If that's the case, we can likely identify the `Method not found` result by its error code, and return null instead of logging an error. We'll know more once we see a report w/ the diagnostics from the PR.

add more diagnostics for an error

---

src/io/flutter/inspector/InspectorTree.java
src/io/flutter/utils/AsyncRateLimiter.java
src/io/flutter/view/InspectorPanel.java
testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java

- address a disposable issue on shutdown
```
ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'io.flutter.view.InspectorPanel[,0,401,327x99,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]' of class io.flutter.view.InspectorPanel
See the cause for the corresponding Disposer.register() stacktrace:
java.lang.RuntimeException: Memory leak detected: 'io.flutter.view.InspectorPanel[,0,401,327x99,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]' of class io.flutter.view.InspectorPanel
See the cause for the corresponding Disposer.register() stacktrace:
...
```

address a disposable issue

---

src/io/flutter/editor/FlutterSaveActionsManager.java

- don't format a read only doc
- fix https://github.com/flutter/flutter-intellij/issues/4096

don't format a read only doc

---

src/io/flutter/utils/StdoutJsonParser.java

- address a npe / race condition in StdoutJsonParser.java
- fix https://github.com/flutter/flutter-intellij/issues/4100

address a npe / race condition in StdoutJsonParser.java

---

src/io/flutter/view/TogglePlatformAction.java

- address an 'Unknown platform' message in the IntelliJ log

address an 'Unknown platform' message in the IntelliJ log

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

- use a `LinkLabel` for the privacy link in the settings page
before:
after:

use a LinkLabel for the privacy link in the settings page

---

src/io/flutter/vmService/VMServiceManager.java

- fix an npe when getting the target fps for a device
`41.2.3`
```
io.flutter.vmService.VMServiceManager$3.received(), VMServiceManager.java::625
org.dartlang.vm.service.VmService.forwardResponse(), VmService.java::887
org.dartlang.vm.service.VmServiceBase.processResponse(), VmServiceBase.java::630
org.dartlang.vm.service.VmServiceBase.processMessage(), VmServiceBase.java::437
org.dartlang.vm.service.VmServiceBase$1.onMessage(), VmServiceBase.java::86
de.roderick.weberknecht.WebSocketReceiver.run(), WebSocketReceiver.java::65
```

fix an npe when getting the target fps for a device

---

src/io/flutter/FlutterUtils.java

Add null check to guard against missing property

---

src/io/flutter/actions/RunReleaseFlutterApp.java
src/io/flutter/analytics/Analytics.java
testSrc/unit/io/flutter/run/MainFileTest.java
testSrc/unit/io/flutter/utils/FileWatchTest.java

Some misc test cleanup:
- format code
- allow the analytics tests to run against a headless IntelliJ
- remove an unused test fixture

misc test cleanup

---

src/io/flutter/pub/PubRoot.java
src/io/flutter/run/test/TestFields.java
testSrc/unit/io/flutter/run/test/TestFieldsTest.java

- fix an NPE in PubRoot.forDescendant
- fix https://github.com/flutter/flutter-intellij/issues/4146

fix an NPE in PubRoot.forDescendant

---

src/io/flutter/dart/FlutterDartAnalysisServer.java

Some of these requests were taking longer than 100ms causing timeouts. Switched to using futures instead as I don't need responses in 100ms.
Fyi as taking more than 100ms may be unexpected.

Switch getWidgetDescription to use CompletableFuture 

---

src/io/flutter/sdk/FlutterCreateAdditionalSettings.java

- remove an unused field
- follow up from https://github.com/flutter/flutter-intellij/pull/4139/
@stevemessick

remove an unused field

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/editor/EditorEventServiceBase.java
src/io/flutter/editor/EditorMouseEventService.java
src/io/flutter/editor/EditorPositionService.java
src/io/flutter/inspector/InspectorGroupManagerService.java
src/io/flutter/run/FlutterDebugProcess.java

Service to track the state of the inspector.

Services to manage tracking inspector and editor events more effectively.

---

src/io/flutter/inspector/InspectorGroupManagerService.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/InspectorTreeMouseListener.java
src/io/flutter/vmService/ServiceExtensions.java
src/io/flutter/vmService/VMServiceManager.java

to prepare for main HotUI CL.
Fixes https://github.com/flutter/flutter-intellij/issues/4052

Support new Inspector select api and a few other minor tweaks

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/PreviewView.java
src/io/flutter/view/FlutterView.java

Stop showing the screen mirror when the version of Flutter a user has won't support it.

---

flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
src/io/flutter/utils/AndroidUtils.java

@kenzieschmoll I think this fixes the problem you found when creating an add-to-app module independently of its Android app.

Fix module path bug on windows

---

src/io/flutter/run/common/CommonTestConfigUtils.java

- fix an NPE from CommonTestConfigUtils.getTestsFromOutline
- fix https://github.com/flutter/flutter-intellij/issues/4182
- rename two methods for clarity
The issue here was that the field returned from a method wasn't nullable. The field was always populated from within the method, but could be cleared out asynchronously from another thread.

fix an NPE from CommonTestConfigUtils.getTestsFromOutline

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

This reverts commit faf5fcdbfc6883f90e5037bfe9a271198602fc32.

Revert "Remove Enable Hot UI checkbox. (#4174)"

---

src/io/flutter/run/FlutterReloadManager.java

- surface a bit more exception information when we see issues with hot reload on save

Surface reload exceptions

---

src/io/flutter/utils/AndroidUtils.java

Fix NPE in add-to-app support

---

src/io/flutter/editor/PropertyEditorPanel.java

Fail gracefully if there is not an active file just as we fail gracefully if there is no outline.

---

src/io/flutter/editor/ColorField.java
src/io/flutter/editor/ColorPickerProvider.java
src/io/flutter/editor/FlutterColors.java

- fix an npe related to hot ui (`buildColorExpression()` could see a null `color` parameter)
- fix https://github.com/flutter/flutter-intellij/issues/4221

fix an npe related to hot ui

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
flutter-studio/src/io/flutter/project/ChoseProjectTypeStep.java
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
flutter-studio/src/io/flutter/utils/AddToAppUtils.java
product-matrix.json
tool/plugin/lib/plugin.dart

Adapt the code to the API changes in ADS 4.0 and update the build to compile the dev channel.
With this PR the base for flutter-studio development changes to the ADS4 code, not the AS beta version.

Build dev channel

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Change assert to null check and return

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

- add an 'Open Dart DevTools' menu item to the top level Flutter menu
- fix https://github.com/flutter/flutter-intellij/issues/4270
- slightly re-order the existing menu

add an 'Open Dart DevTools' menu item

---

src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/utils/AsyncUtils.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

- address a concurrent modification exception in the widget build count code
- fix https://github.com/flutter/flutter-intellij/issues/4234
This moves all accesses of `editorDecorations` to the UI thread.

address a concurrent modification exception in the widget build count code

---

src/io/flutter/ProjectOpenActivity.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/bazel/WorkspaceCache.java
src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/editor/FlutterPubspecNotificationProvider.java
src/io/flutter/inspections/FlutterDependencyInspection.java
src/io/flutter/run/bazel/BazelFields.java
src/io/flutter/run/bazelTest/BazelTestConfigProducer.java
src/io/flutter/run/bazelTest/BazelTestConfigUtils.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/bazelTest/BazelTestLaunchState.java
src/io/flutter/run/bazelTest/FlutterBazelTestLineMarkerContributor.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/utils/FlutterModuleUtils.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/bazel/WorkspaceTest.java

Fix race condition in workspace cache and simplify WorkspaceCache to stop
trying to do work in the background.

Switch to using WorkspaceCache

---

src/io/flutter/FlutterUtils.java
src/io/flutter/dart/FlutterDartAnalysisServer.java
src/io/flutter/editor/ActiveEditorsOutlineService.java
src/io/flutter/hotui/StableWidgetTracker.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/preview/PreviewView.java

- fix an issue with sending in non-absolute paths to flutter.subscriptions
- fix https://github.com/flutter/flutter-intellij/issues/4273
I'm not sure how non-absolute paths are getting into our manager tracking `flutter.setSubscriptions` for files; this change may address the issue.

fix an issue with sending in non-absolute paths to flutter.subscriptions

---

kokoro/macos_external/kokoro_test.sh
kokoro/macos_external/presubmit.cfg
tool/kokoro/test.sh

Add template for running tests. Check existence of tools required to run `plugin build`.

Check pre-reqs for build

---

.idea/misc.xml

revert bad edit

---

tool/kokoro/build.sh
tool/kokoro/test.sh

Install ant

---

tool/kokoro/build.sh
tool/kokoro/test.sh

TBR optimize a bit; add printenv to see what's available

Trim tar output

---

tool/kokoro/build.sh
tool/kokoro/setup.sh
tool/kokoro/test.sh

@devoncarew This is ready for review. It isn't finished, but a number of technical issues have been solved.

Refactor build script

---

tool/kokoro/build.sh
tool/kokoro/setup.sh
tool/kokoro/test.sh

@devoncarew Address review comments. Fix the path to the new file. Hopefully it will work now.

Refactor fix

---

.gitignore
kokoro/macos_external/continuous.cfg
kokoro/macos_external/presubmit.cfg
tool/kokoro/build.sh
tool/kokoro/test.sh
tool/plugin/lib/plugin.dart

Put dev channel artifacts in releases/release_dev and identify that to Kokoro. Also, fix .gitignore to stop trying to add lib/dart-plugin/deps/commons-lang3-3.2.1.jar.

Define dev channel artifacts

---

src/io/flutter/survey/FlutterSurveyNotifications.java

Follow-up from https://github.com/flutter/flutter-intellij/pull/4334#issuecomment-580492201.
/cc @jayoung-lee @stevemessick 
/fyi @DanTup

push back survey window

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Change flutter.io to flutter.dev

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterSdk.java

- print the debug service uri on app startup
- remove an unused method
This verbiage is the same as what the flutter tool uses for web launches.

print the debug service uri on app startup

---

.gitignore
flutter-intellij-community.iml
flutter-intellij.iml

- make the gitignore more specific for content within the .idea directory
This addressed an issue for me where I had local diffs for the com_google_protobuf_protobuf_java_3_5_1.xml, org_powermock_powermock_api_mockito2_2_0_2.xml, ... files but was not aware of it.

make the gitignore more specific for content within the .idea directory

---

tool/kokoro/setup.sh

Apache changed the location. Our Kokoro runs are failing but this should fix it.

Update ant URL

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/android/GradleDependencyFetcher.java

Replace two API usages that are due to be removed soon.
See #4351

Replace deprecated API usage

---

src/io/flutter/utils/ProgressHelper.java

I can't reproduce the issue, but checking that the project is not disposed can't hurt, and might help.
Fixes #4357

Check for disposed project

---

tool/plugin/lib/plugin.dart

This fixes the undefined macro issue.
Fixes #4350

Change 3.6 edits to preserve init() method

---

src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java

- remove an unused flutter command (list samples)
- add some TODOs to switch us to an improved method of getting the flutter sdk version (`flutter --version --machine`)

remove an unused flutter command

---

.gitignore
flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
tool/plugin/lib/plugin.dart

This replaces #4417.
This rebases the sources on 3.6 (stable) Android Studio. We have to do some editing in the plugin tool to build for 4.0 now.

Fix API incompatibilities

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/FlutterFrameFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
flutter-studio/testSrc/io/flutter/tests/gui/NewModuleTest.java
tool/plugin/lib/plugin.dart

Rebase to Android Studio 4.1 sources and start on integration tests.
Changes to integration tests are still a work in progress.

Rebase to Android Studio 4.1 sources and start on integration tests

---

flutter-studio/src/io/flutter/module/FlutterModuleImporter.java

The Flutter docs moved. Update the link for add-to-app.

Fix link to Flutter docs

---

src/io/flutter/dart/DartSyntax.java
src/io/flutter/run/common/CommonTestConfigUtils.java

- fix an NPE in CommonTestConfigUtils.java
- fix https://github.com/flutter/flutter-intellij/issues/4436

fix an NPE in CommonTestConfigUtils.java

---

src/io/flutter/survey/FlutterSurvey.java
src/io/flutter/survey/FlutterSurveyNotifications.java
src/io/flutter/survey/FlutterSurveyService.java

Still a little testing to do but ready for preliminary feedback.
/cc @devoncarew @DanTup 
/fyi @jayoung-lee 
Fixes: #4398.

data drive survey

---

src/io/flutter/survey/FlutterSurveyService.java

Fixes #4463 
More eyes welcome.

Harden survey checking network access

---

CONTRIBUTING.md

This updates some of the instruction details, fixes a few capitalizations, and adds a few contextual comments.

Update setup instructions

---

testSrc/unit/io/flutter/project/ProjectWatchTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigurationFactoryTest.java
testSrc/unit/io/flutter/testing/Testing.java

IdeaTestApplication has been removed. This update causes a new test failure. It is being ignored for now.

Update tests for 2020.1

---

flutter-intellij-community.iml
flutter-studio/flutter-studio.iml
tool/plugin/lib/artifact.dart
tool/plugin/lib/edit.dart
tool/plugin/lib/globals.dart
tool/plugin/lib/lint.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart
tool/plugin/pubspec.yaml

Most of the changes, other than edit.dart, are cosmetic. I reformatted everything. Almost everything in edit.dart was moved from plugin.dart. The classes are new, but the code to implement the edits was copied.
One new thing I've wanted forever is a report of obsolete edit commands.

Refactor edits

---

README.md

Add dev channel to readme

---

src/io/flutter/sdk/FlutterSettingsConfigurable.java

Fixes #4453 
@devoncarew I think you have the most familiarity with the Bazel code.

Ensure the combo is enabled before disabling it

---

src/io/flutter/console/FlutterConsoleFilter.java
testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java

Apply link filter to error messages

---

tool/kokoro/setup.sh

Upgrade ant for kokoro

---

flutter-studio/flutter-studio.iml
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/FlutterFrameFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java

See the comment at the beginning of `IdeaFrameFixture` for instructions for generating it. The changes are almost all mechanical. When `IdeFrameFixture` changes I just copy the new source, paste it into `IdeaFrameFixture` and follow the instructions. Some new methods required adding a new dependency.

Update integration tests for canary

---

src/io/flutter/utils/StdoutJsonParser.java
testSrc/unit/io/flutter/utils/StdoutJsonParserTest.java

Verify that opening workbench, opening project(s), quitting, then re-opening workbench consistently results in re-opened projects having device options.
Fixes https://github.com/flutter/flutter-intellij/issues/3892

Recognize \r as newlines from flutter

---

build.gradle
src/io/flutter/console/FlutterConsoleFilter.java
testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java
testSrc/unit/io/flutter/testing/Testing.java

Split the regex in FlutterConsoleFilter that recognizes error messages into two parts. Use the first to identify lines that contain an error message. Use the second to recognize the file path.
Add a test that times out if catastrophic backtracking occurs.
Fix the test framework to properly initialize IntelliJ.
Fixes #4599 
Fixes #4630

Dual regex

---

flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java

Adapt to API changes in AS 4.2c2

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Add target to registerComponents()

---

src/io/flutter/sdk/FlutterSdk.java

Reverts flutter/flutter-intellij#4622

Revert "Start paused during run mode"

---

.gitignore
CHANGELOG.md
flutter-idea/build.gradle
flutter-studio/build.gradle
gradle.properties
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart

Fix a few problems:
- JxBrowser files were not available to unit tests
- The script wasn't getting updated with the proper IDE and plugin versions
- The result of the external build was not being returned, causing broken bots to be green

Update build script

---

src/io/flutter/run/MainFile.java

Stop checking for BUILD when looking for root dir

---

src/io/flutter/actions/DeviceSelectorAction.java

- update the device selector presentation on toolbar change; this addresses an issue where the device selector looses its text when toggling on and off the toolbar
- fix an issue with the device selector having a larger font than other comboboxes on the toolbar
- fix https://github.com/flutter/flutter-intellij/issues/4689 (a regression introduced in https://github.com/flutter/flutter-intellij/pull/4651)
@stevemessick @helin24

update the device selector presentation on toolbar change

---

src/io/flutter/FlutterBundle.properties

- update our analytics text
- fix https://github.com/flutter/flutter-intellij/issues/4710
cc @kf6gpe

update our analytics text

---

AUTHORS
src/io/flutter/vmService/ServiceExtensions.java
src/io/flutter/vmService/VMServiceManager.java

- Replace Whitelist terminology to Allow List

Replace Whitelist terminology to Allow List

---

testSrc/unit/io/flutter/editor/FlutterEditorAnnotatorTest.java

- suppress several UnstableApiUsage warnings

suppress several UnstableApiUsage warnings

---

src/io/flutter/devtools/DevToolsManager.java

Show notification for when devtools build is slow

---

CHANGELOG.md
docs/testing.md
product-matrix.json
resources/META-INF/plugin.xml
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml

Updates for M48

---

tool/plugin/lib/runner.dart

This line has been causing a build error in our automated tests (see https://travis-ci.org/github/flutter/flutter-intellij/jobs/714557794)

Remove return line that causes build error

---

CHANGELOG.md
flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
flutter-studio/src/io/flutter/module/ImportFlutterModuleStep.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/MacMenuFixture.java
resources/META-INF/plugin.xml
src/io/flutter/run/test/TestFields.java
src/io/flutter/sdk/FlutterSdk.java

Build 48.1

---

CHANGELOG.md
resources/META-INF/plugin.xml

Update change log for 48.1

---

src/io/flutter/pub/PubRoot.java

This cache is never updated although `.packages` file and `lib` folder may be created/deleted while user works with the open project.
This a better fix for #4224.
I've removed 2 `refresh()` calls
```
pubspec.refresh(true, false);
packagesFile.refresh(true, false);
```
because they effectively were noop in this case (asynchronous refresh can't help if you need to check timestamps immediately after calling `refresh`).
As a next step, you may revise the whole `PubRootCache` idea. (Pub root and pubspec files remain cached.) Caching `VirtualFiles` that are within project content usually doesn't help to improve performance. Everything is already cached in the VFS, and methods like `getParent()` or `findChild()` normally take no time. 
On the other hand, manual caching of `VirtualFiles` adds a …

Don't cache VirtualFiles for '.packages' file and 'lib' folder.

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Add note on LGPL compliance to plugin description

---

src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java

Tested with master and stable.
Fixes #4796

Add --platforms to flutter create -t plugin

---

third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java

- fix an issue with the JsonParser.parseString() API
@helin24

fix an issue with the JsonParser.parseString() API

---

tool/kokoro/setup.sh

This should fix the Kokoro script.
I'm not sure about the download link. Having a 32-digit hex number in it seems like something that could change.

Download Java 14

---

tool/plugin/lib/edit.dart

Fixes #4809.
The only change is the if-statement at line 134. The others are from the formatter.

Make edit use init41() for 4.1

---

src/io/flutter/editor/ExpressionParsingUtils.java
testSrc/unit/io/flutter/editor/ExpressionParsingUtilsTest.java

- fix an issue parsing color values
- fix https://github.com/flutter/flutter-intellij/issues/4835

fix an issue parsing color values

---

src/io/flutter/logging/FlutterConsoleLogManager.java

- Fix an NPE from console logging
- fix https://github.com/flutter/flutter-intellij/issues/4833

Fix an NPE from console logging

---

.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/test/plugin_test.dart

- remove 2019.2 from the product matrix

Remove 2019.2 from the product matrix

---

resources/flutter/colors/cupertino.json
resources/flutter/colors/material.json
src/io/flutter/analytics/Analytics.java
src/io/flutter/devtools/DevToolsUtils.java
src/io/flutter/editor/OutlineLocation.java
src/io/flutter/editor/WidgetViewController.java

various misc. fixes:
- remove spurious semi-colons from some json files (the issue upstream has already been addressed)
- use `StandardCharsets.UTF_8` where possible
- remove extra semi-colons from a few places in java files

various misc. fixes

---

src/io/flutter/FlutterBundle.java
src/io/flutter/FlutterErrorReportSubmitter.java
src/io/flutter/FlutterInitializer.java
src/io/flutter/FlutterUtils.java
src/io/flutter/dart/DartPlugin.java
src/io/flutter/settings/FlutterSettings.java

- move off some deprecated methods (`CommonBundle.message()`, `PluginManager.getPlugin()`, ...)

move off some deprecated methods

---

tool/kokoro/deploy.sh
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart

Need to verify that the plugin is not built; also `ls -lR build`

Log exception when no file

---

build.gradle
gradle.properties
tool/kokoro/deploy.sh
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart

This still has debugging code but hopefully fixes the dev channel build issue. Deploy is temporarily disabled.

Set plugin name

---

src/io/flutter/jxbrowser/JxBrowserManager.java

- address lints on JxBrowserManager.java
@helin24 - this isn't necessarily for landing; it looks like `files` is written to but never read from - I don't know what the intent of the variable was. In any case, FYI.

address lints on JxBrowserManager.java

---

src/io/flutter/analytics/ToolWindowTracker.java
src/io/flutter/run/FlutterReloadManager.java

- move off two deprecated APIs (subscribe to message bus topics instead of adding explicit listeners)

move off two deprecated APIs

---

src/io/flutter/logging/FlutterErrorHelper.java
testSrc/unit/io/flutter/logging/FlutterErrorHelperTest.java

- improve the flutter error ids we generate for analytics
- fix https://github.com/flutter/flutter-intellij/issues/4467
This fixes the `'package` error ID we'd seen in analytics.

improve the flutter error ids we generate for analytics

---

tool/plugin/lib/plugin.dart

Should return failure code now.

Fix plugin make

---

.idea/misc.xml

Some functions cannot be found using the 1_8 language level

Change language level to 11

---

.idea/misc.xml
flutter-intellij.iml

- compile with java language version ~9~ 8
- commit a metadata change to `flutter-intellij.iml`

compile with java language version 8

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

- adjust the text for the jsbrowser setting and add a tooltip

adjust the text for the jsbrowser setting

---

tool/plugin/lib/plugin.dart

Hopefully this will fix the Kokoro failures.

Add minor version to kokoro file name

---

src/io/flutter/analytics/Analytics.java
src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/sdk/FlutterSdkVersion.java

- send the flutter sdk version with the analytics for flutter errors
- fix https://github.com/flutter/flutter-intellij/issues/4901

send the flutter sdk version with the analytics for flutter errors

---

src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/perf/WidgetPerfLinter.java
src/io/flutter/performance/FlutterPerformanceView.java
src/io/flutter/performance/FrameRenderingDisplay.java
src/io/flutter/performance/PerfFPSPanel.java
src/io/flutter/performance/PerfMemoryPanel.java
src/io/flutter/performance/PerfWidgetRebuildsPanel.java
src/io/flutter/performance/WidgetPerfTable.java
src/io/flutter/vmService/FlutterFramesMonitor.java

- address various lints in src/io/flutter/perf, src/io/flutter/performance, src/io/flutter/module

address various lints in src/io/flutter/perf, src/io/flutter/performance, src/io/flutter/module

---

README.md
resources/flutter/colors/cupertino.json
resources/flutter/colors/material.json
src/io/flutter/FlutterErrorReportSubmitter.java
src/io/flutter/FlutterInitializer.java
src/io/flutter/FlutterUtils.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/editor/PreviewViewControllerBase.java
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/MultiIconSimpleColoredComponent.java
src/io/flutter/view/TogglePlatformAction.java
src/io/flutter/vmService/DartVmServiceDebugProcess.java
src/io/flutter/vmService/DisplayRefreshRateManager.java
src/io/flutter/vmService/HeapMonitor.java
src/io/flutter/vmService/ServiceExtensionDescription.java
src/io/flutter/vmService/ServiceExtensions.java
src/org/dartlang/analysis/server/protocol/FlutterOutline.java

various lint fixes

---

src/io/flutter/preview/DartElementPresentationUtil.java

- update the DartElementPresentationUtil class
This class is copied from the Dart plugin - this updates to the latest version.

update the DartElementPresentationUtil class

---

src/io/flutter/project/FlutterIconProvider.java

- fix an exception loading the FlutterIconProvider class in EAP
- fix https://github.com/flutter/flutter-intellij/issues/4937, https://github.com/flutter/flutter-intellij/issues/4939
cc @stevemessick, @beansoft

fix an exception loading the FlutterIconProvider class in EAP

---

src/io/flutter/jxbrowser/JxBrowserManager.java

- address an issue with the JxBrowser singleton (we were creating it but not remembering it)
- some minor additions wrt nullability annotations
cc @helin24

address an issue with the JxBrowser singleton

---

build.gradle
flutter-idea/build.gradle
flutter-studio/build.gradle
gradle.properties
tool/plugin/lib/runner.dart

Make the Gradle script use the correct version of Java.

Use Java version

---

src/io/flutter/run/daemon/DaemonConsoleView.java

fix a deprecation warning

---

src/io/flutter/analytics/Analytics.java
src/io/flutter/analytics/ThrottlingBucket.java

- record whether the project type is bazel

record whether the project type is bazel

---

src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/vmService/VmServiceWrapper.java

- minor tweaks to the test seen when we have repeated issues starting the device daemon
- fix some grammar in another error message

minor tweaks to an error message

---

flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
tool/plugin/lib/runner.dart

Fork a shell to build old versions

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/editor/ActiveEditorsOutlineService.java
src/io/flutter/editor/FilteredIndentsHighlightingPass.java
src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
src/io/flutter/editor/WidgetIndentsHighlightingPassFactoryRegistrar.java

This fixes https://github.com/flutter/flutter-intellij/issues/4792

Fix lifecycle bugs for indent guides and bug where guides would sometimes show for other languages

---

tool/kokoro/build.sh
tool/kokoro/deploy.sh

I forgot Kokoro does not have Java 11 installed by default.

Add Java 11 to Kokoro

---

src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkChannel.java

The FlutterSdk.returnOutputOfQuery() is derived from queryFlutterConfigImpl(). The command to run becomes a parameter and post-processing is moved out of that method and into its caller.

Channel command: run 'flutter channel'

---

src/io/flutter/FlutterUtils.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

Temporarily fixes https://github.com/flutter/flutter-intellij/issues/5057

Unset and disable embedded browser option if MacOS Big Sur

---

.github/workflows/presubmit.yaml
CHANGELOG.md
flutter-idea/build.gradle
flutter-intellij-community.iml
flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
gradle.properties
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/artifact.dart
tool/plugin/lib/build_spec.dart
tool/plugin/lib/edit.dart
tool/plugin/lib/runner.dart
tool/plugin/test/plugin_test.dart

There weren't too many API changes this time.
I added support for unpacking MacOS zip files to get compilation artifacts. This will save money as I need to use a metered data plan to download Android Studio executables. Now I don't have to do it twice.

Update build for M52

---

src/io/flutter/FlutterErrorReportSubmitter.java

- fix a compilation issue with IntelliJ 2020.3
I'm assuming we can land this change now that our min. platform is on `2020.1`.

fix a compilation issue with IntelliJ 2020.3

---

src/io/flutter/FlutterErrorReportSubmitter.java

Reverts flutter/flutter-intellij#5100

Revert "fix a compilation issue with IntelliJ 2020.3"

---

src/io/flutter/view/FlutterViewToggleableAction.java

- fix an issue with leaking subscriptions
- see https://github.com/flutter/flutter-intellij/issues/5034 for more info
Previously, every call to Action.update() (which happens frequently in IntelliJ), would create and leak a new stream subscription. I don't know that this resolves https://github.com/flutter/flutter-intellij/issues/5034, but it will at least address one issue.

fix an issue with leaking subscriptions

---

src/io/flutter/sdk/FlutterSdkUtil.java

- minor tweaks to the snap sdk path code

minor tweaks to the snap sdk path code

---

src/io/flutter/run/daemon/DevToolsService.java

We were previously starting a DevTools server on project open; this changes to starting the server when it's first requested (or if a previous attempt to start failed).
This change also adds exception logging and completion for various error conditions while starting the server.

Start DevTools server on first request and handle exceptions

---

CONTRIBUTING.md

- update the contributing docs to mention the min. Java target version for the gradle compiler
@stevemessick

update the contributing docs

---

tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart
tool/plugin/test/plugin_test.dart

some minor cleanups to the dart code:
- remove some references to Android Studio 4.0
- avoid the use of a deprecated List constructor

some minor cleanups to the dart code

---

src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/run/FlutterReloadManager.java
testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java

This depends on `syncScript` being compiled.

Sync before hot reload for bazel projects

---

src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/run/OpenDevToolsAction.java

This switches to using the project-level DevTools server when opening DevTools from the run console area.

Use DevTools service for open action

---

src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/view/FlutterView.java

This is an action available from the Java inspector in the overflow menu.

Use project-level DevTools server for overflow open

---

src/io/flutter/actions/FlutterBuildActionGroup.java
src/io/flutter/actions/FlutterDoctorAction.java
src/io/flutter/actions/OpenInAndroidStudioAction.java
src/io/flutter/actions/OpenInXcodeAction.java
src/io/flutter/android/AndroidEmulator.java
src/io/flutter/android/AndroidSdk.java
src/io/flutter/console/FlutterConsole.java
src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/console/FlutterConsoles.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/daemon/DevToolsService.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterCommandStartResult.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/utils/MostlySilentColoredProcessHandler.java

Resolves #4743 . This is a quick fix according to the suggestion in https://github.com/flutter/flutter-intellij/issues/4743#issuecomment-671463190 .

Use ColoredProcessHandler for the console

---

.idea/codeStyles/Project.xml
CHANGELOG.md
flutter-studio/src/io/flutter/utils/AddToAppUtils.java
resources/META-INF/plugin.xml

Update build for AS canary 4

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/run/OpenDevToolsAction.java

This change addresses https://github.com/flutter/devtools/issues/2345

Rename to "Flutter DevTools"

---

CONTRIBUTING.md

Provide more specifics for how external developers can work on JxBrowser
Related to https://github.com/flutter/flutter-intellij/issues/5164

Update JxBrowser contributing instructions

---

src/io/flutter/run/SdkFields.java
testSrc/unit/io/flutter/run/SdkFieldsTest.java

- fix args parsing in launch configurations
- fix https://github.com/flutter/flutter-intellij/issues/4588

fix args parsing in launch configurations

---

src/io/flutter/vmService/frame/DartVmServiceEvaluatorInFrame.java

Remove newlines prior to sending eval expr to VM

---

src/io/flutter/console/FlutterConsoleFilter.java

Fixes #4309
The color is prominent in all standard themes.

Show "Lost connection to device." in red

---

src/io/flutter/view/FlutterView.java

Add null checks to debugActive()

---

src/io/flutter/view/FlutterView.java

Add a null check before dereferencing sourcePosition

---

src/io/flutter/editor/FlutterIconLineMarkerProvider.java

Add a type check

---

.github/workflows/presubmit.yaml
product-matrix.json
tool/plugin/lib/edit.dart
tool/plugin/test/plugin_test.dart

Work-around for lack of canary support.

Fix unit tests

---

src/io/flutter/editor/WidgetIndentsHighlightingPassFactoryRegistrar.java

Register highlighting for Flutter projects only

---

.github/workflows/presubmit.yaml
CHANGELOG.md
build.gradle
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/edit.dart

Update build for M54.1 and add support for 2021.1 Beta.

Support 2021 beta

---

AUTHORS
CONTRIBUTING.md

Hello, I found some typos while following the directions in `CONTRIBUTING.md`.
Thank you. 🙂

Fix typo in CONTRIBUTING.md

---

flutter-studio/src/io/flutter/utils/GradleUtils.java

Handle include lists in settings.gradle

---

tool/plugin/lib/edit.dart

Change action group name for canary

---

src/io/flutter/test/DartTestEventsConverterZ.java

https://github.com/dart-lang/test/issues/1465

Remove the isFailure option in the Dart test event framework

---

pubspec.yaml
tool/grind.dart

Fix null-safety error

---

src/io/flutter/devtools/DevToolsUrl.java
src/io/flutter/devtools/DevToolsUtils.java
src/io/flutter/jxbrowser/EmbeddedBrowser.java
src/io/flutter/view/FlutterView.java

Fixes https://github.com/flutter/flutter-intellij/issues/5213
This refactors how the DevTools URL is stored so it should be easier to update the URL after an app is launched, e.g. if we also want to modify font sizes in the future.

Listen for theme color changes to update embedded browser

---

CHANGELOG.md
resources/META-INF/plugin.xml

Update change log for 55.1

---

src/io/flutter/dart/DartPsiUtil.java
src/io/flutter/editor/FlutterIconLineMarkerProvider.java
testSrc/unit/io/flutter/editor/FlutterIconLineMarkerTest.java

Allow IconData(null)

---

src/io/flutter/FlutterMessages.java
src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/run/bazelTest/BazelTestRunner.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/utils/MostlySilentColoredProcessHandler.java
src/io/flutter/utils/UrlUtils.java
testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
testSrc/unit/io/flutter/utils/UrlUtilsTest.java

We want to additionally prompt users with a notification if there is a warning about internal configuration. The message can include a link, so I added simple parsing for a URL to make it clickable.
~~I was originally going to change this for running too but I need some help finding where that text is parsed. If this is a good approach for test and run, then I'll make a separate change for app run/debug.~~

Add notification for test and run if config warning

---

resources/META-INF/plugin.xml
tool/plugin/bin/main.dart
tool/plugin/lib/artifact.dart
tool/plugin/lib/build_spec.dart
tool/plugin/lib/edit.dart
tool/plugin/lib/globals.dart
tool/plugin/lib/lint.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart
tool/plugin/lib/util.dart
tool/plugin/pubspec.yaml
tool/plugin/test/plugin_test.dart

- initial null safe conversion of the `tool/plugin` tool

initial null safe conversion of tool/plugin

---

src/io/flutter/performance/PerfWidgetRebuildsPanel.java

Fixes #4499
Running in profile mode:

Improve hover message of "Track Widget Rebuilds"

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/utils/FlutterModuleUtils.java

This fixes the workspace check for bazel projects and is a better solution than https://github.com/flutter/flutter-intellij/pull/5455.

Check for new local Dart SDK

---

src/io/flutter/utils/FlutterModuleUtils.java

Catch an already disposed exception

---

src/io/flutter/vmService/DartVmServiceListener.java

Fix step-over async call

---

src/io/flutter/run/FlutterDebugProcess.java

Use i18n version of "Console"

---

src/io/flutter/actions/OpenInXcodeAction.java
src/io/flutter/sdk/FlutterSdkVersion.java

Use --config-only to set up Xcode

---

src/io/flutter/actions/OpenInXcodeAction.java
src/io/flutter/sdk/FlutterSdkVersion.java

Reverts flutter/flutter-intellij#5474

Revert "Use --config-only to set up Xcode"

---

src/io/flutter/actions/OpenInXcodeAction.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java

@jmagman This version compares timestamps, as done in flutter_tools. Thanks again!

Xcode config only

---

src/io/flutter/run/common/CommonTestConfigUtils.java

Add null-check for listener

---

src/io/flutter/bazel/Workspace.java

Catch InvalidVirtualFileAccessException thrown by VFS in a readAction

---

.github/workflows/presubmit.yaml
CONTRIBUTING.md
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/edit.dart
tool/plugin/test/plugin_test.dart

- update the set of supported IntelliJ versions
This drops two older IntelliJ versions (2020.1 and 2020.2).

update the set of supported IntelliJ versions

---

src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java

We should remove this from flutter.json since it's no longer being used or updated.

Clean up unused version for bazel

---

src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java

Fixes https://github.com/flutter/flutter-intellij/issues/5512

Add switch to disable Chromium notifications

---

src/io/flutter/sdk/FlutterSdk.java

- fix an index out of bounds in FlutterSdk.java (it appears that in some small number of cases `flutter config --machine` doesn't return valid json (or errors before it completes?)
This exception was seen from crash reporting:
```
57.0.5
IntelliJ IDEA/2021.1.2
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.base/java.lang.String.substring(String.java:1837)
at io.flutter.sdk.FlutterSdk.queryConfiguredPlatforms(FlutterSdk.java:579)
at io.flutter.module.FlutterGeneratorPeer.lambda$fillSdkCache$1(FlutterGeneratorPeer.java:93)
at c.i.util.RunnableCallable.call(RunnableCallable.java:20)
at c.i.util.RunnableCallable.call(RunnableCallable.java:11)
at c.i.o.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
at ...
```

fix an index out of bounds in FlutterSdk.java

---

src/io/flutter/actions/DeviceSelectorAction.java

Fixes #5566
I think. I have not been able to reproduce the problem. But I apparently forgot to delete the line of code that triggers the log message.

Fix custom component in a presentation update issue

---

src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java

Maybe fixes https://github.com/flutter/flutter-intellij/issues/5584 (Looking for a physical linux machine to test on)

Add force scale option for linux

---

src/io/flutter/run/coverage/FlutterCoverageSuite.java

Stop asking to delete coverage data

---

src/io/flutter/run/FlutterConfigurationEditorForm.form
src/io/flutter/run/FlutterConfigurationEditorForm.java
src/io/flutter/run/SdkFields.java

Add a field for environment variables to the run config editor

---

src/io/flutter/actions/FlutterBuildActionGroup.java

Disallow iOS builds if not on Mac

---

src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java

Maybe fixes https://github.com/flutter/flutter-intellij/issues/5584

Use off screen render mode for linux

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/run/daemon/DeviceService.java
src/io/flutter/sdk/AndroidEmulatorManager.java

Fixes #5598
I think. I cannot reproduce the problem, which means there may be some odd timing issue, and this may not work. But it looks like it should.

Remove custom listeners before a project is closed

---

src/io/flutter/run/bazel/BazelFields.java
testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java

This should be done in internal logic instead

Remove creating flutter_build_mode flag

---

src/io/flutter/editor/FlutterIconLineMarkerProvider.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/perf/VmServiceWidgetPerfProvider.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

- handle the new event format for widget recount info (`locations`)
-  remove references to `org.jetbrains.yaml` imports - this doesn't compile for me locally
@jacob314

handle the new event format for widget recount info

---

tool/plugin/lib/edit.dart

Edit loadClasses method for 2021.2 as well

---

src/io/flutter/vmService/VmServiceWrapper.java
src/io/flutter/vmService/frame/DartVmServiceValue.java
tool/plugin/lib/edit.dart

Port over support for special list display in the debugger

---

product-matrix.json
resources/META-INF/plugin.xml
testSrc/unit/io/flutter/project/ProjectWatchTest.java
testSrc/unit/io/flutter/testing/AdaptedFixture.java
testSrc/unit/io/flutter/testing/Testing.java
testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java

Delete two obsolete tests and attempt to de-flake others

---

CONTRIBUTING.md

Fix some problems in the set up docs

---

CHANGELOG.md
resources/META-INF/plugin.xml
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java

Remove old code from NPW

---

README.md

#Problem
Broken link - https://flutter.dev/images/favicon.png
#Solution
Updated link - https://github.com/dart-lang/site-shared/blob/master/src/_assets/image/flutter/icon/64.png?raw=1

Fix broken image resorce file link

---

src/io/flutter/actions/FlutterBuildActionGroup.java

Flutter > Build menu should be visible even if no file is selected

---

src/io/flutter/module/FlutterModuleBuilder.java

Delete the project directory if project validation fails

---

src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
src/io/flutter/sdk/FlutterSdk.java

Add --project-name arg to flutter create

---

src/io/flutter/pub/PubRoot.java

Try harder to find pub root

---

src/io/flutter/utils/FlutterModuleUtils.java

Change some deprecated API usage

---

src/io/flutter/bazel/Workspace.java

Bug fix in Workspace.java: parsing of contents out of the json file.

---

CHANGELOG.md
resources/META-INF/plugin.xml

Update changelog for 61.1

---

flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
flutter-idea/src/io/flutter/utils/JxBrowserUtils.java
tool/plugin/lib/edit.dart

Enable downloading M1 version of JxBrowser

---

.github/workflows/presubmit.yaml
CHANGELOG.md
product-matrix.json
resources/META-INF/plugin.xml

Build for M63

---

flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
tool/plugin/lib/edit.dart

Rename old load classes

---

flutter-idea/src/io/flutter/editor/FlutterCompletionContributor.java
flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
flutter-idea/src/io/flutter/view/DiagnosticsTreeCellRenderer.java
flutter-idea/src/io/flutter/view/InspectorPanel.java

Improve icon preview and completion performance

---

docs/testing.md
product-matrix.json

Update compatibility for IntelliJ 2021.2.4.
@jwren

Build for 212.5712

---

flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java

Add analytics to survey notifications

---

CONTRIBUTING.md

This is basically a list of what I had trouble with when setting up gpg.

Add tips for signing commits on OSX

---

tool/plugin/README.md

The old `build` command no longer works.

Change build to make

---

docs/building.md

Add notes on releasing

---

flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
flutter-idea/testSrc/unit/io/flutter/testing/Testing.java
flutter-intellij-community.iml
product-matrix.json
tool/plugin/lib/edit.dart
tool/plugin/test/plugin_test.dart

This fixes some compilation problems that appear when compiling against IJ 2022.1 EAP. It does not yet produce a usable plugin for EAP.

Build for 2022.1 EAP

---

resources/liveTemplates/flutter_miscellaneous.xml
resources/liveTemplates/stanim.txt
resources/liveTemplates/stful.txt
tool/plugin/lib/plugin.dart

Fixes https://github.com/flutter/flutter-intellij/issues/5962.
Fixes https://github.com/flutter/flutter-intellij/issues/5964.

Remove private return type from createState in macros

---

flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java

Relax constraints for identifying the android module

---

flutter-idea/src/io/flutter/editor/FlutterSaveActionsManager.java
flutter-idea/src/io/flutter/utils/JsonUtils.java

Do not merge until we stop building for 2020.3 (Arctic Fox).
Fixes #5903

Stop using some deprecated methods

---

flutter-idea/src/io/flutter/run/FlutterReloadManager.java

Ignore scratch files during hot reload on save

---

flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.form
flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.java
flutter-idea/src/io/flutter/run/test/TestForm.form
flutter-idea/src/io/flutter/run/test/TestForm.java

Fixes #5952 (I think, have not been able to verify yet but will before merging.)

Use expandable test field for run args

---

flutter-idea/src/io/flutter/run/daemon/DeviceSelection.java

Fixes #6000 
It does not implement the suggested change, but will solve the problem.
I'm not sure why it was implemented as it was, so I chose to preserve existing behavior as much as possible.

Select desktop or web if no other device is available

---

tool/plugin/lib/artifact.dart
tool/plugin/lib/build_spec.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart

I added try-finally in two places, which causes a lot of noise in the diff.
Fixes #6085

Plugin tool improvements

---

flutter-idea/src/io/flutter/FlutterConstants.java
flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java

Remove the 30-char limit for project names

---

flutter-idea/src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java

Change setting on EDT

---

tool/github.sh
tool/plugin/lib/plugin.dart

Stop running setup on the bots

---

flutter-idea/src/io/flutter/FlutterInitializer.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

This code needs more testing before being deployed.

Disable new analytics for M67

---

flutter-idea/src/io/flutter/analytics/Analytics.java
flutter-idea/src/io/flutter/analytics/FlutterAnalysisServerListener.java
flutter-idea/src/io/flutter/analytics/ThrottlingBucket.java

No analytics events were being sent after startup.
The timing for completion is now from request to first results, rather than all results, which is probably more important to the user.

Fix trhottling bug

---

flutter-idea/src/io/flutter/run/daemon/DevToolsService.java

Fixes https://github.com/flutter/flutter-intellij/issues/6149

Specify dart bin path

---

flutter-idea/src/io/flutter/run/FlutterDevice.java
flutter-idea/src/io/flutter/run/daemon/DaemonEvent.java
flutter-idea/src/io/flutter/run/daemon/DeviceDaemon.java

Show a meaningful device name in the device selector

---

.github/workflows/presubmit.yaml
.github/workflows/presubmit.yaml.template
.github/workflows/windows.yaml

Add default permissions in order to resolve security code scan findings and pin dependencies using hash. Generated changes into preseubmit yaml via presubmit template as instructed.
Resolves security findings
- https://github.com/flutter/flutter-intellij/security/code-scanning/17
- https://github.com/flutter/flutter-intellij/security/code-scanning/16
- https://github.com/flutter/flutter-intellij/security/code-scanning/15
- https://github.com/flutter/flutter-intellij/security/code-scanning/14
- https://github.com/flutter/flutter-intellij/security/code-scanning/13
- https://github.com/flutter/flutter-intellij/security/code-scanning/12
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
If you need help, …

Add default token permissions values + pin dependencies

---

.idea/misc.xml
flutter-idea/src/io/flutter/analytics/Analytics.java
flutter-idea/src/io/flutter/analytics/FlutterAnalysisServerListener.java
flutter-idea/testSrc/unit/io/flutter/analytics/FlutterAnalysisServerListenerTest.java

This causes timing data to appear in the database.

Send timing data as a GA event

---

flutter-idea/src/io/flutter/inspections/FlutterDependencyInspection.java

Stop relying only on .packages for pub banner

---

flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java

Fixes https://github.com/flutter/flutter-intellij/issues/6196

Use canonical paths to map symlinks

---

flutter-idea/src/io/flutter/utils/Refreshable.java

This needs to be in M68.
Fixes #6178

Use correct code to shut down process

---

flutter-idea/src/io/flutter/module/settings/PlatformsForm.kt
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java

Enable stable platforms

---

.idea/misc.xml
flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
flutter-idea/src/io/flutter/project/FlutterProjectStructureDetector.java

I still need to check that the subscription is cleared if the dialog is cancelled. That's for a follow-up PR.
Opening a monorepo project in IntelliJ is a bit tricky, so I'm adding detailed instructions to the release notes for M69. That's already available, if you'd like to review it.

Improve import for monorepo projects

---

flutter-idea/src/io/flutter/editor/FlutterReaderModeMatcher.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Disable reader mode for Flutter plugins

---

flutter-intellij-community.iml

Trying to build Android Studio from sources with the Flutter plugin.

Update .iml for 221

---

flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java

TIL you cannot revert from the github site. You have to do it locally to get it signed.

Revert "Delete code duplicated from Dart (#6113)"

---

.github/workflows/presubmit.yaml
product-matrix.json

We should distributed this one, too.

Move EAP to stable

---

flutter-idea/src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java

Check for disposed editor

---

flutter-idea/src/io/flutter/project/FlutterProjectStructureDetector.java

Fixes #6267
The irony is that I had disabled the warning that this might happen.

Add missing null check

---

flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java

Guard against JSON file problems

---

flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java

Add listener to clear task on completion

---

flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java

Add View for long toString() values

---

flutter-idea/src/io/flutter/utils/TypedDataList.java
flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java
flutter-idea/testSrc/unit/io/flutter/utils/TypedDataListTest.java

Show values of TypedDataList in debugger

---

flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
flutter-idea/src/io/flutter/module/settings/PlatformsForm.kt

Remove obsolete code from NPW 

---

flutter-idea/src/io/flutter/actions/OpenEmulatorAction.java
flutter-idea/src/io/flutter/android/AndroidEmulator.java

Remove the process listener after termination

---

flutter-idea/src/io/flutter/run/coverage/FlutterCoverageEnabledConfiguration.java

Fix test coverage for monorepo projects

---

flutter-idea/src/io/flutter/module/FlutterProjectType.java
flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
flutter-idea/src/io/flutter/module/settings/ProjectType.java
flutter-idea/src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
resources/liveTemplates/flutter_miscellaneous.xml
resources/liveTemplates/stanim.txt
resources/liveTemplates/stful.txt
resources/liveTemplates/stless.txt

Also adds `const` to live templates. Empty projects are quite new, only available on master and beta today.
Fixes #6402 
Fixes #6397

Add new project types plugin_ffi and empty

---

.github/workflows/presubmit.yaml
CHANGELOG.md
flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java_stub
resources/META-INF/plugin.xml
tool/plugin/lib/edit.dart

This should also fix the unit tests.

Fix problems in 71.1

---

AUTHORS
flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java

Fix creating package project

---

flutter-idea/src/io/flutter/run/FlutterReloadManager.java

Ignore empty files that the Dart plugin says have errors

---

flutter-idea/src/io/flutter/run/test/FlutterTestConsoleProperties.java
flutter-idea/src/io/flutter/run/test/TestConfig.java

This allows IntelliJ to automatically run a test suite prior to doing a commit when using the VCS tool window. If any test fails a message will appear indicating that.
Fixes #6384 
See that issue for usage instructions.

Allow auto pre-commit test to run prior to git commit

---

.github/workflows/presubmit.yaml
flutter-idea/src/io/flutter/analytics/FlutterAnalysisServerListener.java

Fixes #6574 
Also helps with #6470

Stop logging to improve completion times

---

flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowser.java

Catch UnsatisfiedLinkError for inspector

---

flutter-idea/src/io/flutter/utils/TypedDataList.java
flutter-idea/testSrc/unit/io/flutter/utils/TypedDataListTest.java

Fix debugger display of Uint8List elements

---

.github/workflows/windows.yaml

This workflow is disabled but I'm getting errors from it.

Attempt to fix error email

---

flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowser.java

Fixes https://github.com/flutter/flutter-intellij/issues/6612
Right now this is attached to a keypress of Ctrl + J which I randomly chose...

Open chrome devtools from JxBrowser

---

flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java
flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
flutter-idea/src/io/flutter/view/FlutterView.java
flutter-idea/testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java

Fixes https://github.com/flutter/flutter-intellij/issues/6406

Check version of SDK for forming DevTools URL

---

flutter-idea/src/io/flutter/android/AndroidEmulator.java

Use reflection to find EmulatorSettings in both IDEs

---

flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/BoundField.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSamples.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSamplesEvent.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Event.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Func.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/FuncRef.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/InboundReference.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Instance.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceKind.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceRef.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Isolate.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/IsolateRef.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/ProcessMemoryItem.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/RetainingObject.java

These changes were generated by `dart generate.dart` in the `tool` directory.
Edit: I had to fix some bugs in the generated code. See the `TODO` in `BoundField`.

Update VM service protocol to spec version 4.1

---

flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java

Use setIsolatePauseMode

---

flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/BoundField.java

This also includes a patch to `BoundField` that makes it usable, but I expect that will change with the next update to VM service protocol.
@alexander-doroshko

View record fields in the debugger

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Removes some code that hasn't been used since Android Studio 4.2.
Fixes #6660

Remove some obsolete code

---

flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java

Follow-up on #6500, don't use setExceptionPauseMode() if possible

---

flutter-idea/src/io/flutter/actions/DeviceSelectorRefresherAction.java
tool/plugin/lib/edit.dart

Update Refresh on BGT

---

flutter-idea/src/io/flutter/actions/FlutterRetargetAppAction.java
tool/plugin/lib/edit.dart

Use BGT to update UI for restart/reload

---

flutter-idea/artifacts

Delete `flutter-idea/artifacts` link

---

tool/plugin/lib/build_spec.dart
tool/plugin/lib/edit.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/util.dart
tool/plugin/test/plugin_test.dart

...especially for Windows Native (without WSL).
Resolves #6052 #6640 #6733

Allow making the plugin from multiple platforms

---

.idea/runConfigurations/flutter_intellij__plugin_make_.xml
.idea/runConfigurations/flutter_intellij__plugin_test_.xml

* Add `flutter-intellij [plugin-test]` that runs `dart run tool/plugin/bin/main.dart test`.
* Rename `flutter-intellij [make]` to `flutter-intellij [plugin-make]`

Improve run configurations

---

CONTRIBUTING.md

- Combine separated plugin development sections into one single `Setting environments`. The Windows related content should be up-to-date.
- Add TOC, and more semantic titles.
- Fix typos and formats.

♻️ Reorg CONTRIBUTING.md

---

flutter-idea/src/io/flutter/editor/FlutterColorProvider.java

This time it is signed. Turns out you cannot create a PR from the GitHub window, since they are not signed.

Revert color preview patch

---

flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java

FlutterSdkVersion.version needs to be nullable

---

flutter-idea/src/io/flutter/settings/FlutterSettings.java

Change to having the included browser on by default

Default to JCEF browser

---

flutter-idea/src/io/flutter/actions/FlutterAppAction.java

Use BGT to update UI during reload/restart

---

flutter-idea/src/io/flutter/view/EmbeddedBrowser.java

This fixes #6795 again, since my previous patch got lost.

Clear browser tabs when window closes

---

flutter-idea/src/io/flutter/pub/PubRoot.java

Stop showing an error after running tests with coverage

---

flutter-idea/src/io/flutter/ProjectOpenActivity.java
flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
flutter-idea/src/io/flutter/logging/FlutterConsoleLogManager.java
flutter-idea/src/io/flutter/settings/FlutterSettings.java

Fixes #6789 
And this clears the M75 milestone :)

Remove isEnableEmbeddedBrowsers setting

---

flutter-idea/src/io/flutter/actions/OpenInAndroidStudioAction.java

All I did was move old line 99 to new line 69.
Fixes #6847

Use pooled thread to find location of Android Studio

---

flutter-idea/src/io/flutter/console/FlutterConsole.java
flutter-idea/src/io/flutter/preview/PreviewView.java

See this for some additional context: https://youtrack.jetbrains.com/issue/IDEA-299177/NoSuchMethodError-when-calling-com.intellij.ui.content.ContentFactory.getInstance

Change ContentFactory.SERVICE.getInstance() to ContentFactory.getInstance()  (#6948)

---

flutter-idea/src/io/flutter/console/FlutterConsole.java
flutter-idea/src/io/flutter/console/FlutterConsoles.java

https://github.com/flutter/flutter-intellij/issues/6948

Change MessageView.SERVICE.getInstance(project) to MessageView.getInstance(project) (#6948)

---

flutter-idea/src/io/flutter/editor/FlutterColorProvider.java

https://github.com/flutter/flutter-intellij/issues/6942

Fix for IndexOutOfBoundsException in FlutterColorProvider.getColorFrom() (#6942)

---

CHANGELOG.md
resources/META-INF/plugin.xml

```
- Fix for IndexOutOfBounds on startup (#6942)
- Fix for JXBrowser key not provided (#6992)
```

CHANGELOG.md change for `76.1.X` release

---

flutter-idea/src/io/flutter/editor/FlutterColorProvider.java

- Fixes #6957
- Fixes #6961
- Fixes #6962
- Fixes #6965
- Fixes #6967
- Fixes #6968
- Fixes #6970
- Fixes #6972
- Fixes #6973
- Fixes #6974
- Fixes #6975
- Fixes #6977
- Fixes #6978
- Fixes #6981
- Fixes #6984
- Fixes #6986
- Fixes #6989
- Fixes #6995
- Fixes #6997
- Fixes #6998
- Fixes #6999
- Fixes #7001
- Fixes #7004
- Fixes #7007 …

🐛 Fix NPE when calling the argument list

---

README.md

Helps developers to identify the latest version from the repo.

Add the latest plugin version badge to the README

---

flutter-idea/src/io/flutter/run/FlutterReloadManager.java

https://github.com/flutter/flutter-intellij/issues/6996
https://github.com/flutter/flutter-intellij/commit/a3a4312e041c8e6d004605272fc0b01646a0fac8

Add documentation on the previous breakage of Flutter Hot Reload

---

.github/workflows/presubmit.yaml
product-matrix.json
tool/plugin/lib/edit.dart
tool/plugin/test/plugin_test.dart

https://github.com/flutter/flutter-intellij/issues/7094

Remove 2022.2.x as a supported version for Android Studio

---

CHANGELOG.md
resources/META-INF/plugin.xml

Thank you @helin24 for the content here.

Update the changelog for version 77

---

.github/workflows/presubmit.yaml
product-matrix.json
tool/plugin/test/plugin_test.dart

https://github.com/flutter/flutter-intellij/issues/7134

Remove 2022.3.x from the `product-matrix.json` (#7134)

---

flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/BoundField.java

This fixes https://github.com/flutter/flutter-intellij/issues/6666
Also see https://github.com/dart-lang/sdk/issues/51917

Remove the field BoundField.getDecl() (#6666)

---

.github/workflows/presubmit.yaml
build.gradle.kts
flutter-idea/build.gradle.kts
flutter-idea/testSrc/unit/io/flutter/analytics/FlutterAnalysisServerListenerTest.java
flutter-idea/testSrc/unit/io/flutter/bazel/PluginConfigTest.java
flutter-idea/testSrc/unit/io/flutter/bazel/WorkspaceTest.java
flutter-idea/testSrc/unit/io/flutter/console/FlutterConsoleFilterTest.java
flutter-idea/testSrc/unit/io/flutter/run/MainFileTest.java
flutter-idea/testSrc/unit/io/flutter/run/bazel/BazelFieldsTest.java
flutter-idea/testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
gradle.properties
product-matrix.json
tool/plugin/lib/build_spec.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart

This resolves https://github.com/flutter/flutter-intellij/issues/7145
https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension-plugins

Change the Gradle steps to pull the Android plugin from the marketplace when building the Flutter IJ Plugin

---

CHANGELOG.md
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
tool/plugin/lib/edit.dart

https://github.com/flutter/flutter-intellij/issues/7193

Set the vendor information to Google.

---

flutter-idea/src/io/flutter/vmService/frame/DartStaticFieldsGroup.java

https://github.com/flutter/flutter-intellij/issues/7228

Additional hardening in DartStaticFieldsGroup.java in an attempt to resolve issue 7228

---

build.gradle.kts
flutter-idea/build.gradle.kts
product-matrix.json

This is follow up on https://github.com/flutter/flutter-intellij/issues/7145

Fix some logic in the Gradle files to be conditional on the ide being built instead of the version of the platform

---

flutter-idea/src/io/flutter/deeplinks/DeepLinksViewFactory.java
flutter-idea/src/io/flutter/jxbrowser/EmbeddedJxBrowser.java
flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
flutter-idea/src/io/flutter/utils/LabelInput.java
flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
flutter-idea/src/io/flutter/view/FlutterView.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

TODOs:
- New icon?
- Move testing over? (testing this logic is pretty annoying)

Add panel for DevTools deep links

---

flutter-idea/src/io/flutter/run/FlutterReloadManager.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Fixes https://github.com/flutter/flutter-intellij/issues/6844

Convert hot reload notifications to not use deprecated methods

---

flutter-idea/src/io/flutter/deeplinks/DeepLinksViewFactory.java
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java

Add Flutter SDK gating for deep links panel

---

build.gradle.kts
flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

Also--- a few small lint fixes in the Gradle files

Disable verifyPlugin Gradle task in the studio Gradle configuration

---

tool/plugin/lib/plugin.dart
tool/plugin/lib/verify.dart

See https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-verifyplugin

Add a new command in the ./tool/plugin tool to run the Gradle verification tasks.

---

flutter-idea/src/io/flutter/ProjectOpenActivity.java
flutter-idea/src/io/flutter/jxbrowser/EmbeddedJxBrowser.java
flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
flutter-idea/src/io/flutter/view/FlutterView.java
flutter-idea/testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java

This resolves https://github.com/flutter/flutter-intellij/issues/7377

Change the JxBrowserManager to not hold onto a Project reference.

---

flutter-idea/src/io/flutter/run/FlutterPositionMapper.java

This is expected to resolve https://github.com/flutter/flutter-intellij/issues/7380

On shutdown in FlutterPositionMapper, set the project to null

---

flutter-idea/src/io/flutter/vmService/DartVmServiceDebugProcess.java

This resolves https://github.com/flutter/flutter-intellij/issues/7348

Prevent AlreadyDisposedException from DartVmServiceDebugProcess.java

---

flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java

This should resolve https://github.com/flutter/flutter-intellij/issues/7306

Add a project disposal check in FlutterModuleBuilder

---

flutter-idea/src/io/flutter/actions/FlutterExternalIdeActionGroup.java
flutter-idea/src/io/flutter/actions/OpenInAndroidStudioAction.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

This will resolve the issue https://github.com/flutter/flutter-intellij/issues/7103

Remove the FlutterExternalIdeActionGroup and associated OpenInAndroidStudioAction

---

flutter-idea/src/io/flutter/actions/ExtractWidgetAction.java
flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java
flutter-idea/src/io/flutter/actions/FlutterPackagesExplorerActionGroup.java
flutter-idea/src/io/flutter/view/FlutterViewToggleableAction.java

Fixes #7330
I think this covers the remaining actions that have been mentioned in issues so far. There are more actions where I haven't updated the action thread, but I suspect most of them are no longer used.

Specify BGT action thread for remaining classes

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

New UI:
Old UI:
Addresses some of the issues in https://github.com/flutter/flutter-intellij/issues/6595

Fix top toolbar for new UI

---

flutter-idea/src/io/flutter/editor/FlutterColorProvider.java

This fixes https://github.com/flutter/flutter-intellij/issues/7285

Fix possible exceptions out of FlutterColorProvider

---

flutter-idea/src/io/flutter/perf/EditorPerfDecorations.java

This resolves https://github.com/flutter/flutter-intellij/issues/7328

Prevent a possible, and rare, exception out of EditorPerfDecorations.java

---

flutter-idea/src/io/flutter/preview/PreviewView.java
flutter-idea/src/io/flutter/preview/WidgetEditToolbar.java
flutter-idea/src/io/flutter/run/FlutterPopFrameAction.java

Fix missed deprecations for action update thread

---

flutter-idea/src/io/flutter/FlutterBundle.properties
flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
flutter-idea/src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
flutter-idea/testSrc/unit/io/flutter/sdk/FlutterCreateAdditionalSettingsTest.java

This resolves https://github.com/flutter/flutter-intellij/issues/7439

Remove iOS languages from new project creation (#7439)

---

flutter-idea/src/io/flutter/run/FlutterPositionMapper.java

This resolves https://github.com/flutter/flutter-intellij/issues/7449

Resolve debugger issue with the new macro file uri format (#7449)

---

flutter-idea/src/io/flutter/samples/FlutterSampleNotificationProvider.java

This resolves https://github.com/flutter/flutter-intellij/issues/5634

Fix exceptions out of FlutterSampleNotificationProvider (#5634)

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java

This resolves https://github.com/flutter/flutter-intellij/issues/7339

Migrate ProjectActivity interfaces to the ProjectActivity interface

---

flutter-idea/src/io/flutter/devtools/DevToolsUrl.java

Fixes error in https://github.com/flutter/flutter-intellij/pull/7472

Fix to using ideValue instead of calling sdk fn again

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java

This reverts commit 98f46ba15ac25c1b6c511eaa90c5f25541e8cd01.

Revert "Migrate ProjectActivity interfaces to the ProjectActivity interface (#7471)"

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-idea/src/io/flutter/analytics/UnifiedAnalytics.java
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java

I'm leaving this turned off for now as it will show users a notification asking if they consent. Turn on after PR for trying to send existing analytics through DTD with unified analytics.

Add code for getting consent for unified analytics

---

CHANGELOG.md
flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
resources/META-INF/plugin.xml

This resolves https://github.com/flutter/flutter-intellij/issues/4470

When the New Flutter Project action is run in AS, open the AS project view to show the files

---

build.gradle.kts

Version change from `2.0.0-Beta5` to `2.0.0`
https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm

Bump the `org.jetbrains.kotlin.jvm` gradle dependency version

---

flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

See https://devhub.checkmarx.com/cve-details/CVE-2023-2976/

Update the version of com.google.guava to 32.0.0

---

CHANGELOG.md
flutter-idea/src/io/flutter/module/settings/PlatformsForm.kt
resources/META-INF/plugin.xml

This resolves https://github.com/flutter/flutter-intellij/issues/7310

Migrate PlatformsForm.kt to Kotlin UI DSL Version 2

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewFactory.java
flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewService.java
flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

No app running:
App running:
Review after https://github.com/flutter/flutter-intellij/pull/7417 is merged
Partially addresses https://github.com/flutter/flutter-intellij/issues/7195

Add embedded view for other DevTools tabs

---

flutter-idea/src/io/flutter/inspections/FlutterDependencyInspection.java
flutter-idea/src/io/flutter/pub/PubRoot.java

This resolves https://github.com/flutter/flutter-intellij/issues/7538

"Pubspec has been edited" is stuck in Android Studio Koala resolution

---

flutter-idea/src/io/flutter/pub/PubRoot.java
flutter-idea/src/io/flutter/pub/PubRootCache.java

Follow up on this recent commit: https://github.com/flutter/flutter-intellij/commit/a8d3f9820020d740c091f26bddb74379744f100a

Nits in PubRoot.java and PubRootCache.java

---

CHANGELOG.md
resources/META-INF/plugin.xml

This is a follow-up PR for https://github.com/flutter/flutter-intellij/pull/7541/commits/84f5f6cafdd10f803f0912bb43fa80c2f9eb0bf3 & https://github.com/flutter/flutter-intellij/issues/7538

Update the CHANGELOG.md for the "Pubspec has been edited" editor notification is stuck issue

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-idea/src/io/flutter/devtools/DevToolsExtensionsViewFactory.java
flutter-idea/src/io/flutter/devtools/DevToolsExtensionsViewService.java
flutter-idea/src/io/flutter/devtools/DevToolsViewService.java
flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewFactory.java
flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewService.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Add DevTools extensions view as a tool window

---

product-matrix.json

https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2024
https://github.com/flutter/flutter-intellij/blob/master/docs/building.md

Update the product-matrix.json to compile against 2024.1.2 Canary 8

---

flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java

Add warning message for removing performance panel

---

kokoro/macos_external/release.cfg
tool/kokoro/setup.sh
tool/kokoro/test.bat

The new plugin key has been uploaded internally; hopefully this fixes the dev build, but I think I will have to merge this to master to test it out.

Use new plugin key

---

flutter-idea/src/io/flutter/performance/FlutterPerformanceViewFactory.java

Fixes error from https://github.com/flutter/flutter-intellij/pull/7637#pullrequestreview-2286867489
CC @kenzieschmoll

Use correct SDK version check for gating performance page

---

flutter-idea/src/io/flutter/FlutterInitializer.java

Follow up to https://github.com/flutter/flutter-intellij/pull/7647, as the original JSON was malformed and missing a "theme" key.

Wrap theme event data in "theme"

---

flutter-idea/testData/sample_tests/pubspec.yaml
pubspec.yaml
tool/grind.dart
tool/plugin/analysis_options.yaml
tool/plugin/lib/build_spec.dart
tool/plugin/lib/edit.dart
tool/plugin/lib/lint.dart
tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart
tool/plugin/lib/util.dart
tool/plugin/pubspec.yaml
tool/plugin/test/plugin_test.dart

There's likely some restructuring and other cleanup that could be made, but this is just a simple resolving of the new diagnostics from the shared analysis options.

Use shared workspace and analysis options for repo tools

---

tool/plugin/lib/plugin.dart

Removal of dead code -- flags shouldn't be defined which are not yet implemented, or planned to be implemented

Cleanup in the plugin cli tool for the test command

---

flutter-idea/src/io/flutter/editor/FlutterCompletionContributor.java
flutter-idea/src/io/flutter/inspector/DiagnosticsNode.java
flutter-idea/src/io/flutter/module/FlutterGeneratorPeer.java
flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
flutter-idea/src/io/flutter/run/bazelTest/BazelTestRunner.java
flutter-idea/src/io/flutter/run/common/TestType.java
tool/plugin/lib/lint.dart

Enforcement of this added into the `./bin/plugin lint` cli tool
Additional context: https://github.com/dart-lang/sdk/issues/39377

More consistent StringUtil usage

---

flutter-idea/src/io/flutter/preview/PreviewView.java

This is a follow-up on https://github.com/flutter/flutter-intellij/pull/7779

Add some additional instruction in the Flutter Outline message

---

tool/plugin/lib/build_spec.dart

Other changes are from the Dart formatter

Improve the toString method on the BuildSpec class

---

flutter-idea/src/io/flutter/sdk/FlutterSdkUtil.java
flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java

https://github.com/flutter/flutter-intellij/issues/7718

Migrate from deprecated method: JsonParser().parse() to JsonParser.parseString(..)

---

build.gradle.kts
flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm/2.1.0
Additionally, a TODO was added for `org.jetbrains.intellij.platform` and version `2023.3` of the platform

Update the org.jetbrains.kotlin.jvm version to 2.1.0, from 2.0.0

---

build.gradle.kts
flutter-idea/build.gradle.kts

https://github.com/JetBrains/intellij-plugin-verifier

Update the IntelliJ verifier to version 1.381

---

third_party/gradle/wrapper/gradle-wrapper.properties

This may help unblock https://github.com/flutter/flutter-intellij/issues/7810

Update the version of Gradle downloaded from 8.2.1 to 8.5

---

flutter-idea/src/io/flutter/pub/PubRoot.java

This resolves https://github.com/flutter/flutter-intellij/issues/7792

Fix the slow operation notification associated with PubRoot

---

CONTRIBUTING.md

I was prompted but told it not to install it since I didn't know what it was and it wasn't mentioned in the docs, this just adds a mention so people know to accept it :)

Update CONTRIBUTING.md to mention installing DevKit

---

CONTRIBUTING.md

[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

Fix 'upstream' typo

---

flutter-idea/src/io/flutter/FlutterBundle.properties
flutter-idea/src/io/flutter/actions/RestartFlutterAppRetarget.java
flutter-idea/src/io/flutter/actions/RunFlutterAction.java

@jwren fixing some warnings I am seeing as I'm opening files in the project. I'm on JVM 23 so I'm not sure if that is why I'm seeing these warnings, but please let me know if these are appropriate fixes. I just applied the suggestions from the warning in the IDE.

Fix some warnings in RunFlutterAction.java

---

tool/plugin/lib/plugin.dart
tool/plugin/lib/runner.dart
tool/plugin/test/plugin_test.dart

[CQ] remove (stale) deploy `plugin` command

---

tool/kokoro/setup.sh

This is follow up on the previous commit, https://github.com/flutter/flutter-intellij/commit/708d7fb7983c76e3b3b18f498c1e6cad34df8ed3
See https://github.com/flutter/flutter-intellij/pull/7937 for context

Fix the pre-submit for the flutter-intellij project (kokoro)

---

build.gradle.kts
flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

https://github.com/flutter/flutter-intellij/issues/7936

Update the Gradle Plugin versions

---

CONTRIBUTING.md

[docs] remove stale "signing commits" section from the TOC

---

flutter-idea/src/io/flutter/devtools/DevToolsExtensionsViewFactory.java
flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewFactory.java
flutter-idea/testSrc/unit/io/flutter/editor/ActiveEditorsOutlineServiceTest.java
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Takes advantage of Java 8 - introduced lambda expressions and Map operations.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handli …

[CQ] Java 8 migration: lambdas and Map ops

---

flutter-idea/src/io/flutter/run/daemon/DevToolsService.java

Use Java 7 multi-catch syntax 🎉 
[Discord]: …

[CQ] Java 7 migration : collapse catch clauses

---

flutter-idea/src/io/flutter/view/MultiIconSimpleColoredComponent.java
flutter-idea/src/org/dartlang/analysis/server/protocol/ExtractWidgetFeedback.java

Tidy up some needless locals.
[Discord]: …

[CQ] Data Flow: inline redundant locals

---

build.gradle.kts
flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

This resolves https://github.com/flutter/flutter-intellij/issues/7965

Remove the conditional inclusion of `com.google.tools.ij.aiplugin`

---

flutter-idea/src/io/flutter/logging/DiagnosticsNode.java
flutter-idea/src/io/flutter/module/settings/ProjectType.java
flutter-idea/src/io/flutter/run/test/FlutterTestConfigProducer.java

[CQ] cleanup unused imports

---

flutter-idea/src/io/flutter/module/settings/InitializeOnceBoolValueProperty.java

Another opportunistic cleanup: fix visibility (the class is final) and null-safety.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md# …

[CQ] `InitializeOnceBoolValueProperty`: visibility/null fixes

---

flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java

Migrate away from slated-for-removal `Notification` API.
See: https://github.com/JetBrains/intellij-community/blob/b41a4084da5521effedd334e28896fd9d07410da/platform/ide-core/src/com/intellij/notification/Notification.java#L87
See: https://github.com/flutter/flutter-intellij/issues/7718.
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-rep …

[CQ]: migrate to supported `Notification` API

---

.idea/runConfigurations/flutter_intellij__runIde_.xml

Fix per-project triggering of "runIde" task

---

CHANGELOG.md
resources/META-INF/plugin.xml

https://github.com/flutter/flutter-intellij/milestone/99

Update the changelog.md for M85.1

---

flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java

Remove some straggling (dead) widget inspector support and add some null-awareness.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md# …

[CQ] remove dead `FlutterDartAnalysisServer`code; add null-safety

---

.github/workflows/presubmit.yaml
product-matrix.json

Fixes: https://github.com/flutter/flutter-intellij/issues/8073
Should unblock landing of https://github.com/flutter/flutter-intellij/pull/8070, https://github.com/flutter/flutter-intellij/pull/8071 and https://github.com/flutter/flutter-intellij/pull/8018.
See also: https://github.com/flutter/flutter-intellij/issues/7718
[Flutter Style Guide]: …

[product] bump product lower-bound to Meerkat

---

.gitignore
build.gradle.kts
flutter-idea/build.gradle.kts

This resolves https://github.com/flutter/flutter-intellij/issues/8034

Update the verifier to 1.384 and make changes in the build.gradle.kts to fix the IJ Verifier for the Flutter plugin

---

tool/github.sh

https://github.com/flutter/flutter-intellij/issues/7967

Remove Java 8 if condition in github.sh

---

flutter-idea/src/io/flutter/run/SdkRunConfig.java

The hunt for slow ops continues...
Addresses:
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:114)
at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:153)
at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:98)
at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:267)
at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileInde …
```

[perf] stop blocking on `SdkRunConfig.addConsoleFilters`

---

flutter-idea/src/io/flutter/bazel/WorkspaceCache.java

Fixes: https://github.com/flutter/flutter-intellij/issues/8083
See: https://github.com/flutter/flutter-intellij/issues/8089
Tested w/ https://github.com/scalio/bazel-flutter
[breaking change …

[perf] stop blocking on `WorkspaceCache.refresh`

---

flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.java
flutter-idea/src/io/flutter/run/SdkAttachConfig.java
flutter-idea/src/io/flutter/run/SdkRunConfig.java
flutter-idea/src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.java
flutter-idea/src/io/flutter/run/coverage/FlutterCoverageProgramRunner.java
flutter-idea/src/io/flutter/run/test/TestForm.java

Opportunistic cleanup.
---
<details>
</details>

[CQ] remove unneccessary imports

---

CHANGELOG.md
resources/META-INF/plugin.xml

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
- [ X ] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

Update the CHANGELOG.md for a 85.3 release

---

build.gradle.kts
flutter-idea/build.gradle.kts
flutter-studio/build.gradle.kts

Cleanup some Kotlin warnings in build.gradle.kts files

---

tool/plugin/lib/plugin.dart

Follow up to https://github.com/flutter/flutter-intellij/pull/8155

Add note that dev build uses this code

---

pubspec.yaml
tool/plugin/pubspec.yaml

Keeping up with the Joneses.
---
<details>
</details>

[CQ] bump to latest stable `lints` package dep

---

flutter-idea/src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
flutter-idea/src/io/flutter/run/MainFile.java
flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java
flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java

Basic cleanup where call sites basically had the body of a utility method in-lined.

[CQ] Use of FlutterUtils.isDartFile(file)

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-idea/src/io/flutter/actions/FlutterRetargetAppAction.java
flutter-idea/src/io/flutter/actions/FlutterSdkAction.java
flutter-idea/src/io/flutter/actions/ReloadFlutterApp.java
flutter-idea/src/io/flutter/actions/ReloadFlutterAppRetarget.java
flutter-idea/src/io/flutter/editor/FlutterColors.java
flutter-idea/src/io/flutter/editor/FlutterCupertinoColors.java
flutter-idea/src/io/flutter/logging/DiagnosticLevel.java
flutter-idea/src/io/flutter/logging/DiagnosticsNode.java
flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
flutter-idea/src/io/flutter/run/SdkFields.java
flutter-idea/src/io/flutter/run/bazel/BazelFields.java
flutter-idea/src/io/flutter/run/bazelTest/BazelTestFields.java
flutter-idea/src/io/flutter/run/daemon/DeviceService.java
flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
flutter-idea/testSrc/unit/io/flutter/run/common/CommonTestConfigUtilsTest.java
flutter-idea/testSrc/unit/io/flutter/utils/RefreshableTest.java

🧐 Fix some typos, duplicated words and misc grammar nits.
---
<details>
</details>

[CQ] [nits] Grammar round-up

---

flutter-idea/src/io/flutter/FlutterInitializer.java
flutter-idea/src/io/flutter/editor/NativeEditorNotificationProvider.java
flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
flutter-idea/src/io/flutter/run/FlutterRunNotifications.java
flutter-idea/src/io/flutter/run/LaunchState.java
flutter-idea/src/io/flutter/run/daemon/DevToolsServerTask.java
flutter-idea/src/io/flutter/sdk/FlutterSdkUtil.java
flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
flutter-idea/testSrc/unit/io/flutter/ide/DartTestUtils.java

Minor cleanups.
Cleaned up redundant:
* suppressions and
* throws
Fixed a handful of string capitalization inspections.
Removed an unused symbol and an unused import.
---
<details> …

[CQ] remove misc. redundant suppressions/throws

---

flutter-idea/src/io/flutter/FlutterBundle.properties

Cleanup a few straggling unused properties.
Follow-up from https://github.com/flutter/flutter-intellij/pull/8183.
---
<details>
</details>

[CQ] remove unused bundle properties

---

flutter-idea/src/io/flutter/FlutterInitializer.java

The move to project activities has some nuance. In the long run we'll be able to do some real performance tuning but in the short-run some of our assumptions about being in a read context need to be rethunk. Here's one.
The rub is `autoCreateRunConfig` needs to be in a read context but the remaining initialization needs to be on the EDT.
Fixes #8215 
See also: https://github.com/flutter/flutter-intellij/issues/8100 
---
<details>
- Dart …

[PE] fix read context EDT juggling in `FlutterInitializer`

---

CHANGELOG.md
resources/META-INF/plugin.xml

- Fix for empty menu item in the device selector (#8264)

Update the M86 CHANGELOG.md with an additional entry

---

.gitignore

See https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.gitignore

Follow modern best practice from JetBrains and ignore all content under .idea & other .gitignore changes

---

flutter-idea/src/io/flutter/run/daemon/DaemonApi.java
flutter-idea/src/io/flutter/run/daemon/DevToolsServerTask.java
flutter-idea/src/io/flutter/run/daemon/FlutterApp.java

This was for versions of Dart SDK < v2.15 which is very outdated

Remove code for managing daemon startup of DevTools

---

flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
flutter-idea/src/io/flutter/dart/FlutterRequestUtilities.java

Fix nullability problems in `src/io/flutter/dart/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/dart/` as null-"clean".
---
<details>
- Java and Kotlin contributions should strive to follow …

[CQ] fix nullability problems for `flutter/dart`

---

flutter-idea/src/io/flutter/inspections/FlutterDependencyInspection.java

Fix nullability problems in `src/io/flutter/inspections/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/inspections/` as null-"clean".
---
<details>
- Java and Kotlin contributions should …

[CQ] fix nullability problems for `flutter/inspections`

---

flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java

Addresses https://github.com/flutter/flutter-intellij/issues/8298

Add Flutter and Dart versions to survey URL

---

src/io/flutter/test/DartTestEventsConverterZ.java

Follow-up from https://github.com/flutter/flutter-intellij/pull/8367, a missed unchecked assignment.
---
<details>
</details>

[CQ] fix unchecked assignment

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/sdk/FlutterSearchableOptionContributor.java

This removes all add(..) lines that are not expressed in the UI form
This resolves https://github.com/flutter/flutter-intellij/issues/7857

Cleanup the SearchableOptionContributor in the Flutter IJ Plugin

---

src/io/flutter/toolwindow/ToolWindowBadgeUpdater.java

Fix typo in https://github.com/flutter/flutter-intellij/pull/8395.
---
<details>
</details>

[fix] Debug badge update fix

---

src/io/flutter/pub/PubRoot.java

This resolves https://github.com/flutter/flutter-intellij/issues/8438 ahead of the 87.1 point release

Fix the isResolutionWorkspace exception in the new project action

---

docs/Demo-Tips.md

This plugin is no longer being maintained.
https://plugins.jetbrains.com/plugin/7345-presentation-assistant-for-2023-2/versions
---
<details> …

[docs] remove stale plugin recommendation

---

src/io/flutter/run/test/FlutterTestRunner.java

Update test runner to use PluginLogger
