- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- remove the web/desktop user preference
This had been enabled via passing in an environment variable. Now, the way to enable this is via the flutter command line tool. Specifically, for web:
```
flutter config --enable-web
```
That setting will take effect on the master and dev channels currently; the user will need to restart IntelliJ for the setting to take effect. We may want to mention the change in our release notes.
cc @jonahwilliams
> remove the web/desktop user preference

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/OpenEmulatorAction.java
- src/io/flutter/actions/OpenSimulatorAction.java
- src/io/flutter/android/AndroidEmulator.java
- src/io/flutter/android/AndroidSdk.java
- src/io/flutter/run/daemon/DeviceService.java
- src/io/flutter/sdk/AndroidEmulatorManager.java
- src/io/flutter/sdk/XcodeUtils.java
- src/io/flutter/utils/SystemUtils.java
- address some issues with blocking the EDT thread in 2019.2
- fix https://github.com/flutter/flutter-intellij/issues/3697, fix https://github.com/flutter/flutter-intellij/issues/3696
2019.2 changed to complaining if we use a synchronous process execution library call from the EDT thread (and request to block for greater than 10ms).
Depending on whether we receive lots of user reports of this or not, we may choose to cherry-pick this into current stable. If we see few reports, we can assume that its not affecting users, and it can wait until the next stable (eta, ~1 week).
This does have the nice side benefit that the startup of the plugin is likely faster by 1-3 seconds.
> address some issues with blocking the EDT thread in 2019.2

- src/io/flutter/logging/FlutterConsoleLogManager.java
- update the flutter error display wrt the header and footer ansi chars
- fix https://github.com/flutter/flutter-intellij/issues/3680
We output a header and footer string that are >= 100 chars long, with the error message centered 1/3 of the way on the header line.
cc @DanTup for the VS Code work
Here is the current display from the 3 error messages generated by the `flutter_error_studies` app:
> update the flutter error display

- flutter-studio/src/io/flutter/project/ChoseProjectTypeStep.java
The New Project Wizard project descriptions enablement could get out of sync with the selection if someone tried dragging the buttons.
Fixes #3679 
@jacob314 @kenzieschmoll
> Fix highlighting of project descriptions

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- flutter-studio/src/io/flutter/project/FlutterProjectModel.java
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/module/settings/ProjectType.form
- src/io/flutter/module/settings/ProjectType.java
- src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
- src/io/flutter/sdk/FlutterSdkVersion.java
- testSrc/unit/io/flutter/android/AndroidxTest.java
@devoncarew 
Adds UI and logic to support creating projects (and modules) that use AndroidX. Note that modules are created in the style of their host project, so there is no new UI for modules.
Fixes #3616
IntelliJ:
Android Studio:
> Add AndroidX option to new project wizards

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
This fixes two problems discovered during testing.
Flutter modules can use AndroidX. I thought they couldn't when I wrote the code.
The selected SDK should be used determine visibility of the AndroidX section. It wasn't getting updated properly.
> Fix androidx modules

- src/io/flutter/module/settings/ProjectType.java
It is possible for the Flutter SDK to be not set when the first project is created. This change allows the wizard to operate.
> Guard against null sdk

- src/io/flutter/editor/ActiveEditorsOutlineService.java
- fix a ConcurrentModificationException in ActiveEditorsOutlineService.java
- fix https://github.com/flutter/flutter-intellij/issues/3725
If we see more reports of this issue, we may consider patching it into M38.
> fix a ConcurrentModificationException in ActiveEditorsOutlineService.java

- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/vmService/VmServiceWrapper.java
- pass in the `disableBreakpoints: true` option in places where we eval code
(note: not necessarily for landing for the current release)
> pass in disableBreakpoints

- src/io/flutter/preview/PreviewView.java
- address a setPreferredFocusableComponent() warning in the IntelliJ log
> WARN - j.openapi.wm.impl.IdeFrameImpl - Set preferredFocusableComponent in 'null' content in Flutter Outline tool window to avoid focus-related problems.
> address a setPreferredFocusableComponent() warning in the IntelliJ log

- src/io/flutter/view/TogglePlatformAction.java
Added a print so that we can catch cases where we are getting an unknown platform target.
Fixes https://github.com/flutter/flutter-intellij/issues/3771.
> Fix ArrayIndexOutOfBounds for target platform selector.

- src/io/flutter/run/daemon/DeviceDaemon.java
- convert an error to a warning
We were logging this issue as an error, which is user visible. Instead we now log as a warning, and reply on the existing user notification on `DeviceDaemon.RESTART_ATTEMPTS_BEFORE_WARNING + 1` attempts.
> convert an error to a warning

- src/io/flutter/vmService/frame/DartVmServiceValue.java
- improve `computeDefaultPresentation()` in the debugger
When calculating the presentation to use for variables in the debugger, only call `toString()` on a VM object if we don't already have the full toString value locally. This aids in debugging flutter web apps, as `package:dwds` does not yet support the `invoke()` service protocol call (https://github.com/dart-lang/webdev/issues/591).
> improve computeDefaultPresentation

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/settings/FlutterSettings.java
Fixes https://github.com/flutter/flutter-intellij/issues/3808
> Enable structured errors by default.

- src/io/flutter/module/FlutterGeneratorPeer.java
Fixes #3626, sorta. It really just kicks the can down the road. After eliminating the EDT problem a new exception is thrown because the current wizard step should not be the last wizard step. That'll have to wait; it is merely a log assertion anyway (but is visible to users).
> Runs doNextAction() on EDT

- flutter-studio/src/io/flutter/project/FlutterProjectModel.java
AndroidX support is currently broken for Flutter modules so we shouldn't assume people want it by default.
> Change AndroidX default to false

- flutter-intellij-community.iml
- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/actions/OpenInAndroidStudioAction.java
Finding Android Studio can cause a warning about synchronous execution on EDT. This will (probably) fix that. It needs more testing and should be queued for M40.
> Cache values that cause Edt-sync warnings

- src/io/flutter/ProjectOpenActivity.java
- address an instance of process execution on the EDT
Instead of `invokeLater()` - which runs the closure on the EDT - call `executeOnPooledThread()`.
@stevemessick
> address an instance of process execution on the EDT

- src/io/flutter/editor/FlutterSaveActionsManager.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- remove use of some deprecated calls in `FlutterSaveActionsManager.java `
- fix the name for the `isOrganizeImportsOnSaveKey()` method; => `isOrganizeImportsOnSave()`
- move the `myShowStructuredErrors` setting up a bit in the preference page, so that the enabled by default settings show before the disabled by default ones
> remove use of some deprecated calls

- src/io/flutter/project/FlutterIconProvider.java
- fix an NPE in FlutterIconProvider.java
```
at io.flutter.project.FlutterIconProvider.getIcon(FlutterIconProvider.java:65)
at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:101)
at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$2(ElementBase.java:97)
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
```
> fix an NPE in FlutterIconProvider.java

- resources/META-INF/plugin.xml
- tool/plugin/lib/plugin.dart
- tool/plugin/pubspec.yaml
- fix the changelog markdown translation
This was broken by the latest release of `package:markdown`.
@stevemessick
> fix the changelog markdown translation

- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
- src/io/flutter/actions/FlutterExternalIdeActionGroup.java
- src/io/flutter/actions/OpenInAndroidStudioAction.java
- src/io/flutter/utils/AndroidUtils.java
- src/io/flutter/utils/FlutterModuleUtils.java
In IntelliJ, project creation was throwing an error because Android Studio classes were not found. The code block doing that has been disabled for now; it needs to be updated with the proper Gradle hooks when the next phase of add-to-app for IntelliJ commences.
The `Open in Android Studio` menu was flakey. Sometimes it did not appear; other times it was disabled. It has been changed to work all the time (I hope). Instead of relying on dynamic replacement of the action object, we now check at runtime and use the Android Studio one when needed. (I tried using chameleon actions here but could not get that to work, possibly due to action references in plugin.xml.)
> Fix problems discovered during testing M40

- LICENSE
Harmonizing the LICENSE file with other Flutter projects. This change is purely to whitespace; the language of the license is unchanged. With these changes, GitHub should now recognize it as a BSD-3 license (the non-standard comment markers seem to break the detection algorithm).
> Cosmetic fix

- src/io/flutter/utils/AndroidUtils.java
- address a compilation problem against 2019.2
I wasn't able to compile locally against 2019.2; I'm not sure if user's would see this issue or not, but in-lining a small bit of the android `SdkConstants` seems low risk.
@stevemessick
> address a compilation problem against 2019.2

- src/io/flutter/perf/DocumentFileLocationMapper.java
- src/io/flutter/perf/FileLocationMapper.java
- src/io/flutter/perf/FlutterWidgetPerf.java
- fix an NPE in DocumentFileLocationMapper.java (seen via crash reporting)
```
io.flutter.perf.DocumentFileLocationMapper.getText(), DocumentFileLocationMapper.java:98
io.flutter.perf.FlutterWidgetPerf.lambda$onWidgetPerfEvent$2(), FlutterWidgetPerf.java:184
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(), ApplicationImpl.java:946
io.flutter.perf.FlutterWidgetPerf.onWidgetPerfEvent(), FlutterWidgetPerf.java:225
io.flutter.perf.VmServiceWidgetPerfProvider.onWidgetPerfEvent(), VmServiceWidgetPerfProvider.java:93
io.flutter.perf.VmServiceWidgetPerfProvider.onVmServiceReceived(), VmServiceWidgetPerfProvider.java:182
```
The NPE was https://github.com/flutter/flutter-intellij/compare/master...devoncarew:fix_npe_23?expand=1#diff-d56ac0069855b6e0d47e1ae6fbe88902L98 - I …
> fix an NPE in DocumentFileLocationMapper.java

- src/io/flutter/run/daemon/FlutterApp.java
- ignore errors from `app.stop`
- fix https://github.com/flutter/flutter-intellij/issues/3956
These are often reporting that the app is no longer running.
> ignore errors from app.stop

- src/io/flutter/run/daemon/DeviceSelection.java
- fix an issue where non-ephemoral device selection wouldn't persist
- fix https://github.com/flutter/flutter-intellij/issues/3871
> fix an issue where non-ephemoral device selection wouldn't persist

- src/io/flutter/console/FlutterConsoleFilter.java
- fix the offset of console hyperlink detection
This would show up when there was text printed before the line being hyperlinked.
> fix the offset of console hyperlink detection

- src/io/flutter/view/TogglePlatformAction.java
- src/io/flutter/vmService/ServiceExtensionState.java
- src/io/flutter/vmService/VMServiceManager.java
- fix an npe when switching platforms
```
io.flutter.view.PlatformTargetAction.setSelected(), TogglePlatformAction.java:137
io.flutter.view.PlatformTargetAction.lambda$update$1(), TogglePlatformAction.java:111
io.flutter.utils.EventStream.listen(), EventStream.java:115
io.flutter.view.PlatformTargetAction.update(), TogglePlatformAction.java:110
com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(), ActionUtil.java:174
com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(), ActionUpdater.java:375
com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$null$1(), ActionUpdater.java:78
com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(), ActionUpdater.java:106 …
```
> fix an npe when switching platforms

- src/io/flutter/inspector/EvalException.java
- src/io/flutter/inspector/EvalOnDartLibrary.java
- add more info to eval() exceptions
We see a fair amount of CompletionExceptions coming from the inspector eval. Many of them have the message 'Server error'; this PR adds more info to the failures, so we can identify in what cases they occur, and better know where to handle the  CompletionException in the inspector codebase.
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Server error
java.util.concurrent.CompletableFuture.encodeThrowable(), CompletableFuture.java:292
java.util.concurrent.CompletableFuture.completeThrowable(), CompletableFuture.java:308
java.util.concurrent.CompletableFuture.uniApply(), CompletableFuture.java:593
java.util.concurrent.CompletableFuture$UniApply.tryFire(), CompletableFuture.java:577 …
```
> add more info to eval() exceptions

- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/FlutterViewFactory.java
- change the inspector tool window to not only show when an app is running
This addresses an issue where, when the inspector view closed when an app closes, it closes the right tool window sidebar. This would also hide the Flutter Outline view - that's not desirable as there are already enough discoverability issues with the sidebar views.
When the Inspector is open and there's no application running, the content says 'No running applications'.
> change the inspector tool window to not only show when an app is running

- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/perf/FlutterWidgetPerf.java
- src/io/flutter/perf/VmServiceWidgetPerfProvider.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/utils/AsyncRateLimiter.java
- src/io/flutter/view/BoolServiceExtensionCheckbox.java
- src/io/flutter/view/FlutterPerfView.java
- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/InspectorPanel.java
- src/io/flutter/vmService/VMServiceManager.java
- address several warnings in the IntelliJ log about leaked resources
It looks like the pattern for using the IntelliJ auto dispose mechanism is to register the disposal via `Disposer.register(parent, child)`, and then actually do the dispose using `Disposer.dispose()` (and not by calling `dispose()` on the object directly).
> address several warnings in the IntelliJ log about leaked resources

- src/io/flutter/inspector/EvalOnDartLibrary.java
- don't invoke eval when shutting down
As follow-up to the resource leak PR, we can now occasionally try and invoke eval on an inspector that's been disposed. This PR prevents that.
> don't invoke eval when shutting down

- src/io/flutter/view/PerfMemoryTab.java
- src/io/flutter/vmService/HeapMonitor.java
- src/io/flutter/vmService/VMServiceManager.java
- src/io/flutter/vmService/VmServiceWrapper.java
- detect whether the vm service connection supports the `getMemoryUsage` API
- cleanup code around memory polling to move more of the domain knowledge from `VMServiceManager` into `HeapMonitor`
Instead of polling the vm connection once a second for the device's memory usage, we use the error return code to detect whether that connection supports the `getMemoryUsage()` API (package:dwds doesn't currently support it). If it doesn't support the API we stop polling.
> detect whether the vm service connection supports the getMemoryUsage API

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
Android Studio doesn't always show the Project view when a project is created and opened for the first time. This makes it do so.
> Force AS to show the Project view

- src/io/flutter/run/FlutterPositionMapper.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/bazelTest/BazelTestRunner.java
- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/vmService/VmServiceConsumers.java
- src/io/flutter/vmService/VmServiceWrapper.java
- testSrc/unit/io/flutter/run/FlutterPositionMapperTest.java
- remove support for file path breakpoints (continue to send in `file:`, `dart:`, and `package:` breakpoint uris); file paths are no longer used with the switch to the CFE
- handle multiple vm breakpoints better; register all successful vm breakpoints created from a user breakpoint; only convert the user breakpoint to a 'breakpointFailed' type if no vm breakpoints succeeded
Additional cleanup to the codebase while working in this area:
- renamed the `PositionMapper` class to `FlutterPositionMapper` to avoid a name conflict with an other `PositionMapper`
> remove support for file path breakpoints; handle multiple vm breakpoints better

- AUTHORS
- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/DaemonEvent.java
- src/io/flutter/run/daemon/DeviceDaemon.java
The devices list was keeping showing "Loading..." in Android Studio.
Windows 10, Android Studio `3.5.1`, Flutter `1.9.1+hotfix.5`, flutter-intellij `4.2.2`
May be related to #3892
Flutter-doctor is able to detect the devices. Android Studio logs showed that AS didn't receive the "device.enable" command response. Just putting some breakpoints were solving the issue, identifying a race condition (sending the command too early).
The fix waits for the "daemon.connected" before sending any commands.
I was not able to correctly build the plugin. The version I built showed the fix is working, but other stuff were broken. It may be caused by me using the "master" version of the plugin in AS 3.5.1, or by bad project/dependencies configuration.
> Wait Device Daemon connected to prevent race condition in devices list

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterUtils.java
- src/io/flutter/dart/DartSyntax.java
- src/io/flutter/editor/ActiveEditorsOutlineService.java
- src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/project/FlutterIconProvider.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/pub/PubRootCache.java
- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/common/CommonTestConfigUtils.java
- src/io/flutter/run/common/TestLineMarkerContributor.java
- src/io/flutter/run/test/FlutterTestConfigProducer.java
- src/io/flutter/run/test/FlutterTestLocationProvider.java
- src/io/flutter/run/test/TestConfigUtils.java
- src/io/flutter/util/DartTestLocationProviderZ.java
- src/io/flutter/utils/FlutterModuleUtils.java
- testSrc/unit/io/flutter/testing/FakeActiveEditorsOutlineService.java
- address some performance issues with displaying test markers
- fix https://github.com/flutter/flutter-intellij/issues/4012
The main portion of this PR is introducing a project service - `PubRootCache` - that caches the parsed pubspec info and `PubRoot`s. This information is requested frequently, especially when visiting the PSI AST of a Dart file, when looking for nodes that match `test` and `group`s in order to create in-line run line markers.
> address some performance issues with displaying test markers

- src/io/flutter/inspector/EvalOnDartLibrary.java
- fix an issue with using an alarm after its been disposed
- fix https://github.com/flutter/flutter-intellij/issues/4049
We'll likely see a few issues like this, now that we're being better about disposing of resources after a launched app terminates.
> fix an issue with using an alarm after its been disposed

- src/io/flutter/actions/AttachDebuggerAction.java
IntelliJ seems to have tightened the expectations on UI performance, and we may be lagging.
The event used here changes status from running to canceled by the time the code at line 107 executes. Once canceled, we can't get the project anymore.
Also, Android apps (without Flutter) won't display the attach button. After a module is added the button needs to be made visible again (without restarting the IDE).
> Re-enable attach button for add-to-app projects

- src/io/flutter/preview/PreviewViewState.java
- src/io/flutter/sdk/FlutterPluginLibraryProperties.java
- silence a log warning
```
WARN - com.intellij.util.xmlb.Binding - no accessors for class io.flutter.sdk.FlutterPluginLibraryProperties 
WARN - com.intellij.util.xmlb.Binding - no accessors for class io.flutter.preview.PreviewViewState 
```
> silence a log warning

- src/io/flutter/run/daemon/DeviceService.java
- reduce the severity of a warning (issues starting the device daemon up are already reported to the user)
- remove an obsolete todo:
> reduce the severity of a warning

- docs/testing.md
- flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
- flutter-studio/src/io/flutter/module/FlutterModuleModel.java
- flutter-studio/src/io/flutter/module/ImportFlutterModuleStep.java
- src/io/flutter/FlutterUtils.java
- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/actions/FlutterBuildActionGroup.java
Address all P1 items in #4064.
cc: @xster 
Start Android Studio and use the File > New > New Project menu to fire 
up the new project wizard. Choose the template that includes a Basic
Activity. One the next page, use Kotlin and minimum API level 16.
Let the system stabilize (Gradle sync).
Close the editor for content_main.xml. Switch the Project view to
the Project Files mode. Collapse the Gradle window if it is open.
Use the File > New > New Module menu to start the new module wizard.
Choose the Flutter Module template. Fill out the wizard pages and
click Finish, then wait a bit. Android Studio needs to do two
successive Gradle sync's. The first one generates an error message,
which is corrected by the second one. Ignore the error. Let the
system stabilize again.
Go to the editor for …
> Support for debugging add-to-app modules in Android Studio

- flutter-intellij-community.iml
- flutter-intellij.iml
- product-matrix.json
@jacob314 I added the library to both module definitions. I only tested the one I'm using. I think this is safe, but it it causes problems we can revert the change to fultter-intellij.iml.
> Build for Android Studio beta 4 and later

- src/io/flutter/editor/ActiveEditorsOutlineService.java
listers was accessed on the main and background threads without synchronization.
> Fix cases where ActiveEditorsOutlineService as not thread safe.

- flutter-studio/src/io/flutter/module/FlutterModuleStep.java
Add the project location field to the new module wizard when running from an Android app.
The UI looks the same as a new project using the module template.
> Allow defining location of Android modules

- src/io/flutter/editor/WidgetIndentsHighlightingPass.java
- src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- remove the two secondary UI guides settings
- closes https://github.com/flutter/flutter-intellij/issues/4001
@jacob314 @InMatrix 
The new settings page UI:
> remove the two secondary UI guides settings

- src/io/flutter/utils/AndroidUtils.java
Force synchronous VFS refresh to prevent adding multiple, redundant include statements to settings.gradle.
> Force VFS refresh to prevent adding multiple include statements

- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorService.java
- add some more logging information to help diagnose the 'method not found' errors
- some work towards addressing https://github.com/flutter/flutter-intellij/issues/4048
@jacob314
> add some more logging information to help diagnose the 'method not found' errors

- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
We can't currently restrict installation of the beta plugin into Android Studio canary. When trying to create a project you get an error. This adds a catch-block for that error which pops up a message, rather than just reporting a random error.
Hopefully, this will reduce the number of issues like #4136
> Show error dialog when creating a project with canary builds

- .travis.yml
- product-matrix.json
- resources/META-INF/plugin.xml
- tool/plugin/test/plugin_test.dart
- update the product matrix for 2019.3 stable
- remove support for `2019.1` (but keep the 2019.1 based Android Studio 3.5 build)
@stevemessick
> update the product matrix for 2019.3 stable

- docs/testing.md
- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
- flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
- flutter-studio/src/io/flutter/module/FlutterModuleModel.java
- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/actions/AttachDebuggerAction.java
- src/io/flutter/utils/AndroidUtils.java
Finish up some in-progress changes and clean up a few things for add-to-app:
- Add Java code to the testing instructions, and note that both Java and Kotlin need to be tested.
(The compileOptions section is added when using Kotlin but not Java.)
- Eliminate redundant Gradle sync listeners (cleans up duplicated lines in settings.gradle).
- Change the build.gradle editing to use the proper framework. Add compileOptions.
- Use the module location setting that was added to the UI in a previous PR.
- Set the project type to "io.flutter" when a project is created so it doesn't use the default.
- If there is only one Flutter run config, use it for attach whether it is selected or not.
- Remove TODOs that only apply to IJ support for add-to-app. That isn't happening.
> Smooth out the rough spots in add-to-app support

- src/io/flutter/view/FlutterView.java
Remove the nonsense `if (hasExtension) call`.
> Fix bug with missing inspector selection icon on Flutter builds without the "enableOnDeviceInspector" extension.

- src/io/flutter/editor/PropertyEditorPanel.java
Add tooltips including the property name in bold.
Screenshot of the tweaked UI with ellipsis showing for property names that are too long.
> Force property labels to respect the column width in the widget property editor.

- src/io/flutter/samples/FlutterSampleNotificationProvider.java
- remove some (unnecessary) OS path conversions
It turns out that the paths we're getting from `VirtualFile` are already OS independent (normalized to forward slash); the additional normalizations were harmless but not necessary.
@kenzieschmoll
> remove some (unnecessary) OS path conversions

- src/io/flutter/editor/PropertyEditorPanel.java
- src/io/flutter/preview/PreviewView.java
Fix bad default where text fields were auto scrolled to the end resulting in empty content for long properties.
Remove some over aggressive filtering out of properties back from when we were trying to render this as a popup instead of a sidebar window.
Change the text from Widget Properties to just Properties.
Before:
After:
> Polish property display.

- src/io/flutter/editor/ActiveEditorsOutlineService.java
- fix two NPEs from the outline view
- fix https://github.com/flutter/flutter-intellij/issues/4187
The VirtualFile.getCanonicalPath() call can return null for some file (editor?) types.
> fix two NPEs from the outline view

- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorService.java
- provide more stack trace details for inspector timeouts
This will help us track down issues like https://github.com/flutter/flutter-intellij/issues/4189 - to know whether they represent real problems, or things that we should ignore (not log as errors) at the call sites.
> provide more stack trace details for inspector timeouts

- src/io/flutter/sdk/FlutterSdk.java
- if track widget creation is not enabled, pass in --no-track-widget-creation
- fix https://github.com/flutter/flutter-intellij/issues/4130
> if track widget creation is not enabled, pass in --no-track-widget-creation

- flutter-studio/flutter-studio.iml
- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
- src/io/flutter/actions/AttachDebuggerAction.java
- tool/plugin/lib/plugin.dart
When an Android project containing an add-to-app module is opened, add a listener that detects app launches. The listener then launches `fluter attach` for it. The Attach button on the toolbar will seldom need to be used; only when there are multiple Flutter run configs is it needed. In conjunction, change the Attach button to be disabled when the attach process is running, and re-enable it when the process terminates.
@xster I'm not sure if this gets everything in the video you added to #4064, but I'll get you a new build to check out.
@devoncarew @DaveShuckerow for review.
> Launch flutter attach when the Android app starts

- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/pub/PubRoot.java
- fix an issue with the 'pub update needed' notification showing when things were already up to date
- fix https://github.com/flutter/flutter-intellij/issues/4224
> fix an issue with the pub notification showing when things were already up to date

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- rename an action; `Flutter Widget...` ==> `Extract Flutter Widget...` (it wasn't clear in context what the action would perform)
before the change:
> rename a flutter refactor action

- src/io/flutter/inspector/InspectorTree.java
- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/InspectorPanel.java
- draw a separator line between the main inspector tree and the details tree
- remove an override that will be removed from the platform in the 2020.1 version
> draw a separator line between the main inspector tree and the details tree

- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
refactor the reload on save implementation:
- stop using an app global `handlingSave` flag (if this ever gets out of sync, reload on save will stop working until IntelliJ is restarted)
- switch to using the FlutterApp state to indicate that a reload is - or will soon be - in progress
- rename a preference method reload to reload on save for clarity
- some cleanup around the UI of reload on save for consistency w/ the different ways it can be invoked
- fix https://github.com/flutter/flutter-intellij/issues/3235
> refactor the reload on save implementation

- src/io/flutter/vmService/FlutterFramesMonitor.java
We were hard coding 60.0. Now we pull the actual refresh rate from the VM and use it in our frame calculation. Verified that we correctly show 90.0 FPS for a pixel 4.
Before:
After:
Fixes https://github.com/flutter/flutter-intellij/issues/4205
> Remove hard coded refresh rate for fps calculation.

- src/io/flutter/utils/FlutterModuleUtils.java
If you have the option set to convert multiple imports from a package into a single implicit import, and you change the explicit import of IntelliJ's `Module` into `*`, and you are using Java 8, you will break compilation using Java 11.
> Restore ability to use Java 11

- src/io/flutter/performance/PerfWidgetRebuildsPanel.java
- selectable area is now restricted to the checkbox and its text - not the entire width of the row.
- changes the alignment of the second checkbox in the setting panel to match the track widget rebuilds checkbox.
Fixes https://github.com/flutter/flutter-intellij/issues/4254
> Restrict checkbox selectable region in performance window.

- src/io/flutter/view/InspectorPanel.java
- don't process refresh requests for apps which have terminated
- fix https://github.com/flutter/flutter-intellij/issues/4293 (`'parent: ... has already been disposed'`)
> don't process refresh requests for apps which have terminated

- kokoro/macos_external/continuous.cfg
- kokoro/macos_external/kokoro_build.sh
- kokoro/macos_external/presubmit.cfg
- tool/kokoro/build.sh
First cut at defining build files for Kokoro. This version does nothing. It will be useful to verify the config is correct before digging into the actual build mechanics.
@athomas @devoncarew @keertip
> Kokoro build configuration

- src/io/flutter/NotificationManager.java
- src/io/flutter/performance/FrameRenderingDisplay.java
- src/io/flutter/performance/PerfFPSPanel.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/vmService/DisplayRefreshRateManager.java
- src/io/flutter/vmService/FlutterFramesMonitor.java
- src/io/flutter/vmService/VMServiceManager.java
This warns the user when an invalid refresh rate was received and uses the default (60 FPS) instead.
> Defend against invalid refresh rates for flutter desktop devices.

- kokoro/macos_external/kokoro_build.sh
- kokoro/macos_external/kokoro_test.sh
- tool/kokoro/build.sh
- tool/kokoro/setup.sh
- tool/kokoro/test.sh
Distinguish build vs test runs by looking at the job name and do no more work than necessary in each.
> Separate build vs test scripts

- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
simplify the logic we use to prevent reload on save:
- remove the logic that would block a reload on save if there are analysis errors in the project; this was overly conservative - errors in tests shouldn't block reload, as well as errors in code that's not part of the app's execution path
- revert back to some older logic which does block reload on save if there are analysis errors in the file currently being edited (and that file is a Dart file)
cc @InMatrix for fyi about the UX change (to remove blocking reload on save on analysis errors - which had been discussed - but to continue to block on a much stricter sub-set; analysis errors in the current file)
> simplify the logic we use to prevent reload on save

- .idea/libraries/com_google_protobuf_protobuf_java_3_5_1.xml
- .idea/libraries/org_powermock_powermock_api_mockito2_2_0_2.xml
- .idea/libraries/org_powermock_powermock_module_junit4_2_0_2.xml
- CONTRIBUTING.md
Keep info about maven libs under git: libs will get auto-downloaded for new contributors as soon as they open the project.
To reviewers: please check `com_google_protobuf_protobuf_java_3_5_1.xml`, `org_powermock_powermock_api_mockito2_2_0_2.xml`, and `org_powermock_powermock_module_junit4_2_0_2.xml` files in your local project setup. I guess they are 100% equivalent to the ones from this PR - this means that this PR is safe to accept. Otherwise, we should first understand why these files are different on your end.
> Simplify flutter-intellij project setup for new contributors

- src/io/flutter/FlutterUtils.java
- src/io/flutter/run/FlutterRunConfigurationType.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/run/bazel/BazelRunner.java
- src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
The effect is as if 'Allow parallel run' check box is always checked (but it doesn't appear in UI at all).
> Don't use deprecated API. Hide 'Allow parallel run' checkbox.

- tool/plugin/lib/plugin.dart
`git` suddenly started complaining about argument order.
> Fix git arg order

- src/io/flutter/FlutterErrorReportSubmitter.java
- src/io/flutter/editor/FlutterCompletionContributor.java
- move away from use of deprecated APIs (planned for removal in IntelliJ 2020.3)
```
JBUI.scale() (2) (scheduled for removal in a future release)
- Deprecated method JBUI.scale() is invoked in FlutterCompletionContributor.findIcon(). This method will be removed in a future release
- Deprecated method JBUI.scale() is invoked in FlutterCompletionContributor.<clinit>(). This method will be removed in a future release
ErrorReportSubmitter.submit() (1) (scheduled for removal in 2020.3)
- Deprecated method ErrorReportSubmitter.submit() is overridden in class FlutterErrorReportSubmitter. This method will be removed in 2020.3
ErrorReportSubmitter.submitAsync() (1) (scheduled for removal in 2020.3)
- Deprecated method ErrorReportSubmitter.submitAsync() is overridden in class …
```
> remove use of deprecated APIs

- tool/kokoro/setup.sh
- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
The initial dev channel support only built the specs that identified as dev channel specs. This makes a number of changes in how things are built:
- A dev channel build produces all versions
- A master branch build produces all versions, plus the version for integration tests
- A release build produces only the versions intended to be published (no change)
The dev channel version is now derived from the previous release and the number of weeks since its branch was committed. This is how it looks in the plugin management page:
(There may be unresolved issues with point releases. I couldn't test that.)
I did a little refactoring, too. Initialization of globals was really confusing, and now that it has to be done async it needed to be cleaned up.
@devoncarew
> Change the plugin tool to properly build the dev channel

- CONTRIBUTING.md
- README.md
- docs/android.md
- docs/testing.md
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- resources/inspectionDescriptions/FlutterDependency.html
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/run/LaunchState.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
Replace instances of:
- [flutter.io]() with [flutter.dev]()
- [www.dartlang.org]() with [dart.dev]()
- [docs.flutter.io]() with [api.flutter.dev]()
Also fix a broken image link and remove a reference to Flutter being a mobile-only SDK
> Tidy up old domain name links

- .gitignore
- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
- src/io/flutter/sdk/AbstractLibraryManager.java
- src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
This makes a few changes to the new project wizard.
- Use the --package-name option to pass the package name to `flutter create`
- Simplify the layout of the settings page, making it more compatible with Android Studio
- Remove company domain
- Make the package name a text field instead of a label that converts to a text field when edited
- Add some annotations
It also disallows committing project roots while the indexer is running.
Fixes #4352
> Use --package-name in flutter create

- src/io/flutter/sdk/AbstractLibraryManager.java
Remove usage of @internal API, and ensure write access and smart mode before updating the library model.
> Ensure indexing is finished before updating library model

- src/io/flutter/view/FlutterView.java
- no longer depend on JBRunnerTabs implementing Disposable
- fix https://github.com/flutter/flutter-intellij/issues/4405
@stevemessick
> no longer depend on JBRunnerTabs implementing Disposable

- flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/FlutterSettingsStepFixture.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/NewFlutterProjectWizardFixture.java
- flutter-studio/testSrc/io/flutter/tests/gui/NewProjectTest.java
- flutter-studio/testSrc/io/flutter/tests/util/WizardUtils.java
Normally, I would have deleted
```java
//@RunWith(GuiTestSuiteRunner.class)
```
but I'm still trying to understand when I want which runner. WIP.
Another puzzle I'm concerned with is why, when the test framework creates a new package, it opens `README.md` instead of `main.dart`. I changed the test to match the behavior, but I don't understand the behavior. It works as expected when I manually create a package. Also WIP.
> Revive GUI test NewProjectTest

- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/bazelTest/BazelTestLaunchState.java
- src/io/flutter/run/daemon/DaemonConsoleView.java
- src/io/flutter/run/test/TestLaunchState.java
Fix an issue with discovering hyperlinks in test consoles:
- add a `DartConsoleFilter` console filter to the test console
- some related cleanup and normalization to our filters for various consoles
- fix https://github.com/flutter/flutter-intellij/issues/4429
- fix https://github.com/flutter/flutter-intellij/issues/3851
We'd never contributed a `DartConsoleFilter` to the test consoles before (which we should have), and recent changes in the `FlutterConsoleFilter` had caused the test console hyperlink support to regress further.
@gspencergoog, this will likely address the issue you're seeing. We have a release scheduled for next Friday, so you'll see this change then. If you want to try out a version before that, we now have a beta channel that gets automatically pushed to every Sunday …
> fix an issue with discovering hyperlinks in test consoles

- src/io/flutter/logging/FlutterConsoleLogManager.java
- improve how we calculate when to summarize flutter errors
- fix https://github.com/flutter/flutter-intellij/issues/4363
Instead of deciding to summarize errors subsequent to the first error after a reload, we instead summarize errors subsequent to the first error after a frame event. Those errors are more likely to be errors (overflow, ...) triggered by the first error.
From the flutter error sample app, navigating to the material error, then the overflow error, you can see now that the overflow triggered by the material error is summarized, but the later overflow from the overflow page is not.
...
> improve how we calculate when to summarize flutter errors

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/actions/FlutterPackagesGetAction.java
- src/io/flutter/actions/FlutterPackagesUpgradeAction.java
- src/io/flutter/editor/FlutterPubspecNotificationProvider.java
- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkVersion.java
- add support for 'flutter pub outdated' (expose it in the pubspec file's header action bar); this is contingent on having a recent enough Flutter SDK
- remove `flutter upgrade` from the pubspec file's header action bar
- rename user facing references to `flutter packages` to `flutter pub`
- fix https://github.com/flutter/flutter-intellij/issues/4439
- fix https://github.com/flutter/flutter-intellij/issues/4440
> add support for 'flutter pub outdated'

- src/io/flutter/actions/DeviceSelectorAction.java
For example, Android apps (without add-to-app) or Java projects do not need the device selector.
> Only show the Flutter device selector in projects that have a Flutter module

- src/io/flutter/run/FlutterRunConfigurationType.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazelTest/BazelTestFields.java
- src/io/flutter/run/bazelTest/BazelTestLaunchState.java
- src/io/flutter/run/bazelTest/BazelTestRunner.java
- src/io/flutter/run/test/FlutterTestConfigType.java
- in-line run config names to address runtime warnings
These warnings are new, and are likely a result of the work that JetBrains is doing to better support I18N of IntelliJ.
```
2020-04-10 15:55:36,818 [   7666]   WARN - util.DeprecatedMethodException - The default implementation of ConfigurationFactory.getId is deprecated, you need to override it in io.flutter.run.FlutterRunConfigurationType$Factory. The default implementation delegates to 'getName' which may be localized but return value of this method must not depend on current localization. 
com.intellij.util.DeprecatedMethodException: The default implementation of ConfigurationFactory.getId is deprecated, you need to override it in io.flutter.run.FlutterRunConfigurationType$Factory. The default implementation delegates to 'getName' …
```
> in-line run config names to address runtime warnings

- src/io/flutter/editor/WidgetIndentsHighlightingPass.java
Fixes #4297 
Before (note line through `child:` briefly appears):
After:
> Prevent drawing child lines through other chars (https://github.com/flutter/flutter-intellij/issues/4297)

- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/utils/FlutterModuleUtils.java
Dart SDK path check was too stringent before, resulting in device selector not appearing for internal projects.
Before:
After (Mac):
After (Linux):
> Allow internal Dart SDK paths

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/actions/DeviceSelectorRefresherAction.java
- src/io/flutter/utils/FlutterModuleUtils.java
External project:
Internal project with gcert/prodaccess active:
Internal project that lost and regained prodaccess can refresh/retrieve devices menu (really slow on chrometop, sorry):
Eventually recovers device menu:
> Add device selector refresh button for internal projects

- src/io/flutter/actions/DeviceSelectorRefresherAction.java
Need to check for null project. I should have caught this in the code review.
> Add null check to device refresh

- src/io/flutter/run/bazelTest/BazelTestLaunchState.java
- src/io/flutter/run/test/TestLaunchState.java
Save all editors before launching test runner. This seems like something the IntelliJ framework should do, but it isn't happening when launched in debug mode.
Fixes #4548
> Save files before launching debug tests

- tool/plugin/lib/plugin.dart
- tool/plugin/lib/runner.dart
- tool/plugin/test/plugin_test.dart
- tool/travis.sh
There's more refactoring here since Gradle builds the plugin and we don't need to copy files or zip them up.
See the comment in runner.dart for yet another strange error that took some digging to find a work around.
This changes travis to use the Gradle builder. We'll see how well that works...
> Add "plugin make" that uses Gradle instead of Ant

- src/io/flutter/run/FlutterReloadManager.java
- remove a delay on hot reload
This delay was an artifact from when we used the results of the analysis server to inform whether we should issue a hot reload on save or not. We no longer use the analysis server results - we always reload, unless there are structural issues with the file (that info comes from IntelliJ's PSI model, and we don't need a delay to get that info).
Related to https://github.com/flutter/flutter/pull/55376.
cc @DanTup @jonahwilliams 
@stevemessick and @helin24 for review.
> remove a delay on hot reload

- src/io/flutter/run/SdkFields.java
- src/io/flutter/sdk/FlutterSdkVersion.java
https://github.com/flutter/flutter/pull/58118 added a flag to set structured errors on startup. This change sets the flag for the run command without requiring changes to an individual project's config.
Running with an early error should cause:
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running pod install...                                              1.7s
Running Xcode build...
Xcode build done.                                           33.6s
Waiting for iPhone SE (2nd generation) to report its views...
Debug service listening on ws://127.0.0.1:50854/5Ztl1ytHvmY=/ws
Syncing files to device iPhone SE (2nd generation)...
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following FormatException was …
```
> Display structured errors immediately

- src/io/flutter/console/FlutterConsoleFilter.java
The console filter regex was matching way too much. It is now restricted to a line that contains "Error" and does lazy matching.
> Use lazy regex with bounds

- src/io/flutter/sdk/FlutterSdk.java
App should be paused on run mode as well as on debug mode so we won't miss any events from the beginning of an app's running.
Verified that a project can be run without hangs in run mode (no breakpoints), profile mode, and release mode.
> Start paused during run mode

- resources/liveTemplates/flutter_miscellaneous.xml
- update the `InheritedWidget` template
- fix https://github.com/flutter/flutter-intellij/issues/4635
> update the InheritedWidget template

- product-matrix.json
Note that AS beta and canary use the same plugin build.
> Update product matrix for canary

- src/io/flutter/actions/DeviceSelectorAction.java
- fix a display issue with the device selector
This addresses an issue with the flutter device selector combo box collapsing for some workspace / toolbar configurations.
> fix a display issue with the device selector

- .gitignore
- flutter-intellij.iml
- src/io/flutter/editor/FlutterCompletionContributor.java
- src/io/flutter/editor/FlutterCupertinoColors.java
- src/io/flutter/editor/FlutterEditorAnnotator.java
- handle displaying previews of cupertino colors
https://github.com/flutter/flutter-intellij/pull/4628 added support for displaying previews of Cupertino icons; this PR updates the plugin to also display Cupertino color previews.
cc @stevemessick @helin24
> handle displaying previews of cupertino colors

- tool/colors/flutter/colors_cupertino.dart
- tool/colors/flutter/colors_material.dart
- tool/colors/generate_properties.dart
- tool/colors/update_colors.dart
- tool/grind.dart
This splits the `update_colors.dart` script into two scripts so it no longer calls itself (which simplifies debugging, and avoids getting into the situation where a broken generated file prevents running the script to regenerate it) and also consolidates the downloaded files so there's just one set.
Running `grind colors` works properly this time, and generates the same files that were in the repo - with the exception of the downloaded files being unformatted (I didn't commit the format changes because it would make this PR harder to review - I can add them once this is reviewed, or just send another PR with just the (un)formatting changes).
@devoncarew the rebase was messy, so I manually applied your changes to my existing change. If you think I've missed anything, let me know!
> Split icon generation into two scripts + use single set of downloaded files

- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/sdk/FlutterSdk.java
We reverted a change (https://github.com/flutter/flutter-intellij/pull/4673) that was similar to this one because it was breaking tests.
However, we still want to start with the app paused to catch early errors since we're now expecting structured errors from flutter_tools. If we do not start paused, there's a chance that the app will start running before flutter_tools has started listening for errors and we will miss early ones.
While looking into why run mode during tests doesn't resume app execution, I found that running tests (NOT in debug mode) uses the runner `DefaultRunProgramRunner` from the IntelliJ platform - it seems like we should be using a flutter-specific test runner for run and debug modes? But I'm not sure whether there's a reason we have been using the default runner.
I …
> Start paused for run mode and use FlutterTestRunner for run tests

- src/io/flutter/editor/ExpressionParsingUtils.java
- src/io/flutter/editor/FlutterEditorAnnotator.java
- testSrc/unit/io/flutter/editor/FlutterEditorAnnotatorTest.java
The goal of this pull request is to resolve the issue displaying color icons in IntelliJ Idea and Android studio for `Colors.fromARGB` and `Colors.fromRGBO` functions.
Added annotation support for `const Color.fromARGB`, `Color.fromARGB`, `const Color.fromRGBO`, `Color.fromRBGO`
Added helper functions to `ExpressionParsingUtils.java` to parse color components and create corresponding Color
Added unit tests
https://github.com/flutter/flutter-intellij/issues/3347
> [ISSUE-3347]

- src/io/flutter/run/MainFile.java
We removed a check for BUILD to fix https://github.com/flutter/flutter-intellij/issues/4692 but this caused problems for internal projects.
> Check for BUILD file for bazel projects only

- CHANGELOG.md
- resources/META-INF/plugin.xml
I just noticed that the last two versions weren't bold on the IntelliJ plugin web site, assuming this was not intentional.
> Fix version headings

- flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/MacMenuFixture.java
You can mostly ignore `IdeaFrameFixture.java `. See its class comment for instructions to produce a new version of it.
The new method in `FlutterProjectStep` was copied from an old version of `StudioWizardStepPanel`, which has been deleted in Android Studio. I'm in the process of re-implementing these classes; this is part of the new project wizard.
Once this is merged the next dev channel build will work for canary again.
Tested by building a new plugin, installing it into canary 7, then creating a Flutter app.
> Fix Android Studio canary build

- flutter-studio/src/io/flutter/module/ImportFlutterModuleStep.java
Missed one. The build didn't catch it because it is based off an earlier canary that didn't need it. I need to change that before the next release.
> Add deprecated once more

- src/io/flutter/run/test/TestFields.java
- src/io/flutter/sdk/FlutterSdk.java
This fixes https://github.com/flutter/flutter-intellij/issues/4737 temporarily.
We previously tried starting all tests with `--start-paused` for structured errors, but this causes directory scope tests to hang because we need to connect to multiple observatory URIs sequentially to run each contained test (and this isn't implemented yet).
> Avoid start-paused for directory scope tests

- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/run/test/TestLaunchState.java
I had previously changed test runs to start paused and to use the FlutterTestRunner instead of the default runner so that we could resume once the IDE was listening for vm service messages. However, the FlutterTestRunner was set up for debugging and this caused test runs to show the debugging console and recognize breakpoints. This change skips the debugging setup for run mode tests.
To check that process termination works correctly (so we don't keep waiting for the observatory URI if the user has stopped the test run), I ran with a debugging statement in the waiting loop and verified that the execution gives up if the run is stopped before the tests run:
```
while (url == null) {
if (launcher.isTerminated()) return;
System.out.println("Waiting");
TimeoutUtil.sleep(1000);
url = …
```
> Show run console and skip breakpoints during test run

- src/io/flutter/sdk/FlutterSdk.java
I was initially thinking that I could make a change to flutter_tools to enable resuming on Chrome for our web-server device mode, but since run mode for web server doesn't show structured errors anyway, it makes more sense to skip starting paused for this device.
Fixes https://github.com/flutter/flutter-intellij/issues/4751
> Skip start-paused for web server in run mode

- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/FlutterApp.java
Instead of building and serving devtools independently, we want to make a request to flutter daemon to start serving devtools which should already be built.
This change requires https://github.com/flutter/flutter/pull/62702 to be merged internally.
> Use daemon API to get devtools host and port for internal use

- src/io/flutter/inspections/FlutterDependencyInspection.java
Dart SDK from `flutter/bin/cache/dart-sdk` may be used for pure Dart projects, without any Flutter-related code. Flutter-specific inspection shouldn't work in this case.
Once the Flutter plugin update with this fix is published, I'll enable 'Outdated Dependencies' inspection from the Dart plugin for such cases. I don't want to enable it right now to avoid having 2 similar warnings from 2 inspections at the same time.
> FlutterDependencyInspection shouldn't work in a non-Flutter project

- tool/plugin/lib/runner.dart
- tool/plugin/lib/util.dart
For local builds, the JxBrowser key will not be returned from the keystore and instead should be manually pasted into the resources directory. We should only try to fetch the key from the keystore, but skip writing into the resources directory unless the key isn't empty.
> Fix local build overwriting JxBrowser key

- src/io/flutter/jxbrowser/JxBrowserManager.java
- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
While refactoring the `JxBrowserManager` file (https://github.com/flutter/flutter-intellij/pull/4714), I left out the download path while loading files.
This can be tested by running `bin/plugin build` with JxBrowser enabled and the key included, then installing and running the plugin .jar file.
> Load correct file path for JxBrowser files

- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- src/io/flutter/utils/JxBrowserUtils.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
This adds a setting under Flutter > Experiments that's off by default:
If the setting is enabled, then the Inspector panel will display the embedded DevTools page. Newly enabling the setting will run the setup steps for JxBrowser if they have not already been run previously.
> Add experimental setting for embedding devtools

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
The transparent background setting shows a grey screen briefly instead of a white background, and waiting to create the `BrowserView` allows us to skip a white background that is probably from the initial browser page being about:blank.
Before:
After:
> Fix white screen during embedded browser load

- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/devtools/DevToolsUtils.java
- testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java
Found that the class `UIUtil` has static methods to get default colors that I'm assuming come from the theme. 
Light:
Dark:
> Send IntelliJ component background color to devtools

- src/io/flutter/FlutterUtils.java
- src/io/flutter/settings/FlutterSettings.java
Users on the dev release of our plugin should automatically have the embedded browser setting enabled. I verified that this setting can also be turned off.
> Enable embedded browser by default in dev

- src/io/flutter/FlutterUtils.java
- src/io/flutter/settings/FlutterSettings.java
`PluginManagerCore` seems to be incompatible with Android Studio, so I changed back to using `PluginManager` though the function there is deprecated.
Also moving `isPluginVersionDev` out of utils since we want to limit divergence of release vs. dev/local behavior and keep it only within settings.
> Use PluginManager method for Android Studio and move function

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
The table that's accessible in BigQuery seems to be delayed, so I think I have to check back tomorrow to see if my testing recorded events. 
Update - I still don't see this in BigQuery, but I do see it in analytics:
> Add jxbrowser installation events

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
Fixes https://github.com/flutter/flutter-intellij/issues/4803
It seems that hardware accelerated mode can fail on Windows, but we aren't sure if this is due to a machine setting or a JxBrowser limitation. Adding this check so that we can try a backup mode.
~~Verified that this works, but it is comically zoomed in:
The `OFFSCREEN` mode works fine; in the previous screenshot my windows device had a strange zoom setting.
The `HARDWARE_ACCELERATED` mode works too; in comments below the issue was also due to the local zoom setting.
> Skip transparent background if hardware accelerated causes error

- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/devtools/DevToolsUtils.java
- testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java
There are currently two page params used while creating a DevTools URL, and the one in the form `#timeline` doesn't seem to do anything. I wanted to remove this since it's clearer and it will make adding a "simulated" embedded browser page (for developers without a JxBrowser license) a little easier.
I checked that opening DevTools from the run console and from the performance tab hasn't changed.
> Remove extra page param when launching DevTools

- tool/kokoro/build.sh
- tool/kokoro/deploy.sh
The Ant script has to manage the entire class path. Changing to Java 14 on Kokoro breaks it. This change switches to using Gradle instead. We won't know that it works until this is merged, but it should since the Gradle-driven tests do work.
> Use Gradle to compile for Kokoro

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/utils/JxBrowserUtils.java
When there isn't a jxbrowser.properties file, the logs should show something like:
```
2020-09-10 17:26:22,153 [   6543]   INFO - ter.jxbrowser.JxBrowserManager - jxbrowser.properties file does not exist 
2020-09-10 17:26:22,153 [   6543]   INFO - ter.jxbrowser.JxBrowserManager - flutter_error_studies: Unable to find JxBrowser license key file 
```
instead of an NPE.
Since this should mostly occur in development, should I use `System.out.println` here instead?
Fixes https://github.com/flutter/flutter-intellij/issues/4812
> Log exception when jxbrowser license key file is missing

- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/vmService/VmServiceConsumers.java
- src/io/flutter/vmService/VmServiceWrapper.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
Follow up from https://github.com/flutter/flutter-intellij/pull/4813:
- update to the latest VM service protocol library (w/ the version number change)
- create an abstract `EmptyResumeConsumer` so we don't have so many empty implementations of a ResumeConsumer around
> update to the latest VM service protocol library

- flutter-idea/build.gradle
The plugin tool was building a 450M+ zip file.
> Only reference runtime artifacts for testing

- build.gradle
- flutter-studio/build.gradle
Also, stop compiling forms when running tests, since it intermittently fails with AS 4.1. And the Android plugin no longer gets loaded by its id, so use its name.
> Use 0.4.18 IntelliJ plugin for Gradle

- tool/plugin/lib/runner.dart
I don't know if this is a permanent change yet. I need it for debugging the Kokoro build.
> Enable Gradle logging for dev channel

- src/io/flutter/vmService/VmServiceWrapper.java
- remove a log error about no isolates at initial app connection
I believe that DDS can change the timing of when isolates are reported to exist; @bkonyi to confirm.
cc @bkonyi, @jwren
> remove a log error about no isolates

- src/io/flutter/dart/FlutterDartAnalysisServer.java
- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/inspector/FlutterWidget.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/logging/tree/DataPanel.java
- src/io/flutter/run/bazelTest/BazelTestRunner.java
- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/survey/FlutterSurveyService.java
- src/io/flutter/test/DartTestEventsConverterZ.java
- src/io/flutter/utils/JsonUtils.java
- testSrc/unit/io/flutter/logging/FlutterConsoleLogManagerTest.java
- testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java
- testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java
- testSrc/unit/io/flutter/testing/FakeActiveEditorsOutlineService.java
- introduce a wrapper around some deprecated json parsing APIs (`JsonUtils.parseString` and `JsonUtils.parseReader`)
- redirect the existing json parsing calls to JsonUtils
This reduces the number of warnings we see when building the plugin.
> redirect json parsing calls to JsonUtils

- src/io/flutter/vmService/DartVmServiceDebugProcess.java
- support pausing a running app
- make the `DartVmServiceDebugProcess` class abstract as we don't instantiate it but instead have 3 concrete subclasses
W/ this change, the 'pause' button becomes enabled when the app is running (not paused).
cc @jwren, @alexander-doroshko  as we'll likely want a similar change in the Dart plugin
> support pausing a running app

- src/io/flutter/run/test/DartTestLocationProviderZ.java
- src/io/flutter/run/test/FlutterTestLocationProvider.java
- move DartTestLocationProviderZ to the `io.flutter.run.test` package
This is a semantics free refactoring - we had one class in the `io.flutter.util` package and dozens in the `io.flutter.utils` one. Instead of moving it into the general utils package however, I moved it into single package the class was referenced from.
> move DartTestLocationProviderZ to io.flutter.run.test

- tool/kokoro/setup.sh
Log version info similar to:
> ------------------------------------------------------------
> Gradle 5.6.1
> ------------------------------------------------------------
>
>Build time:   2019-08-28 02:49:34 UTC
>Revision:     b6bd8e7934ca41d9e52610058aa7cb834df81fc4
>
>Kotlin:       1.3.41
>Groovy:       2.5.4
>Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
>JVM:          11.0.7 (JetBrains s.r.o 11.0.7+10-b765.53)
>OS:           Mac OS X 10.15.6 x86_64
> Log versions of most tools

- src/io/flutter/utils/JxBrowserUtils.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
With this change, running the development workbench without a jxbrowser license shows a message in the inspector panel: "The JxBrowser license could not be found. Click to open Devtools in the browser." that can be clicked to open the same DevTools URL in the normal browser.
When we're ready to remove the old inspector view, we can also use this path for users who elect not to use JxBrowser.
> Open DevTools in standard browser if jxbrowser license is missing

- src/io/flutter/logging/FlutterConsoleLogManager.java
- only send analytics for the first error for a frame
- fix https://github.com/flutter/flutter-intellij/issues/4466
As noted in the above bug, errors after the first one in a frame are likely to be caused by the initial error, and will likely add noise to the analytics data.
> only send analytics for the first error for a frame

- tool/plugin/lib/edit.dart
- tool/plugin/lib/plugin.dart
This changes the plugin tool to stop the Gradle daemon after each version of the plugin is built. It also removes editing support for AS 3.6.
The `plugin make` command has been failing after the fourth invocation of the `:instrumentCode` task in a single daemon:
> Forms instrumentation failed for .../io/flutter/project/FlutterProjectStep.form: : FlutterProjectStep.form: ZipFile invalid LOC header (bad signature)
This wasn't a problem with Gradle 4 but began failing with 5.6.1 and 6.6.1. JetBrains has deprecated forms, so this work-around seems like the best fix. Longer term, we should rewrite all the forms using the [Kotlin UI DSL](https://jetbrains.org/intellij/sdk/docs/user_interface_components/kotlin_ui_dsl.html).
I've had three consecutive successful builds with this change, and I …
> Stop the Gradle daemon after each build

- src/io/flutter/analytics/Analytics.java
- src/io/flutter/dart/DartSyntax.java
- src/io/flutter/devtools/DevToolsUtils.java
- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/test/DartTestLocationProviderZ.java
- src/io/flutter/sdk/FlutterPluginLibraryType.java
This reverts some Java 11 changes.
On a Mac, I can build the plugin one at a time.
```shell
export JAVA_HOME=/Applications/Android\ Studio\ 4.1\ Preview.app/Contents/jre/jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
bin/plugin build -o4.1 -u
```
> Fix plugin build for use with 4.0 and 4.1

- src/io/flutter/bazel/Workspace.java
- testSrc/unit/io/flutter/bazel/WorkspaceTest.java
Fixes https://github.com/flutter/flutter-intellij/issues/4825
To test:
- Typical flutter project like flutter gallery can be run 
- Flutter project included inside a directory with a bazel WORKSPACE file (but without flutter.json file) can be run as a flutter project - verify that in Flutter language settings, the flutter SDK is customizable and not set by bazel
- Flutter project that has a flutter.json file has SDK set by bazel
We discussed potentially simplifying the `Workspace` and `WorkspaceCache` setup process since it is confusing to follow; but for now this change should be sufficient.
> Return null workspace if missing flutter.json

- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
There seems to be a class loading conflict when using `verifyStatic` in this test context. It looks like there are some mysterious ways to fix this with `@PowerMockIgnore` ([example](https://stackoverflow.com/questions/34343601/powermockito-notamockexception-on-a-mock)) but this didn't work here easily, and it may be better to convert these to more mockable instance methods instead.
> Skip verifyStatic checks to fix tests

- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- remove the explicit disable track widget creation option (users can still pass it in via run command line options)
- pass in `--track-widget-creation` if the flutter sdk supports the option
- don't pass it in if the user has an explicit value for track-widget-creation in the additional args
> remove the explicit disable track widget creation option

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/settings/FlutterSettings.java
- make the flutter settings page slightly more compact
- record analytics for the JxBrowser setting
> make the flutter settings page slightly more compact

- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/SdkAttachConfig.java
- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/sdk/FlutterSdk.java
- make the `device` param into various run methods not null
Found while working on some changes to `FlutterSdk. flutterRun()`.
> make the device param into various run methods not null

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- move the `Always suggest multiple run configurations for test code` settings from the bazel area to the experiments area
- rename it to `Show all possible run configurations for apps or tests, even if a created configuration already exists`
- delete the `Bazel` settings area
I considered moving the setting into the `General` section, but I don't think we want to recommend this as a normal / higher volume user setting.
> make the settings page more compact

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
- fix a null assertion in the inspector
- fix https://github.com/flutter/flutter-intellij/issues/4936
This is being reported frequently to crash reporting; the code here hasn't changed, so perhaps we're seeing a timing difference in the vm service becoming available when starting an app.
The main issue here was that when we went to create an `InspectorService.ObjectGroup` in the FlutterConsoleLogManager class, the VM service connection wasn't always ready. We now delay construction until the ObjectGroup is first needed.
> fix a null assertion in the inspector

- src/io/flutter/jxbrowser/JxBrowserManager.java
I was confused about why analytics showed multiple "installed" events per client, and it turns out I wasn't checking the full file path when deciding whether or not to download the JxBrowser files again! (So files were getting downloaded on every restart)
> Prevent repeat downloads of JxBrowser files

- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
- adjust the layout for the jsbrowser error feedback ui
- remove one or two null checks that are now no longer needed (since we've propagated our nullability annotations a bit further through the project)
This breaks the error feedback UI from a single long line into two shorter ones; this is to make it work better in (generally fairly narrow) tool windows.
> adjust the layout for the jsbrowser error feedback ui

- src/io/flutter/jxbrowser/JxBrowserManager.java
This adds the exception message and elapsed time to analytics if one of the file downloads fails.
I was hoping to check bytes downloaded, but I couldn't find a way to do that using this API. I tried just checking the size of `new File(DOWNLOAD_PATH + "/" + currentFileName)` but it seems the file doesn't appear unless it's completely downloaded. Any other ideas on this?
> Add more detail for JxBrowser failed downloads

- gradle.properties
- tool/kokoro/build.sh
- tool/kokoro/deploy.sh
- tool/kokoro/setup.sh
- tool/kokoro/test.sh
- tool/plugin/lib/plugin.dart
- tool/plugin/lib/runner.dart
- tool/plugin/lib/util.dart
Specifying Java target compatibility apparently doesn't work they way I expect it to. Class files built by Java 11 that specify Java 8 compatibility still have class file version 55 so the plugin can't be used in Android Studio 4.0 and 4.1. That might be a bug in the IntelliJ plugin for Gradle.
There are a number of changes here:
- Add Java version to Gradle script, set it in the plugin tool based on build version
- Unroll the build loop to do a single build at a time, manually incrementing the minor version number
- Change the Java version halfway through
- Refactor two utility functions (devBuildNumber(), _nextRelease()) into util.dart
- Move build version constructor from a switch branch to buildVersionNumber() in util.dart
- Use buildVersionNumber() everywhere that needs to use that …
> Fix dev channel build

- src/io/flutter/jxbrowser/JxBrowserManager.java
Last week I fixed downloading happening repeatedly on each open but didn't realize that "installed" is being recorded to analytics each time class loading happens (which happens even if a new download wasn't needed). This records to analytics only for each download so we can verify that downloading is only happening once per version.
> Add analytics for download finished

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
We are currently only offering an option to retry the JxBrowser download if it failed; we should offer the option to open DevTools in the normal browser as well.
> Show option to open browser DevTools on general download failure

- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
If an app is started while JxBrowser is still installing, we present:
If the installation times out:
If something else goes wrong, like installation is interrupted:
> Show option to open DevTools in browser during JxBrowser installation

- src/io/flutter/run/test/FlutterTestRunner.java
- src/io/flutter/run/test/TestLaunchState.java
- fix an issue resuming isolates at the start of running tests
- fix https://github.com/flutter/flutter-intellij/issues/4967
- fix https://github.com/flutter/flutter-intellij/issues/4960
From the reported issue, and looking at the code, I believe the problem was that we were resuming all known isolates (reported by the VM object) at test start. However, there's a chance the test isolate might not be executable yet. I believe the state changes that isolates go through are (https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#streamlisten) `IsolateStart`, `IsolateRunnable`, and `PauseStart`. If you try and resume an isolate that's not yet runnable (or paused) the VM will return an error.
This changes to resuming all isolates that are `'PauseStart'` when we first …
> resume isolates at test start

- CONTRIBUTING.md
- flutter-intellij-community.iml
- flutter-studio/flutter-studio.iml
- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
- flutter-studio/src/org/jetbrains/kotlin/tools/projectWizard/wizard/NewProjectWizardModuleBuilder.java
- src/io/flutter/FlutterBundle.properties
The main change is in `FlutterNewProjectAction.actionPerformed()`. The previous content has bee embedded in an if-statement detecting version 4.2 or earlier. If later, the IntelliJ new project wizard will be used.
In 4.2 the Welcome screen changes, and I thought a more compact title would be better (I stretched the screen a little so the search option shows).
> Migrate to IntelliJ NPW for AS 4.3

- src/io/flutter/run/test/FlutterTestEventsConverter.java
- src/io/flutter/test/DartTestEventsConverterZ.java
- fix an issue with unnamed test groups (`<no name>`)
- fix https://github.com/flutter/flutter-intellij/issues/4771
@stevemessick - the only important change here is in `Group.from()` - updating for the change that unnamed groups changed to be reported w/ names of `""` instead of `null`. The other changes are just updating the `DartTestEventsConverterZ` class from the original version in the Dart plugin.
> fix an issue with unnamed test groups

- src/io/flutter/console/FlutterConsoleFolding.java
- improve aesthetics for the run console folding
- remove older iOS Simulator (and likely seldom used) foldings
This changes our console folding to not combine the `flutter test xyz...` folding with the proceeding line of text (generally something like 'Testing started at 10:14 AM ...'). This would look odd, esp. for the console for running tests.
Before:
Note there's no space between the '...' and the 'flutter test...' text.
After:
This PR also removes some older older, iOS specific foldings. These were untested, and likely encountered pretty infrequently.
> improved aesthetics for the run console folding

- src/io/flutter/settings/FlutterSettings.java
Analytics are already logged for settings on IntelliJ startup.
> Enable embedded browser by default

- src/io/flutter/pub/PubRoot.java
@alexander-doroshko I can't reproduce the original problem but this ought to fix it.
Fixes #4979
> Fix hang when opening a project if previous selection was a directory

- src/io/flutter/ProjectOpenActivity.java
Creating a new project with IntelliJ caused a notification to appear (which disappeared before I could capture the image). I would click its "Configure" button then deselect the items in this window. 
If you did nothing the notification would appear next time you open the project. If you allow the configuration to proceed your Android module is ruined.
This just stops the detector from running on Flutter projects.
Fixes #989
> Stop running the Android framework detector

- src/io/flutter/settings/FlutterSettings.java
I changed the default value in `isEnableEmbeddedBrowsers` (the method above this change) but neglected to update the set method as well, so non-dev users would have been unable to disable the embedded browsers setting.
I verified with a non-dev version that the embedded browser option can be both enabled and disabled.
> Make embedded browser default enabled, not version-specific

- src/io/flutter/ProjectOpenActivity.java
Previously we were exiting `ProjectOpenActivity` early for bazel projects so that JxBrowser files weren't installed. This change moves up JxBrowser installation in `ProjectOpenActivity` to after verifying that a project is either a Flutter project with a pubspec file or a bazel project.
> Allow bazel projects to set up JxBrowser

- src/io/flutter/editor/FilteredIndentsHighlightingPass.java
- src/io/flutter/editor/WidgetIndentsHighlightingPass.java
We could diverge from the IntelliJ default but the new default
seems fine and I like that the lines are now to the left of the cursor which is a bit clearer than when they were to the right.
Before:
After:
This is related to https://github.com/flutter/flutter-intellij/issues/4982
An existing CL already resolved the doubling aspect by ensuring our indent renderer wins but we still have the issue that our widget indent guides had diverged from the default indent guides in terms of where lines were drawn.
> Fix indent delta to match change to IntelliJ.

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/jxbrowser/JxBrowserManager.java
(maybe) fixes https://github.com/flutter/flutter-intellij/issues/5025
This changes `EmbeddedBrowser` to a singleton class so that we can maintain one JxBrowser `Engine` and `Browser` with a folder for the browser data.
> Set user-data folder for embedded browser

- analysis_options.yaml
- pubspec.yaml
- tool/grind.dart
- tool/plugin/lib/edit.dart
- tool/plugin/pubspec.yaml
- use the same sdk constraint in the project pubspec files
- require types in APIs (this will catch places where we unintentionally leave off types)
> use the same sdk constraint in the project pubspec files

- flutter-intellij-community.iml
- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java_stub
- flutter-studio/src/io/flutter/module/FlutterModuleGroup.java
- product-matrix.json
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/FlutterGeneratorPeer.form
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/module/settings/ProjectType.java
- src/io/flutter/module/settings/SettingsHelpForm.form
- src/io/flutter/module/settings/SettingsHelpForm.java
- tool/plugin/lib/edit.dart
For Android Studio 4.2 and later, change the new project wizard to this:
This includes one goal for this quarter: adding a link on the first page of the wizard that points to the installation docs.
`FlutterNewProjectAction.replaceModuleBuilders()` (and `restoreModuleBuilders()`) does some tricky stuff with reflection. This could break, and our fallback is to simply stop using those methods. That would make the wizard look like it does in IntelliJ. There should be no changes to the IntelliJ wizard, although almost all the code is shared.
Android Studio has always highlighted the help message for the selected project type, so I found a way to do that here, too. 
FlutterNewProjectAction.java_stub is the previous version of `FlutterNewProjectAction`, which is required for AS 4.1 (see the …
> Simplify the new project wizard for AS 4.2+

- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/run/bazel/BazelFields.java
- testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
This uses the updated `runScript`, which:
- Processes `bazel-options` as a string of all of the bazel arguments
- Handles the device-specific logic internally (so we can remove from the plugin)
> Use runScript for bazel run

- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/run/bazel/BazelFields.java
- testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
Reverts flutter/flutter-intellij#5046
I need to temporarily revert this because the compiled version of the runScript hasn't been updated for necessary changes yet. The changes will be included in the next compiled version sometime this week.
TBR @jacob314 @stevemessick
> Revert "Use runScript for bazel run"

- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/run/bazel/BazelFields.java
- testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
Reverts flutter/flutter-intellij#5050
At the time I reverted, I didn't realize the original change had already gone out in the dev channel anyway. The compiled files have been updated, so this now works as expected.
> Revert "Revert "Use runScript for bazel run""

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
This render mode has comparable FPS performance to hardware-accelerated: https://jxbrowser-support.teamdev.com/docs/guides/browser-view.html#off-screen
Hopefully this fixes the issues where the embedded browser shows up in the wrong place (e.g. https://github.com/flutter/flutter-intellij/issues/5042)
> Use OFF_SCREEN render mode for windows

- src/io/flutter/run/bazelTest/BazelTestFields.java
- src/io/flutter/utils/MostlySilentOsProcessHandler.java
SIGKILL is currently sent when a test process is stopped, but this can't be routed to remote processes spawned from the original one.
> Send SIGINT for bazel test processes

- .github/workflows/presubmit.yaml
- .github/workflows/presubmit.yaml.template
- .github/workflows/windows.yaml
- src/io/flutter/module/settings/PlatformsForm.kt
The `pull_request_target` should allow actions to run as expected on repo forks. The `workflow_dispatch` is supposed to enable manual triggering from the github UI.
> Add dispatch events to run actions

- src/io/flutter/actions/OpenInAndroidStudioAction.java
- src/io/flutter/sdk/FlutterSdk.java
Also fixes a json parsing error I introduced in my previous PR, along with some logging to help decipher launch failures.
> Move launching of Android Studio off EDT onto a background thread

- src/io/flutter/FlutterUtils.java
- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/OpenDevToolsAction.java
- src/io/flutter/run/bazelTest/BazelTestDebugProcess.java
- src/io/flutter/run/test/TestDebugProcess.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
We're currently launching a new devtools server when opening the embedded browser, but for bazel projects it is faster to use the existing devtools server.
> Use existing devtools for bazel in panel and remove opening devtools for tests

- src/io/flutter/devtools/DevToolsManager.java
This stops the DevTools server when a project is closed (or IntelliJ quits). This change only applies to the external DevTools server, so a separate change is needed for the bazel case.
> Stop devtools process on closing

- src/io/flutter/devtools/DevToolsManager.java
Previously we weren't saving the instance of the DevTools server between app runs, so a new server was started for each app. This saves instances between apps for the same project.
(for bazel only, saving instances between apps is already the case for external projects)
> Save instance of DevTools between bazel app runs

- .github/workflows/presubmit.yaml
- .github/workflows/presubmit.yaml.template
This restricts Github actions to run on master only. It also switches the unit test bot to run on MacOS.
It is now the same as devtools, with the addition of `workflow_dispatch` to allow manual triggering.
> Slight change to github actions

- src/io/flutter/devtools/DevToolsManager.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
May fix https://github.com/flutter/flutter-intellij/issues/5032
`addBrowserInspectorViewContent` should be run on the UI thread since it removes content from the panel and `app.getConnector().getBrowserUrl()` may be inaccurate when not run on the UI thread.
However, `DevToolsManager::openBrowserIntoPanel` has some actions that should be run on a non-UI thread since we have to wait for the devtools server to start.
> Run devtools panel actions on UI thread

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/DevToolsService.java
This change is to start running a DevTools server for the duration of a project instead of having it associated with an application. 
Currently we don't use the daemon to serve DevTools for non-bazel projects, but this should be okay once we're using `pub global run devtools` in flutter tools.
> Add devtools service

- src/io/flutter/sdk/FlutterSdkUtil.java
Fixes: https://github.com/canonical/flutter-snap/issues/19.
Changes proposed in this pull request:
* If present, add the Flutter snap SDK path to the list returned from getKnownFlutterSdkPaths()
* This path is well-known and standard on all Linux platforms.
> Add Flutter snap path to getKnownFlutterSdkPaths()

- flutter-studio/flutter-studio.iml
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/run/test/TestForm.form
- src/io/flutter/run/test/TestForm.java
- src/io/flutter/sdk/FlutterSdk.java
Add a field to the test config that allows definition of additional arguments to be passed to the test runner.
The change in `flutter-studio.iml` adjusts the class path to put the Flutter plugin source ahead of the Dart plugin source. No idea how it got out of order but this allows use of our version of the analysis server protocol.
Fixes #3570, #3835, #4987, #5089
> Add additional args field to test config

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/view/FlutterView.java
We want to log error messages to analytics if the embedded browser doesn't load and provide an alternative link to open DevTools in the browser:
Fixes https://github.com/flutter/flutter-intellij/issues/5073
> Add log and run callback if the embedded browser fails

- testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java
- skip the `AsyncRateLimiterTest. rateLimited` test - it's flaky (see https://github.com/flutter/flutter-intellij/pull/5135#issuecomment-747751471 for a flake)
> skip a flaky test

- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/run/bazelTest/BazelTestFields.java
- testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
We don't expect the test script to not be available, so this part has been changed to an assert instead of using a backup launch script.
With this change and a previous change to use `runScript` instead of `launchScript` to run apps, the launch script is no longer used.
Similarly, the devtools script is no longer being used, since bazel projects now use a daemon action to launch devtools.
> Remove launch script and devtools script

- src/io/flutter/run/daemon/DevToolsService.java
I looked at our exceptions logged to analytics and it seems they probably all pass through `Analytics::sendException`. I wanted to log exceptions from `DevToolsService` since this is replacing a previous system and I'd like to see if there are common error paths.
> Send exception if DevTools server fails to start

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
May fix https://github.com/flutter/flutter-intellij/issues/5119, https://github.com/flutter/flutter-intellij/issues/5139
It seems that sometimes the browser fails to start because the directory assigned to JxBrowser is already in use. Closing the engine should stop the use of the directory.
> Close embedded browser engine on application close

- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/analytics/TimeTracker.java
- src/io/flutter/dart/FlutterDartAnalysisServer.java
We want to find the time lapsed to start the analysis server and finish indexing, and send these values to analytics.
Example times:
```
Has computed errors: 6890
Indexing has finished: 28634
```
> Track time lapsed to start analysis server and finish indexing

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
Sometimes verbose logs would be helpful to the JxBrowser team when they're debugging issues (e.g. for https://github.com/flutter/flutter-intellij/issues/5152)
These logs will be available in idea.log files (they will not be reported to our analytics).
> Enable JxBrowser logging with verbose logging option

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/settings/SettingsHelpForm.form
- src/io/flutter/module/settings/SettingsHelpForm.java
Re-use the help screen link on the first page. This is only for IntelliJ; the whole help screen appears for Android Studio.
> Add link to install docs to first page of NPW

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
JxBrowser by default does not show page dialogs and does the equivalent of "cancel". I'm adding the default dialogs here. This is mainly so that DevTools can use the fallback version if necessary (see context https://github.com/Dart-Code/Dart-Code/issues/3024#issuecomment-753318011)
This is using @DanTup 's sample site with dialogs:
> Show custom dialog for embedded browser

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
This logs console messages from the embedded browser to idea.log. e.g.:
```
2021-01-15 14:55:17,559 [  82786]   INFO - ter.jxbrowser.JxBrowserManager - Browser message(LOG): PreferencesController: storage not initialized 
2021-01-15 14:55:17,575 [  82802]   INFO - ter.jxbrowser.JxBrowserManager - Browser message(LOG): DevTools version 0.9.6. 
```
Fixes https://github.com/flutter/devtools/issues/2606
> Log console messages from embedded browser

- src/io/flutter/sdk/FlutterSdkVersion.java
- testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java
I think we need to use a beta version to gate the upcoming change for DevTools since the next major release of flutter to include the needed changes won't be out by the time we want the full setup to be working.
I didn't find a built in way to compare these versions, so added this. Let me know if there is an easier way though.
> Add compare function that works for beta versions

- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/daemon/DevToolsService.java
- src/io/flutter/sdk/FlutterSdkVersion.java
We want to keep using a DevTools server that persists across app runs (associated with an open project instead), but we also want to pass the address of this server to flutter_tools during `flutter run` so that upcoming features like DevTools links generated in flutter_tools can use the same server.
However, I'm not sure when we should start the project DevTools server:
- If we should start it right before a user wants to run an application, this introduces a delay for the run process starting, and this runs on the UI thread (maybe there's a way to move to other thread?)
- If we start it when a project is opened, this is unnecessary if the user isn't running an app. If the user tries to run an app quickly, this could still result in a delay
- If we don't change the start time, then it …
> Start DevTools server and pass address to run

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/daemon/DevToolsInstance.java
- testSrc/unit/io/flutter/run/bazel/BazelFieldsTest.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
I should have combined this with https://github.com/flutter/flutter-intellij/pull/5176 (see for more context). I thought I would need to change some internal configuration but the flag is already recognized and passed through. This change similarly waits for the project-level DevTools server to start before passing the URL into bazel flutter run.
> Pass DevTools server URL to bazel run also

- src/io/flutter/run/common/CommonTestConfigUtils.java
- src/io/flutter/run/common/TestLineMarkerContributor.java
Add a run icon to the definition of main(). Works for both the app and its tests.
Fixes #5000
> Add run icon to definition of main()

- src/io/flutter/inspector/EvalOnDartLibrary.java
Fixes #4946. Maybe.
I think what happens is the Flutter SDK decides to download a bunch of stuff, causing a time-out. The exception is being reported to the user. This just hides it. I'm not sure if that will break something upstream, though.
> Handle time-out when getting Flutter SDK

- src/io/flutter/view/FlutterView.java
I think we won't have this problem frequently since we've fixed a threading issue related to DevTools starting and we're now using an instance of the server that persists for a project. But providing an expectation of how long the loading should take and an action that is reported to help seems reasonable in case the problem persists.
Fixes https://github.com/flutter/flutter-intellij/issues/5172
> Suggest invalidating caches if DevTools taking too long

- src/io/flutter/editor/FlutterIconLineMarkerProvider.java
Fixes #5071 
This adds a check to ensure an icon preview is only shown for the known, cached icons.
We plan to investigate showing custom icon previews soon. See #2334.
> Show icons only for known sets

- src/io/flutter/view/FlutterView.java
Reverts flutter/flutter-intellij#5202
We don't actually see a way that invalidating caches could solve the issue here, so I'm going to revert this change and instead make the change to restart DevTools on closing the tool window.
> Revert "Suggest invalidating caches if DevTools taking too long"

- src/io/flutter/devtools/DevToolsUtils.java
- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
When an app throws a render overflow error and sends a URL with a deep link to DevTools, we want to parse the widget ID and open in the embedded DevTools window (if the user has enabled this).
I think we were under the impression that navigating to the same URL but with one param changed should not cause a full page refresh, but I haven't found a way to avoid this.
> Show notification on error with deep link 

- src/io/flutter/logging/FlutterConsoleLogManager.java
I forgot about this when making the earlier deep link change. If the inspector isn't already open, we want to open the it if someone clicks on the link; otherwise it will seem like this link isn't working.
> Show tool window if not visible on deep link

- src/io/flutter/logging/FlutterConsoleLogManager.java
- Removes title to be more similar to VS Code notification
- Notification persists for 25 seconds (unless clicked/removed)
- Icon denotes error instead of using the standard Flutter icon
CC @InMatrix
> Modify deep link notification appearance

- src/io/flutter/run/SdkFields.java
The future outside the progress indicator has to be completed with an exception if DevTools exceeds the max waiting time allowed; otherwise flutter run can't resume.
> Complete exceptionally if DevTools is taking too long

- resources/META-INF/plugin.xml
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/daemon/DevToolsService.java
- src/io/flutter/toolwindow/FlutterViewToolWindowManagerListener.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
There have been cases where DevTools installation gets stuck. This may be fixed with our change to having one DevTools instance per project, but we wanted to offer a way to restart DevTools if users are waiting a long time. 
The logic when a user closes and reopens the window:
- If the DevTools instance has successfully been created, the same instance is returned but the browser is refreshed (this may be useful if users see the frozen wheel or another issue within DevTools)
- If DevTools has completed with a failure, we try to start a new instance
- If DevTools is still in progress, we force a restart by canceling the existing future and trying to start a new instance
Fixes https://github.com/flutter/flutter-intellij/issues/5162
> Restart DevTools and browser on inspector window reopen

- .idea/libraries/KotlinJavaRuntime.xml
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/vmService/frame/DartVmServiceEvaluatorInFrame.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
The `flutter channel` query was being run on the EDT during start-up, so I moved that to run on a pooled thread.
I missed some expression evaluation paths, but I think this catches all of them.
> Fix bugs in M53

- src/io/flutter/sdk/FlutterSdkVersion.java
The SDK version seems to be null if flutter has just been updated.
> Add version null check for DevTools URL support

- src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
Since JxBrowser uses Chromium we have some situations where a user opens the embedded browser and is prompted to unlock the keyring in Linux if Chrome hasn't been opened already. We're hoping to avoid this by passing a Chrome option.
> Modify password store to avoid keyring prompts

- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/utils/FlutterModuleUtils.java
Change from "XCode" to "Xcode" to match the app's correct casing.  See in docs: https://developer.apple.com/xcode/
Introduced in #1321
> XCode -> Xcode casing

- src/io/flutter/sdk/FlutterSdkVersion.java
- testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java
Versioning has been adjusted in flutter so that master versions are aware of the preceding dev release, so I'm updating our versioning check to fully consider all types (stable, beta, dev, and master channels).
CC @christopherfujino
> Compare master versions with beta

- src/io/flutter/toolwindow/FlutterViewToolWindowManagerListener.java
- src/io/flutter/view/FlutterView.java
We've been loading the inspector embedded browser content on app run, but we can delay this until the inspector tool window is first made visible.
> Delay loading embedded browser until inspector visible

- src/io/flutter/view/FlutterView.java
Hopefully fixes https://github.com/flutter/flutter-intellij/issues/5228
It looks like `myUI` within `ContentManagerImpl` can be set back to null after dispose, and we didn't have a check of dispose status here.﻿
> Check for content manager disposed before replacing panel

- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/SdkRunConfig.java
If DevTools fails to start, we don't want to wait for it on every run. I think waiting the first time is okay since we want the same experience across runs (e.g. we don't want deep links to not be available only on the first run). But if DevTools hasn't started by the time an app is run for the second time, there probably isn't an easy way to fix DevTools and we should proceed without it. ﻿
> Skip waiting for DevTools after first run

- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkChannel.java
There was no reason to log an error if `git` was not available. Now, we try running `flutter channel` if needed. It may have a better ability to find the channel, but if not it will still be classified as "unknown". Open question whether it should be "stable" instead. The channel is used to determine if platform selection should be shown when creating a new project.
Fixes #5232
> Run flutter channel if git is not available

- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/module/settings/PlatformsForm.kt
PlatformsForm.kt changed a lot less than it looks. The formatter changed a lot of indents. My change added a field `component` and an assignment to initialize it. That's so it can be disabled when `Package` type is selected.
Fixes #5252
> Stop adding --platforms for packages

- src/io/flutter/actions/AttachDebuggerAction.java
- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/FlutterConfigurationEditorForm.java
- src/io/flutter/run/SdkFields.java
- testSrc/unit/io/flutter/run/SdkFieldsTest.java
Add another field to the run config, for use by `flutter attach`.
Fixes #5237
> Add attach args field to run config

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/view/FlutterView.java
Since we now wait for the inspector window to be visible before navigating to DevTools in the embedded browser (instead of navigating on app start), there could be cases where a notification with a deep link is shown before the navigation happens. This change shows the tool window before trying to navigate and waits for the main URL to be set before navigating to the URL with a widget ID.
> Permit deep link to open embedded browser

- product-matrix.json
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/FlutterProjectType.java
- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
- testSrc/unit/io/flutter/sdk/FlutterCreateAdditionalSettingsTest.java
This fixes a problem I discovered during testing. The support for platforms is complex because it depends on the selected Flutter SDK, which can change while the new project wizard is running. And it depends on the platforms the user has chosen to configure for use via the CLI tool. And on the project type; only apps and plugins allow the `--platforms` option.
I also bumped the version to work with the latest canary, which is now built on the latest stable IJ.
> Platform selector bug

- src/io/flutter/inspector/InspectorGroupManagerService.java
Fixes https://github.com/flutter/flutter/issues/76680
> Wait for stream to be available before loadSelection

- src/io/flutter/run/daemon/DeviceService.java
Wait for indexing to finish before updating the device list. This change is going to affect all daemon state changes. I think it is OK but want someone to double-check that it is not causing downstream problems.
Fixes #5248
Fixes #5244
> Get device list after indexing finishes

- src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
`engine.close()` can throw an error, potentially because there wasn't a check of whether the engine was already closed. I'm also wrapping all of this in a try/catch since this function should always return true.﻿
Fixes https://github.com/flutter/flutter-intellij/issues/5299
> Log any exceptions on jxbrowser close and check closed status

- build.gradle
- flutter-idea/build.gradle
- product-matrix.json
- tool/plugin/lib/edit.dart
It appears that ideaIC-211.6305.21 is actually labeled internally as 211.6222.4. Upgrading the IDE asks to upgrade the Dart plugin. After restarting, there is an error due to the Dart plugin requiring a newer version and the about box still has the 6222.4 version.
> Automate EAP build for dev channel

- src/io/flutter/module/settings/PlatformsForm.kt
All platforms can be enabled in stable now so no need to check for a minimum channel. Looks like the formatter had some rule changes, too.
Fixes #5304
> Simplify platform selection code

- src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/utils/FlutterModuleUtils.java
- tool/plugin/lib/edit.dart
Fixes #5313 
We used to use `DartPlugin.isDartSdkEnabled(module)` as a quick short-circuit for checking if the Flutter SDK was configured. That isn't reliable (not sure why) anymore. The result is that the first time a project is created after IntelliJ is launched, the project does not have its SDK configured. Projects created after the first one do, however.
This also adds support for the new `.dart_tool/package_config.json` file.
Since the Dart SDK is configured, I tried to find a way to determine its location on disk. You can see in External Libraries that it knows about its content, so the path has to be somewhere. The IntelliJ API does not appear to reveal that information.
@alexander-doroshko If you can take a minute to look at this I'd appreciate any tips on finding the Dart SDK on …
> Fix the lost SDK on start up problem

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/utils/FileUtils.java
Fixes https://github.com/flutter/flutter-intellij/issues/5327#issuecomment-801129734
This will get rid of the error message but I'm not sure why this error occurs in the first place. I can't reproduce it on windows myself, but I actually see other similar errors when running on Windows that don't come from our plugin. I'll check with Alex to see if there's something I can change in our path logic to make this more consistent for Windows.
> Catch class loading exceptions and log full path

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/utils/FileUtils.java
- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
I noticed while debugging another issue that a file can not exist and still seem to be "loaded" correctly because no exceptions are thrown during the `loadClass` function. I don't think this is actually happening (it shouldn't) but for completeness it seems like we should check for this since we're checking for other exceptions.
> Check that files exist during class load

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/RestartFlutterDaemonAction.java
- src/io/flutter/run/daemon/DeviceService.java
Add a `Refresh` item to the device list. `DeviceService.isRefreshInProgress` was added to eliminate the flashing caused by the widget being hidden while the device service was inactive.
Fixes #5221 
Fixes #4801 
Fixes #4208
To be fair, this is not the "fix" requested in some of those issues, but is a work-around for the problem described. Automatically updating the device list after a new emulator is created isn't practical. Alternatively, recreating the list every time it is shown isn't performant.
> Refresh devices

- src/io/flutter/pub/PubRoot.java
- src/io/flutter/sdk/FlutterSdkUtil.java
I think this fixes the other half of #5132, reporting that `flutter pub get` needed to be run.
Fixes #5132
I also renamed a variable, as suggested in another PR.
> Use proper package file

- src/io/flutter/view/FlutterView.java
Fixes https://github.com/flutter/flutter-intellij/issues/5321
There are some cases where JxBrowser doesn't get set up from ProjectOpenActivity ([code pointer](https://github.com/flutter/flutter-intellij/blob/0ca51f4dd74dcb791d20285eab865abb6a798e20/src/io/flutter/ProjectOpenActivity.java#L62)). I'm not sure why this may be - in the issue linked, the user had a pubspec.yaml file with flutter as a dependency, and that seems to be the only condition checked.
However, even though I'm not sure why this would happen, it's definitely more correct to check for JxBrowser status before resetting the URL in case it's in another state. It also seems reasonable to set up JxBrowser if we haven't tried yet at the point that we're hoping to show the embedded DevTools.
> Skip URL reset if JxBrowser not installed

- src/io/flutter/run/SdkFields.java
Fixes https://github.com/flutter/flutter-intellij/issues/5312
We expect DevTools startup to be slow and exceed our timeout limit sometimes, but the app should continue running normally after that (though without some embedded features). I think this doesn't need to be printed to the user's console but is worth logging to our analytics to check how often different DevTools failures occur.
> Report DevTools timeout but remove from console log

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
We want to default to disabling updating generated files during hot restart and add an option to turn this on for all projects if desired. (A user could enable this feature globally in settings but manually add a flag to disable for a particular project)
This setting is only visible for bazel projects.
> Disable bazel hot restart by default

- src/io/flutter/test/DartTestEventsConverterZ.java
Dart IJ Plugin change: https://github.com/JetBrains/intellij-plugins/commit/9bf7b23b8c8aa8e1ec19ec98c6248d413a84d629
> Follow up on the isFailure json attribute change, removal of the error attribute to match the Dart IJ Plugin

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/logging/FlutterConsoleLogManager.java
This ameliorates https://github.com/flutter/flutter-intellij/issues/5376 by marking JxBrowser installation as failed and reporting the error.
> Check for NoClassDefFoundError before setting JxBrowser enabled

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
I think in all of these cases we don't need users to receive an error notification since the exceptions are handled (e.g. show a failure message). It's more important to send the exceptions to analytics so we have a sense of how often they occur and log in the idea.log file in case a user reports experiencing a problem. Otherwise we get error reports that tend to have no context and aren't particularly helpful.
Fixes https://github.com/flutter/flutter-intellij/issues/5424
> Log JxBrowser exceptions as info

- src/io/flutter/vmService/DartVmServiceDebugProcess.java
We want to see how often different types of internal connection errors are occurring. I could make this bazel-specific but it seems like we might want to know how often these problems are occurring externally also, or at least check on them for one release.
> Report VM service connection problems

- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
Fixes #5421 by adding an option to display all stack traces in the console log.
> Add option to display all stack traces in debugger log

- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/utils/FileUtils.java
- tool/plugin/lib/edit.dart
The older (deprecated) URL class loading fails for 2021.1 on Mac, but there is now a new method for loading classes in 2021.1. This works for me locally (building the plugin and installing to 2021.1).
> Use alternative JxBrowser class loading for 2021.1 

- src/io/flutter/actions/DeviceSelectorAction.java
This menu disappeared for me yesterday, but oddly it was working a few days before. And I can't find what change caused this problem (e.g. when I install a v54.0 plugin I still see this problem, even though I'm pretty confident I had this menu for the past couple months).
Regardless, it seems like the check here should include bazel projects and this change fixes the problem.
> Show device menu for bazel projects

- src/io/flutter/FlutterUtils.java
- src/io/flutter/project/FlutterIconProvider.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/run/common/TestLineMarkerContributor.java
- src/io/flutter/run/test/TestFields.java
This does a few things:
- Change the icon for `integration_test` to indicate it is a test source directory
- Change the icon for integration test files to indicate the file is a test source
- Add the device id to the flutter_tools command
- Stop displaying duplicate menu items on the `main()` test run button in the gutter
We also need to update the flutter_tools project templates to mark `integration_test` as a test source root.
> Add support for integration tests to the UI

- src/io/flutter/run/test/TestFields.java
The `integration_tests` directory may not exist.
> Fix NPE when no integration test folder exists

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/jxbrowser/FailureType.java
- src/io/flutter/jxbrowser/InstallationFailedReason.java
- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/utils/JxBrowserUtils.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
- tool/plugin/lib/edit.dart
If a user is using an M1 mac and the version of IntelliJ native to this chip, then JxBrowser is not currently supported. If we detect this combination then show users the option to open DevTools in the browser instead.
It seems that automatically disabling embedded browser for situations where JxBrowser is not supported results in the setting being somewhat sticky once it is supported, e.g. it seems previously disabling for Big Sur resulted in a much higher proportion of users staying disabled despite no additional errors that would suggest a poorer user experience (maybe this setting sticks around as long as users keep their version of IntelliJ? I'm not sure). So I'm inclined to try prompting users to open in the browser instead. This should be a smaller proportion of users anyway.
Fixes …
> Detect M1 mac and skip JxBrowser

- src/io/flutter/settings/FlutterSettings.java
When we disabled the embedded browser option for Big Sur users (back when JxBrowser did not support Big Sur yet - see https://github.com/flutter/flutter-intellij/pull/5065), this caused embedded browser to stay disabled if users adjusted unrelated settings (See https://github.com/flutter/flutter-intellij/pull/5487#issuecomment-842517418 for more detail). 
We want to enable embedded browser for Big Sur users by default now, but only once (if a user elects to disable embedded browser in the future, we want to allow this).
> Enable embedded browser (once) for Big Sur users

- src/io/flutter/jxbrowser/EmbeddedBrowser.java
If the embedded browser is created but it fails to load the DevTools URL, we want to show users an option to open in the normal browser and report the issue to analytics.
Fixes https://github.com/flutter/flutter-intellij/issues/5507
> Handle if embedded browser load fails

- tool/plugin/lib/edit.dart
The `Subst` edit is only for a single change per file. You can use `MultiSubst` for multiple changes. I should have caught this during the code review.
> Fix edit.dart to clean up its changes

- src/io/flutter/devtools/DevToolsUrl.java
- src/io/flutter/devtools/DevToolsUtils.java
- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/view/FlutterView.java
Passing a `fontSize=<size>` param in the DevTools URL will result in no change until https://github.com/flutter/devtools/pull/3054 is deployed.
I also cleaned up how the listener is set up because a new one was being created for every run of the app.
> Add IDE font size to embedded browser URL

- src/io/flutter/devtools/DevToolsUrl.java
- src/io/flutter/devtools/DevToolsUtils.java
- src/io/flutter/performance/FlutterPerformanceView.java
- src/io/flutter/run/OpenDevToolsAction.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java
- testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java
This is to clean up an old util method that we don't really need since adding a `DevToolsUrl` class and move its associated tests.
Also adding a test for finding a widget ID since we didn't have one before.
(does not need to be part of v57)
> Stop using DevTools URL util method, reorg tests

- src/io/flutter/vmService/frame/DartVmServiceValue.java
- allow Instance fields to be nullable
When debugging a Fluter web app, I saw:
```
Argument for @NotNull parameter 'fields' of io/flutter/vmService/frame/DartVmServiceValue.addFields must not be null
```
when expanding a closure instance in the variables view. We were expecting the `fields` field to always be populated, but from the spec this field should be nullable (the VM impl had just always passed an empty list; the package:dwds impl. instead passes null).
> allow Instance fields to be nullable

- src/io/flutter/settings/FlutterSettings.java
Fixes https://github.com/flutter/flutter-intellij/issues/5557
It looks like the previous change was returning `true` for the embedded browser status once, but not saving it. I'm not sure how I missed this in testing last month; it's possible I built an earlier version with this line while testing the change and then accidentally deleted it before submitting. I verified with this current version that the embedded browser status is set to true.
> Change embedded browser setting

- src/io/flutter/analytics/Analytics.java
- src/io/flutter/jxbrowser/EmbeddedBrowser.java
- src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/daemon/DevToolsService.java
We want to reserve `Analytics::sendException` for unexpected exceptions rather than for tracking how often different types of caught exceptions occur.
This may be a clumsy usage of the event fields, since I'm combining a label and the exception title into the event action. There is an `eventLabel` field that we don't seem to be using in analytics, but I'm not sure what the abbreviation for this field is - perhaps it would be better to make the event action a description of where the exception comes from (e.g. "embedded-browser-setup") and make the label store the exception title/details.
> Send caught exceptions as events

- src/io/flutter/toolwindow/FlutterViewToolWindowManagerListener.java
- src/io/flutter/view/FlutterView.java
Setting `inspectorIsOpen` to false caused the embedded browser to load twice if the inspector window is initially open when app is run.
> Check for initial open state of embedded browser

- src/io/flutter/run/OpenDevToolsAction.java
- src/io/flutter/run/bazelTest/BazelTestDebugProcess.java
- src/io/flutter/run/test/TestDebugProcess.java
I'm not sure if this is actually useful - I think opening DevTools from the console used to be available while running/debugging tests, but at some point we removed it when we were starting DevTools from an app (since tests don't have an associated app and we didn't want to add another way to start DevTools). Since we're serving DevTools separately from apps now, we can add back this option for tests.
> Allow open DevTools from tests

- src/io/flutter/logging/FlutterConsoleLogManager.java
- src/io/flutter/view/FlutterView.java
There are some instances where constructing the embedded browser is delayed (e.g. waiting for the inspector tab to be opened), so it's possible for the project to be disposed before then. This change adds a check for project status before using the embedded browser.
Fixes https://github.com/flutter/flutter-intellij/issues/5527
> Check for disposed project before getting embedded browser

- src/io/flutter/perf/FlutterWidgetPerf.java
- src/io/flutter/perf/VmServiceWidgetPerfProvider.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/ClientNameConsumer.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/PortListConsumer.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/SetTraceClassAllocationConsumer.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/WebSocketTargetConsumer.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Breakpoint.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/ClassObj.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/ClassRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/ClientName.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Context.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSample.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSamples.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Event.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/EventKind.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Field.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/FieldRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/FuncRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Instance.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceKind.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Isolate.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/IsolateFlag.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/LibraryDependency.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/PortList.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Stack.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/WebSocketTarget.java
- add some NotNull annotations in the FlutterWidgetPerf classes
- rev to the latest VM service protocol lib
This PR is in response to https://github.com/flutter/flutter-intellij/issues/5587. The case of the stack trace wasn't immediately clear (in fact, nothing in that stack trace should have been null). This PR adds some NotNull annotations to clarify some if the intent of the variables.
```
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:120)
at io.flutter.perf.FlutterWidgetPerf.dispose(FlutterWidgetPerf.java:461)
at io.flutter.perf.FlutterWidgetPerfManager.updateCurrentAppChanged(FlutterWidgetPerfManager.java:276)
```
When in here, I also addressed an old TODO in terms of unregistering an event listener. As well, I updated to the latest version of the VM service protocol …
> Add some NotNull annotations in the FlutterWidgetPerf classes; rev to the latest VM service protocol lib

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/performance/FlutterPerformanceView.java
- src/io/flutter/performance/FlutterPerformanceViewFactory.java
- src/io/flutter/preview/PreviewViewFactory.java
- src/io/flutter/view/FlutterViewFactory.java
From reading over https://github.com/flutter/flutter-intellij/pull/4281, it looks like these are the goals:
- Do not show any of the tool windows (outline, inspector, performance) for non-Flutter projects (defining this as having a Flutter module or being in a bazel workspace)
- Flutter outline should be available as soon as Flutter project is detected
- Flutter inspector and performance should be available when an app starts running, although they can also be open when app is not running. Once an app has run these tool windows should remain open
- Show windows if add to app module is created - Do we also want to remove tool windows if the only Flutter app module is deleted? (Can be done but maybe not worth the trouble)
> Skip Flutter tool windows for non-Flutter projects (WIP)

- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazelTest/BazelTestFields.java
- src/io/flutter/run/daemon/DevToolsService.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/sdk/FlutterCommand.java
- avoid the use of a deprecated member (move from using `CharsetToolkit.UTF8_CHARSET` to `StandardCharsets.UTF_8`)
> avoid the use of a deprecated member

- src/io/flutter/editor/FlutterSaveActionsManager.java
Fixes https://github.com/flutter/flutter-intellij/issues/5621
It looks like since the `WriteCommandAction` is inside `invokeLater`, there's a chance the project could be disposed in between the earlier check and when `execute` is called.
> Check for project disposal right before organize executes

- AUTHORS
- CONTRIBUTING.md
- src/io/flutter/actions/OpenInAndroidStudioAction.java
I have tested this on Linux.
Please test this on macOS and Windows.
I was not able to run the tests as explained in [Running plugin tests](https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md#running-plugin-tests).
<details>
<summary>$ bin/plugin test</summary>
```terminal
JAVA_HOME=/home/hrk/.sdkman/candidates/java/current
Getting artifacts
artifacts/intellij-javac2.zip exists in cache
rm -rf /mnt/common-data/study-material/flutter/flutter-intellij/artifacts/javac2
creating /mnt/common-data/study-material/flutter/flutter-intellij/artifacts/javac2/
unzip -q -d javac2 intellij-javac2.zip {cwd=artifacts}
artifacts/Dart-212.4037.9.zip exists in cache
rm -rf /mnt/common-data/study-material/flutter/flutter-intellij/artifacts/Dart
creating …
```
> Open source file in Android Studio at exact cursor

- AUTHORS
- resources/liveTemplates/flutter_miscellaneous.xml
When using the live template to create a stateful widget whose name starts with an underscore, don't let the associated state class name start with double underscores
Fixes #4577
> Update live template to not use double underscores

- flutter-intellij.iml
- src/io/flutter/devtools/DevToolsUrl.java
- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/run/daemon/DevToolsService.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/utils/JxBrowserUtils.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java
- testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java
- testSrc/unit/io/flutter/jxbrowser/JxBrowserManagerTest.java
- testSrc/unit/io/flutter/view/FlutterViewTest.java
Powermock has not been reliable and is generally intended for mocking classes we don't control anyway, so I'm instead planning to change utility classes to have non-static methods so we can mock them more easily.
partially addresses https://github.com/flutter/flutter-intellij/issues/5585
> Fix some tests using non-static methods

- src/io/flutter/run/daemon/DeviceDaemon.java
Fixes #5521
After the first crash (down from 100) an error message is shown in the bottom-right corner of the screen:
In case there is an intermittent issue, we increase the wait time allowed to start the daemon by 10 seconds.
After five crashes it changes to a modal dialog, displayed in the center of the IDE window. The Flutter plugin isn't usable anyway.
> Daemon crash

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/actions/OpenInAppCodeAction.java
- src/io/flutter/actions/OpenInXcodeAction.java
Add `Open iOS module in AppCode` parallel to the Xcode item.
There are some caveats:
- It requires Spotlight indexing to be enabled.
- The iOS module must have previously been opened and trusted by AppCode
Fixes #5446
> Add menu item to Open in AppCode

- src/io/flutter/run/FlutterPositionMapper.java
- src/io/flutter/vmService/VmServiceWrapper.java
This will log events about analyzer availability while setting breakpoints in bazel projects. This is only one specific case where we suspect there could be breakpoint setting issues, so perhaps there's a more general way to check if a breakpoint has been set successfully?
> Add analytics for null analyzer during add breakpoint

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/performance/FlutterPerformanceViewFactory.java
- src/io/flutter/preview/PreviewViewFactory.java
- src/io/flutter/utils/ViewListener.java
- src/io/flutter/view/FlutterViewFactory.java
Follow up to https://github.com/flutter/flutter-intellij/pull/5622
We want to save the state of whether a tool window is open or closed between project open and close (the previous change made it so that tool windows were always closed/not "activated" on project open since the tool windows would all be newly available).
This change can be tested by:
1. Open a Flutter project
2. Open one of the Flutter tool windows
3. Close the project
4. Reopen the project -> the previously opened Flutter tool window should be opened again once the project is loaded.
> Persist tool window open states during project open/close

- src/io/flutter/editor/FlutterIconLineMarkerProvider.java
- src/io/flutter/font/FontPreviewProcessor.java
I added a lot of logging that I'm not sure I want to keep. The main thing is to clear KnownPaths.
The issue was that the icons were not disappearing after an icon package was removed from preferences.
> Make reanalyze() work after packages are removed from icon package list

- src/io/flutter/font/FontPreviewProcessor.java
- tool/plugin/lib/edit.dart
This avoids an error message in 2021.2. The refactoring I'm working on will eliminate the need for this hack.
TBR @helin24
> Allow slow op for 2021.2

- resources/liveTemplates/flutter_miscellaneous.xml
- resources/liveTemplates/mdof.txt
I think this one deserves its own live template, it's probably used even more than `Theme.of(context)` due to the wider multi-platform support that Flutter now has.
Part of #3256
> Add live template for `MediaQuery.of(context)`

- .idea/modules.xml
- CONTRIBUTING.md
- flutter-intellij-community.iml
- flutter-intellij.iml
- flutter-studio/flutter-studio.iml
- src/WRONG_TREE.md
This effectively reverts #5720. I have not had success creating a Gradle-based project, with an optional module, that can launch the runtime workbench. It did, however, run unit tests in the IDE.
We lose git history for the *.iml files, I think. I don't think that was very useful, anyway.
Fixes #5733 
@jwren
> Convert pack to iml-based project

- src/io/flutter/run/test/FlutterTestConfigProducer.java
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/sdk/FlutterSdk.java
- testSrc/unit/io/flutter/run/test/TestFieldsTest.java
This modifies how Flutter `testWidgets` unit tests are run when a run config is automatically created by clicking the 'Run' icon next to the test name in the editor. In this case, we should only run a single test.
> Make unit test name matching more strict

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/FlutterProjectType.java
- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/module/settings/ProjectType.java
- src/io/flutter/sdk/FlutterSdkVersion.java
- src/io/flutter/utils/FlutterModuleUtils.java
The change to FlutterModuleUtils fixes a problem I introduced last week. FlutterSdkVersion has a number of formatting changes, but I did add a method to check if the skeleton is available.
> Add the new skeleton template to the New Project Wizard

- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Fixes #5222
Note that `onVersionChanged()` runs when the SDK is changed and when OK or Apply are clicked.
> Run flutter pub get after changing SDK in preferences

- src/io/flutter/run/FlutterReloadManager.java
This hooks up hot reload to IntelliJ's existing `Save files if the IDE is idle ...` option. Hot reload on save shows a notification if there are any analysis errors. This does not, since the errors could be anywhere. It just silently does nothing.
Fixes #5140 
@jwren
> Do hot reload on auto-save

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/console/FlutterConsoleExceptionFolding.java
Fixes #5445 
If this is first in the list of foldings a stack trace collapses to a single line (the first line in the screen shot). If it is last, another folding may interfere. With it second in the list, a stack trace looks like this:
That preserves the spirit of the structured stack traces option, I think, but we may need to iterate. If the option to include all stack traces is selected then no folding is done.
> Make console stack traces expandable

- src/io/flutter/FlutterUtils.java
Fixes #5797 
Significant enough to warrant a point release. #getInstance is not annotated with either @Nullable or @NotNull, and I forgot that implicitly means it is @Nullable.
@jwren
Had to start over. All commits must be signed and the first one previously was not.
> Add null check for manager

- src/io/flutter/sdk/FlutterSdk.java
> Fix test regex

- CONTRIBUTING.md
> Update install instructions for Gradle

- flutter-intellij-community.iml
- flutter-studio/flutter-studio.iml
To work with Android Studio sources we still need to use `*.iml` modules (that is, not Gradle). Those were out of date.
This PR is the first step toward a rewrite of the New Project Wizard for AS. The current version does not work in the canary builds. See https://github.com/flutter/flutter-intellij/issues/5878 for more info.
> Update AS modules for 212

- flutter-intellij-community.iml
- flutter-studio/flutter-studio.iml
The *.iml files were not correct for working with an Android Studio source-based project. This affects me, and probably no one else.
> Fix modules for working with AS sources

- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
- flutter-studio/build.gradle.kts
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
- product-matrix.json
- tool/plugin/lib/artifact.dart
- tool/plugin/lib/edit.dart
- tool/plugin/test/plugin_test.dart
Sorry, but things got mixed up dealing with the Bumblebee crises. This should have been two PRs.
It fixes a number of problems caused by upgrading the Gradle plugin for IntelliJ. Turns out, it couldn't be upgraded yet because the newer version won't work with the oldest Android Studio we support.
It also fixes the "missing Android module" problem that causes some AS features to be disabled in a Flutter project.
Fixes #5464
> Fix build issues and missing module problem

- product-matrix.json
- tool/plugin/test/plugin_test.dart
For now, canary is only on the dev channel. The plugin file is not compatible with the equivalent IntelliJ.
> Build for canary (Dolphin)

- flutter-idea/src/io/flutter/actions/OpenInAndroidStudioAction.java
Some ancient code disallows a directory named "Android Studio 2021.3".
> Open AS 2021.x

- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- flutter-idea/src/io/flutter/run/bazelTest/BazelTestFields.java
- flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
- flutter-idea/src/io/flutter/utils/MostlySilentColoredProcessHandler.java
We were sending SIGKILL for apps, which is preventing other work from being done that relies on trapping a signal.
CC @chingjun
> Try SIGINT before SIGKILL for processes

- .idea/runConfigurations/flutter_idea__runIde_.xml
Our run configuration was opening two instances of workbench, and only one of them would connect debug endpoints.
> Change run config to open one instance of workbench

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/run/bazelTest/BazelTestRunner.java
We're now using the VM service instead for file mapping during debugging, so this bazel test code is no longer needed for test breakpoints to work.
> Remove old bazel test file mapping code

- flutter-idea/src/io/flutter/perf/FlutterWidgetPerf.java
I suspect something gets disposed out-of-order and that causes NPEs where I added the logging. #5940 and #5945 provide some hints about possible causes.
This does not actually fix anything but will stop throwing the NPE. We can close a bunch of uninformative issues.
Fixes #5965
Fixes #5943
Fixes #5831
Fixes #5813
Fixes #5791
Fixes #5746
Fixes #5587
Fixes #5536
> Log perf dispose NPEs

- flutter-idea/src/io/flutter/survey/FlutterSurvey.java
The javadoc says the original code uses the time zone, but it actually does not. This version does. Everyone in Asia was seeing the survey a day ahead of schedule. There may still be cases where someone testing date-sensitive code will see it before they should, but hopefully this will be a very small number.
Fixes #5866
> Use time zone in survey calculation

- CONTRIBUTING.md
- gradle.properties
The jvm arg was throwing an error on IntelliJ startup with our plugin code.
Added a couple additional instructions while building the plugin and setting up gpg
> Remove unnecessary(?) arg from gradle properties, update contributing

- .github/workflows/presubmit.yaml
- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/ProjectOpenActivity.java
- flutter-idea/src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
- flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
- product-matrix.json
- tool/plugin/test/plugin_test.dart
This actually does a few things, since I couldn't test initialization interactions separately.
- Add an Android module if needed
- Switch to showing "Project" in the project view (not "Android")
- Open `main.dart` for new projects if needed
- Merge preview builds into stable
Fixes #5932 
Fixes #5933
> Add Android module when opening any project

- bin/plugin
- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/run/MainFile.java
- flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java
- flutter-idea/src/io/flutter/sdk/FlutterSdk.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkUtil.java
- flutter-idea/src/io/flutter/utils/JsonUtils.java
Cleans up reliance on `.packages` file. Most places that use it had already been changed to look for the package config file instead. I added a fall-back option to the one place that hadn't. I expect the Dart plugin will be updated soon, and when it is this fall-back option can be removed.
We are not deleting the code that uses `.packages` yet because old projects could, possibly, not have the package config file. That seems unlikely, but at some point it should be safe to trim all references to `.packages`.
Fixes #5614
> Change .packages file use to package config file

- .idea/kotlinScripting.xml
- CONTRIBUTING.md
- product-matrix.json
- tool/plugin/lib/build_spec.dart
- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Run `bin/plugin make -csetup -osetup -u` before starting the IntelliJ debugger.
> Add build spec to configure IDE for debugging

- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
We want to continue using the daemon to start DevTools even though we no longer want to pass the URL to apps.
fixes https://github.com/flutter/flutter-intellij/issues/6004
> Use separate version check for using daemon

- docs/testing.md
- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
The IntelliJ project name is not necessarily the same as the Flutter project name.
Also updates test script to account for the difference.
There is a configuration error that causes 2022.1 and unit tests to fail. None of them touch the code in this PR.
Fixes #6019
> Use actual project name to find Android module

- flutter-idea/src/io/flutter/run/daemon/DaemonConsoleView.java
- flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
This is to help us track internal disconnection errors. Not all errors caught here will be truly the types of errors we'll be looking for, ~but this at least filters out startup messages as an app compiles (the startup messages are intended to go to stderr,~ as stdout is intended to be only what should be parsed by the flutter daemon).
Once we have a sense of what types of post-startup error exist, then we can further refine what messages represent different types of disconnections if needed.
> Send internal errors to analytics for disconnections

- flutter-idea/src/io/flutter/bazel/PluginConfig.java
- flutter-idea/src/io/flutter/bazel/Workspace.java
- flutter-idea/src/io/flutter/run/bazel/BazelFields.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
- flutter-idea/testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
This should show a notification only when bazel users haven't seen the notification before while running an app. If a user is running an iOS app, the notification title is about the process having improved; if running on another device, the notification title suggests trying out iOS.
> Notify bazel users to try running iOS apps

- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
This fixes a bug from https://github.com/flutter/flutter-intellij/pull/6044 where SDK check was returning NPE for bazel projects. Bazel projects don't require a version check for using the VM mapping functions.
> Check for bazel workspace when using VM mapping

- .github/workflows/scorecards-analysis.yml
- tool/github.sh
This will allow us to assess the security posture of this repository.
> Enable scorecards in intellij repo.

- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
Fixes #6093 
I think.
The method allows for multiple pub roots but was requiring all of them to have an Android module with the same name as the project. That can't happen, there is only one. That might be the cause of this bug, or it could be something else causing it, but this still should be fixed.
> Look for a single module by name

- flutter-idea/src/io/flutter/sdk/FlutterSdkUtil.java
Manually tested by disabling Dart for a project with two modules, seeing the banner to enable Dart, then changing the Flutter SDK, and seeing the banner disappear.
> Enable Dart with multiple modules

- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
Using `dart devtools` is the faster way to start the server and less complex than the daemon method.
@stevemessick  Can we start deleting the other methods of starting the DevTools server? The oldest method using pub is for versions of Flutter before v1.26, which is from a year ago. 
cc @kenzieschmoll
> Add dart devtools for starting server

- flutter-idea/src/io/flutter/ProjectOpenActivity.java
- flutter-idea/src/io/flutter/analytics/Analytics.java
We have a custom field defined for the Flutter SDK version, but we don't seem to be reporting it. This adds it to an analytics event that happens on startup.
> Report flutter SDK version on startup

- flutter-idea/src/io/flutter/analytics/DartCompletionTimerListener.java
- flutter-idea/src/io/flutter/bazel/PluginConfig.java
- flutter-idea/src/io/flutter/bazel/Workspace.java
- flutter-idea/src/io/flutter/run/bazel/BazelFields.java
- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- flutter-idea/testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- flutter-idea/testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- flutter-idea/testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- flutter-idea/testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
We've been using the daemon to request DevTools server start, but I changed over external DevTools to use `dart devtools` directly instead since that's a little faster and less indirection. This is the equivalent change for bazel workspaces
> Use devtools script to launch bazel devtools

- flutter-idea/src/io/flutter/analytics/FlutterAnalysisServerListener.java
- flutter-idea/src/io/flutter/analytics/RequestDetails.java
- flutter-idea/testSrc/unit/io/flutter/analytics/FlutterAnalysisServerListenerTest.java
This fixes the calculation of timings for completions and references. The old version was incorrect because it measured the time to get a response, but no work was done before the response was sent.
> Fix analytics

- flutter-idea/src/io/flutter/editor/WidgetIndentsHighlightingPass.java
Fixes https://github.com/flutter/flutter-intellij/issues/6123 (and seems to not break other things)
Two issues here:
- We don't want to extend the left vertical line if a segment of code has been folded
- We want to evaluate the line immediately following the end of a folded segment; if we skip `continue;` then we will evaluate two lines after
I find this code really hard to follow and debug, so I posted https://github.com/flutter/flutter-intellij/issues/6127
No folding:
First statement folded:
Both statements folded:
> Fix child lines when folding code

- flutter-idea/src/io/flutter/analytics/DartCompletionTimerListener.java
- flutter-idea/src/io/flutter/analytics/TimeTracker.java
- flutter-idea/src/io/flutter/bazel/WorkspaceCache.java
- flutter-idea/src/io/flutter/dart/DartPlugin.java
- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
- flutter-idea/src/io/flutter/editor/EditorMouseEventService.java
- flutter-idea/src/io/flutter/editor/EditorPositionService.java
- flutter-idea/src/io/flutter/editor/FlutterSaveActionsManager.java
- flutter-idea/src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
- flutter-idea/src/io/flutter/inspector/InspectorGroupManagerService.java
- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/perf/EditorPerfDecorations.java
- flutter-idea/src/io/flutter/perf/FlutterWidgetPerfManager.java
- flutter-idea/src/io/flutter/performance/FlutterPerformanceViewFactory.java
- flutter-idea/src/io/flutter/preview/PreviewViewFactory.java
- flutter-idea/src/io/flutter/pub/PubRootCache.java
- flutter-idea/src/io/flutter/run/FlutterAppManager.java
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageAnnotator.java
- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- flutter-idea/src/io/flutter/run/daemon/DeviceService.java
- flutter-idea/src/io/flutter/sdk/AndroidEmulatorManager.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkManager.java
- flutter-idea/src/io/flutter/view/FlutterViewFactory.java
Replace `ServiceManager.getService(project, aClass)` with `project.getService(aClass)`. Where it makes sense, the existing nullability rules are annotated. Other minor changes are due to reformatting.
> Stop using a deprecated method

- flutter-idea/src/io/flutter/analytics/Analytics.java
- flutter-idea/src/io/flutter/analytics/FlutterAnalysisServerListener.java
- flutter-idea/src/io/flutter/analytics/ThrottlingBucket.java
The analytics implementation limits events to occur no more than once per second. We have one measurement that sends four events, so we disable the one-second throttling in that case. This could send up to 2KB (including HTTP headers) but it only runs once every two hours.
> Disable fast throttling for multiple events

- flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
Fixes https://github.com/flutter/flutter-intellij/issues/6144 (hopefully)
> Check for project disposal before JxBrowser download

- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
Partially addresses: https://github.com/flutter/flutter-intellij/issues/6159, namely the issue with directory paths that include spaces.
The string of characters passed to `PercentEncoder` matches the list for Dart's [encodeFull](https://api.dart.dev/stable/2.17.1/dart-core/Uri/encodeFull.html), which is what the VM uses.
> Escape spaces for VM mapping

- flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java
- flutter-idea/src/io/flutter/actions/FlutterSdkAction.java
- flutter-idea/src/io/flutter/pub/PubRoot.java
- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Update Flutter commands on Build and Tools menu to run for all Flutter modules when no files are open and nothing is selected in the Project view. This may not be a great UI, but I hope to get something out to experiment with.
Also adds a Build option for the Web platform.
Fixes #5808
Helps with #5291
> Update Flutter commands on Build and Tools menu to run for all Flutter modules

- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
Bazel generated files have another path if we map to canonical files, so only use canonical paths for non-bazel projects.
This is a follow up to https://github.com/flutter/flutter-intellij/pull/6203
> Avoid using canonical path for bazel

- flutter-idea/src/io/flutter/run/FlutterPositionMapper.java
- flutter-idea/src/io/flutter/vmService/DartVmServiceDebugProcess.java
- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
- flutter-idea/testSrc/unit/io/flutter/run/FlutterPositionMapperTest.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSamples.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/CpuSamplesEvent.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Field.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/FieldRef.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/Func.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/FuncRef.java
This should not change behavior, as the old analyzer path mapping is the one that will be used for file mapping. I'm only using the new bazel mapping package to see whether the path generated is the same, logging if not.
> Log bazel mapping differences from analyzer

- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
Fixes https://github.com/flutter/flutter-intellij/issues/6317 and https://github.com/flutter/flutter-intellij/issues/6318
> Revert to using OFF_SCREEN render mode for Linux

- AUTHORS
- flutter-idea/src/io/flutter/pub/PubRoot.java
- flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java
Since Flutter 3.3 flutter plugins library manager doesn't updates flutter plugins library correctly (see #6330).
This pull request fixes that by watching both .packages and .dart_tool/package_config.json files. It also uses dart plugin method to extract path map from package_config.json.
> Adds Flutter 3.3 support for flutter plugins library manager

- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowser.java
Fixes https://github.com/flutter/flutter-intellij/issues/6351
I'm not able to reproduce that issue myself, but it seems appropriate to catch any exceptions from the JxBrowser browser.
> Catch browser close exceptions

- .idea/compiler.xml
- .idea/misc.xml
- resources/liveTemplates/flutter_miscellaneous.xml
- resources/liveTemplates/stanim.txt
- resources/liveTemplates/stful.txt
- resources/liveTemplates/stless.txt
Fixes #6288
Also updates a couple settings that got changed when I moved to IntelliJ 2022.2 as the dev platform.
@DanTup We can coordinate the actual date that this is released, if you want.
> Change Container to Placeholder in live templates

- flutter-idea/src/io/flutter/actions/AttachDebuggerAction.java
- flutter-idea/src/io/flutter/actions/FlutterDoctorAction.java
- flutter-idea/src/io/flutter/actions/FlutterSdkAction.java
- flutter-idea/src/io/flutter/bazel/PluginConfig.java
- flutter-idea/src/io/flutter/bazel/Workspace.java
- flutter-idea/src/io/flutter/run/bazel/BazelAttachConfig.java
- flutter-idea/src/io/flutter/run/bazel/BazelFields.java
- flutter-idea/src/io/flutter/run/bazel/BazelRunConfig.java
- flutter-idea/testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
- flutter-idea/testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
- flutter-idea/testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
- flutter-idea/testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java
This enables the attach button for bazel projects and calls the correct command for attach. We wanted to add attach to the IDEs since the internal scripts for attach have been updated to make this easier.
CC @chingjun
> Permit attach in bazel context

- flutter-idea/src/io/flutter/analytics/DartCompletionTimerListener.java
I think this will eliminate the symptom observed in #6400, but I don't know how the default project got disposed.
Fixes #6400
> Catch exception if default project was disposed

- .idea/misc.xml
- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java_stub
- product-matrix.json
- tool/plugin/lib/edit.dart
There are two problems with the build, in all but 2022.3.
First, the change to `DeviceSelectorAction` causes an old, very puzzling bug to re-appear. The fix is to use the old version of the code for all older builds.
Second, the change to show the device selector in the new UI breaks 2022.2. The fix is to remove that line for it.
> Fix build issues

- flutter-idea/src/io/flutter/run/FlutterAppManager.java
> Ignore disposed project in FlutterAppManager

- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java
- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java_stub
- product-matrix.json
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- tool/plugin/lib/edit.dart
Fixes: #6549 
Fixes: #6477
Getting this stack trace on start up. Waiting on resolution of the [Gradle plugin bug](https://github.com/JetBrains/gradle-intellij-plugin/issues/1246) to continue. The device selector is visible in the new UI. it is only visible for Flutter projects in new and old UI.
```java
DeviceSelectorAction#update@NavBarToolbar (io.flutter.actions.DeviceSelectorAction), actionId=Flutter.DeviceSelector
java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.
at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:417)
at io.flutter.FlutterUtils.invokeAndWait(FlutterUtils.java:99)
at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:132)
at …
```
> Run update() on BGT

- .github/workflows/presubmit.yaml
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.form
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
- product-matrix.json
- resources/META-INF/plugin.xml
- tool/plugin/test/plugin_test.dart
Makes some cosmetic changes to the settings page.
- Add comment to SDK section saying it applies to current project.
- Add comment that all other options apply to all projects
- Add comment about formatting with link to IDE settings for per-project option
> Update settings to emphasize global options

- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
- flutter-idea/testSrc/unit/io/flutter/editor/ActiveEditorsOutlineServiceTest.java
This is for #6613, which I don't want to close yet. It has a custom plugin build attached to it that includes this patch.
When a service is created, it should not cause another service to be created. I'm not sure when that rule was created, but it is causing errors in the latest EAP. This PR fixes that error. There may be other places that cause cascaded service creation, but they don't run at start-up, and we'll have to track them down.
> Create only a single service at a time

- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
- flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/BoundField.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/InboundReference.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/element/RetainingObject.java
This restores debugger functionality, which I broke in #6629.
It also does some clean up in VMServiceWrapper, making it a bit closer to the source in the Dart plugin.
> Fix debugger and BoundField.getName()

- CONTRIBUTING.md
Cloning the repo on Windows will cause the symlinks invalid, which requires a manual setup process.
I wonder if it's fine to add a script file in the `/tool` directory to address the extra step. …
> Add symlink handling when setup the project on Windows

- flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
The Android Studio-specific code we relied on to make the choice is no longer available as of 2022.3.
Fixes #6644
> Always open Android module in new window

- tool/plugin/lib/artifact.dart
Makes the artifact manager no longer uses the fixed base if `FLUTTER_STORAGE_BASE_URL` is configured on the host platform.
The change happens with the tool, I don't think any tests are related at present.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-c …
> ⚡️ Use `FLUTTER_STORAGE_BASE_URL` for `ArtifactManager`

- tool/plugin/lib/util.dart
Windows can change the encoding setting in its system region setting, and Gradle output options can be defined in system environments. There is no need to use `latin1` and it will break if the system or Gradle has manually set the encoding to UTF-8. …
> ⚡️ Always use `Utf8Codec` for plugin logs

- tool/plugin/lib/util.dart
The `removeAll` command is never been awaited for the result and it will throw exceptions if the corresponding directory does not exist on Windows.
The PR converts it to a Dart `Directory` delete and ignore exceptions to match previous behavior on all platforms. …
> ⚡️ Use `Directory.delete` instead of `rm`

- .idea/runConfigurations/flutter_idea__make_.xml
- .idea/runConfigurations/flutter_intellij__make_.xml
This could be a handy step when first setting up the environment at met the exception guided in [CONTRIBUTING.md](https://github.com/flutter/flutter-intellij/blob/master/CONTRIBUTING.md#flutter-plugin-development-on-macos-and-linux).
> Specified localPath '/.../flutter-intellij/artifacts/ideaIC' doesn't exist or is not a directory
[flutter/tests]: …
> Add the run configuration to make the plugin

- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java
- flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java
I forgot while making this change: https://github.com/flutter/flutter-intellij/pull/6614 that Bazel cases will not have a Flutter SDK, and this prevented DevTools from opening for bazel workspaces. Instead, we should check both workspace status and Flutter SDK before deciding what type of DevTools URL to use (we can assume bazel is always up to date).
> Fix DevTools opening for bazel workspaces

- product-matrix.json
Also note that in `edit.dart` we change the version of IntelliJ to the latest EAP build. All this is really doing is updating the Dart plugin version to work with EAP.
This also fixes the build failure in #6716 and #6717, which I merged before this was approved.
> Update Dart version for latest EAP build

- flutter-idea/src/io/flutter/run/bazelTest/BazelTestRunner.java
Bazel test output during startup is going to be using VM service URI instead going forward.
> Use VM service URI instead of observatory URI for bazel test startup

- flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.form
- flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.java
> Enable envars for run configs

- flutter-idea/src/io/flutter/editor/FlutterColorProvider.java
Fixes #5436.
| Before | After |
|------|------|
| ![image](https://github.com/flutter/flutter-intellij/assets/15884415/632e3d1c-9bf4-4ff9-9b87-dd79930a5830) | ![image](https://github.com/flutter/flutter-intellij/assets/15884415/c9188e22-4e93-4bc8-a0ab-756b5aec6f43) |
- `Colors` and `CupertinoColors` are hard-coded to determine *colored element*. The condition has been removed, which means all elements will be predicated.
- Referenced will be resolved before the element gets parsed by text directly.
- All the additional checks will be called only if the element type is `VAR_INIT` (for declarations) or `FUNCTION_BODY` (for getters) to avoid too much performance regression.
Test case:
```dart
import 'package:flutter/material.dart' hide Colors;
const Color _c1 = Color(0xff000000);
final _c2 = …
```
> 🐛 Resolves the referenced element before parsing colors

- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/run/FlutterDevice.java
- flutter-idea/src/io/flutter/view/FlutterView.java
Resolves #6189.
https://github.com/flutter/flutter-intellij/assets/15884415/b5a3438b-4fbd-4fa8-9027-fd3fe0f11963
- `Browser` is a singleton in the previous implementation. The PR updates it to be stored as a mapping between the tab name (the unique device name) and the browser instance.
- `Content`s are also cached to ensure they can be added after removing the empty content.
`FlutterPerformanceView` should be able to apply the same update but I didn't investigate it yet. …
> ✨ Support multiple running instance for inspectors

- CHANGELOG.md
- resources/liveTemplates/flutter_miscellaneous.xml
This also fixes a problem caused by a PR that didn't do `bin/plugin generate`, and I didn't want to take the time to get the author to update it, since I want to get the release out on time.
> Update changes for M74

- flutter-idea/src/io/flutter/run/LaunchState.java
Resolves https://github.com/flutter/flutter-intellij/issues/6189#issuecomment-1477406823.
> 🚸 Add device name for running processes

- AUTHORS
- flutter-idea/src/io/flutter/editor/NativeEditorNotificationProvider.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
I (hopefully) added an option "Open in Xcode". Does anyone else maybe have a test environment ready? I will test locally, opening PR to get feedback on the design question.
**Design Question:** I did not add a second action, using "flutter.xcode.open" for iOS and macOS, should it rather be refactored to use two different actions? Something like ["flutter.xcode.openiOS" and "flutter.xcode.openMacOS"] or ["flutter.xcode.open.iOS" and "flutter.xcode.open.macOS"] or something else?
[Missing open MacOS module in xcode #6209](https://github.com/flutter/flutter-intellij/issues/6209)
[Tree Hygiene]: …
> add Open in Xcode for macOS

- .gitignore
IntelliJ expects Gradle at the top level. We have it in third_party. You can symlink to it I think, but I just let IntelliJ install it for me. In any case, we don't want to check it in.
> Add gradle to ignore list

- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
No need to check for ".macos" since modules only work for iOS and Android.
> Allow Open iOS/macOS module to work for top-level macOS directory

- product-matrix.json
> Use IJ version in 2023.1

- flutter-idea/src/io/flutter/settings/FlutterSettings.java
Reverts flutter/flutter-intellij#6834
We aren't able to run this on Linux, potentially related to https://youtrack.jetbrains.com/issue/JBR-4484/JCEF-is-not-supported-in-this-env-or-failed-to-initialize-for-CentOS-7-machine
> Revert "Default to JCEF browser (#6834)"

- flutter-idea/src/io/flutter/inspector/InspectorService.java
- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
Fixes #6875
Some things I'm not sure about:
- I'm currently using the custom VM service stream 'ToolEvent' directly. VS Code is using the DAP forwarding of events from this stream; is this a point where it would make sense to use DAP from DDS?
- This skips large portions of previous architecture to listen for changes in selections, e.g. classes like `InspectorObjectGroupManager` - is that okay?
> Use ToolEvent for inspect elements

- flutter-idea/src/io/flutter/editor/FlutterCompletionContributor.java
- flutter-idea/src/io/flutter/inspector/DiagnosticsNode.java
- flutter-idea/src/io/flutter/module/FlutterGeneratorPeer.java
- flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
- flutter-idea/src/io/flutter/run/bazelTest/BazelTestRunner.java
- flutter-idea/src/io/flutter/run/common/CommonTestConfigUtils.java
- flutter-idea/src/io/flutter/run/common/TestType.java
- flutter-idea/src/io/flutter/utils/JsonUtils.java
- flutter-idea/src/io/flutter/view/DiagnosticsTreeCellRenderer.java
- flutter-idea/src/org/dartlang/analysis/server/protocol/FlutterOutline.java
- flutter-idea/src/org/dartlang/analysis/server/protocol/FlutterWidgetProperty.java
- flutter-idea/src/org/dartlang/analysis/server/protocol/FlutterWidgetPropertyEditor.java
- tool/plugin/lib/lint.dart
Fix for https://github.com/flutter/flutter-intellij/issues/6933, removal of the soon to be deprecated `org.apache.commons.lang.*` references.
> Fix for #6933: remove deprecated org.apache.commons.lang.* references

- flutter-idea/src/io/flutter/font/ProjectOpenListener.java
- flutter-idea/src/io/flutter/project/FlutterProjectStructureDetector.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkManager.java
https://github.com/flutter/flutter-intellij/issues/6953
> Add comments to identify current risk from the Components deprecation

- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
Changes in the implementation of AnActionListener - beforeActionPerformed and afterActionPerformed have APIs that are being removed with time
> Changes in the implementation of AnActionListener

- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
Message wasn't displayed previously, and we want this before making JCEF default. I figure logging should help us understand what platforms are failing.
> Log and show link to open DevTools in separate browser if JCEF fails

- flutter-idea/src/io/flutter/logging/FlutterConsoleLogManager.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Partially addresses https://github.com/flutter/flutter-intellij/issues/6844
FlutterReloadManager also uses this API but that seems a bit more complex, so I'll leave it for a separate commit.
> Remove deprecated notification group usage from deep link

- flutter-idea/src/io/flutter/run/SdkAttachConfig.java
- flutter-idea/src/io/flutter/run/SdkRunConfig.java
The listener added to shut down a running app should stop listening when an app ends, not when a project is closed.
I believe this should fix https://github.com/flutter/flutter-intellij/issues/6930
> Dispose SDK config correctly on app ending

- flutter-idea/src/io/flutter/run/common/CommonTestConfigUtils.java
This class was pointed out as a source of memory leaks, and it seems this is because file paths aren't removed from `listenerCache` on project close. I wanted to check with @alexander-doroshko following the conversation on https://github.com/flutter/flutter-intellij/pull/7065 that this is a reasonable fix.
> Remove listener for file path on project dispose

- flutter-idea/src/io/flutter/devtools/DevToolsIdeFeature.java
- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java
- flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java
Addresses https://github.com/flutter/flutter-intellij/issues/7100
CC @kenzieschmoll
> Ide feature

- flutter-idea/src/io/flutter/FlutterUtils.java
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.form
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
- flutter-idea/src/io/flutter/utils/JxBrowserUtils.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
This removes the option to select JCEF or JX Browser in settings for simplicity. We will instead check if JCEF is available first, and if not, download and use JX Browser. Embedded browser failures in IJ (where JCEF is included by default) were very low, so I think it's unlikely users will benefit from having a choice here.
I still need to build this to check whether this is detecting the presence of JCEF accurately.
> Make JX Browser the fallback and remove settings option

- CHANGELOG.md
- flutter-idea/src/io/flutter/FlutterUtils.java
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.form
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
- flutter-idea/src/io/flutter/utils/JxBrowserUtils.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- resources/META-INF/plugin.xml
This reverts commit d5a941c302eed420c22c590350bdaa0ddde79978.
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
*List which issues are fixed by this PR. You must list at least one issue.*
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
[Flutter Style Guide]: …
> Revert "Make JX Browser the fallback and remove settings option (#7232)"

- tool/github.sh
- tool/kokoro/setup.sh
This will prevent Flutter IJ work if the master branch gets into a state that the master branch can't build the cli tool.
> Change the git clone to sync to the stable branch and only to download the single (stable) branch

- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/testSrc/unit/io/flutter/view/FlutterViewTest.java
This is a refactor while working on adding a deep links panel. It seems that the `FlutterView` class is passing around `inspectorService` in a lot of places, but I don't see it being used.
> Remove unused inspector service from jxbrowser functions

- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
Fixes https://github.com/flutter/flutter-intellij/issues/7133
Prior to version 3.7.1, we will be using the debug stream to receive inspect events to jump to code
> Check version before starting ToolEvent stream

- flutter-idea/src/io/flutter/inspector/InspectorService.java
- flutter-idea/src/io/flutter/vmService/ServiceExtensions.java
> Change to using addPubRootDirectories

- flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java
- flutter-idea/src/io/flutter/actions/OpenInAppCodeAction.java
- flutter-idea/src/io/flutter/actions/OpenInXcodeAction.java
- flutter-idea/src/io/flutter/actions/RunFlutterAction.java
Partially addresses https://github.com/flutter/flutter-intellij/issues/7330
These are classes where there's clearly no UI manipulations happening in `update` in either the direct classes or inheriting children.
> Fix simplest cases of ActionUpdateThread

- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java
- flutter-idea/src/io/flutter/actions/OpenEmulatorAction.java
- flutter-idea/src/io/flutter/actions/OpenSimulatorAction.java
- flutter-idea/src/io/flutter/actions/RestartFlutterDaemonAction.java
Partially addresses #7330 
I'm not sure if these are needed since I wasn't seeing the deprecation notice while using the device menu, but I looked through update activities in these classes and it seems safe to make all of these BGT. 
I think there is potentially a bug with emulator options: https://github.com/flutter/flutter-intellij/issues/7409
> Specify BGT updates for device-related actions

- flutter-idea/src/io/flutter/actions/FlutterToolsActionGroup.java
- flutter-idea/src/io/flutter/actions/OpenInAndroidStudioAction.java
- flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
Partially addresses https://github.com/flutter/flutter-intellij/issues/7330
> Make tool menu actions BGT update

- CHANGELOG.md
- resources/META-INF/plugin.xml
This release will be marked as hidden for Iguana and Jellyfish.
> Update the CHANGELOG.md for a point release, versioned `79.1`

- flutter-idea/src/io/flutter/deeplinks/DeepLinksViewFactory.java
- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/devtools/DevToolsUtils.java
- flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java
- flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/testSrc/unit/io/flutter/devtools/DevToolsUrlTest.java
Fixes #7319 
This became a larger change than I originally intended, but I figured refactoring the `DevToolsUrl` class would be helpful for upcoming work on integrating more DevTools panels.
Summary of changes:
- Add param `&theme=[light/dark]` to fix the original issue
- Use builder for making DevToolsUrl class
- Use utility class for finding the IDE's background color, light/dark mode, and font size
- Only send theming information when browser is embedded
> Fix background color

- flutter-idea/src/io/flutter/FlutterBundle.properties
- flutter-idea/src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
Race conditions where the sdk hasn't been cached resulting in the notification provides more of a distraction than value. (The Flutter SDK being tested here is pre-`0.0.12`.)
This work should be replaced with something such as https://github.com/flutter/flutter-intellij/issues/2932
> Remove the SDK minimum validation notification in the Flutter Plugin

- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
- flutter-idea/src/io/flutter/preview/PreviewView.java
This fixes the Flutter outline by using the new file uri keys, dependent on the version of the Dart SDK being used, i.e. support for macro enabled SDKs.
This is follow up on https://github.com/flutter/flutter-intellij/pull/7462
> Fix the Flutter outline

- flutter-idea/src/io/flutter/deeplinks/DeepLinksViewFactory.java
I didn't know we could hide tool windows based on SDK using `isApplicableAsync`. Originally we only added an error message about SDK version because we thought we couldn't hide tool windows. I think it's neater to hide unusable tool windows - this takes off deep links as a window option in the View menu.
> Hide deep links window when insufficient SDK version

- CHANGELOG.md
- resources/META-INF/plugin.xml
This re-writes history collapsing the change log notes from the point releases in `79.x` as these releases were not pushed out the stable AS releases.
> Update the CHANGELOG.md for version 80

- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
> Use embed=one for DevTools URL

- CHANGELOG.md
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- resources/META-INF/plugin.xml
This fixes https://github.com/flutter/flutter-intellij/issues/7507
> Release the Project and Editor references from the FlutterReloadManager

- CHANGELOG.md
- flutter-idea/src/io/flutter/editor/NativeEditorNotificationProvider.java
- resources/META-INF/plugin.xml
Additionally, nullability annotations were added to method signatures.
This is follow up on https://github.com/flutter/flutter-intellij/pull/7412
This resolves https://github.com/flutter/flutter-intellij/issues/7488
> Prevent the NativeEditorNotificationProvider from passing `flutter.androidstudio.open` as a valid action id.

- CHANGELOG.md
- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
- flutter-idea/src/io/flutter/run/common/CommonTestConfigUtils.java
- flutter-idea/src/io/flutter/run/test/FlutterTestLineMarkerContributor.java
- resources/META-INF/plugin.xml
This resolves https://github.com/flutter/flutter-intellij/issues/7505 and https://github.com/flutter/flutter-intellij/issues/7522
> Use URI keys in ActiveEditorsOutlineService, this fixes the run icons for flutter tests

- flutter-idea/src/io/flutter/performance/FlutterPerformanceView.java
Follow up to https://github.com/flutter/flutter-intellij/pull/7577
> Make performance tab warning text red

- flutter-idea/src/io/flutter/FlutterUtils.java
- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
- flutter-idea/src/io/flutter/view/FlutterView.java
Sometimes starting the JX Browser engine is causing the UI freezes. This is trying to move some work out of the UI thread according to info from https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html
> Move JX Browser engine initialization to a separate thread

- .github/workflows/presubmit.yaml
- CHANGELOG.md
- product-matrix.json
- resources/META-INF/plugin.xml
- tool/plugin/test/plugin_test.dart
This resolves https://github.com/flutter/flutter-intellij/issues/7595
> Initial support 2024.2 & Android Studio Ladybug Canary 6

- flutter-idea/src/io/flutter/performance/FlutterPerformanceViewFactory.java
Fixes https://github.com/flutter/flutter-intellij/issues/7624
> Remove performance view for newer Flutter SDK versions

- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/testSrc/unit/io/flutter/view/FlutterViewTest.java
This change:
- Removes an automatic refresh of the inspector tool window when theming changes
- Adds check for theming during manual refresh of all of the DevTools windows
> Remove automatic refresh of inspector window on theme change and check during manual refresh

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/analytics/UnifiedAnalytics.java
- flutter-idea/src/io/flutter/dart/DtdUtils.java
- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/devtools/DevToolsUtils.java
Addresses https://github.com/flutter/flutter-intellij/issues/7626
> Send theme changed event over DTD

- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
This offers a way to use a development version of DevTools (whatever `devtools_tool serve` runs) while using a standard Flutter plugin. This should be helpful when testing DevTools-IJ interactions.
Typically, the Dart plugin starts DTD and then also starts DevTools, passing in the DTD URL. The Flutter plugin will then use this instance of DevTools to access embedded tool windows. When using this locally served DevTools, the Dart plugin behaves the same way, but the Flutter plugin starts its own instance of local DevTools using the same DTD URL. (Note that there could be some side effects from having two DevTools instances started, connected to the same DTD instance.)
Instructions for using this:
1. Set the registry key to your DevTools directory: Go to Help > Find action > Registry > Find …
> Add a way for developers of DevTools to use Flutter plugin with locally served DevTools

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
Analogous to https://github.com/Dart-Code/Dart-Code/pull/5257
> Add notification when SDK is unsupported

- flutter-idea/src/io/flutter/utils/JxBrowserUtils.java
See https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/openapi/util/SystemInfo.java#L199
> Migration from SystemInfo.isXXBit

- flutter-idea/src/io/flutter/performance/FlutterPerformanceViewFactory.java
A workaround for #7691, not accessing the tool window if it wasn't created due to `isApplicableAsync` being false for the SDK version. Does it in this listener so if the SDK version changes, the event still can be handled properly.
> Gracefully handle perf tool window not being created

- flutter-idea/src/io/flutter/run/FlutterAppManager.java
https://github.com/JetBrains/intellij-community/blob/337bcc327a5d34720e134e312768de414c5572b0/platform/core-api/src/com/intellij/openapi/components/ServiceManager.java#L35
https://github.com/JetBrains/intellij-community/blob/d587049edb9cc85f67d4e070584ad79f68befc2e/platform/execution/src/com/intellij/execution/ExecutionManager.kt#L40
This is progress towards resolving https://github.com/flutter/flutter-intellij/issues/7718
> Migrate off of `ServiceManager.getServiceIfCreated` API usage

- .gitignore
This is part of the Gradle IntelliJ migration, https://github.com/flutter/flutter-intellij/issues/7670
Message from the updated plugin:
```
> Task :flutter-idea:verifyPluginProjectConfiguration
[org.jetbrains.intellij.platform] The following plugin configuration issues were found:
- The IntelliJ Platform cache directory should be excluded from the version control system. Add the '.intellijPlatform' entry to the '.gitignore' file.
```
> Add the .intellijPlatform directories to .gitignore

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
Flutter SDK version `3.10.0`, Dart SDK version `3.0.0`
This work is in prep for a point release soon (1-2 days).
This work is in sync with DartCode, see https://dartcode.org/releases/#v31000-2024-10-31.
> Enable notification when SDK will soon be unsupported soon

- tool/plugin/lib/plugin.dart
This is a followup on https://github.com/flutter/flutter-intellij/issues/7670
> Fix the Kokoro failure introduced with the IntelliJ Platform Gradle Plugin (2.x) migration

- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-idea/src/org/jetbrains/android/facet/AndroidFrameworkDetector.java
- tool/kokoro/build.sh
- tool/plugin/lib/verify.dart
This is follow-up work for https://github.com/flutter/flutter-intellij/pull/7774 and https://github.com/flutter/flutter-intellij/issues/7670
> Re-enable the verify Gradle task and have Kokoro run it again

- flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
- flutter-idea/src/io/flutter/font/FontPreviewProcessor.java
- flutter-idea/src/io/flutter/inspections/FlutterDependencyInspection.java
- flutter-idea/src/io/flutter/perf/FlutterWidgetPerf.java
- flutter-idea/src/io/flutter/performance/WidgetPerfTable.java
- flutter-idea/src/io/flutter/run/FlutterPositionMapper.java
- flutter-idea/src/io/flutter/run/ObservatoryFile.java
- flutter-idea/src/io/flutter/test/DartTestEventsConverterZ.java
- flutter-idea/src/io/flutter/view/MultiIconSimpleColoredComponent.java
- flutter-idea/src/io/flutter/vmService/DartVmServiceBreakpointHandler.java
- flutter-idea/src/io/flutter/vmService/DartVmServiceDebugProcess.java
- flutter-idea/src/io/flutter/vmService/IsolatesInfo.java
- flutter-idea/src/io/flutter/vmService/VMServiceManager.java
- flutter-idea/src/io/flutter/vmService/frame/DartVmServiceEvaluator.java
- flutter-idea/testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java
- tool/plugin/lib/lint.dart
These are deprecated references caught by the `./bin/plugin verify` tool
> Removal of all gnu.trove.* deps from the Flutter plugin

- build.gradle.kts
- flutter-idea/build.gradle.kts
- tool/kokoro/build.sh
Local runs are producing different output than the Kokoro bot, hence the continued volatility
Verify has been disabled for the time being as the CI bots currently throw an exception (see below)
> Update the settings in build.gradle.kts for the validate task

- flutter-idea/src/io/flutter/perf/FlutterWidgetPerf.java
- flutter-idea/src/io/flutter/run/ObservatoryFile.java
- tool/plugin/lib/lint.dart
The `Int2ObjectOpenHashMap` implementation is the most common implementation I found across the IntelliJ platform, so went with that for its general usage characteristics.
> Avoid internal AS collections

- flutter-idea/src/io/flutter/FlutterBundle.properties
- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/utils/FlutterModuleUtils.java
- flutter-idea/testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java
Original work: https://github.com/flutter/flutter-intellij/commit/da5eea7792c7da6a09740e65ed9bfc590137dcee
> Remove the old logic (2017) to migrate Flutter projects from one module type to another

- flutter-idea/src/io/flutter/preview/PreviewView.java
Without this change, exceptions are thrown as various file and caret listeners try to interact with an outline view that is not created.
> Remove some listener events from the removed Outline view

- tool/plugin/lib/plugin.dart
This is similar to the end of the verify cli command
> Write a summary at the end of the make cli command

- flutter-idea/src/io/flutter/editor/FlutterPubspecNotificationProvider.java
This is progress on https://github.com/flutter/flutter-intellij/issues/7830
> Migrate the FlutterPubspecNotificationProvider to the new EditorNotificationProvider API

- flutter-idea/src/io/flutter/editor/NativeEditorNotificationProvider.java
This is progress on https://github.com/flutter/flutter-intellij/issues/7830
> Migrate the NativeEditorNotificationProvider to the new EditorNotificationProvider API

- flutter-idea/src/io/flutter/FlutterUtils.java
- flutter-idea/src/io/flutter/jxbrowser/EmbeddedBrowserEngine.java
- flutter-idea/src/io/flutter/module/settings/SettingsHelpForm.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
https://github.com/JetBrains/intellij-community/blob/768c7392257e8fbedcc1aa4c738fa523b89fa0e6/platform/core-api/src/com/intellij/openapi/components/ServiceManager.java#L19
This is progress on https://github.com/flutter/flutter-intellij/issues/7718
The removal of the method in flutter-idea/src/io/flutter/module/settings/SettingsHelpForm.java is due to the method being unused
> Migrate off of ServiceManager.getService(..)

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/project/ProjectWatch.java
- flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
https://github.com/flutter/flutter-intellij/issues/7718
https://github.com/JetBrains/intellij-community/blob/ab4c7fdf3cc2887d44d081681ec642843adfff6d/platform/projectModel-api/src/com/intellij/ProjectTopics.java#L12
> Migrate from deprecated method: ProjectTopics.X to ModuleListener.X

- flutter-idea/src/io/flutter/ProjectOpenActivity.java
- flutter-idea/src/io/flutter/utils/AndroidUtils.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
https://github.com/JetBrains/intellij-community/blob/b68fd84f1e958485be2e7d3df46a6703101b43df/platform/projectModel-api/src/com/intellij/openapi/project/ProjectTypeService.java#L37
> Migrate usages of ProjectTypeService.getProjectType(..)

- flutter-idea/src/io/flutter/run/OpenDevToolsAction.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Append "Open Flutter DevTools" action with to "in Browser", this makes the action consistent with other actions in IDEA which trigger the browser to open.
Cleanup related to https://github.com/flutter/flutter-intellij/issues/7839
> Rename the Open Flutter DevTools action

- flutter-idea/src/io/flutter/project/FlutterProjectOpenProcessor.java
This is progress towards https://github.com/flutter/flutter-intellij/issues/7718
> Migrate off of Extensions.getExtensions() usages

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/actions/OpenInXcodeAction.java
- flutter-idea/src/io/flutter/dart/DartPlugin.java
- flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
- flutter-idea/src/io/flutter/editor/FlutterPubspecNotificationProvider.java
- flutter-idea/src/io/flutter/module/settings/ProjectType.java
- flutter-idea/src/io/flutter/run/SdkFields.java
- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- flutter-idea/src/io/flutter/run/test/FlutterTestConfigProducer.java
- flutter-idea/src/io/flutter/run/test/FlutterTestRunner.java
- flutter-idea/src/io/flutter/run/test/TestFields.java
- flutter-idea/src/io/flutter/run/test/TestLaunchState.java
- flutter-idea/src/io/flutter/sdk/FlutterSdk.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
- flutter-idea/testSrc/unit/io/flutter/editor/FlutterIconLineMarkerTest.java
- flutter-idea/testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java
https://github.com/flutter/flutter-intellij/issues/7882
> Remove support for old Flutter SDKs

- tool/grind.dart
- tool/plugin/lib/build_spec.dart
- tool/plugin/lib/edit.dart
- tool/plugin/lib/lint.dart
- tool/plugin/lib/plugin.dart
- tool/plugin/lib/runner.dart
- tool/plugin/lib/util.dart
- tool/plugin/lib/verify.dart
- tool/plugin/test/plugin_test.dart
Modernize dart files w/ a fresh formatting (to tall-style).
To avoid future churn, we might consider formatting validation in a test or a presubmit.
We might consider similar for sorting (as we do in the analyzer code base). …
> [CQ] dart re-format

- flutter-idea/src/io/flutter/editor/ExpressionParsingUtils.java
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
*List which issues are fixed by this PR. You must list at least one issue.*
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
[Flutter Style Guide]: …
> Fix warnings for NullPointerException in flutter-idea/src/io/flutter/editor/ExpressionParsingUtils.java

- resources/inspectionDescriptions/FlutterDependency.html
Fixes a warning found by "Inspect Code."
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
> Add a lang attribute to the FlutterDependency html tag

- CONTRIBUTING.md
Since we're not requiring signing anymore, we can remove this bit from the contributing docs.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-h …
> [PE] remove stale commit signing instructions

- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageAnnotator.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageEnabledConfiguration.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageEngine.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageProgramRunner.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageRunner.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageSuite.java
- flutter-idea/src/io/flutter/run/coverage/LcovInfo.java
- flutter-studio/build.gradle.kts
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Fix the test coverage regression, this resolves https://github.com/flutter/flutter-intellij/issues/7810.
> 7810 test coverage regression fix

- .github/workflows/presubmit.yaml
- .github/workflows/presubmit.yaml.template
- tool/github.sh
With the current version of `git` used by the presubmits an issue is being hit.  See https://github.com/flutter/flutter-intellij/pull/7937 for context
> Fix the pre-submit for the flutter-intellij project

- CHANGELOG.md
- resources/META-INF/plugin.xml
https://github.com/flutter/flutter-intellij/milestone/96
https://plugins.jetbrains.com/plugin/9212-flutter/edit/versions
```
- Fix the slow operation notification associated with PubRoot (#7885)
- Cleanup: removal of pre Dart SDK 3.0 code (#7882)
- Cleanup: removal of the deprecated Swing-- Fix the slow operation notification associated with PubRoot (#7885)based Inspector window (#7861)
- Cleanup: removal of the deprecated Outline window (#7816)
- Cleanup: removal of the deprecated Performance page window (#7816)
- Migrated all instances of EditorNotifications.Provider to the new API (#7830)
```
> Prep the CHANGELOG.md for M84

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
This was unintentionally deleted in https://github.com/flutter/flutter-intellij/pull/7706
> Restore the Flutter Inspector in the Flutter IJ plugin support

- CONTRIBUTING.md
Fixes https://github.com/flutter/flutter-intellij/issues/7911
> Update CONTRIBUTING steps

- flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewFactory.java
Resolves https://github.com/flutter/flutter-intellij/issues/7952
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat …
> Hide Flutter DevTools' debugger

- .github/workflows/presubmit.yaml
- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-studio/build.gradle.kts
- product-matrix.json
- tool/github.bat
- tool/github.sh
- tool/kokoro/setup.sh
- tool/plugin/lib/build_spec.dart
- tool/plugin/lib/runner.dart
Changes to support Release 85 - IntelliJ 2025.1
> Changes to support Release 85 - IntelliJ 2025.1

- flutter-idea/src/io/flutter/pub/PubRoot.java
https://github.com/flutter/flutter-intellij/issues/7968
The issue was introduced with this change: https://github.com/flutter/flutter-intellij/pull/7885
The documentation from JetBrains states that this code is to avoid deadlocks: https://github.com/JetBrains/intellij-community/blob/idea/243.21565.193/platform/core-api/src/com/intellij/openapi/application/ReadAction.java#L94
> Fix the IntelliJ freeze issue 7968

- product-matrix.json
Typo was introduced in this change: https://github.com/flutter/flutter-intellij/commit/38e78f0d9fac4ed3d35b59e8445c8f415e4f09c7
A group of Narwhals is called a blessing.  The same fact is true about unicorns.
> Fix typo in the product matrix, 2025.1 is Narwhal

- CONTRIBUTING.md
Fixes a few typos in the `gradle.properties` template. …
> [docs] fix `gradle.properties` template

- flutter-idea/src/io/flutter/FlutterErrorReportSubmitter.java
- flutter-idea/src/io/flutter/actions/ReloadAllFlutterApps.java
- flutter-idea/src/io/flutter/actions/RestartAllFlutterApps.java
- flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
- flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
- flutter-idea/src/io/flutter/project/FlutterProjectStructureDetector.java
- flutter-idea/src/io/flutter/run/test/DartTestLocationProviderZ.java
- flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java
- flutter-idea/src/io/flutter/test/DartTestEventsConverterZ.java
- flutter-idea/src/io/flutter/vmService/DartVmServiceListener.java
- flutter-idea/testSrc/unit/io/flutter/ide/DartTestUtils.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
- flutter-studio/src/io/flutter/utils/GradleUtils.java
Clean up a bunch of unneeded (redundant) warning suppressions.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-cha …
> [CQ] remove redundant warning suppressions

- flutter-idea/src/io/flutter/FlutterUtils.java
- flutter-idea/src/io/flutter/android/IntelliJAndroidSdk.java
- flutter-idea/src/io/flutter/console/FlutterConsoleFilter.java
- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/editor/FlutterColorProvider.java
- flutter-idea/src/io/flutter/editor/OutlineLocation.java
- flutter-idea/src/io/flutter/jxbrowser/EmbeddedJxBrowser.java
- flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
- flutter-idea/src/io/flutter/logging/DiagnosticsNode.java
- flutter-idea/src/io/flutter/pub/PubRoot.java
- flutter-idea/src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
- flutter-idea/src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.java
- flutter-idea/src/io/flutter/run/common/RunMode.java
- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
- flutter-idea/src/io/flutter/run/daemon/DeviceDaemon.java
- flutter-idea/src/io/flutter/run/test/DartTestLocationProviderZ.java
- flutter-idea/src/io/flutter/sdk/AndroidEmulatorManager.java
- flutter-idea/src/io/flutter/sdk/FlutterSdk.java
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
- flutter-idea/src/io/flutter/test/DartTestEventsConverterZ.java
- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/FlutterView.java
- flutter-idea/src/io/flutter/vmService/DartVmServiceDebugProcess.java
- flutter-idea/src/io/flutter/vmService/VMServiceManager.java
- flutter-idea/src/io/flutter/vmService/frame/DartVmServiceEvaluator.java
- flutter-idea/src/io/flutter/vmService/frame/DartVmServiceSuspendContext.java
- flutter-idea/testSrc/unit/io/flutter/utils/IconPreviewGeneratorTest.java
- flutter-studio/src/io/flutter/utils/GradleUtils.java
Get null-safe comparisons when comparators might be null using [`Object.equals`](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#equals-java.lang.Object-java.lang.Object-). …
> [CQ] nullability: make equality checks safe w/ `Objects.equals()`

- flutter-idea/src/io/flutter/module/settings/InitializeOnceBoolValueProperty.java
Methods in `final` classes don't need the extra annotation.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-change …
> [CQ] Declaration Redundancy: remove unnecessary `final` method modifiers

- flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
This `stopwatch` field is unused so can be safely removed. …
> [CQ] Write-only: remove unused stopwatch

- flutter-idea/src/io/flutter/view/MultiIconSimpleColoredComponent.java
- flutter-idea/src/io/flutter/vmService/FlutterFramesMonitor.java
Implicit casts can lead to lossy conversions.
[Discord]: …
> [CQ] Numeric issues: fix implicit casts

- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageAnnotator.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageEnabledConfiguration.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageEngine.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageProgramRunner.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageRunner.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageSuite.java
- flutter-idea/src/io/flutter/run/coverage/LcovInfo.java
- flutter-studio/build.gradle.kts
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
If successful, this will resolve https://github.com/flutter/flutter-intellij/issues/7810
Delay is due to Gradle IJ (upstream IJ platform) issues, this work was blocked until this was resolved: https://github.com/flutter/flutter-intellij/issues/7936
> Repair the support for Test with Coverage

- flutter-idea/testSrc/unit/io/flutter/FlutterUtilsTest.java
Expected and actual are flipped here which makes debugging confusing!
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-break …
> [CQ] debuggability: fix order of `assertSame` args

- flutter-idea/testSrc/unit/io/flutter/run/FlutterPositionMapperTest.java
- flutter-idea/testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java
- flutter-idea/testSrc/unit/io/flutter/utils/UrlUtilsTest.java
Similar to #8015. Fix order of `actual` and `expected` assert args to keep debugging sane. 
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hyg …
> [CQ] debugability: fix mis-ordered asserts

- CONTRIBUTING.md
- flutter-idea/src/io/flutter/run/daemon/DevToolsService.java
This PR:
- Updates the CONTRIBUTING docs to include instructions for how to run IntelliJ with a local DevTools
- Changes the `devtools_tool` command to `dt` now that is has been renamed
> Updates for developing with a local DevTools version

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
This resolves https://github.com/flutter/flutter-intellij/issues/8029
> Fix a sporadic error with the IDEA platform not registering all toolWindows

- CHANGELOG.md
- resources/META-INF/plugin.xml
https://github.com/flutter/flutter-intellij/milestone/97?closed=1
> Staging of the CHANGELOG.md for M85 release

- resources/liveTemplates/flutter_miscellaneous.xml
Since we're not going to externalize these strings, it's best to not get nagged by the inspection about it. (Especially not 7 times! 🙃) …
> [CQ] suppress `LiveTemplateI18n` warnings

- flutter-idea/src/io/flutter/run/common/TestLineMarkerContributor.java
Migrate to supported `RunLineMarkerContributor.Info` constructor uses.
See: https://github.com/flutter/flutter-intellij/issues/7718. …
> [CQ] migrate from slated-for-removal `RunLineMarkerContributor.Info` APIs

- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
Migrate to future-safe `modulesAdded` API and fix unchecked calls.
(Removing another bit of noise from the run console.)
See: https://github.com/flutter/flutter-intellij/issues/7718. …
> [CQ] `AddToAppUtils`: fix deprecated API use and unchecked calls

- flutter-studio/src/io/flutter/utils/FlutterExternalSystemTaskNotificationListener.java
The default constructor is slated for removal.
See: https://github.com/JetBrains/intellij-community/blob/b41a4084da5521effedd334e28896fd9d07410da/platform/external-system-api/src/com/intellij/openapi/externalSystem/model/task/ExternalSystemTaskNotificationListenerAdapter.java#L18 …
> [CQ] migrate away from slated-for-removal adapter API

- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.form
- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
As per https://plugins.jetbrains.com/docs/intellij/built-in-button.html#browse
> Replace deprecated ComboBoxWithBrowserButton

- build.gradle.kts
- flutter-idea/build.gradle.kts
I thought this was working in January, however clearly the jar was not included in the original PR: https://github.com/flutter/flutter-intellij/pull/7871
Changing back for now until we update the verifier jar again.
This is the start of the work involved with https://github.com/flutter/flutter-intellij/issues/8034
> Change the verifier CLI version back to 1.379

- product-matrix.json
This resolves https://github.com/flutter/flutter-intellij/issues/8040
> Fix the disappearance of the New Flutter Project menu item

- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
Fixes an issue where we never unsubscribe outline listeners.
The rub is that `getLocalFileUri` is being called on a path that is already a URI and is producing a bogus path which has no associated listener registered (because it’s bogus).
In general the issue here is a symptom of URIs being encoded in strings that are never validated.
The quick fix is to not “uri-ify” an already valid UR string. Longer term we should consider a deeper audit of places we’re passing URIs around. It’s possible there are other related issues. If/when we do this, Alex shared some [interesting thoughts from his work on the Dart plugin](https://github.com/flutter/flutter-intellij/issues/7980#issuecomment-2785510617) that’d be worth synthesizing.
Fixes: https://github.com/flutter/flutter-intellij/issues/7980
If …
> Fix `FlutterOutline` service infinite subscriptions

- flutter-idea/src/io/flutter/devtools/DevToolsUtils.java
- flutter-idea/src/io/flutter/view/FlutterView.java
Restores source navigation from the embedded devtools inspector.
Fixes: https://github.com/flutter/flutter-intellij/issues/8041 …
> Fix broken devtools inspector source navigation

- CHANGELOG.md
- resources/META-INF/plugin.xml
Update the changelog for https://github.com/flutter/flutter-intellij/pull/8058
https://github.com/flutter/flutter-intellij/milestone/101
> Update the changelog.md for M85.2

- flutter-idea/src/io/flutter/bazel/PluginConfig.java
- flutter-idea/src/io/flutter/bazel/Workspace.java
- flutter-idea/src/io/flutter/pub/PubRoot.java
- flutter-idea/src/io/flutter/run/FlutterPositionMapper.java
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- flutter-idea/src/io/flutter/run/bazelTest/BazelTestRunner.java
- flutter-idea/src/io/flutter/utils/EnableDartSupportForModule.java
- flutter-idea/src/io/flutter/utils/OpenApiUtils.java
- flutter-idea/src/io/flutter/vmService/VmServiceWrapper.java
- flutter-idea/src/io/flutter/vmService/frame/DartVmServiceValue.java
- flutter-idea/testSrc/unit/io/flutter/run/FlutterPositionMapperTest.java
Add a null-safe `safeRunReadAction` and migrate unsafe callers to use it.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-b …
> [CQ] ensure null-safe read actions

- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
Fixes unchecked operations that are unsafe **and** clutter our plugin runs with noise.
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene. …
> [CQ] fix unchecked ops in `AddToAppUtils`

- flutter-idea/src/io/flutter/run/daemon/DeviceDaemon.java
The constructor we were invoking was defaulting to `IdeModalityType.PROJECT` which is not fully supported. Migrating to use `IdeModalityType.IDE` addresses this. 
(Verified on Meerkat.)
Fixes: https://github.com/flutter/flutter-intellij/issues/7986
[CLA]: …
> Fix `DaemonCrashReporter` dialog modality type

- flutter-idea/src/io/flutter/module/FlutterGeneratorPeer.java
Migrate from a flavor of `addBrowseFolderListener` that's slated for removal. …
> [CQ] API: migrate `FlutterGeneratorPeer` from slated-for-removal addBrowseFolderListener

- flutter-idea/src/io/flutter/run/test/TestForm.java
Another unsafe `addBrowseFolderListener` migration, as in https://github.com/flutter/flutter-intellij/pull/8070.
[breaking change …
> [CQ] API: migrate `TestForm` from removed `addBrowseFolderListener` API

- flutter-idea/src/io/flutter/FlutterMessages.java
- flutter-idea/src/io/flutter/ProjectOpenActivity.java
- flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java
Migrates from unsafe slated-for-removal `Notification` constructors. …
> [CQ] migrate off to-be-removed `Notification` APIs

- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
Migrate to safe `AnActionListener` APIs.
This migration has been attempted before but was reverted as possibly causing a hot reload regression (https://github.com/flutter/flutter-intellij/issues/6996).
I've confirmed that hot reload works (Mac OS Meerkat) but have preserved the note in case anything odd happens.
[Flutter Style Guide]: …
> [CQ] API: migrate from to-be-removed `AnActionListener` APIs

- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/run/SdkFields.java
- flutter-idea/src/io/flutter/run/bazel/BazelFields.java
- flutter-idea/testSrc/unit/io/flutter/utils/UrlUtilsTest.java
We can't make URLs secure, so the warnings are just noise. …
> [CQ] suppress insecure URL warnings for devtools URLs

- flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java
- flutter-idea/src/io/flutter/devtools/DevToolsUtils.java
- flutter-idea/src/io/flutter/editor/ActiveEditorsOutlineService.java
- flutter-idea/src/io/flutter/font/FontPreviewProcessor.java
- flutter-idea/src/io/flutter/jxbrowser/EmbeddedJxBrowser.java
- flutter-idea/src/io/flutter/run/FlutterConfigurationEditorForm.java
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- flutter-idea/src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.java
- flutter-idea/src/io/flutter/run/coverage/FlutterCoverageProgramRunner.java
- flutter-idea/src/io/flutter/run/test/TestForm.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
- flutter-idea/testSrc/unit/io/flutter/testing/JsonTesting.java
- flutter-idea/third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryType.java
Addressed/removed unnecessary code in the form of:
* redundant suppressions
* redundant throws
* redundant casts
* unused imports
* redundant `toString()`, `substring(..)` calls
* unnecessary `default` branches
* explicit types where `<>` will do
* stream API call chains where `toList()` is enough
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for- …
> [CQ] Unnecessary code cleanup

- flutter-idea/src/io/flutter/FlutterErrorReportSubmitter.java
Fix up the generic wildcard bounds so we can remove these unsafe casts (that are spamming the logs).
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing …
> [CQ] [unchecked cast]: fix generic bounds

- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
If no file is selected, the file chooser will return `null`. This guards against that.
Fixes: https://github.com/flutter/flutter-intellij/issues/8069
---
<details> …
> Fix SDK browsing NPE in `FlutterSettingsConfigurable`

- build.gradle.kts
- flutter-idea/build.gradle.kts
Adds handling for the "IU" (Idea Ultimate) product variant, currently skipped over and failing builds due to android plugin dependency logic being tied to "IC". This conflicts with the [contributing.md](https://github.com/flutter/flutter-intellij/blob/944aa028132052a6d14a99e073ebe4c7e5525ce3/CONTRIBUTING.md#L111):
> ...
> 1. Make sure you're using the latest stable release of IntelliJ,
>    or download and install the latest version of IntelliJ (2023.1 or later). 
>     - [IntelliJ Downloads](https://www.jetbrains.com/idea/download/)
>     - **Either the community edition (free) or Ultimate will work.** <-- no it won't
> 
> 2. Create a `gradle.properties` file.
> ...
> Refactor product handling logic in build script

- flutter-idea/src/io/flutter/run/LaunchState.java
- flutter-idea/src/io/flutter/run/test/FlutterTestRunner.java
Java 16 introduces [pattern matching](https://dev.java/learn/pattern-matching/) which allows us to cleanup some unnecessary casts.
---
<details> …
> [CQ] Language migration: use pattern variables

- CONTRIBUTING.md
Fixes up stale TOC and a step mis-numbering.
---
<details>
</details>
> [cleanup] Fix Contributing doc TOC and list numbers

- flutter-studio/src/io/flutter/editor/AndroidStudioColorPickerProvider.java
`java.awt` colors are not dark-theme friendly but `JBColor`s are. As a bonus we can use the `Gray` constant.
---
<details>
</details>
> [PE] make color picker “dark theme” aware

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/bazel/WorkspaceCache.java
- flutter-idea/src/io/flutter/logging/FlutterConsoleLogManager.java
- flutter-idea/src/io/flutter/survey/FlutterSurveyNotifications.java
- flutter-idea/testSrc/unit/io/flutter/project/ProjectWatchTest.java
Fixes: https://github.com/flutter/flutter-intellij/issues/8110
---
<details>
</details>
> [perf] use `try`-with-resources  for auto-closeables

- flutter-idea/src/io/flutter/editor/FlutterIconLineMarkerProvider.java
From the inspection description:
> Static initialization is performed once the class is loaded, which may cause excessive classloading or early initialization of heavy resources. Since extension point implementations are supposed to be cheap to create, they must not have static initializers.
---
<details>
- …
> [perf] stop static initialization in line marker extension

- .idea/inspectionProfiles/Project_Default.xml
- flutter-idea/src/io/flutter/logging/FlutterConsoleLogManager.java
Inspection description:
> Reports calls to Throwable.printStackTrace() without arguments.
Such statements are often used for temporary debugging and should be either removed from the production code or replaced with a more robust logging facility.
Note that this PR disables the inspection in TEST scopes since `printStackTrace()` is handy there and "robust" logging in a test context is often more of a hinderance than help.
---
<details>
- Dart …
> [PE] migrate `printStackTrace` to proper logging

- flutter-idea/src/io/flutter/run/FlutterDebugProcess.java
`ProcessCanceledException`s need to be rethrown so that the IDEA infrastructure can handle them properly.
---
<details>
</details>
> [fix] stop swallowing `ProcessCanceledException`

- flutter-idea/src/io/flutter/editor/OutlineLocation.java
- flutter-idea/src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
- flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
More opportunistic tidying.
🧹 Remove unused empty method bodies. (Also a rogue `;`.) 
🧹 Simplify a boolean expression.
---
<details>
</details>
> [CQ] remove (dead) empty methods

- flutter-idea/src/io/flutter/survey/FlutterSurveyService.java
A bit pedantic but generally good practice and easy to fix. (There's also no real reason to store the instance.)
Inspection motivation:
> Such services' assignments contribute to global state and make it impossible to tear down an application and set up another one in tests, therefore, repeated tests in the same process may fail. The only exception is an explicit constructor call to store dummy/default instances.
> The recommended way to avoid storing services is to retrieve a service locally. Alternatively, one can wrap it in java.util.function.Supplier (Java, Kotlin) or convert the property to a function (Kotlin).
---
<details>
- See our [contributor guide]([https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md](https://github.com/flut …
> [CQ] stop storing property service instance

- docs/Release-testing.md
The link didn't seem to make the wiki migration:
---
<details>
</details>
> [fix] stale `testing.md` link

- flutter-idea/src/io/flutter/view/FlutterView.java
This method is marked as unstable and slated for possible removal.
That said, this replacement doesn't totally preserve the current semantics.
@helin24: is there any reason we don't want to prompt a call to the application manager here?
Specifically, we'll now cause this to happen (if `ourInstance` is `null`):
```java
(ProgressManager)ApplicationManager.getApplication().getService(ProgressManager.class);
```
See: #https://github.com/flutter/flutter-intellij/issues/7718
---
<details>
- Larger or significant changes should be …
> [CQ] API: migrate off unstable `getInstanceOrNull`

- flutter-studio/src/io/flutter/utils/GradleUtils.java
The `com.intellij.openapi.vfs. CharsetToolkit` is marked unstable.
Luckily there's a standard Java substitute (as of Java 7).
---
<details> …
> [CQ] API: migrate from unstable `CharsetToolkit`

- flutter-idea/src/io/flutter/sdk/FlutterSdkManager.java
Move to the stable `afterLibraryRenamed` API variant.
---
<details>
</details>
> [CQ] API: migrate `FlutterSdkManager` off deprecated `afterLibraryRenamed`

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
✅ Fixes/ignores capitalization inspections.
✅ Removes redundant `serviceInterfaces`
(Not needed if the implementation class defines the interface: https://intellij-sdk-docs-cn.github.io/intellij/sdk/docs/basics/plugin_structure/plugin_services.html.)
✅ Disables i18N inspections (just noise unless we decide to externalize/internationalize)
---
<details>
- Dart contributions to our repos should follow the [Dart style …
> [CQ] plugin.xml cleanup: redundant declarations; i18n

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Further embracing the yak shave, tidies up some more plugin.xml inspections.
✅ Adds missing (required) group `id` attributes
✅ Defines a `contextId` for our contributed ``liveTemplateContext`
✅ Suppresses `PluginXmlValidity` for build variables
With this, we are left with 17 remaining problems.
---
<details>
- Dart contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart …
> [CQ] plugin.xml: specify missing group and context ids

- flutter-idea/src/io/flutter/actions/AttachDebuggerAction.java
- flutter-idea/src/io/flutter/run/daemon/DeviceDaemon.java
- flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
The preferred access to this constant is now `ModalityState.nonModal()`.
---
<details>
</details>
> [CQ] migrate off deprecated `ModalityState.NON_MODAL`

- flutter-idea/src/io/flutter/run/LaunchState.java
Move off deprecated `Messages` constant.
See: https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/openapi/ui/Messages.java
`Messages.getOkButton()` is the future.
---
<details>
- Java and Kotlin contributions should strive to follow Java and Kotlin best …
> [CQ] migrate off deprecated `Messages.OK_BUTTON`

- flutter-idea/src/io/flutter/editor/FlutterSaveActionsManager.java
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
`FileDocumentManagerListener.TOPIC` is preferred and the deprecated reference is just a redirect so this is sure to be behavior-preserving:
---
<details>
- Java and Kotlin contributions should strive to follow Java and Kotlin best practices ([discussion](https://github.com/flutter/flutter-intellij/issues/809 …
> [CQ] migrate off deprecated `AppTopics`

- flutter-idea/src/io/flutter/run/daemon/DaemonConsoleView.java
Move deprecated `GlobalSearchScopes` to preferred `ExecutionSearchScopes`. Source confirms this is behavior-preserving:
---
<details>
</details>
> [CQ] migrate off deprecated `GlobalSearchScopes` scope

- flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
These validation messages were not getting passed their required parameters.
And so weren't being properly created.
---
<details>
</details>
> Fix missing `FlutterBundle` property parameters

- flutter-idea/src/io/flutter/sdk/FlutterSettingsConfigurable.java
- flutter-idea/src/io/flutter/utils/FileWatch.java
Removes method declarations that are identical to an overridden super.
---
<details>
</details>
> [CQ] remove redundant method declarations

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/settings/FlutterSettings.java
> New notification to nudge users to try Gemini in Android Studio

- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/EmbeddedJcefBrowser.java
From the inspection description:
> Reports exceptions that are declared in a method's signature but never thrown by the method itself or its implementations and overriding methods.
---
<details> …
> [CQ] remove redundant throws

- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
Removes `Welcome.CreateNewProject` which is slated for removal.
Interestingly this code has been dead since https://github.com/flutter/flutter-intellij/commit/6350cf8d1da5fc8d4739a2519ca22dfdc037bfcb#diff-677d60b823c040a662bc3a70f9be4541281838b806d79c129da0e1227bada185.
---
<details>
- Dart contributions to our repos should follow the [Dart style …
> [CQ] remove slated-for-removal `Welcome.CreateNewProject` reference

- tool/plugin/lib/plugin.dart
- tool/plugin/lib/runner.dart
- tool/plugin/test/plugin_test.dart
I think this should fix the dev build, which stopped uploading back in February. It uses the command `./bin/plugin deploy --channel=dev` (see `tool/kokoro/deploy.sh`). The deletion happened in https://github.com/flutter/flutter-intellij/pull/7929.
I can't test it from an internal command until these changes are in the main branch though.
It could be we no longer need the dev build, but this seems like an easy enough change.
> Revert deletion of deploy command to fix dev build

- flutter-idea/src/io/flutter/dart/DartPlugin.java
- flutter-idea/src/io/flutter/dart/DartPluginVersion.java
- flutter-idea/src/io/flutter/dart/DartPsiUtil.java
- flutter-idea/src/io/flutter/dart/DartSyntax.java
- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/dart/FlutterRequestUtilities.java
- flutter-idea/src/io/flutter/propertyeditor/PropertyEditorViewFactory.java
> Some nullability and documentation cleanup in package io.flutter.dart

- flutter-idea/src/io/flutter/FlutterInitializer.java
The `moduleAdded` callback has been deprecated in favor of a more general `modulesAdded`:
with source/recommendation:
---
<details>
</details>
> [CQ] migrate off deprecated `moduleAdded` API

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/deeplinks/DeepLinksViewFactory.java
- flutter-idea/src/io/flutter/devtools/AbstractDevToolsViewFactory.java
- flutter-idea/src/io/flutter/devtools/DevToolsExtensionsViewFactory.java
- flutter-idea/src/io/flutter/devtools/DevToolsUrl.java
- flutter-idea/src/io/flutter/devtools/RemainingDevToolsViewFactory.java
- flutter-idea/src/io/flutter/propertyeditor/PropertyEditorViewFactory.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkVersion.java
- flutter-idea/src/io/flutter/view/ViewUtils.java
Fixes the issue of DevTools windows not appearing (https://github.com/flutter/flutter-intellij/issues/8029).
The class AbstractDevToolsViewFactory is introduced to validate the existence of the Flutter SDK for 4 of the DevTools windows, providing actionable messages for users to fix their Flutter dev setup.
Example of one of the 3 error cases:
> Fixes the issue of DevTools windows not appearing

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/logging/FlutterConsoleLogManager.java
- flutter-idea/src/io/flutter/toolwindow/InspectorViewToolWindowManagerListener.java
- flutter-idea/src/io/flutter/view/InspectorView.java
- flutter-idea/src/io/flutter/view/InspectorViewFactory.java
- flutter-idea/src/io/flutter/view/InspectorViewState.java
- flutter-idea/src/io/flutter/vmService/DisplayRefreshRateManager.java
- flutter-idea/src/io/flutter/vmService/VMServiceManager.java
- flutter-idea/testSrc/unit/io/flutter/view/InspectorViewTest.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
As discussed, when the inspector was the only view, it made sense to dub it `FlutterView` but now that's a little general (and suggests an abstract class of some kind).
---
<details> …
> [CQ] rename `Flutter` -> `InspectorView`

- flutter-idea/build.gradle.kts
Additional context for this version bump: https://www.mend.io/vulnerability-database/CVE-2023-2976?utm_source=JetBrains
> Update the com.google.guava version to `32.0.1`

- flutter-idea/src/io/flutter/bazel/WorkspaceCache.java
- flutter-idea/src/io/flutter/dart/FlutterDartAnalysisServer.java
- flutter-idea/src/io/flutter/run/FlutterReloadManager.java
- flutter-idea/src/io/flutter/run/common/CommonTestConfigUtils.java
- flutter-idea/src/io/flutter/run/daemon/DeviceService.java
- flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
- flutter-idea/src/io/flutter/sdk/FlutterPluginsLibraryManager.java
- flutter-idea/src/io/flutter/sdk/FlutterSdkManager.java
- flutter-studio/src/io/flutter/utils/AddToAppUtils.java
Using a `Project` as a parent disposable  can lead to plugins not being unloaded correctly leading to memory leaks. This follows the advice given in the Jetbrains [disposer docs](https://plugins.jetbrains.com/docs/intellij/disposers.html?from=IncorrectParentDisposable#choosing-a-disposable-parent) and is (I think) consistent with the Dart plugin (@alexander-doroshko?).
This gets us *most* of the way to fixing https://github.com/flutter/flutter-intellij/issues/8107 with an open question about `AndroidModuleLibraryManager`. (Question posed there 👍 .)
---
<details>
- See our [contributor guide]([https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md](https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview) …
> [PERF] migrate Project parentDisposables to Services

- flutter-idea/src/io/flutter/FlutterBundle.properties
Remove unused properties. (Interestingly the associated inspection doesn't catch references in `.form`s, so there are some ignores for those (and grepping to double check).
---
<details> …
> [CQ] cleanup unused .properties

- flutter-idea/src/io/flutter/actions/DeviceSelectorRefresherAction.java
- flutter-idea/src/io/flutter/actions/RestartFlutterDaemonAction.java
- flutter-idea/src/io/flutter/actions/RunFlutterAction.java
- flutter-idea/src/io/flutter/actions/RunProfileFlutterApp.java
- flutter-idea/src/io/flutter/actions/RunReleaseFlutterApp.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
Stops eagerly creating action presentations (allocating resources prematurely and possibly unnecessarily) in favor of the preferred registration in plugin metadata that will only get loaded as-needed.
From the inspection:
> Reports any actions that are registered in the plugin.xml file and instantiate the com.intellij.openapi.actionSystem.Presentation object in their constructors.
> Any of the constructors of AnAction with parameters instantiate the Presentation object. However, instantiating the  Presentation object in constructor results in allocating resources, which may not be necessary. Instead of creating an instance of Presentation that stores text, description, or icon, it is more efficient to utilize no-argument constructors of 
AnAction and other base classes and follow the …
> [perf] create action presentations lazily

- flutter-idea/src/io/flutter/module/settings/PlatformsForm.kt
Micro-change. Removes unused channel symbol.
---
<details>
</details>
> [CQ] (redundancy) remove unused `FlutterSdkChannel` property

- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/ViewUtils.java
`VerticalFlowAlignment` identifies some "magic" constants:
that are prefered:
(Note that both `CENTER` and `MIDDLE` are initialized to `1` so this is semantics preserving.)
---
<details> …
> [CQ] prefer “magic” flow layout constants

- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java
- flutter-idea/src/io/flutter/run/LaunchState.java
- flutter-idea/src/io/flutter/run/daemon/FlutterApp.java
- flutter-idea/src/io/flutter/sdk/FlutterSdk.java
Migrate off deprecated APIs:
* `getClientProperty`
* `ExecutionManager.getInstance(project).getContentManager()` (for run content descriptors)
* `EdtInvocationManager.getInstance()` (for `EDT` querying)
---
<details>
- Java and Kotlin …
> [CQ] migrate off deprecated descriptor, EDT, clientProperty accesses

- flutter-idea/src/io/flutter/FlutterInitializer.java
- flutter-idea/src/io/flutter/FlutterProjectActivity.kt
- flutter-idea/src/io/flutter/ProjectOpenActivity.java
`StartupActivity` is marked as obsolete with `ProjectActivity` identified as the path forward.
This introduces a `FlutterProjectActivity` that does some rudimentary error handling as well.
See https://github.com/flutter/flutter-intellij/issues/7718 and https://github.com/flutter/flutter-intellij/issues/8100
---
<details>
- Dart contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use …
> [CQ] migrate post-startup `Startup` to `Project` activities

- build.gradle.kts
- flutter-idea/build.gradle.kts
- flutter-studio/build.gradle.kts
Fixes broken `com.google.tools.ij.aiplugin` and `org.jetbrains.plugins.yaml` plugin references by adding missing gradle dependencies.
See inspection details here:
https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html?from=DevkitPluginXmlInspection
---
<details>
- Java and Kotlin contributions …
> [PE] fix missing ai, yaml plugin dependencies

- flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- flutter-studio/src/io/flutter/project/FlutterModuleGroup.java
Following up on a TODO from Steve to remove an unused method and callers.
Interestingly, `FlutterModuleGroup` seems entirely unused. It's meant to:
```
// Define a group of Flutter project types for use in Android Studio 4.2 and later.
```
Steve warns:
```
// TODO (messick) DO NOT delete this during post-4.2 clean-up.
```
but maybe we can? Especially if noone has plans to re-integrate.
@jwren : do you have any context on this?
---
<details>
- Dart …
> [CQ] remove `FlutterCreateAdditionalSettingsField` deadcode

- flutter-idea/src/io/flutter/run/MainFile.java
- flutter-idea/src/io/flutter/run/SdkRunConfig.java
Speeds up `SdkRunConfig.getState` which necessarily runs on the Event Dispatch Thread.
The fix has two parts:
1. Move the expensive call to `ModuleUtilCore.findModuleForFile(..)` into an async read action (because we can) and
2. Speed up `inProject` because we can't background it and there's a speedy alternative to the old more expensive approach
Addresses stack traces like this:
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:114)
at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:153)
at …
```
> [perf] optimize EDT `SdkRunConfig.getState`

- flutter-idea/src/io/flutter/editor/NativeEditorNotificationProvider.java
The (neat) `DataContext` functional interface is slated to be removed.
This migrates us to a `SimpleDataContext` builder which is the [new path forward](https://github.com/JetBrains/intellij-community/blob/7b62c265ab76de3c80882525fdc4047895f3f4b1/platform/core-ui/src/openapi/actionSystem/DataContext.java#L18).
---
<details>
- Dart contributions to our repos should follow the [Dart style …
> [CQ] migrate off slated-for-removal `DataContext` functional interface

- docs/Triaging.md
Updates 
* the inbox query
* stale gitter/stackoverflow redirect guidance
* out of date issue moving process
Part of https://github.com/flutter/flutter-intellij/issues/8101.
---
<details> …
> [process] upate the triage “inbox” query

- flutter-idea/src/io/flutter/devtools/AbstractDevToolsViewFactory.java
- flutter-idea/src/io/flutter/propertyeditor/PropertyEditorViewFactory.java
- flutter-idea/src/io/flutter/run/daemon/DevToolsServerTask.java
- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
- flutter-idea/src/io/flutter/view/ViewUtils.java
This threads a potential warning message from an individual tool window (specifically property editor) to an embedded browser tab. There's probably a better way to structure this code, but I've already spent an embarrassing amount of time on shuffling around the UI pieces. 🙃  Suggestions welcome though.
Fixes https://github.com/flutter/flutter-intellij/issues/8181
> Add warning about "docked unpinned" state

- flutter-idea/src/io/flutter/module/FlutterModuleBuilder.java
`FlutterModuleBuilder` settings validation happens off the `EDT`, which is great for performance but it means we need to take an extra step when wanting to display dialogs.
Fixes: https://github.com/flutter/flutter-intellij/issues/8243
---
<details>
- Java and Kotlin contributions should strive to follow …
> [fix] open the `FlutterModuleBuilder` error dialog on the EDT

- flutter-idea/src/io/flutter/propertyeditor/PropertyEditorViewFactory.java
The property editor was sometimes failing to load. I think this was the repro:
1. Open a project (property editor will load)
2. Close the project
3. Open the project again (property editor fails to load)
It seems the static var is set to null only on IJ first startup, not on project open. There may be a better way to fix this but I'm not sure what it is yet.
> Add a forceLoad option to property editor

- tool/triage/bin/triage.dart
- tool/triage/lib/github.dart
- tool/triage/pubspec.yaml
See #8101.
Adds CSV output to make importing into sheets easier:
```
☁  flutter-intellij [master] ⚡  dart tool/triage/bin/triage.dart
issues: 743 (+ 6 PRs)
unprioritized: 684 (92%)
created within ...
| 1 week | 2 weeks | 1 month | 3 months | 1 year | 3 years | longer |
| --- | --- | --- | --- | --- | --- | --- |
| 2 | 1 | 0 | 8 | 53 | 182 | 438 |
06/24/2025, 2, 1, 0, 8, 53, 182, 438, , 743, 684
```
---
<details>
- Dart contributions to our repos …
> [tool] triage report csv output

- flutter-idea/src/io/flutter/actions/AttachDebuggerAction.java
- flutter-idea/src/io/flutter/actions/DeviceSelectorAction.java
- flutter-idea/src/io/flutter/actions/ExtractWidgetAction.java
- flutter-idea/src/io/flutter/actions/FlutterBuildActionGroup.java
- flutter-idea/src/io/flutter/actions/FlutterExternalIdeActionGroup.java
- flutter-idea/src/io/flutter/actions/FlutterPackagesExplorerActionGroup.java
- flutter-idea/src/io/flutter/actions/FlutterRetargetAppAction.java
- flutter-idea/src/io/flutter/actions/FlutterSdkAction.java
- flutter-idea/src/io/flutter/actions/OpenEmulatorAction.java
- flutter-idea/src/io/flutter/actions/OpenInAndroidStudioAction.java
- flutter-idea/src/io/flutter/actions/OpenInAppCodeAction.java
- flutter-idea/src/io/flutter/actions/OpenInXcodeAction.java
- flutter-idea/src/io/flutter/actions/ReloadAllFlutterApps.java
- flutter-idea/src/io/flutter/actions/ReloadFlutterApp.java
- flutter-idea/src/io/flutter/actions/RestartAllFlutterApps.java
- flutter-idea/src/io/flutter/actions/RestartFlutterApp.java
- flutter-idea/src/io/flutter/actions/RestartFlutterDaemonAction.java
- flutter-idea/src/io/flutter/run/daemon/DeviceService.java
- flutter-idea/src/io/flutter/sdk/AndroidEmulatorManager.java
- flutter-idea/src/io/flutter/view/EmbeddedBrowser.java
Fix nullability problems for all the actions in `src/io/flutter/actions/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/actions/` as null-"clean".
---
<details>
- Java and Kotlin contributions …
> [CQ] fix nullability problems for `flutter/actions`

- flutter-idea/src/io/flutter/bazel/PluginConfig.java
- flutter-idea/src/io/flutter/bazel/Workspace.java
Fix nullability problems in `src/io/flutter/bazel/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/bazel/` as null-"clean".
---
<details>
- Java and Kotlin contributions should strive to follow …
> [CQ] fix nullability problems for `flutter/bazel`

- flutter-idea/src/io/flutter/propertyeditor/PropertyEditorViewFactory.java
Fix nullability problems in `src/io/flutter/propertyEditor/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/propertyEditor/` as null-"clean".
---
<details>
- Java and Kotlin contributions …
> [CQ] fix nullability problems for `flutter/propertyEditor`

- flutter-idea/src/io/flutter/settings/FlutterSettings.java
- flutter-idea/src/io/flutter/settings/FlutterUIConfig.java
Fix nullability problems in `src/io/flutter/settings/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/settings/` as null-"clean".
---
<details>
- Java and Kotlin contributions should strive to …
> [CQ] fix nullability problems for `flutter/settings`

- flutter-idea/src/io/flutter/pub/PubRoot.java
Fix nullability problems in `src/io/flutter/pub/`.
If we pursue https://github.com/flutter/flutter-intellij/issues/8292, we could mark `src/io/flutter/pub/` as null-"clean".
---
<details>
- Java and Kotlin contributions should strive to follow …
> [CQ] fix nullability problems for `flutter/pub`

- flutter-idea/src/io/flutter/jxbrowser/JxBrowserManager.java
I was planning to change over classes that are logging to using the plugin logger. In this case there were some file paths being logged and I removed those; however, now I'm thinking about whether it would make sense to allow logs with file paths to help users debug on their own (perhaps as a setting that's off by default?). Anyway, that's more a topic for a doc. In this case, I think our JX Browser download process is fairly stable and does not require file details.
> Change JX Browser file management to plugin logger

- flutter-idea/src/io/flutter/FlutterMessages.java
- flutter-idea/src/io/flutter/run/daemon/DeviceDaemon.java
Also: cleanup of nullability parameters in `FlutterMessages.java`
> Remove usage of deprecated Notification.setListener(..)

- CONTRIBUTING.md
> Correct typos

- flutter-idea/src/io/flutter/test/DartTestEventsConverterZ.java
This is the cause of the error mentioned in #8325.
Previously, the correct message was being sent hard-coded and was supposed to be replaced by `ServiceMessageBuilder.testsStarted()` once the method was available. Instead, `ServiceMessageBuilder.testStarted("")` was used which changes the message to `##teamcity[testStarted name='']` from `##teamcity[enteredtheMatrix]` (hence the error).
This one-liner just replaces the erroneous call to the correct one.
---
<details>
- Larger or significant changes should be discussed in an issue …
> Change the message sent to IntelliJ when starting the test suites to the correct one

- src/io/flutter/jxbrowser/JxBrowserManager.java
This was added in https://github.com/flutter/flutter-intellij/pull/5882 for tests and older versions of IJ that are not relevant now.
> Remove function to get plugin loader directory

- src/io/flutter/vmService/frame/DartVmServiceValue.java
`LayeredIcon(...)` has been deprecated in favor of a version that uses a supplier. 
https://github.com/JetBrains/intellij-community/blob/5c3b582e154b720700a8f133fcb9513543682824/platform/core-ui/src/ui/LayeredIcon.kt#L63
---
<details>
- Java and Kotlin contributions should strive to follow Java and Kotlin …
> [CQ] migrate from deprecated `LayeredIcon` constructor

- testSrc/unit/io/flutter/utils/RefreshableTest.java
The junit `assertThat` has been deprecated in favor of the one from `org.hamcrest.MatcherAssert`.
---
<details>
</details>
> [CQ] migrate off deprecated org.junit `assertThat`

- src/io/flutter/utils/GradleUtils.java
Remove stale reflective logic introduced in  https://github.com/flutter/flutter-intellij/commit/24812e6f8b336bd917e0f018cf75725efa610ccf
See: https://github.com/flutter/flutter-intellij/issues/8352
---
<details> …
> [CQ] remove reflective support for olde 4.1 API

- src/io/flutter/run/LaunchState.java
Ideally there'd be no reflection here but at least this gets rid of the conditional support for 2023.
See: https://github.com/flutter/flutter-intellij/issues/8352
---
<details> …
> [CQ] remove pre-2024 reflective support for `myDisplayName`

- src/io/flutter/sdk/FlutterSdkUtil.java
`PropertiesComponent.getValues` is deprecated in favor of `PropertiesComponent.getList`.
Verifier output:
```
#Deprecated method com.intellij.ide.util.PropertiesComponent.getValues(String) invocation
Deprecated method com.intellij.ide.util.PropertiesComponent.getValues(java.lang.String arg0) : java.lang.String[] is invoked in io.flutter.sdk.FlutterSdkUtil.updateKnownPaths(String, String) : void
Deprecated method com.intellij.ide.util.PropertiesComponent.getValues(java.lang.String arg0) : java.lang.String[] is invoked in io.flutter.sdk.FlutterSdkUtil.getKnownFlutterSdkPaths() : String[]
```
---
<details>
- See our [contributor guide]([https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md](https://github.com/flutter/flutter/blob/main/docs/ …
> [CQ] migrate off deprecated `PropertiesComponent.getValues` invocations

- src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.java
- src/io/flutter/run/test/TestForm.java
`ListCellRendererWrapper` is deprecated, with favor given to `SimpleListCellRenderer`:
https://github.com/JetBrains/intellij-community/blob/8e46815dd140357c19061ceba77416d40d81866d/platform/platform-api/src/com/intellij/ui/ListCellRendererWrapper.java#L18-L24
Verifier ouput:
```
#Deprecated class com.intellij.ui.ListCellRendererWrapper reference
Deprecated class com.intellij.ui.ListCellRendererWrapper is referenced in io.flutter.run.bazelTest.FlutterBazelTestConfigurationEditorForm$1.<init>(FlutterBazelTestConfigurationEditorForm)
Deprecated class com.intellij.ui.ListCellRendererWrapper is referenced in io.flutter.run.bazelTest.FlutterBazelTestConfigurationEditorForm$1
Deprecated class com.intellij.ui.ListCellRendererWrapper is referenced in io.flutter.run.test.TestForm$1.<init>(TestForm) …
```
> [CQ] migrate off deprecated `ListCellRendererWrapper`

- src/io/flutter/vmService/VmServiceWrapper.java
`Logger.error(object)` is deprecated and the `String` API is preferred.
https://github.com/JetBrains/intellij-community/blob/8e46815dd140357c19061ceba77416d40d81866d/platform/util/src/com/intellij/openapi/diagnostic/Logger.java#L378
(This logging isn't awesome and maybe we'll revisit but at least the API calls are clean.)
Verifier output:
```
#Deprecated method com.intellij.openapi.diagnostic.Logger.error(Object) invocation
Deprecated method com.intellij.openapi.diagnostic.Logger.error(java.lang.Object message) : void is invoked in io.flutter.vmService.VmServiceWrapper$10.onError(RPCError) : void
```
---
<details>
- See our [contributor guide]([https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md](https://github.com/flutter/flutter/blob …
> [CQ] migrate off deprecated `Logger.error` API

- build.gradle.kts
- src/io/flutter/toolwindow/ToolWindowBadgeUpdater.java
The class `com.intellij.ui.BadgeIcon` is marked `@experimental` and is flagged by the verifier:
```
Experimental API usages (4): 
#Experimental API class com.intellij.ui.BadgeIcon reference
Experimental API class com.intellij.ui.BadgeIcon is referenced in io.flutter.toolwindow.ToolWindowBadgeUpdater.lambda$updateBadgedIcon$1(ToolWindow) : void. This class can be changed in a future release leading to incompatibilities
Experimental API class com.intellij.ui.BadgeIcon is referenced in io.flutter.toolwindow.ToolWindowBadgeUpdater.lambda$updateBadgedIcon$0(ToolWindow) : void. This class can be changed in a future release leading to incompatibilities
#Experimental API constructor com.intellij.ui.BadgeIcon.<init>(Icon, Paint) invocation
Experimental API constructor …
```
> [CQ] remove experimental `BadgeIcon` dependency

- src/io/flutter/FlutterProjectActivity.kt
- src/io/flutter/actions/AttachDebuggerAction.java
- src/io/flutter/android/AndroidEmulator.java
- src/io/flutter/jxbrowser/JxBrowserManager.java
- src/io/flutter/run/bazelTest/BazelTestLaunchState.java
- src/io/flutter/test/DartTestEventsConverterZ.java
- src/io/flutter/utils/GradleUtils.java
- src/io/flutter/vmService/frame/DartVmServiceValue.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
Some opportunistic cleanup.
Removing:
* redundant semi-colons
* redundant suppressions
* an unused Import
Fixed static member via instance accesses
Fixed an unchecked call to `put(K, V)`
---
<details> …
> [CQ] cleanup dead/redundant code

- src/io/flutter/jxbrowser/EmbeddedJxBrowser.java
- src/io/flutter/view/EmbeddedBrowser.java
- src/io/flutter/view/EmbeddedJcefBrowser.java
Related to https://github.com/flutter/flutter-intellij/issues/8369
> Use plugin logger for embedded browser

- .idea/runConfigurations/flutter_intellij__runIde_.xml
- src/io/flutter/editor/FlutterColors.java
- src/io/flutter/editor/FlutterCupertinoColors.java
- src/io/flutter/editor/FlutterCupertinoIcons.java
- src/io/flutter/editor/FlutterIconLineMarkerProvider.java
- src/io/flutter/editor/FlutterMaterialIcons.java
Related to https://github.com/flutter/flutter-intellij/issues/8369
I also attempted to make the flutter.log file viewable in sandbox mode with a generic file path, but this doesn't work for now - I get an empty file. Oddly this file path will work for `idea.log`, but seems to skip some lines. As the note says, this topic needs further investigation to understand how to optimize this part of setup.
> Change editor directory files to use PluginLogger

- AUTHORS
- resources/META-INF/android-contribs.xml
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
> [!TIP]
> To try out the plugin on other IDEs, head over to https://github.com/AlexV525/flutter-intellij/releases and download the latest release!
Resolves https://github.com/flutter/flutter-intellij/issues/6809
Resolves https://github.com/flutter/flutter-intellij/issues/7205
Resolves https://github.com/flutter/flutter-intellij/issues/7947
Tested with PyCharm 2024.3.2
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.m …
> ⚙️ Flip `org.jetbrains.android` to optional

- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/analytics/UnifiedAnalytics.java
I'm just looking through the code and checking that paths aren't going to be logged. Bazel path for flutter doctor probably is used very little (if at all) and analytics isn't used at all (will probably be moved to dart plugin?).
Related to https://github.com/flutter/flutter-intellij/issues/8369
> [logging] Use PluginLogger for bazel doctor and analytics

- docs/building.md
Depends on (rebase after) https://github.com/flutter/flutter-intellij/pull/8384
Perhaps this release we can test out doing a gradle build with larger version span, and see if any issues come up? At this point, running `bin/plugin make` will still work as before, so we can also do that as a backup if needed.
> Revise notes for building for releases

- build.gradle.kts
This is annoying - the plugin view in IJ settings doesn't show markdown text properly, only HTML (otoh, the jetbrains web site shows markdown from the changelog properly). So we have to convert the markdown to HTML ourselves. Perhaps I can file this as a feature request for jetbrains, since I'm pretty sure having a CHANGELOG.md file is recommended for plugins.
> Convert markdown to html for changelog

- CHANGELOG.md
- build.gradle.kts
This follows how the IJ plugin template is doing things, see https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/build.gradle.kts (forgot to look there when I created https://github.com/flutter/flutter-intellij/pull/8393!)
> Convert to reading changelog with gradle plugin

- build.gradle.kts
- src/io/flutter/toolwindow/ToolWindowBadgeUpdater.java
Reverts https://github.com/flutter/flutter-intellij/pull/8365.
Fixes: https://github.com/flutter/flutter-intellij/issues/8422
---
<details> …
> [revert] removal of `BagdeIcon`

- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
I'm not sure if the `FlutterSdk` class actually gets asked to call `flutter run`, `flutter attach`, or `flutter test`, but seems reasonable to check in case.
> [logging] Convert FlutterSdk class to using PluginLogger

- src/io/flutter/run/daemon/FlutterApp.java
Addresses https://github.com/flutter/flutter-intellij/issues/8261
> Register VM service with DTD

- CHANGELOG.md
- src/io/flutter/utils/FlutterModuleUtils.java
This resolves https://github.com/flutter/flutter-intellij/issues/8447 and https://github.com/flutter/flutter-intellij/issues/8446
Additional work may be needed to limit the number of read actions by the plugin, see https://github.com/flutter/flutter-intellij/issues/8242
> Resolves a "Slow operations are prohibited on EDT" exceptions

- CONTRIBUTING.md
- README.md
- docs/Milestones.md
- docs/Release-testing.md
- docs/Triaging.md
- src/io/flutter/run/daemon/DevToolsServerTask.java
I think this is what we all need to do to set upstream to main:
```
git branch -m master main
git fetch upstream
git branch -u upstream/main main
git remote set-head upstream -a
```
(The default instructions on the repo assume we are cloning this repo but we are all probably working on our own forks)
> Update links to main

- src/io/flutter/android/AndroidModuleLibraryManager.java
This should fix one of the critical problems in plugin compatibility (instead of using something from Android Studio / Android plugin, just declare a new facet), but further examination of how the modules should work is still needed (this is still in info-gathering stage and in a doc).
> Remove use of AndroidFacet

- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/utils/UrlUtils.java
As of Java 20, `URL(uri)` is deprecated in favor of `URI(uri).toURL()`.
See: https://bugs.openjdk.org/browse/JDK-8296385?jql=parent%3DJDK-8294241
---
<details>
- Java and Kotlin contributions should strive to follow Java and Kotlin best practices ([discussion](https://github.com/flutter/flutter-intellij/issu …
> [CQ] migrate off deprecated `URL` constructor invocations

- src/io/flutter/view/ViewUtils.java
Prefer `JBColor` over `java.awt.Color` which doesn't play nice with dark themes.
https://www.jetbrains.com/help/inspectopedia/UseJBColor.html
---
<details>
- Java and Kotlin contributions should strive to follow Java and Kotlin best practices ([discussion](https://github.com/flutter/flutter-intellij/issues/8 …
> [CQ] prefer Darcula-aware JBColor

- src/io/flutter/actions/RestartFlutterDaemonAction.java
This inspection guards against eager presentation creation for actions that are referenced in `plugin.xml` but not used. This particular constructor is only used dynamically so there's nothing eager about it -- it will only be invoked on use.
---
<details>
- Java and Kotlin contributions should strive to …
> [CQ] RestartFlutterDaemonAction: ignore spurious perf warning

- src/io/flutter/actions/RestartFlutterDaemonAction.java
The same sentence is legitimately a title and a sentence but we still need annotations to ensure the inspection sees we're respecting the contract.
---
<details> …
> [CQ] RestartFlutterDaemonAction: fix action description contract

- src/io/flutter/run/coverage/FlutterCoverageProgramRunner.java
- src/io/flutter/run/coverage/FlutterCoverageRunner.java
Part of https://github.com/flutter/flutter-intellij/issues/8369
> [logging] Use plugin logger for test coverage files

- src/io/flutter/logging/PluginLogger.java
- src/io/flutter/run/daemon/DaemonApi.java
This will enable debug-level logs to be seen in our log file when verbose logging is enabled.
Addresses https://github.com/flutter/flutter-intellij/issues/8519
> Change log level in PluginLogger for verbose logging

- src/io/flutter/font/FontPreviewProcessor.java
Part of https://github.com/flutter/flutter-intellij/issues/8369
Now that debug logs are logged in verbose mode, we don't need conditional logger creation in this file.
> Convert font processor to use PluginLogger

- .idea/runConfigurations/flutter_intellij__runIde_.xml
- src/io/flutter/run/daemon/DaemonApi.java
I thought the flutter log wasn't working with the sandbox, but the problem was my own filtering.
> Remove unnecessary comment and import

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/logging/PluginLogger.java
Fixes https://github.com/flutter/flutter-intellij/issues/8562
I'm realizing from this problem that logging at plugin startup may be tricky. E.g. with this change, I'm not totally sure what the setting will be at project initialization - probably with a level of INFO, or whatever is default in the IntelliJ logger. That's probably fine - if we are trying to log information from project startup, it would be reasonable to make the logs INFO or higher, as DEBUG level logs could be excluded even with a user setting of verbose.
> Move log level setup to initializer

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/io/flutter/utils/AndroidLocationProvider.java
I removed code that seems to be related to making gradle files editable within a Flutter project window as the Android Studio code has changed. I will record some additional details in my internal notes.
There were also test compilation failures that suggested the annotations library wasn't required correctly. (see https://stackoverflow.com/questions/62066166/string-notnull-syntax-causes-notnull-not-applicable-to-type-use-in-in - thanks @pq). When I asked gemini about this, it suggested that we were compiling production source code twice for tests, because the test source sets included `src` as well. I guess it turns out that this isn't needed and the dependency on the production source code is implied; additionally, compiling the production source during test is bad because it can be …
> Update Android Studio version
