flutter/flutter-intellij

src/io/flutter/FlutterBundle.properties
src/io/flutter/module/FlutterGeneratorPeer.form
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkGlobalLibUtil.java

Adds a Flutter SDK Configuration page to the New Flutter Project Wizard w/ SDK validation (see #45 for screenshots).  Validation ensures that a project cannot be created without a Flutter SDK set (#80).
Fixes: https://github.com/flutter/flutter-intellij/issues/45
Fixes: https://github.com/flutter/flutter-intellij/issues/80

Add Flutter SDK configuration to project creation (#45).

---

src/io/flutter/sdk/FlutterSdk.java

There’s no reason the flutter repo couldn’t be cloned into a directoring _not_ called `flutter`.
Fixes https://github.com/flutter/flutter-intellij/issues/87.

Make flutter home testing less prescriptive (#87).

---

resources/META-INF/plugin.xml
src/io/flutter/console/FlutterConsoleFolding.java

- this folds the `flutter run` line in the console when running flutter apps
this:
becomes this:
and on hover:
@pq @stevemessick 
@stevemessick, we can adjust this as the daemon run changes change the console output -

fold 'flutter run' in the flutter console

---

.gitignore
.travis.yml
build.gradle
src/io/flutter/run/FlutterRunner.java
testSrc/io/flutter/FlutterCodeInsightFixtureTestCase.java
testSrc/io/flutter/sdk/FlutterSdkUtilTest.java
testSrc/io/flutter/util/DartTestUtils.java
third_party/intellij-plugins-dart/README.md

- update gradle build to compile against the Dart plugin
- inline DartTestUtils.java
- compile against the current stable version of IntelliJ CE + the stable version of the Dart plugin
- tests currently disabled on travis pending some debugging

update gradle build to compile against the Dart plugin

---

build.gradle

Fix an issue w/ the built plugin (`flutter-intellij-0.0.1.jar`) - it wasn't including its resources.

fix the built plugin jar

---

CONTRIBUTING.md

Part of this was copied from the Dart plugin readme.

Add test setup instructions

---

docs/alpha/updatePlugins.xml

- add meta-data for an update site
Trial run for an update site; definitely not something for users to consume!

add meta-data for an update site

---

third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceBreakpointHandlerZ.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

@devoncarew See if this fixes your latest class loader problem with the built plugin.

Rename copy of debug service and make it a subclass of the real one

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/sdk/FlutterSettingsConfigurable.form

- some tweaks to the flutter settings page (an additional label, and a margin for the version text area)
@pq

tweaks to the flutter settings page

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

Adjust the flutter preference page layout; add a spring to the bottom, and fix the version textbox height so it doesn't resize when the content changes.
@pq

adjust the flutter preference page layout

---

resources/META-INF/plugin.xml
src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/run/FlutterRunConfiguration.java

Adds a Flutter toolbar group and contributes a stubbed out device selector combobox to the navbar and toolbar.
To be wired up when the daemon-mode bits land.
Obviously some proper device icons would be great.  Flutter is just a stand-in.

Device Selector toolbar contribution UI (#137).

---

src/io/flutter/inspections/WrongDartSdkConfigurationNotificationProvider.java

Fix an issue where a notification would compare the flutter sdk path to the dart sdk path, instead of  flutter's dart sdk path to the dart sdk path (the warning would always show, even when using the dart sdk from the flutter sdk).

fix a flutter sdk toast message

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/actions/OpenComputedUrlAction.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/run/FlutterAppState.java
src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonService.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/ObservatoryConnector.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

@pq @devoncarew This adds Restart and Reload commands, as well as restoring the observatory connection. At least one, maybe both, need new icons. Reload does not seem to be working but restart does what's expected. It may be a problem in flutter. I notice that when I start the daemon in hot mode there are a lot more log messages printed than before, so I think hot mode is selected correctly.

Wire up restart commands

---

src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java

* updates Dart SDK location when the Flutter SDK is configured.
* disables Dart SDK update checking (since there’s no Flutter channel).
Fixes: https://github.com/flutter/flutter-intellij/issues/121.

Set Dart SDK location w/ Flutter configuration (#121).

---

src/io/flutter/run/daemon/ConnectedDevice.java

@pq @devoncarew Define equals() and hashCode() for FlutterDevice so the list stops growing. I had defined it as a set but didn't get around to defining these two until now.

Eliminate device list duplication

---

src/io/flutter/actions/DeviceSelectorAction.java

Remove device actions from all but the toolbars.
Fixes: https://github.com/flutter/flutter-intellij/issues/166

Remove device actions from menus (#166).

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java

- change the tooltips for reload and restart in order to help differentiate them for users
- have them both save all documents before running
- update `RestartFlutterApp` to pass in false for the isFullRestart flag
@stevemessick

changes to reload and restart

---

build.gradle
flutter-intellij.iml
src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/daemon/FlutterApp.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- rev to 162.2233 of the dart plugin
- fix debugging for the latest Dart plugin
@stevemessick, this upgrades us to compiling against the latest published version of the Dart plugin, and fixes debugging against that latest version. We'll need to update this later - as part of debugging apps running under hot reload, we need to guess the uri prefix for the app. The Dart plugin currently only does this when remote debugging, so we spoof that here.

Rev dart plugin

---

src/io/flutter/run/daemon/DaemonListener.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java

@pq @devoncarew This allows launching apps repeatedly without having to restart IntelliJ.
There's still something wrong because the app running on the device isn't always terminated when the Stop button is clicked. I'll continue to look into that.

Clean up internal structures when processes exit.

---

resources/META-INF/plugin.xml
src/io/flutter/actions/FlutterKeyAction.java
src/io/flutter/actions/ReloadFlutterAppKeyAction.java
src/io/flutter/actions/RestartFlutterAppKeyAction.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

* keybindings for reload and restart (provisional)
* (temporary) connection-finding logic
Non-conflicting key-bindings are hard so I just punted.  
They can easily be updated once we settle on better ones.  In the meantime, the actions can be invoked via the **Find Action** command (**⌘ + A**) and the keymappings updated locally for demo (**Preferences > Keymap**).
Console out from invocation:
Fixes: https://github.com/flutter/flutter-intellij/issues/185

Hot reload/restart keybindings (#185).

---

src/io/flutter/run/daemon/ConnectedDevice.java
src/io/flutter/run/daemon/FlutterAppManager.java

This will let us know things like if the ios simulator is already running.
https://github.com/flutter/flutter/pull/6114 will need to land before this.

add emulator info to devices

---

src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java

@pq @devoncarew Cleaning up some concurrency issues and wiring up app.stop correctly. Now, in most cases the debugger is updated whether the app stops due to the Stop button being clicked or the app exiting on the device.
Actually disconnecting the device while the debugger is running causes a whole host of other problems that are not addressed here.

Stop apps cleanly

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java

- expose `baseUri` (currently unused)
- redux of https://github.com/flutter/flutter-intellij/pull

add a baseuri field

---

resources/META-INF/idea-contribs.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/dart/DartPlugin.java
src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java

Adds an inspection to check for a minimum Dart Plugin version.
Also adds a new class `DartPlugin` to centralize our access to the Dart Plugin.
If this approach looks good, I'd like to move many if not all of our Dart Plugin API access to this class.  A step in the direction of better managing our dependency...
fixes #168

Check for minum required Dart Plugin version (#168).

---

src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonService.java

There are a number of changes here that radically improve the Stop button action. (Still need to work on the case where the app is terminated on the device.)
* Replace roll-yer-own busy-wait loop with standard IDE service
* Use Futures to control app start and stop execution
* Finish wiring up app.stop response handler
* Make synchronized blocks smaller
* Reformat everything

Make Stop button deterministic

---

src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java

A few improvements and bug fixes for Flutter app management.
* De-bounce the Debug button. This still needs work but now if it is clicked when an app is running it won't break the world. It just does nothing. #221 
* Stop trying to stop an app if it isn't running.
* After the process has terminated, re-launch the polling service if needed.

App management improvements

---

src/io/flutter/run/FlutterAppState.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

We just needed to pass the proper mode argument through to the daemon.
Apps launched via the Run button will not stop properly. I reported https://github.com/flutter/flutter/issues/6208

Make Run button work

---

src/io/flutter/FlutterBundle.properties
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

Force debugger view refresh after observatory connection is completed to update connection status message. Also pick up some async fixes that got dropped. Fixes #161 

Fix issues in debugger

---

src/io/flutter/sdk/FlutterSdk.java

Generates a default run configuration for new projects.
Also fixes a race condition with opening `main.dart` by forcing a filesystem refresh before doing the existence check.
Fixes: https://github.com/flutter/flutter-intellij/issues/44

Generate a run config during project creation (#44).

---

src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/daemon/ConnectedDevice.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/ProgressHandler.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/ObservatoryConnector.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

If an app is paused at a breakpoint when the Stop button is clicked then make sure it is allowed to continue before the process terminates. Otherwise, the app will stay in the paused state on the device even after Flutter exits.
Fixes #242 
It is still possible to leave the app wedged. Clicking the Stop button while the flutter daemon is syncing files to the device, for instance, will not stop the app. Not sure if we can detect that case, but for now, patience is suggested: let the app get started before stopping it.

Stop the flutter app even when paused

---

src/io/flutter/module/FlutterModuleBuilder.java

- group the dart and flutter wizards in the new project dialog
I'm of two minds about this; I like the Dart and Flutter wizards being grouped, but in a more web based intelliJ product, this would but the Flutter wizard in with the web focused wizards. @pq @stevemessick

group dart and flutter wizards

---

flutter-intellij.iml

- remove the dart nature for smaller build artifacts
- fix https://github.com/flutter/flutter-intellij/issues/254
We're back down to around 205k for the `flutter-intellij.jar` file; @pq.

remove the dart nature for smaller build artifacts

---

src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkManager.java

Makes the device daemon more “self-healing”.
With this, the “Clean Install” user story becomes:
1. Install Flutter plugin
2. Restart IDE
3. Create Flutter project (setting SDK in the process)
4. Profit
:)
No more extra restart and fatal exceptions.
Fixes: https://github.com/flutter/flutter-intellij/issues/178

Watch for SDK config changes and trigger daemon starts/stops (#178).

---

flutter-intellij.iml
gradle.properties
resources/META-INF/plugin.xml

- fix an issue w/ the `<vendor>` field in the plugin.xml meta-data (we had two entries for vendor)
- make the description more verbose
- uncomment the change-log entry; add some initial notes
- rev to `0.1.0`; @pq, @stevemessick, thoughts?
The entry now looks something like this (modulo the exact change log notes):

update plugin metadata

---

third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

@pq @devoncarew I have not seen any docs saying this is the right thing to do, but it works for the cases that were causing problems. We should not try to use DAS to map URIs that are produced by a running Flutter app. This also keeps the Sync button (aka Scroll from Source) working.
The Flutter URIs look similar to:
`.../Library/Developer/CoreSimulator/Devices/E27B10B8-0E7D-4522-AD48-71DF05F0C237/data/Containers/Data/Application/543CCD6E-3543-45D1-9A4E-C8E83E9D2A79/tmp/myappxlOknB/lib/main.dart`
but the significant part is the `lib/main.dart`, which is relative to the project root.

Use baseUri to prevent invalid uri errors

---

src/io/flutter/sdk/FlutterSdk.java

As per #293, we;re going to start using the `VERSION` file for baseline SDK compatibility checks; this updates the docs accordingly.

Update getVersion() docs.

---

resources/META-INF/idea-contribs.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java
src/io/flutter/settings/FlutterSettings.java

Adds an editor notification that pops up when Flutter is less than `0.0.2`, the earliest tagged reload-friendly SDK. (See: #293.)
Fixes #194 

Track and check minimum supported Flutter SDK (#194).

---

src/io/flutter/run/daemon/FlutterDaemonService.java

@pq @devoncarew This makes #301 obsolete.
Instead of using the minimal number of daemon process the approach is to spawn a separate daemon for each application. I've only tested this with two devices but it seems solid, except for the bug I filed about breakpoints.
I chose to leave the old code in place as a comment until we're sure it won't be needed.

Stop sharing daemons

---

src/io/flutter/actions/DeviceSelectorAction.java

As per https://github.com/flutter/flutter-intellij/pull/313#pullrequestreview-4550282, gets project from the action directly.
/cc @alexander-doroshko @stevemessick @devoncarew

Cleanup `DeviceSelectorAction` project access.

---

src/io/flutter/run/FlutterAppState.java

@pq @devoncarew @alexander-doroshko 
Due to refactoring, we were adding two identical buttons to the run console that would open the observatory.

Add a single Observatory button

---

.idea/inspectionProfiles/Project_Default.xml
resources/META-INF/idea-contribs.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java

Fixes: #341 
Taking inspiration from the Go plugin, this check tests for the presence of a `flutter.yaml` file and the absence of the Flutter module type and gives users the opportunity to enable Flutter support.
/cc @alexander-doroshko @devoncarew @stevemessick

Notification to detect Flutter projects w/o Flutter Module Types (#341).

---

src/io/flutter/actions/FlutterKeyAction.java
src/io/flutter/actions/HotReloadFlutterAppKeyAction.java
src/io/flutter/actions/RestartFlutterAppKeyAction.java
src/io/flutter/run/FlutterAppState.java

Use project associated with action when invoking via key events.
Alex pointed this out in a side-band conversation and this is just follow-up.
/cc @stevemessick @alexander-doroshko

`findConnector` cleanup.

---

resources/META-INF/plugin.xml

Technically we’re overreaching but this is necessary for the plugin to load in the latest 2016.3 EAP.
FYI @stevemessick I think this address your loading issue of earlier today.

Widen version constraints to play nice with EAP.

---

.idea/inspectionProfiles/Project_Default.xml
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

Now it look like this:
As a bonus the text is copyable now:
P.S. useful inspection is enabled back, now there are no more violators

Show Flutter SDK version details as a copyable multiline label

---

src/io/flutter/dart/DartPlugin.java

Ensures that we have a Dart plugin where `pub` works as expected.
See: https://github.com/flutter/flutter-intellij/issues/271
/cc @alexander-doroshko @devoncarew @stevemessick

Bump minimume Dart to `162.2485`.

---

resources/META-INF/plugin.xml

@pq @devoncarew @alexander-doroshko 
Following up from Alex's comments about version ranges.
I looked for a way to revert the fix to #380 but realized typing the number and doing a normal commit would be faster.

Reduce upper bound of version range

---

src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/run/daemon/ProgressHandler.java
src/io/flutter/sdk/FlutterSdkManager.java

Make the daemon lifecycle mirror its projects.
The daemon is running now if any Flutter project is open. It doesn't have to have focus, since it takes a few seconds to spin up the device list. The alternative is to start and stop the daemon based on the project that has focus.
Also reformatted everything in flutter.io.run and picked up a few little things.
Fixes #372

Start and stop the daemon based on project open and close

---

src/io/flutter/run/daemon/ProgressHandler.java

Avoid an NPE when showing progress tasks from flutter_tools. @pq @stevemessick

avoid an npe

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java

- add support for an `app.started` event (fix https://github.com/flutter/flutter-intellij/issues/413)
- rename classes that parse events to end in `Event`
- when we get an event that we don't understand, don't log an error
@danrubel

add an app.started event

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/FlutterConfigurationEditorForm.form
src/io/flutter/run/FlutterConfigurationEditorForm.java
src/io/flutter/run/FlutterRunConfigurationType.java

* removes unused “program arguments” field
* sets default proposed name to project name (rather than “Unnamed”)
* renames “Dart file” label to “Dart entry point”
Fixes: #258 
/cc @alexander-doroshko @devoncarew

Cleanup run config UI (#258).

---

src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java

Updates button enablement to track Flutter app running state.
Addresses some of #407.
Fixes: #332.

Update restart/reload button enablement (#407, #332).

---

src/io/flutter/inspections/SdkConfigurationNotificationProvider.java

This mitigates app state message version skew.
See: https://github.com/flutter/flutter-intellij/pull/426
/cc @devoncarew 
(N.B. this hinges on https://github.com/flutter/flutter/pull/6771 for landing.)

Up flutter tools lower bound to `0.0.3`.

---

.idea/inspectionProfiles/Project_Default.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/run/FlutterAppState.java
src/io/flutter/run/FlutterAppStateBase.java
src/io/flutter/run/FlutterRunConfiguration.java
src/io/flutter/run/FlutterRunConfigurationBase.java
src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/FlutterRunnerBase.java
src/io/flutter/run/FlutterRunnerParameters.java

- refactor the launch config code to split out from Dart base
A larger PR, but this sets the stage for future work, including creating a second Flutter launch config to support the Bazel/internal use case. This fully separates out the Flutter and Dart launch config code.
@pq

refactor the launch config code to split out from Dart base

---

src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/actions/FlutterKeyAction.java

* actions may be null if not debugging
* actions get created fresh for new debugging sessions (so need to be re-registerable)

Restart/reload action mapping fixes.

---

src/io/flutter/actions/FlutterAppAction.java

TL;DR; the action manager doesn't permit over-writing action mappings so we need to remove first.

Action registry fixes.

---

src/io/flutter/actions/HotReloadFlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java

- some work to restore breakpoints across a hot reload; this tests for the capability in the dart plugin and if it's found, it requests that an isolate be paused after a reload
- also, inline a `StopWatch` to remove a dep on apache.commons
@pq

restore breakpoints across a reload

---

.idea/inspectionProfiles/Project_Default.xml
resources/META-INF/idea-contribs.xml
resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/actions/FlutterDoctorAction.java
src/io/flutter/actions/FlutterUpgradeAction.java
src/io/flutter/console/FlutterConsole.java
src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/console/FlutterConsoleHelper.java
src/io/flutter/inspections/FlutterYamlNotificationProvider.java
src/io/flutter/sdk/FlutterSdk.java

- create a better-bar for flutter.yaml files (fix https://github.com/flutter/flutter-intellij/issues/169)
- include actions for flutter upgrade and flutter doctor
@pq, I have a few questions here:
- what's the best way to display an error to the user ("No Flutter SDK present")?
- how can we prevent the consoles from piling up (see associated TODO:)?
Thanks! Will do some cleanup of this PR once I know the above.

add a butter-bar for flutter.yaml files

---

src/io/flutter/run/FlutterRunnerBase.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/sdk/FlutterSdkManager.java
src/io/flutter/sdk/FlutterSdkUtil.java

- some debugging code refactorings to help code clarity and to set us up for more significant refactorings later (in particular, switching over to `flutter run --machine`
- move to separating out the daemon instance used for device polling and the daemon instance(s) used for running apps
Part of writing this PR was just to get me more familiar with the architecture of the flutter debugger code.
@pq

Debug refactor

---

.idea/inspectionProfiles/Project_Default.xml

Fixes #483 .
(This assumes we decide that yes we do want to go this way.  FWIW I'm not hugely invested in this style in particular but I lean towards thinking that biting the bullet and enforcing via an inspection presubmit may be easiest in the long run.)

Flip the bit on `final` inspections (#483).

---

resources/META-INF/plugin.xml
testing.md

- remap reload and restart keybindings; use `ctrl-\` and `shift-ctrl-\`
- fix https://github.com/flutter/flutter-intellij/issues/335 (IntelliJ mapped `ctrl-,` to `cmd-,` on the mac, which conflicts with the binding to open preferences)
@pq @mit-mit

remap reload and restart keybindings

---

src/io/flutter/run/daemon/FlutterAppManager.java

These data classes get their fields filled in by reflection so the “CanBeFinal” inspection is inappropriate.
Last bit of follow-up from #483 (I promise!)

Suppress “CanBeFinal” for reflected fields.

---

src/io/flutter/inspections/FlutterYamlNotificationProvider.java

Some minor tweaks to the flutter.yaml editor notification panel; @pq.

ui improvements to the FlutterYamlNotificationProvider

---

src/io/flutter/run/FlutterRunConfiguration.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java

- respond to an app stopped event (terminate the debug process). Previously we only knew about an app stopping if we'd requested it ourselves; this handles the case were the phone goes away or the app stops for some other reason
- only show the run button as active if we can run something (it behaves similarly to the debug button now)
- some refactoring to remove unused code and to simplify things a bit
@pq

respond to an app stopped event

---

gradle.properties
resources/META-INF/plugin.xml

* reload and restart keybinding mapping fixes
* new buttter bar with actions for flutter.yaml files
* ”run" behavior re-designed to support reload
* improved console output for reloading and restarting
* miscellaneous fixes and stability improvements
/cc @devoncarew 
/FYI @mit-mit

Bump to `0.1.6`.

---

.gitignore
src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/daemon/DaemonJsonInputFilterProvider.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonService.java

- update IntelliJ to use `flutter run --machine` (instead of flutter daemon `app.startApp`) when starting an app (fix https://github.com/flutter/flutter-intellij/issues/401). We still use the daemon protocol, but use it in the one-shot manner provided by flutter run --machine
@pq, @danrubel

Flutter run machine

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/inspections/FlutterYamlNotificationProvider.java
src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java

Adds a new action to `flutter.yaml` files that allows you to enable Flutter support.
Partially address: #466.

Tweak WrongModuleTypeNotificationProvider (#466).

---

src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java

Partially address: #466
With this fix Flutter projects that lack a `flutter.yaml` file will get detected by their flutter pubpspec dependencies.
/cc @devoncarew 
Note the hacky regexp.  Happy to refine.

Improve test for Flutteriness in module type check (#466).

---

resources/META-INF/plugin.xml
src/io/flutter/actions/FlutterToolsActionGroup.java

Contents to be filled in.  To start, groups existing upgrade and doctor commands.
See: #515.
Not crazy about the text labels.  Maybe abbreviate to `Upgrade` and `Doctor`?

Top-level Flutter Tool menu (#515).

---

src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonService.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

Varied fixes around launching flutter apps:
- update the text we're looking for to link to source files in the console
- add a new `wsUri` field to the app.debugPort event
- remove apps when the daemon controller exists. This fixes an issue with action enablement on subsequent runs
- stop looking for an observatory connection message if the process exists
@pq

misc fixes around launching flutter apps

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterConstants.java
src/io/flutter/actions/FlutterUpgradeAction.java
src/io/flutter/inspections/FlutterYamlNotificationProvider.java
src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java

- have the flutter upgrade action better locate pubspec files; previously, it would only work when invoked on `flutter.yaml` directly. Now it looks in the Module for the most likely pubspec to act on.
- some refactoring of our use of dart+flutter constants
@pq

have the flutter upgrade action better locate pubspec files

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterErrorReportSubmitter.java

- add an error handler for the flutter plugin - use the `< errorHandler />` extension. Any exceptions that our plugin throws will be (offered to be) reported to our github repo
- fix https://github.com/flutter/flutter-intellij/issues/517
@pq

add an error handler for the flutter plugin

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/FlutterDoctorAction.java
src/io/flutter/actions/FlutterPackagesGetAction.java
src/io/flutter/actions/FlutterPackagesUpgradeAction.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/sdk/FlutterSdk.java

* adds Tools menu actions for `flutter packages get` and `flutter packages upgrade`
* rejiggers actions a bit and adds a base class to do away with some duplication
Fixes: #515.

Flutter package actions (#515).

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/console/FlutterConsoleHelper.java
src/io/flutter/sdk/FlutterSdk.java

Fixes: #527.
* adds process termination console output
* fixes pubspec finding (when `CommonDataKeys.PSI_FILE` or `LangDataKeys.MODULE` cache-miss)

Add console output on Flutter command completion (#527).

---

src/io/flutter/actions/DeviceSelectorAction.java

* ensure presentation update occurs on the AWT dispatch thread
Reliably seeing this stack trace on `2016.2.5` without this fix.
```
[  15413]   WARN - tellij.ide.HackyRepaintManager - Access to realized (ever shown) UI components should be done only from the AWT event dispatch thread, revalidate(), invalidate() & repaint() is ok from any thread 
java.lang.Exception
at com.intellij.ide.IdeRepaintManager.checkThreadViolations(IdeRepaintManager.java:107)
at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:97)
at javax.swing.JComponent.repaint(JComponent.java:4793)
at java.awt.Component.repaint(Component.java:3356)
at java.awt.Component.repaintParentIfNeeded(Component.java:2332)
at java.awt.Component.reshape(Component.java:2320)
at …
```

Fix invalid thread access (#554).

---

src/io/flutter/actions/DeviceSelectorAction.java

- update the DeviceSelectorAction class - actions live for the life of the app
- fix https://github.com/flutter/flutter-intellij/issues/556
@pq

actions have a application lifetime

---

resources/META-INF/plugin.xml
src/io/flutter/module/FlutterModuleConfigurationEditorProvider.java

- add a module config editor page (fix #317)
Instead of being blank, the module page in the structure dialog now shows:
@pq, @alexander-doroshko

add a module config editor page

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/console/FlutterConsoleHelper.java
src/io/flutter/inspections/FlutterYamlNotificationProvider.java
src/io/flutter/run/FlutterAppState.java
src/io/flutter/run/README.md
src/io/flutter/run/bazel/FlutterBazelAppState.java
src/io/flutter/run/daemon/DaemonListener.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppManager.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonControllerHelper.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/run/daemon/FlutterDevice.java
src/io/flutter/run/daemon/ProgressHelper.java
src/io/flutter/utils/StopWatch.java
src/io/flutter/utils/TimeoutUtil.java

- code motion and refactoring to simplify the debugger codebase
- rename FlutterAppManager to FlutterDaemonControllerHelper
This is a largely semantic free refactoring of the debugger codebase to improve maintainability. There's now:
- one daemon service per IntelliJ window
- one controller active for device detection
- one controller per launch, with a lifetime of that launch
- the FlutterDaemonControllerHelper, which is wholly owned by and assists the daemon controller
@pq

Debugger code refactor

---

src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonControllerHelper.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

* adds missing form UI mnemonics.
* misc. cleanup
@devoncarew

Bazel run config mnemonics (and cleanup).

---

resources/META-INF/plugin.xml
src/io/flutter/actions/HotReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java

**TL;DR; we had no shortcuts displayed in reload/restart action tooltips... now we do!** 👍 
* removes now unneeded `FlutterAppKey` actions in favor of attaching shortcuts to the toolbar actions
* connects shortcuts to associated debugger view actions
Confirmed custom keybindings are tracked:
@devoncarew

Fix reload/restart action keybinding tooltips.

---

src/io/flutter/module/FlutterGeneratorPeer.form
src/io/flutter/sdk/FlutterSettingsConfigurable.form

* adds missing mnemomic to Analytics checkbox
* wraps settings error text in a scrollpane (as per recommended IDEA style)
@devoncarew

Form cleanup.

---

src/io/flutter/module/FlutterGeneratorPeer.form

Inspection be damned, wrapping this in a scrollpane produces an ugly UI artifact.
Reverting to remove.
@devoncarew 
FYI: @alexander-doroshko : advice on addressing the inspection appreciated.

Revert scrollpane wrapping.

---

.idea/inspectionProfiles/Project_Default.xml

TL;DR; they don’t know anything about the ant or IDEA plugin namespaces and generate loads of spurious warnings.

Disable XML namespace warnings.

---

src/io/flutter/run/FlutterRunner.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- lengthen a timeout (the user can cancel manually)
- allow a launch to use the cwd of a project when locating sources when debugging (for projects without pubspecs) 
@pq

handle devfs breakpoints for projects without pubspecs

---

docs/alpha/updatePlugins.xml

Remove the old update site - this isn't used since we started hosting in the main plugin repo.
@pq @eseidelGoogle

remove the old update site

---

src/io/flutter/module/FlutterGeneratorPeer.form
src/io/flutter/module/FlutterGeneratorPeer.java

Follow-up from: https://github.com/flutter/flutter-intellij/pull/598.
* scrollpane as per @alexander-doroshko's recommendation
* no border to keep presentation clean (and the same)

Error Text scrollpane fix.

---

src/io/flutter/FlutterBundle.properties

- adjust the text for invalid sdks (specify `https://flutter.io/setup` explicitly)
- fix https://github.com/flutter/flutter-intellij/issues/619
@pq

adjust the text for invalid sdks

---

src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- refactor `DartVmServiceDebugProcess` to support breakpoints in both paths from sources run from snapshots (long paths rooted on the host machine but running on the target machine), and devfs paths (the baseUri info received from the daemon protocol, a path prefix for the target device)
@pq

Snapshot bp paths

---

resources/META-INF/plugin.xml
src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java
src/io/flutter/sdk/FlutterSdkUtil.java

- detect flutter module types in small IDEs
Re: the `<depends>` change, I believe we get the list of supported platforms from the JetBrains plugins site now - we can toggle on support for specific platforms.
@pq

detect flutter module types in small IDEs

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterConstants.java
src/io/flutter/FlutterUtils.java
src/io/flutter/actions/FlutterPackagesGetAction.java
src/io/flutter/actions/FlutterPackagesUpgradeAction.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/actions/FlutterUpgradeAction.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/sdk/FlutterSdkUtil.java

* adds an open processor that delegates to the platform for basic project import but adds it’s own post-processing hooks
* detects missing `.packages` and runs `flutter packages get` (#630)
* updates SDK actions to allow for running w/o analytics (for programmatic access)
* analytics reporing enabled for flutter doctor calls
* `FlutterSdkUtil` cleanup and refactoring
Still TODO: add detection and handling of stale `.packages` (a toast suggesting update) --- I'll pick that up in a follow-up PR with a bit more cleanup too.
@devoncarew

Open processor first steps (#316)

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/sdk/FlutterSdkManager.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java

Since the Flutter SDK is derived the from Dart SDK, we actually handle
this by reporting: 'No Flutter SDK configured'. When the user fixes
the Flutter SDK, the Dart SDK will also be fixed.
Fixed combo box to display correctly when no Flutter SDK is configured.
Fire a Flutter SDK changed event when the user changes the Flutter SDK.
Removed dead code.
Not done: when the user changes the Dart SDK, we should fire a Flutter
SDK changed event.
(Sorry about the repost; I accidentally deleted the branch for the last pull request.)

Show error when Dart SDK is not set correctly (#636)

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/actions/FlutterRetargetAction.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/editor/FlutterEditorAnnotator.java
src/io/flutter/inspections/FlutterYamlNotificationProvider.java
src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/run/FlutterRunConfigurationType.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/FlutterModuleUtils.java
src/io/flutter/view/FlutterViewCondition.java

* adds flutter module type (if missing)
* reloads project
* runs `flutter packages get`
* code cleanup (new `FlutterModuleUtils` class)
Fixes: #316.

Add Flutter Module type on project open (#316).

---

src/io/flutter/project/FlutterProjectOpenProcessor.java

* perform packages `get` rather than `upgrade` on project import
Follow-up on: https://github.com/flutter/flutter-intellij/pull/648#discussion_r97264115.
@devoncarew @danrubel

Prefer packages `get` over `upgrade` in project open (#648).

---

resources/META-INF/plugin.xml
src/io/flutter/actions/FlutterRetargetAppAction.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/ReloadFlutterAppRetarget.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/actions/RestartFlutterAppRetarget.java
src/io/flutter/sdk/FlutterSdkUtil.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- for the hot reload and full restart key-bindings, send the reqests to the active (focused) debug process
- fix https://github.com/flutter/flutter-intellij/issues/644
- (some class renames so that similar actions are grouped together in the project view)
@pq

proxy key bindings to the front-most debug process

---

resources/META-INF/plugin.xml
resources/inspectionDescriptions/FlutterDependency.html
src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterConstants.java
src/io/flutter/FlutterUtils.java
src/io/flutter/inspections/FlutterDependencyInspection.java

* Flutter’s version of the check performed by the Dart Plugin  (soon suppressed) on `pubspec.yaml` edits
* Offers to run `flutter packages get` or `flutter packages update`
(Notice the pile-up of notifications --- https://github.com/JetBrains/intellij-plugins/pull/472 will suppress the Dart one.)
Still TODO:
* word-smithing (input welcome)
* consider auto-close of inspection banner on fix execution (not done by the Dart one either)
@devoncarew

Flutter dependency inspection.

---

resources/META-INF/idea-contribs.xml
src/io/flutter/editor/FlutterPubspecNotificationProvider.java

(Note that this is _in addition_ to the Dart Plugin provided pubspec notification until JetBrains/intellij-plugins#472 is pushed to stable suppressing that.)
@devoncarew

Restore Flutter pubspec editor banner.

---

src/io/flutter/actions/FlutterRetargetAppAction.java

- fix the reload action when the app was launched from 'run'
- fix https://github.com/flutter/flutter-intellij/issues/701
@pq

fix the reload action when the app was launched from 'run'

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/actions/FlutterGettingStarted.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/actions/FlutterSubmitFeedback.java
src/io/flutter/actions/OpenObservatoryAction.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/view/FlutterView.java

- add analytics events for run, debug, and process stop
- fix https://github.com/flutter/flutter-intellij/issues/697
These will look like `RunApp`, `DebugApp`, `StopApp` and `RunBazelApp`, `DebugBazelApp`, `StopBazelApp`.
@pq, @mit-mit

add analytics events for run, debug, and process stop

---

src/io/flutter/inspections/FlutterDependencyInspection.java

Bypasses the Virtual FS (which lags) in favor of a trip to `java.io`.
Fixes: #715, #667

Fix pubspec timestamp checking (#715, #667).

---

resources/META-INF/plugin.xml
src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/bazel/WorkspaceCache.java
src/io/flutter/bazel/WorkspaceWatch.java
src/io/flutter/project/ProjectWatch.java
src/io/flutter/utils/FileWatch.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/bazel/WorkspaceTest.java
testSrc/unit/io/flutter/project/ProjectWatchTest.java
testSrc/unit/io/flutter/testing/AdaptedFixture.java
testSrc/unit/io/flutter/testing/ProjectFixture.java
testSrc/unit/io/flutter/testing/TestDir.java
testSrc/unit/io/flutter/testing/Testing.java
testSrc/unit/io/flutter/utils/FileWatchTest.java

Finds the workspace based on the content roots. The ancestor directories of
each content root are searched for a WORKSPACE file. There should be a unique
workspace for each project.
Also, automatically detect changes to the configuration. This can be due
to a changed WORKSPACE file, config file, or a changed module configuration.
Also, implemented some test infrastructure to test it all, based on JUnit 4.
Not hooked up to anything yet.

Add support for loading a plugin config file from a Bazel Workspace

---

src/io/flutter/editor/FlutterPubspecNotificationProvider.java

- add tooltips to the pubspec editor inspector
- fix https://github.com/flutter/flutter-intellij/issues/733
@pq, @skybrian

add tooltips to the pubspec editor inspector

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/bazel/WorkspaceCache.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonControllerHelper.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/sdk/FlutterSdkManager.java
src/io/flutter/utils/FileWatch.java
src/io/flutter/utils/Refreshable.java
testSrc/unit/io/flutter/bazel/PluginConfigTest.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/bazel/WorkspaceTest.java
testSrc/unit/io/flutter/utils/RefreshableTest.java

- Start showing the device menu for Bazel users. In this case they don't have
to configure a Flutter SDK. Instead, the device menu will be shown based on the
project's content roots.
By default, a content root containing 'flutter' will trigger the device menu.
This can be overridden by the 'directoryPatterns' setting in flutter.json.
- Show or hide device menu when the user changes the Dart or Flutter SDK,
or the Bazel workspace changes.
- Start/stop/restart the 'flutter daemon' process when the configuration changes.
- Fixed a bug where Flutter SDK changes would not be detected when the user changes
the Dart SDK.
- Made API clearer for attaching FileRoot or Refreshable to a Disposable.
- Refreshable class improvements:
- add a callback when a value is unpublished
- make sure the variable …

Various device menu fixes

---

src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/utils/Refreshable.java
testSrc/unit/io/flutter/utils/RefreshableTest.java

- Register device daemon as a disposable
- Make sure that a Reflectable calls its unpublish callback when closing, which kills the process.

Bugfix: shut down device daemon process when project is closed

---

src/io/flutter/view/FlutterViewFactory.java
src/io/flutter/view/FlutterViewMessages.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- some cleanup to our use of the message bus
This converts to sending launch events on the project bus, not the application one. I think this is more correct, in that you don't want to have flutter views listening to launches in other windows.
@skybrian

some cleanup to our use of the message bus

---

src/io/flutter/console/FlutterConsoleFolding.java

- some additional console folding for ios
This last bit of folding means that you don't need to scroll the console to see all the initial output from an iOS simulator run.
@pq @skybrian

some additional console folding for ios

---

src/io/flutter/FlutterErrorReportSubmitter.java

- include the product name in exception reports (related to https://github.com/flutter/flutter-intellij/issues/772)
@pq @skybrian

include the product name in exception reports

---

src/io/flutter/bazel/Workspace.java
src/io/flutter/run/daemon/DeviceDaemon.java

For Bazel, only show the device list when we are in a Flutter project (according to the Workspace).
If the Bazel repo has a script to start the device daemon, prefer that, but fall back to the Flutter SDK if configured.
Fixes a bug where the device menu would not show up because the user configured a Flutter SDK (for open source work) but forgot they did that. The device list should still appear.
Also, log when the device daemon starts and stops (at INFO level).

device list visibility fixes for Bazel

---

src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/utils/Refreshable.java
testSrc/unit/io/flutter/utils/RefreshableTest.java

- change API to optionally pass a Request to the callback.
This provides access to the previous version and isCancelled() method.
- expose getState() with the current status: busy/idle/closed
- Fire events for state changes, not just value changes.
Avoid starting and immediately killing the daemon process due to another event arriving.

updates to Refreshable

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterInitializer.java
src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/run/FlutterAppState.java
src/io/flutter/run/FlutterRunner.java
src/io/flutter/run/bazel/FlutterBazelAppState.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/DeviceSelection.java
src/io/flutter/run/daemon/DeviceService.java
src/io/flutter/run/daemon/FlutterDaemonController.java
src/io/flutter/run/daemon/FlutterDaemonControllerHelper.java
src/io/flutter/run/daemon/FlutterDaemonService.java
src/io/flutter/sdk/FlutterSdkManager.java

Keeps track of the device list in the DeviceDaemon class. This
avoids a possible bug due to lost events when the process
restarts.
Simpified event handling when updating the device list UI. The
same code gets executed regardless of what changed.

Move device list tracking to a separate service

---

src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/bazel/BazelFields.java
src/io/flutter/run/bazel/BazelRunConfig.java
src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java

* Uses the workspace root as the work dir by default.
* Gets the launch script from flutter.json
* Sets the fields only if the corresponding template field is blank.
Partial fix for #643 
(Doesn't try to calculate the target, which seems harder.)

Populate work dir and launch script in new Bazel run configs

---

src/io/flutter/run/daemon/FlutterApp.java

We should not set any breakpoints until receiving the app.started
event from the flutter command, because until then, the flutter
command is still using Observatory.
To be safe, don't tell the debugger the Observatory URL until then.
Possibly related to #784 (found while attempting to reproduce it)
but the symptoms are different.

Fix race condition when there is a breakpoint in main

---

src/io/flutter/FlutterErrorReportSubmitter.java

Add a bit more info to our error reports:
```
IntelliJ IDEA `2016.3.5` • Flutter plugin `0.1.11.1` • Dart plugin `163.13137`
```
(previous format seen here: https://github.com/flutter/flutter-intellij/issues/802)
@pq @skybrian

add dart plugin version info to our error report

---

.idea/runConfigurations/Flutter_Plugin.xml
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/Launcher.java
src/io/flutter/run/daemon/FlutterApp.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

FlutterApp:
- fix a hang when stopping the Flutter process. (It could hang for 10 seconds waiting for
the process to terminate when it has already terminated.)
Launcher:
- extract code to get analysis server execution id. Log a warning if it's not available.
- don't try to get an execution id when not debugging.
DartVmServiceDebugProcessZ:
- suppress assert error logged in DartVmServiceDebugProcess constructor if analysis server
execution id isn't available. (Always pass in an execution id to fake it out.)
- remove overrides that are called in the superclass's constructor when subclass variables
aren't initialized yet.
- add comments

Fix miscellaneous minor bugs related to debugging

---

resources/META-INF/plugin.xml
resources/liveTemplates/flutter_miscellaneous.xml
src/io/flutter/template/DartToplevelTemplateContextType.java
src/io/flutter/template/FlutterLiveTemplatesProvider.java

@pq @devoncarew Define three live templates to generate boilerplate code for certain types of widgets as defined in #814.
I'm open to suggestions for different template names. I chose: stless, stful, stanim. Respectively, they generate new subclasses of StatelessWidget, StatefulWidget, and StatefulWidget with an animation controller.
To generate a new StatefulWidget, for example, you would type `stful` then `tab`, then type the name of the class once. That name will be inserted everywhere it needs to be, according to the boilerplate @HansMuller gave.
#814 should remain open because we still need to provide a mechanism to add (and remove?) various attributes of Flutter classes (like animation controllers).

Add some Flutter templates to create widgets

---

resources/META-INF/idea-contribs.xml
resources/META-INF/plugin.xml
src/io/flutter/utils/FlutterModuleUtils.java

Fix an issue where the flutter pubspec.yaml editor notification would not show in small IDEs (note that this is not a recent regression).
@pq 
Phil, do you know why we only define `editorNotificationProvider`s in `idea-contribs.xml` and not the main `plugin.xml`?

show the flutter editor notification in small ides

---

src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java

- enable Dart support when setting the sdk location
This will prevent the issue where users can see and set the sdk in the Flutter settings page, but the value doesn't persist (when they re-open the settings page, the sdk location isn't persisted and the project didn't have Dart enabled).
@skybrian (/cc @pq)

enable Dart support when setting the sdk location

---

src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
testSrc/unit/io/flutter/bazel/WorkspaceCacheTest.java
testSrc/unit/io/flutter/bazel/WorkspaceTest.java

This handles the case where dart/config/intellij-plugins is not checked out, or the directory containing the daemon script isn't checked out.
Fixes #791

Bazel: load plugin config and daemon script from READONLY directory

---

src/io/flutter/editor/FlutterEditorAnnotator.java

A small PR to add borders to the color swatch icons:
@skybrian

add a border to the color icons

---

src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/dart/DartPlugin.java
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/view/FlutterViewFactory.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceBreakpointHandlerZ.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- some 2016.3 cleanup (remove some uses of reflection)
- update debugger code now that we're fully on 2017.1
- remove obsolete todos
@skybrian

some 2016.3 cleanup and remove obsolete todos

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterInitializer.java
src/io/flutter/run/FlutterRunNotifications.java

The first time we run a Flutter app for a project, show a notification as a prompt to use hot reload:
@pq @skybrian @mit-mit

show a hot reload info toast on first run

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/FlutterRunNotifications.java

Some changes to the hot reload first-run toast:
- use the hot reload icon (to help the user identify where in the ui to access reload)
- use an action instead of a hyperlink
- make the text terse to ensure it doesn't wrap and end up below the fold
@pq @skybrian

change the icon for the hot reload toast

---

src/io/flutter/run/daemon/FlutterAppListener.java

- remove the IntelliJ reload success message
As of https://github.com/flutter/flutter/pull/9328, we can now just use the reload success message from flutter_tools.
@pq @skybrian

remove the IntelliJ reload success message

---

resources/META-INF/plugin.xml
src/io/flutter/run/FlutterDebugProcess.java

- fix the restart action enablement
- fix https://github.com/flutter/flutter-intellij/issues/901
In order for the action to be enabled, we need to have an instance of `RestartFlutterApp` created w/ the right FlutterApp. Also, re-add the keybindings for full restart; we still have a bit of work left to do wrt rationalizing the keybindings.
@pq

fix the restart action enablement

---

resources/META-INF/plugin.xml
src/io/flutter/project/FlutterIconProvider.java

See: #824 
* emphasizes `lib` dir
* tags `.idea` as generated
Before:
After:
Still spitballing, so refinements most welcome!

Project node presentaion tweaks (#824)

---

src/io/flutter/actions/FlutterPackagesGetAction.java
src/io/flutter/actions/FlutterPackagesUpgradeAction.java
src/io/flutter/actions/FlutterUpgradeAction.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java

If "flutter create" writes an android.iml file, make sure it's added to the project.
Also, make sure all files generated by the "flutter create" command are visible in IDEA. (There was a race condition where we didn't wait for "flutter create" to finish before continuing.)
Progress towards fixing #782
The android.iml file will be added in https://github.com/flutter/flutter/pull/9335

Enable android module if present when creating Flutter project

---

resources/META-INF/idea-contribs.xml
resources/META-INF/plugin.xml

- move two editor notification providers (so that they're available in both IDEA and in small IDEs)
(follow up from https://github.com/flutter/flutter-intellij/pull/846)
@pq @skybrian

move two editor notification providers

---

src/io/flutter/run/FlutterRunNotifications.java

- dismiss the hot reload notification when the user clicks on the 'show more info' link
@pq @skybrian

dismiss the hot reload notification

---

resources/META-INF/plugin.xml

- move the reload action into the main run group
@pq, @skybrian 
(given we have screenshots for the current release, we can wait to land this until after M13)

move the reload action into the main run group

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterInitializer.java
src/io/flutter/ProjectOpenActivity.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/FlutterModuleUtils.java

Also:
- add cross-references between different code that runs at project open
- FlutterSdk.getDartSdkPath() now returns null if the SDK doesn't exist
- clean up callers

sync Flutter SDK on open if Dart SDK doesn't exist

---

src/io/flutter/FlutterConstants.java
src/io/flutter/FlutterUtils.java
src/io/flutter/actions/FlutterPackagesExplorerActionGroup.java
src/io/flutter/actions/FlutterPackagesGetAction.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/editor/FlutterPubspecNotificationProvider.java
src/io/flutter/inspections/FlutterDependencyInspection.java
src/io/flutter/project/FlutterIconProvider.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/pub/PubRoots.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/FlutterModuleUtils.java

Most of this functionality was in FlutterModuleUtils before.
There shouldn't be any user-visible changes; this is for readability.

Centralize pub directory-related code in PubRoot class

---

src/io/flutter/pub/PubRoot.java

@pq, @skybrian, fix an NPE in the icon provider:
```
Argument for @NotNull parameter 'dir' of io/flutter/pub/PubRoot.forDirectory must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'dir' of io/flutter/pub/PubRoot.forDirectory must not be null
at io.flutter.pub.PubRoot.$$$reportNull$$$0(PubRoot.java)
at io.flutter.pub.PubRoot.forDirectory(PubRoot.java)
at io.flutter.project.FlutterIconProvider.getIcon(FlutterIconProvider.java:29)
at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
at …
```

fix an NPE in the icon provider

---

src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterView.java
testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java

- return the result of calling service protocol extensions
- use this in the `TogglePlatformAction` action, in order to know which platform the device is currently rendering, so we can toggle appropriately
The `app.callServiceExtension` method is now documented here: https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode#callserviceextension)
@pq @skybrian

return the result of calling service protocol extensions

---

src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/sdk/FlutterSdkUtil.java
testSrc/unit/io/flutter/testing/Testing.java

- store the last used flutter sdk path first; this ensures that the last one selected by the user is the 'default' flutter sdk path to use when opening a project w/o a previously set flutter sdk
- fix https://github.com/flutter/flutter-intellij/issues/951
@pq, @skybrian

store the last used flutter sdk path first

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/ProjectOpenActivity.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/run/FlutterRunConfigurationType.java
src/io/flutter/utils/FlutterModuleUtils.java

- If .packages file is missing, we don't need to run two flutter commands.
- On project open, check if we should create a run configuration
- On project open, check if we should open lib/main.dart
(Depends on #965; look at the second commit.)

Handle project open more consistently

---

src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/sdk/FlutterSdkVersion.java

Redo fix from #1002, broken due to a bad merge.
While we're here, move this code to FlutterSdkVersion and simplify.

fix Flutter version handling again

---

src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
src/io/flutter/sdk/FlutterSdkUtil.java

- It wasn't enabling Dart for the module.
- Default to the most recently used Flutter SDK.
- Sort Flutter SDK's in most-recently-used order.
(Previously was random order.)
Also simplify the code a bit.

fix new project creation for WebStorm

---

src/io/flutter/android/AndroidSdk.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/run/SdkFields.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/DeviceService.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java

This allows the user to override the setting of ANDROID_HOME from IntelliJ's
environment, and ensures that it's consistent with the one used to resolve
imports in Java code.
If the project's Java SDK isn't set to an Android SDK, we still fall back
to using ANDROID_HOME.
Fixes #981

Use project's Java SDK to set ANDROID_HOME for flutter commands

---

src/io/flutter/project/FlutterProjectOpenProcessor.java

* extra check to ensure we don’t try and access modules in disposed projects
Fixes: #1013.
I was unable to repro the disposed project case captured in the stacktrace but this guard should ensure we don't fall over when trying to read modules.

Getting defensive: project disposal checking on open (#1013).

---

src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/DaemonEvent.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/DeviceService.java
src/io/flutter/run/daemon/FlutterAppListener.java

- For occasional flakes, automatically restart
- For other unexpected failures, report as an IDE error so that
it can be sent as a bug.
Fixes #1008

Handle failed daemon processes better

---

resources/META-INF/plugin.xml

Since SDKs are set on a per-project level this doesn’t make sense.
Fixes: #1018.
@devoncarew @alexander-doroshko

Remove SDK settings from the template project (#1018).

---

.travis.yml
build.xml
resources/META-INF/plugin.xml

- update to the latest version of IntelliJ and the Dart plugin that we support
- increase our IntelliJ version range to support 2017.2 (https://github.com/flutter/flutter-intellij/issues/1040)
@pq @skybrian

rev the versions we build against

---

src/io/flutter/run/daemon/DaemonEvent.java
src/io/flutter/run/daemon/FlutterAppListener.java
testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java

If we receive an error from the app.stop event, display that to the console as stderr output.
@pq @skybrian, /cc @tvolkert

show any error from app run termination

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterInitializer.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/DaemonConsoleView.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

add some diagnostic logging:
- log process start and stop to the IntelliJ log file
- add a user toggleable option to enable more verbose debug logging
- when that's set, start flutter run apps up with `--verbose`; this can help identify a lot of issues with the various toolchains (android, gradle, ios, ...) (the same as `flutter run -v` on the cli)
@skybrian @pq

add some diagnostic logging

---

resources/META-INF/plugin.xml
src/io/flutter/dart/DartPlugin.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/run/FlutterRunConfigurationProducer.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/test/TestConfig.java
src/io/flutter/run/test/TestConfigProducer.java
src/io/flutter/run/test/TestConfigType.java
src/io/flutter/run/test/TestFields.java
src/io/flutter/run/test/TestForm.form
src/io/flutter/run/test/TestForm.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java

For now this just executes 'flutter test' and sends the output
to the console. Still to do: show test output in IDEA's UI
and support debugging. (That will require modifying the
"flutter test" command to support --machine mode.)
Previously, running a test from within IDEA would fail because
the Dart plugin does it and it doesn't use "flutter test",
which is needed for all tests using a flutter pubspec.

Add new run configuration type for 'flutter test'

---

src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/FlutterModuleType.java

Note why we don't use the override annotation, so we don't accidentally re-add it.
@alexander-doroshko

SuppressWarnings for getBigIcon override

---

src/io/flutter/run/FlutterRunConfigurationProducer.java
src/io/flutter/run/test/TestConfigProducer.java

Instead, require it to be in the test directory of a pubroot.
(This is closer to what the Dart plugin does.)

Don't require a test's filename to end with _test.dart

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppListener.java
src/io/flutter/view/AbstractToggleableAction.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewAction.java
src/io/flutter/view/FlutterViewFactory.java

improved feedback on reload:
- clear the console when a reload starts (fix #939)
- disable the reload button while a reload is occurring
- print progress messages to the console view (in addition to using IntelliJ's normal progress mechanism) (part of #1068)
- (and, some small tweaks to the FlutterView)
@skybrian @pq

improved feedback on reload

---

src/io/flutter/view/AbstractToggleableAction.java
src/io/flutter/view/FlutterViewAction.java
src/io/flutter/view/FlutterViewFactory.java

Revert parts of https://github.com/flutter/flutter-intellij/pull/1077 - re-add `DumbAwareAction`.
From the docs: `A marker interface for the things that are allowed to run in dumb mode` - so it sounds since these actions do not need to access bits of the index, we want to keep them dumb aware.

re-add DumbAwareAction

---

src/io/flutter/view/OpenFlutterViewAction.java

- tweak the 'open flutter view' icon to not include the small arrow badge (from seeing it for a while, it seems more distracting than helpful)
@pq, @skybrian

change the 'open flutter view' icon

---

src/io/flutter/editor/FlutterPubspecNotificationProvider.java
src/io/flutter/pub/PubRoot.java

- support nested packages for `flutter packages get / upgrade`
- fix https://github.com/flutter/flutter-intellij/issues/1092
This specifically addresses the use case of the pubspec.yaml file editor banner, and a context click on a pubspec.yaml file in the project navigator.
@pq

support nested packages

---

src/io/flutter/actions/InstallSdkAction.java
src/io/flutter/module/FlutterGeneratorPeer.form
src/io/flutter/module/FlutterGeneratorPeer.java

Still very much a work in progress and disabled by default but gives us an initial steel thread that:
0. prompts for install location
1. clones repo
2. runs flutter doctor (to complete installation) and reports progress
3. sets SDK location
Lots of hardening, UI refinement and error-handling to follow.  Some things notably:
* support for progress cancellation
* `flutter doctor` message cleanup
* `NEXT` button disablement
* proper error reporting
* error handling in general
For more context see: #764
@devoncarew

Flutter SDK installation WIP (#764).

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/dart/DartfmtSettings.java
src/io/flutter/sdk/FlutterSdkUtil.java

Toggle the default for whole file format (fix https://github.com/flutter/flutter-intellij/issues/1108):
- if the `DartCodeStyleSettings` class exists
- we use reflection to set the default value of the 'use dartfmt for whole file formats'
- and set a setting so we remember we changed the default, and only do it once (the user can then override)
@pq @skybrian

toggle the default for whole file format

---

src/io/flutter/bazel/WorkspaceCache.java
src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form

- in the 'no flutter sdk' editor notification, add a hyperlink to open the flutter settings (this parallels what the dart plugin does)
- add flutter icons to our editor notifications
- fix two analysis issues
@pq @skybrian @jwren

open flutter settings from the no flutter sdk notification

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/actions/OpenEmulatorAction.java
src/io/flutter/actions/OpenSimulatorAction.java
src/io/flutter/android/AndroidEmulator.java
src/io/flutter/android/AndroidSdk.java

- use the `AndroidSdk` class to find the best android sdk for a paritcular project
- look for the `tools/emulator` binary inside the sdk
- list and display any existing emulator avds in the device pulldown menu
- on selection, launch the indicated avd; display errors as appropriate on launching
- fix https://github.com/flutter/flutter-intellij/issues/536
@skybrian @pq

add the ability to start android emulators from the device pulldown

---

src/io/flutter/run/test/TestConfigProducer.java

Quick stab at scoping test config over-contribution.
I'm not sure `FlutterModuleUtils.hasFlutterModule` is the long-term fix but maybe OK short-term?
Fixes: #1128.

Scope Flutter test run config contrib (#1128).

---

.gitignore
src/io/flutter/FlutterInitializer.java
src/io/flutter/actions/OpenEmulatorAction.java
src/io/flutter/android/AndroidSdk.java
src/io/flutter/android/IntelliJAndroidSdk.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/sdk/FlutterCommand.java

- fix an issue launching android emulators
We would only locate an android sdk if we could both locate the sdk, _and_ an `Sdk` for it had been configured in IntelliJ. We now separate out the concepts of a wrapper around an `AndroidSdk` on disk and the `IntelliJAndroidSdk` wrapper, that references IntelliJ's Sdk instance.
@pq

fix launching android emulators

---

src/io/flutter/module/FlutterGeneratorPeer.java

For reference,
disabled:
vs. enabled:
Note that the action is still clickable in either case, which is deliberate.  (Happy to discuss the rationale.)
Fixes: #1145
@devoncarew

Keep `Install SDK…` action visible (#1145).

---

src/io/flutter/run/test/TestConfig.java
src/io/flutter/run/test/TestConfigProducer.java

Currently, we default to creating a test config based on filtering by name which is not yet supported in alpha and so we get this error:
This changes the default in that case to a file-based config which runs happily.
@devoncarew

Don’t filter tests by name if it’s not supported.

---

src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkRunner.java

- fix #971, have the run button active when there are no devices connected
- fix #1112, when the app hasn't fully started yet the play button should be disabled
@pq, @stevemessick

some improvements to run/debug button enablement

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterUtils.java
src/io/flutter/dart/DartSyntax.java
src/io/flutter/run/FlutterRunConfigurationProducer.java
src/io/flutter/run/test/FlutterTestLineMarkerContributor.java
testSrc/unit/io/flutter/dart/DartSyntaxTest.java

Basic support for running tests from editor line markers.
In general, we should add some better scoping to our test discovery (at the moment we're not picky about the provenance of functions called `test`); TODO added and I'll follow-up with a fix, as well as some noodling on support, in general, for `testWidgets`.
Fixes: #1174.
@devoncarew

Flutter test run line markers (#1174).

---

src/io/flutter/run/test/FlutterTestLineMarkerContributor.java

Follow-up from #1180 and continuing #1174, adds state awareness to run marker icons to distinguish:
1. previously green tests
1. unrun tests
1. previously red tests
1. previously skipped tests
For example:
A future arc of work would get this under test but I think we have some integration test fleshing out for that.

Test state icons.

---

src/io/flutter/utils/FileWatch.java

- potential fix for a file watching npe
```
at io.flutter.utils.FileWatch$Subscriptions.addWatchesForFile(FileWatch.java:208)
at io.flutter.utils.FileWatch$Delivery.after(FileWatch.java:250)
at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.jav …
```

potential fix for a file watching npe

---

flutter-intellij-community.iml

Needed to get tests working in `flutter-intellij-community.iml` (note this is consistent w/ `flutter-intellij.iml`).
(Open question whether we still need this distinct IML file?)
@stevemessick

Fix test source path for community IML.

---

src/io/flutter/run/test/TestConfigUtils.java
testSrc/unit/io/flutter/AbstractDartElementTest.java
testSrc/unit/io/flutter/dart/DartSyntaxTest.java
testSrc/unit/io/flutter/run/test/TestConfigUtilsTest.java

* scans main for named test calls (`test('')` // `group('')`)
* adds new `TestConfigUtilsTest`
Fixes: #1202.
@stevemessick @jwren

Scope main test markers to mains w/ tests (#1202).

---

flutter-studio/README.md
flutter-studio/flutter-studio.iml
flutter-studio/resources/META-INF/plugin.xml
flutter-studio/src/io/flutter/startup/FlutterStudioInitializer.java

Replace the simplified 'New Project' wizard of Android Studio with the traditional IntelliJ one. This allows creation of Flutter projects (and many others) in addition to Android projects.
Consider this proof-of-concept and subject to revision as we understand the requirements better.

Restore New Project wizard

---

src/io/flutter/editor/FlutterPubspecNotificationProvider.java

In the FlutterPubspecNotificationProvider, have the constructor receive the Project to avoid the call to ProjectLocator.getInstance().guessProjectForFile(file).
The other two NotificationProviders already do this.

FlutterPubspecNotificationProvider optimization

---

src/io/flutter/actions/FlutterRetargetAppAction.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/daemon/FlutterApp.java

Some small tweaks the reload action enablement:
- disable the reload button if there's no action app session
- have the 'open flutter view' and 'open observatory' buttons be enabled if there's an open session (previously they were enabled and disabled during a reload)
@pq @stevemessick @jwren

tweak the reload action enablement

---

src/io/flutter/run/test/FlutterTestEventsConverter.java
src/io/flutter/run/test/FlutterTestLocationProvider.java
src/io/flutter/run/test/TestConfigUtils.java
src/io/flutter/run/test/TestLaunchState.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/test/DartTestEventsConverterZ.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/util/DartTestLocationProviderZ.java

Adds:
* line marker support for `testWidgets`
* test tree rewriting to elide synthetic framework-generated test groups and fix location mapping
Fixes: #1181.
@stevemessick

Widget test discovery and execution (#1181).

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/RunFlutterAction.java
src/io/flutter/actions/RunProfileFlutterApp.java
src/io/flutter/actions/RunReleaseFlutterApp.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/FlutterLaunchMode.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/bazel/BazelFields.java
src/io/flutter/run/bazel/BazelRunConfig.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/RunMode.java
src/io/flutter/run/test/DebugTestRunner.java
src/io/flutter/run/test/TestDebugProcess.java
src/io/flutter/sdk/FlutterSdk.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

re-enable flutter run in profile and release modes (fix https://github.com/flutter/flutter-intellij/issues/930):
- re-enable launching in profile and release modes
- plumb the profile and release mode info down through the different debugger layers and abstractions
- ensure that we don't try and connect the debugger in profile or release mode
- ensure that the open observatory action is available in debug and profile modes, but not in release mode
- ensure that the reload action is available in debug mode, but not profile or release
@pq

re-enable flutter run in profile and release modes

---

src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/DeviceService.java

- adjust the device list refresh (some work towards https://github.com/flutter/flutter/issues/8439)
- don't use a fixed delay before we show devices in the pulldown
- do introduce a bit more delay when restarting the deamon process

adjust device list refresh

---

src/io/flutter/run/PositionMapper.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

Non breaking change to the `DartVmServiceDebugProcessZ` in order to get ready for the introduction of the `openSourceLocation` service.
Related https://github.com/dart-lang/sdk/issues/30023
Related https://github.com/B3rn475/intellij-plugins/tree/172

Prepare for 'openSourceLocation' service registration

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/FlutterModuleConfigurationEditorProvider.java
src/io/flutter/utils/FlutterModuleUtils.java

- fix an exception upgrading the module type in webstorm; the `WebModuleType.getInstance()` will always throw an exception in webstorm (2017.2?) - we work around the issue by using IDs
- fix https://github.com/flutter/flutter-intellij/issues/1239
- wordsmithing of the module upgrade text
@pq

fix an exception upgrading the module type in webstorm

---

src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/run/daemon/FlutterDevice.java

- ensure that we show a unique name in the device dropdown - if there are different devices with the same name, display the name with the device id as well (some work towards https://github.com/flutter/flutter-intellij/issues/1244)
So, Instead of `Foo Device`, show `Foo Device (device-id)`.

de-dupe device names

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/module/settings/SettingsHelpForm.form
src/io/flutter/module/settings/SettingsHelpForm.java

As per the discussion in https://github.com/flutter/flutter-intellij/pull/1232, migrates us to a LinkLabel.
@branflake2267 @devoncarew

Migrate to a LinkLabel

---

src/io/flutter/run/test/FlutterTestEventsConverter.java
src/io/flutter/run/test/FlutterTestLocationProvider.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/util/DartTestLocationProviderZ.java

Fix group handling for widget tests (#1249).

---

src/io/flutter/module/FlutterModuleBuilder.java

FlutterModuleBuilder.settingsFields is nullable but was not marked as such and had recently been assumed notnull. This only occurs in the AS plugin.

Allow nullable settingsFields

---

src/io/flutter/sdk/FlutterCreateAdditionalSettings.java

Android Studio 3.0 canary 9 does not include the Apache commons-lang3 library. We could distribute it, but it seems easier to in-line the single function that is used.

Eliminate dep on commons-lang3

---

src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/bazel/BazelRunConfig.java
src/io/flutter/run/daemon/FlutterApp.java

- fix https://github.com/flutter/flutter-intellij/issues/1254
This fixes an issue with the run action when there is a currently running app, and the user has two devices connected. Previously we ignored the device selection when deciding to issue a restart command (the user hits running with a currently running app). We now pay attention to the device selection, and will instead launch an app on that second device.
As part of fixed that issue, I also fixed one where the retargetable actions (reload and restart) would send their command to the last launched app. They now target the foreground process (which we determine via the last process that queried for `update()` in their actions, there being no real API in IntelliJ to determine the active launched process).

allow running on a second device

---

src/io/flutter/view/FlutterView.java

For iteration purposes.
* provisional icon : ![image](https://user-images.githubusercontent.com/67586/29097183-54568f5e-7c4d-11e7-934d-5c32170bd7b9.png)
* functionality a no-op until https://github.com/flutter/flutter/pull/10332 lands
Fixes: #1104.
@devoncarew 
FYI @jacob314

Initial “toggle inspect mode action” (#1104).

---

testSrc/integration/io/flutter/testing/FlutterModuleFixture.java
testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java

Additional tests on FlutterModuleUtils.isFlutterModule() will be required to be integration tests

Some initial unit tests for FlutterModuleUtils

---

src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/daemon/FlutterApp.java

Some iteration on the reload on save UI (fix https://github.com/flutter/flutter-intellij/issues/1215):
- fix an issue where the reload actions could become disabled when the run or debug views were not front-most
- remove the code to only reload on save if there had been changes since the last reload
- always provide reload UI feedback on save (if there is an open document and a flutter app is running)
- switch to using the information from the analysis server to determine whether to reload
- if there are errors, show an in-line notification (Reload not performed), and a decoration on the analysis view
- show 'reloading...' when starting a normal reload
@stevemessick

iterate on the reload on save UI

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterInitializer.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/DaemonConsoleView.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterAppListener.java
src/io/flutter/run/test/DebugTestRunner.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java

additional changes to the reload on save workflow:
- send analytics information about what experimental features users have enabled (reload on save, improved memory view)
- ask the user for feedback the first time they disable reload on save
- provide info about reload-on-save reload starts and stops as balloons on the run/debug view, instead of as inline tooltips in the editor. The inline tooltips were a bit too distracting as you were typing, and made the UI seem a bit jerky.
- some refactoring of the code for how we persist user settings
@stevemessick

additional changes to the reload on save workflow

---

src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/run/daemon/FlutterApp.java

- measure the number of sessions using reload vs restart in their workflow (at the end of an app run, the session was a 'reload' session if they reloaded at least once; a 'restart' session if they restarted at least once; and otherwise, we record 'none' for that session)
- fix a bug where some restart events were recorded as reload (this only happened if the user had hit the reload button with the shift key pressed)
@stevemessick

measure users using reload vs restart

---

src/io/flutter/FlutterBundle.properties

@devoncarew @mit-mit New help text for the Package option in module creation.
The cli help message uses "project" in a much different way than IntelliJ. IMO that text isn't a good fit here.

Fix help text for Package

---

flutter-studio/src/io/flutter/module/AdditionalLanguageSettings.form
flutter-studio/src/io/flutter/module/AdditionalLanguageSettings.java
flutter-studio/src/io/flutter/module/FlutterPackageStep.form
flutter-studio/src/io/flutter/module/FlutterPackageStep.java

Change the layout a bit. Instead of a separate help section distribute those texts throughout the form.
The package page is identical except it doesn't have any fields below description.

Rearrange the configuration page for modules

---

resources/META-INF/plugin.xml
src/io/flutter/actions/FlutterExternalIdeActionGroup.java
src/io/flutter/actions/OpenInAndroidStudioAction.java
src/io/flutter/actions/OpenInXcodeAction.java

- add an open in android studio action (fix https://github.com/flutter/flutter-intellij/issues/1063, fix #1118)
- adjust slightly where in the context menu we contribute the `open in...` actions
- make the open in xcode action not show when the android folder is selected; make the open in android studio action not selected when the ios folder is selected

add an open in android studio action

---

src/io/flutter/project/FlutterIconProvider.java

- use distinct icons for the android and ios source folders
@pq, @stevemessick

use distinct icons for the android and ios source folders

---

src/io/flutter/run/FlutterReloadManager.java

- fix an issue with reload on save in 2017.1 (fix https://github.com/flutter/flutter-intellij/issues/1324)
(access to the PSI info from a document needs to be synchronized)
@stevemessick

fix an issue with reload on save in 2017.1

---

src/io/flutter/run/daemon/ProgressHelper.java

Fix a (relatively rare) exception that happens when closing a device.
@stevemessick 
```
null
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
at com.sun.proxy.$Proxy16.onTextAvailable(Unknown Source)
at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:201)
at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
at …
```

fix an exception in ProgressHelper

---

resources/META-INF/plugin.xml
src/io/flutter/FlutterInitializer.java
src/io/flutter/ProjectOpenActivity.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/sdk/FlutterPluginLibraryProperties.java
src/io/flutter/sdk/FlutterPluginLibraryType.java
src/io/flutter/sdk/FlutterPluginsLibraryManager.java

- show flutter plugins as IntelliJ libraries (fix https://github.com/flutter/flutter-intellij/issues/1090)
This shows shows flutter plugins in the `External libraries` section of the Project view ,as well as in the project structure dialog. You can expand these entries to dig into the android and ios code that makes up the plugin implementation. Some screenshots:

show flutter plugins as IntelliJ libraries

---

flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.form
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
src/io/flutter/module/FlutterGeneratorPeer.java
src/io/flutter/module/InstallSdkAction.java

Adds the same style of Install SDK button to the Android Studio wizards as is found in the IntelliJ wizards.
InstallSdkAction needed somne refactoring to become reusable. Getting the event-based validation in the new wizard framework to work required adding a few calls that could change how it behaves w.r.t. the old wizards. I verified that it still works, but I didn't check that cancelling has exactly the same before-and-after behavior. But it seems reasonable. It may look worse than it is because it got reorganized during reformating. Everything is still there.
Also, this removes the error message that @mit-mit found inhibiting his progress.
Static screenshot:
Action-packed screenshot:
The validation error goes away once validation runs after the installation is …

Add an Install SDK button to the new module wizard.

---

src/io/flutter/FlutterConstants.java

Fixes #1352 
Disallows 'flutter_test' as a module or project name.

Disallow flutter_test module name

---

flutter-studio/src/io/flutter/project/FlutterProjectStep.java

Just as the title says.
Event-driven validation is cool, but some components don't seem to generate all the events they should.

Validate the SDK when selected from the file chooser

---

resources/META-INF/plugin.xml

(Still WIP.)
@stevemessick @mit-mit 
FYI @devoncarew

Back out Open in… release notes.

---

src/io/flutter/run/FlutterReloadManager.java

- fix an issue where - with multiple project windows open - we'd receive multiple save action notifications, and perform reload on save for each notification (fix https://github.com/flutter/flutter-intellij/issues/1377)
@stevemessick @pq 
(this is likely a fix we'll want to release as part of a M18.1)

fix an issue with multiple reloads

---

src/io/flutter/module/FlutterModuleBuilder.java

* updates message dialog to use our Flutter branded one
* adds an option to run `flutter doctor`
Fixes: #1399

Improve error reporting on create failures (#1399).

---

src/io/flutter/FlutterUtils.java
src/io/flutter/run/test/TestConfigProducer.java
src/io/flutter/run/test/TestConfigUtils.java

Ensures tests run in a vanilla dart project (with nonetheless an SDK vended into a Flutter install) are not run w/ `flutter test` and that new test run configs are only fluttery if they should be.
Fixes: #1371 
@devoncarew

Ensure vanilla dart tests are not mis-indentified as fluttery (#1371).

---

src/io/flutter/run/daemon/FlutterApp.java

-guard against a ConcurrentModificationException
```
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:896)
at io.flutter.run.daemon.FlutterApp.changeState(FlutterApp.java:335)
at io.flutter.run.daemon.FlutterAppListener.processTerminated(FlutterAppListener.java:55)
at io.flutter.run.daemon.DaemonApi$1.processTerminated(DaemonApi.java:142)
```

fix a ConcurrentModificationException

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/OpenInAndroidStudioAction.java

Detect Android Studio 2.x and offer suggestion to fix path.
Ignore trailing slash in path.
No-break-space is used to keep the command on a single line in the message box.
The source got sorted when I reformatted. If you want the original sorting I'll re-do it.
Fixes #1372 

Harden "Open in Android Studio"

---

flutter-studio/src/io/flutter/FlutterStudioInitializer.java

Check to see if the version of Android Studio is too old to use. This check runs before the splash screen is removed. The error will be displayed even if the welcome screen is the only UI that is shown. Currently, beta 7 and later are acceptable.
Ideally, we'd disable the plugin. I experimented with that but it is hard to get working. It would require shutdown and restart anyway, so doesn't actually prevent the user from doing things that will generate stack traces as in #1395.
Fixes #1396

Check that Android Studio is up-to-date

---

build.xml

This adjusts the build script so that we always build the main plugin (the non-android one) against an idea product. So, for IDEA or WebStorm builds, we use the passed in idea product for the build. For Android Studio builds, we use the default idea product and version (currently, IDEA and 2017.2).
Also, rev the default version of the platform we compile against to 2017.2. This addresses an issue with access permissions at runtime when creating the webstorm project wizard (fix https://github.com/flutter/flutter-intellij/issues/1384).
@pq @stevemessick 
I may still investigate re-writing the build system into Dart (for maintainability and simplicity). That's no longer blocking https://github.com/flutter/flutter-intellij/issues/1384 however, so is less urgent.

build the idea core plugin against an idea product

---

flutter-studio/src/io/flutter/project/FlutterProjectModel.java

The Swift button should be independent of the Kotlin button. Apparently, during manual testing I always changed them both.

Fix Swift button

---

flutter-studio/src/io/flutter/project/FlutterProjectStep.java

Remove check for module name matching identifier syntax.

No need to check for identifier clash

---

flutter-studio/src/io/flutter/module/FlutterModuleStep.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
resources/META-INF/plugin.xml

Changes name-related error messages to use 'project' or 'module' as appropriate for the item being created. This is something that could confuse new users, while experienced devs won't even notice.
Something like this may be needed for the IntelliJ plugin -- I haven't checked.

Make errors refer to proper project or module

---

src/io/flutter/run/FlutterConfigurationEditorForm.form

- add descriptive text to the flutter run launch config; this is to help clarify that 'build flavors' are optionsl
- sort the build flavor last in the dialog
@pq @stevemessick @mit-mit

add some descriptive text to the flutter run launch config

---

flutter-studio/src/io/flutter/module/FlutterModuleStep.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.java

You cannot modify the module location. Adding the validator can cause spurious errors when testing very long module names because the validator has a hard limit of 100 chars for project location paths.

Do not validate module location

---

src/io/flutter/editor/FlutterPubspecNotificationProvider.java

Fixes: #1445.
@devoncarew @jwren 
FYI @jwren, @alexander-doroshko : we'll want to update the check in the Dart Plugin (if we haven't already) to make sure that it verifies that projects are declaring Flutter when we test for flutteriness.

Scope Flutter pubspec action contributions (#1445).

---

build.xml
resources/META-INF/plugin.xml.template

Template plugin.xml added to ant script to produce usable plugin.xml. The args used in build-all.sh can be used to make a plugin.xml for Android Studio (no one but me needs to).
@devoncarew @pq @jwren

Change build script to leave usable plugin.xml

---

flutter-intellij-community.iml

Change from java module to plugin module. That adds the Build>Prepare Plugin Module menu item. It still doesn't work due to an error encountered when building, but at least it's there.

Update module file

---

flutter-intellij-community.iml
flutter-studio/src/io/flutter/FlutterStudioInitializer.java

The message was just plain wrong. Now it is better. I'm still looking for a way to prevent installation into 3.1 but haven't found it. This message shows up while the splash screen is still visible, so it is impossible to miss.

Provide better feedback when installing into canary AS

---

flutter-studio/src/io/flutter/project/FlutterProjectCreator.java

When the new project wizard tries to create a project it may ask to re-use the current window or open a new one (depending on settings). If you cancel that dialog no project is created. It is bad form to go ahead and try to use it anyway.

Fix NPE from project wizard

---

flutter-studio/flutter-studio.iml
resources/META-INF/plugin.xml

Adjust the lower-bound version in plugin.xml so it works for Android Studio. Once we get back to using a script this won't matter. Also remove some AS dependencies that aren't needed.

Minor clean up

---

resources/META-INF/plugin.xml

This error appears to prevent sources from loading in a runtime workbench and occurs when the androidstudio is not installed.
@stevemessick

Suppress missing (optional) androidstudio module error.

---

src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/actions/FlutterRetargetAppAction.java
src/io/flutter/actions/ProjectActions.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterView.java

This addresses an issue I saw this weekend. I had two project windows open against two separate flutter projects. I hit run in one project; when the app came up, the reload icon became enabled both in the current project, but also in the 2nd open project window. Hitting reload in either window would reload the app running for the first window.
- switch from using `ActionManager` to track globally registered actions, to using a new tracker that's scoped to projects
- additionally, fix an issue in reload on save where we didn't reload when the focused dart editor wasn't in the module for the app currently running. From dogfooding, it's surprising when the app doesn't reload (users get a sense that cmd-s means reload).
@pq

fix how we retarget flutter actions

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template

- add add a keybinding for shift-cmd-s (for a full restart - a companion to cmd-s and hot reload on save). While writing Flutter code I found myself wanting this :)
- remove the semi-colon keybinding for reload and restart; we now have three keybinding and this one seems the most esoteric. perhaps a resolution is to update the docs to mention the two keybindings, and to point people to existing intellij docs on customizing keybindings if the existing ones don't work for them
@pq @mit-mit

add a keybinding for shift-cmd-s

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

- add a placeholder for a feedback link for the widget inspector (fix https://github.com/flutter/flutter-intellij/issues/1418)
Note: I won't land this until we have a goo.gl short link for the feedback.
@jacob314 @InMatrix

add a feedback link for the widget inspector

---

src/io/flutter/inspector/DiagnosticsNode.java

Follow-up from: https://github.com/flutter/flutter-intellij/pull/1484#pullrequestreview-75258371.
We can move other bits over from `DiagnosticsNode` to taste but this minimally cleans up the duplication I introduced.
@jacob314

getStringMember de-duping.

---

.idea/misc.xml
src/io/flutter/FlutterUtils.java
src/io/flutter/editor/FlutterPubspecNotificationProvider.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/utils/FlutterModuleUtils.java

Fix for https://github.com/flutter/flutter-intellij/issues/1449 and a change to the Dart Plugin and Flutter Plugin to check for the flutteriness of a pubspec.  We now look to see if the individual pubspec declares flutter when determining if a notification should appear for a pubspec, _instead_ of asking the module if some pubspec.yaml declares flutter.
Nit: when comparing a file name to "pubspec.yaml" the two plugins are not consistent in _not_ ignoring the case of the filename.
Corresponding PR: https://github.com/JetBrains/intellij-plugins/pull/557

Fix for https://github.com/flutter/flutter-intellij/issues/1449

---

build-all.sh
build.xml
resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
src/io/flutter/FlutterUtils.java

- update the build to allow the android studio zip file binary to work for IntelliJ as well
- extend the version range of the AS binary to span 2017.1 through 2017.3
- ensure that the intellij source are compiled against 2017.1
- make the AS module dep listed in plugin.xml be the `com.android.tools.apk` one (important for the wizard dialog to function)
@stevemessick 
Steve, this is a bit of a pragmatic change, but does get us though the next release.

update the build to allow the android studio zip file binary to work for IntelliJ as well

---

src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/FlutterModuleUtils.java

- improve the set of flutter sdks we show in the flutter sdk path combo
This is to mitigate the chance that the flutter sdk path combo will be empty (in places like the new project wizards). When testing Android Studio, the combo was empty, even though another open project window did have a flutter sdk set.
@stevemessick @pq @jwren

improve the set of flutter sdks we show in the flutter sdk path combo

---

tool/plugin/lib/plugin.dart
tool/plugin/pubspec.yaml
tool/plugin/test/plugin_test.dart

Implement the release-mode validity checks. Add --cwd to allow testing. Add tests.
Most travis builds passed. One failed with:
```bash
HTTP error 500: Internal Server Error at https://pub.dartlang.org/api/packages/collection.
This is likely a transient error. Please try again later.
```

Add release validity checks

---

flutter-intellij-community.iml
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

Add a plugin-matrix.json and drive the build from it. Change BuildSpec creation and update tests. Format the code. (Sorted in a previous PR)
Still working on `plugin build`. It will put the built file into a subdirectory of either artifacts or artifacts/release_NN, named after the platform version (3.0, 2017.2, 2017.3). All the files will be zip files, to reduce bandwidth.

Add product-matrix.json

---

tool/plugin/compile.xml
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

Implement (most of) `plugin build`. Artifact provisioning is not complete, but if everything is already in place this will build one zip file. I have not tested building the others yet. The file contents are the same as produced by the old ant script. It works in Android Studio to the limited extent I tested it.

Work on 'plugin build'

---

src/io/flutter/actions/FlutterExternalIdeActionGroup.java
src/io/flutter/project/FlutterIconProvider.java
src/io/flutter/run/test/TestLaunchState.java
src/io/flutter/sdk/FlutterSdk.java

- guard against a null getBaseDir() from a Project when the user is deleting projects (fix https://github.com/flutter/flutter-intellij/issues/1513)

fix an NPE in the icon provider when deleting projects

---

src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/DaemonConsoleView.java
src/io/flutter/run/test/DebugTestRunner.java
src/io/flutter/utils/StdoutJsonParser.java
testSrc/unit/io/flutter/utils/StdoutJsonParserTest.java

Improve parsing of the daemon json stream:
- we now handle cases where larger json blobs would be split across two or more messages; previously we'd drop the messages on the floor; now we combine and parse correctly
- handle a case where flutter_tools occasionally sends a newline before any other output when starting an app
@stevemessick @jwren @pq

improve parsing of the daemon json stream

---

src/io/flutter/FlutterUtils.java
src/io/flutter/run/test/TestConfigProducer.java

@pq, expand our idea of what a flutter project is slightly to allow us to run unit tests from the //packages/flutter project in IntelliJ.

allow to run package:flutter tests from IntelliJ

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
tool/plugin/lib/plugin.dart

The value of the --release argument will be used as the version number. If there is no --release argument then the version tag will be omitted. Also, fix a range error.
Apparently, if all the TODOs in a file have a space before TODO then the TODO viewer of IntelliJ won't find any of them. In other words, do this:
`//TODO`
and not this:
`// TODO`
Fixed that, too.

Add a template variable for version

---

tool/plugin/lib/plugin.dart

unzip hangs if a file exists that it is trying to write. There may be a flag for that, but we should be cleaning out the destination anyway. Reformatting changed another line.

Stop unzip from hanging if files exist

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
src/io/flutter/inspector/FlutterWidget.java

Causing a conditionally-included file to get loaded twice is a bad idea. It creates duplicate actions, which cause errors, which prevents the UI from starting when there is nothing other than the Welcome screen to display.
I also added a logger that might help with resource loading issues.
I need to extend `build gen` to do the right thing for the plugin.xml used for debugging.

Fix error due to duplicate actions

---

product-matrix.json
tool/plugin/README.md
tool/plugin/compile.xml
tool/plugin/lib/plugin.dart

@devoncarew @jacob314 @pq 
Fix various bugs in provisioning. Make it more resilient to errors.
It can still get into a bad state. The simplest fix is:
```shell
rm -rf artifacts
plugin build
```
Also, I converted the documentation to markdown and added it. I couldn't find an easy way to wrap the lines so the raw markdown is unreadable. However, it looks good in a proper reader. As I update it I will wrap the lines.

Fix provision; convert doc

---

flutter-intellij.iml

- update the idea iml file to exclude AS specific source
@stevemessick - I'm not entirely sure that this is the best fix, but it does allow the `flutter-intellij.iml` file to build successfully

update the idea iml file

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/FlutterDevice.java
src/io/flutter/utils/CustomIconMaker.java
src/io/flutter/view/AbstractToggleableAction.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java

Misc inspector UI tweaks:
- add generated icons for widgets without specific icons
- bug fix to the CustomIcon class
- move the ability to bring a simulator to the foreground into a new `bringToFront()` method
- when the user starts inspect mode, bring the ios simulator to the foreground
- don't show the top level `[root]` node
- reduce the width of the 'Properties' table (give more space to the values)
- give the table rows slightly more vertical space
- in the elements tab, have `child n` prefixes have the same look as the `child` prefix
- tweak the look of nodes in the widget tree; node types are no longer bold, and the suffix id has a space between he name, and shows as gray (supplemental information)
- null values show as empty instead of w/ text `null`
Comments and thoughts welcome, …

misc inspector UI tweaks

---

src/io/flutter/view/FlutterView.java

- put the inspect button behind a user preference
- fix https://github.com/flutter/flutter-intellij/issues/1566
@jacob314

put the inspect button behind a user preference

---

src/io/flutter/utils/ColorIconMaker.java
src/io/flutter/view/InspectorPanel.java

Gray out unimportant properties and highlight warning and error properties.
The color icon code is a bit uglier than I'd like because I don't see an obvious way to center the icons so I had to make them have a margin so centering vertically wasn't needed.

Show color properties with a nice color swatch icons

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/InspectorPanel.java

actual Dart properties of the Color object instead of depending on parsing
the toString output for Color objects.
The code to get the Dart properties is ugly. Unfortunately we can't just use the Dart fields which would be more cleanly exposed through the Observatory protocol because many common objects we care about use properties not fields for the relevant data. If it becomes a performance bottlekneck (unlikely given this is just for properties) we could get a built in observatory protocol method to access a specified list of Dart properties for an object.
One valid design question is why these properties aren't just specified in the DiagnosticsNode protocol. The answer is that it could be but there are some nice advantages of this approach.  With this method, we can iterate on visual …

Cleanup code to display colors nicely so that it depends on getting the

---

tool/plugin/lib/plugin.dart

Verified that it produces, in the appropriate files:
```xml
<version>20.0.1</version>
<version>20.0.2</version>
<version>20.0.3</version>
```

Change version to NN.M.I

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
tool/plugin/lib/plugin.dart

Fix `plugin gen` so it creates a plugin.xml that will correctly launch Android Studio with the Flutter plugin extension enabled. (Verified that `plugin build` is not affected.)
Also, the --no-ij and --no-as flags were not being checked. If you're debugging a build issue specific to one platform you can stop building the other. Note that --ij and --as are both assumed so specifying either does nothing. (And yes, --no-as will still build two ij versions.)

Gen plugin

---

src/io/flutter/view/InspectorPanel.java

Gives us, for example, a tree like this:
and
compared to the current default:
Happy to nudge out a bit if this looks too tight.
cc @jacob314 @devoncarew

Reduce inspector tree indent.

---

gen/icons/FlutterIcons.java
src/io/flutter/FlutterBundle.properties
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterView.java

- remove specific references to the timeline and memory views (the memory view was not complete)
- add a reference in the flutter view to the observatory; this mirrors what people see in the run and debug views
@pq, @jacob314, /cc @mit-mit

remove the memory dashboard reference; add an open obs. action

---

src/io/flutter/pub/PubRoot.java

Oddly we were looking for `lib/example/lib/main/dart` instead of the expected `example/lib/main.dart`.

Fix example `main.dart` run config auto-creation.

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java

- rename the `Flutter` view to `Flutter Inspector`
- increase the tree indent arbitrary (both 3 - and 4 - seem too compressed, but do do a lot of help with the horizontal indent)
@pq @jacob314

rename the Flutter view

---

src/io/flutter/run/FlutterReloadManager.java

- address an exception in the log due to registering notification groups more than once
```
Notification group Flutter Dart Analysis is already registered 
java.lang.Throwable
at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:50)
at com.intellij.notification.NotificationGroup.toolWindowGroup(NotificationGroup.java:82)
at io.flutter.run.FlutterReloadManager.showAnalysisNotification(FlutterReloadManager.java:278)
at io.flutter.run.FlutterReloadManager.lambda$handleSaveAllNotification$2(FlutterReloadManager.java:220)
```

address an exception in the log

---

src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/FlutterApp.java

- show a notification when a reload indicates that not all reload elements ran after view reassembly
- fix https://github.com/flutter/flutter-intellij/issues/1398
@pq @jacob314 @mit @InMatrix 
The notification shows once per reload, for each reload that has un-run, reloaded program elements. The message is longer than I'd want, but I had trouble creating a shorter message that was still clear.
Dependent on https://github.com/flutter/flutter/pull/13996 (or similar) landing.

add a notification for reloaded but not run elements

---

tool/plugin/lib/plugin.dart

When on the wrong branch, I see the error message: `the current git branch must be named "release_2"` (I'm on release_21.0).
@stevemessick

fix an issue with plugin build

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/InspectorPanel.java

Fix multiple race conditions occurring when the inspector is executed
in run mode.
Fix case where isolate ids were not available and fix case where the inspector
is called after the first frame has already rendered.
Add ability to perform capability detection to determine whether the
inspector supports a specific service method.
Fix null property type case.
Combined with a package:flutter fix, this fixes all pending inspector crasher bugs.

Inspector stability improvements.

---

src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
src/io/flutter/sdk/FlutterSdkVersion.java

The flutter version file was renamed from `VERSION` to `version` (and the contents changed slightly). We received a crash report in https://github.com/flutter/flutter-intellij/issues/1646; the existing code should have been hardened against the name change - I don't see a clear reason for the crash - but this PR does update to pull from the new file name.
Also, this PR removes several (now pretty old) version numbers.
@pq @jwren

handle updates to the flutter version file

---

src/io/flutter/sdk/FlutterSdkVersion.java
testSrc/unit/io/flutter/sdk/FlutterSdkVersionTest.java

Another fix for https://github.com/flutter/flutter-intellij/issues/1662; the flutter sdk's `verison` file can contain text like `'unknown'`, which the semver version class we're using doesn't like.
@stevemessick @scheglov

fix an NPE on bad version file text

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterView.java

- add a preference to open the inspector view at app launch (fix https://github.com/flutter/flutter-intellij/issues/1618)
- when the app closes, re-show the previously active view, unless the user has manually selected other views in the interim
@pq @jacob314

open the inspector view at app launch

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewState.java
src/io/flutter/view/InspectorPanel.java

- restore inspector splitter position between IntelliJ sessions
- show text `'Widget tree for the running app'` when there is no content in the widget / element tree view. This is to help the user know that an app must be running for content to display
- rename the 'Toggle Inspect Mode' toolbar button to 'Toggle Select Widget Mode'. I think the new name makes more sense now that the view has been renamed to 'Flutter Inspector'
- reorder the toolbar icons so the inspect mode action comes first
@jacob314 @pq

misc inspector work

---

src/io/flutter/actions/OpenSimulatorAction.java

I can't repro w/o an incomplete Xcode upgrade but it looks like the issue stems from a `null` error message in case of a process failure.  This should work around that case.
Fixes: #1647.
@devoncarew

Harden error reporting on iOS simulator start failures (#1647).

---

resources/META-INF/plugin.xml
resources/META-INF/plugin.xml.template
src/io/flutter/dart/FlutterDartAnalysisServer.java
src/io/flutter/preview/PreviewView.java

So, now it is safe to subscribe for Flutter notifications even when Analysis Server has not yet started. For example when the view is open on start.
And subscribe to the currently selected file during opening of the view.

Pull the existing or new Analysis Server service.

---

src/io/flutter/preview/PreviewView.java

- sync editor selection on any click on the widget tree
- move focus to the editor if the click count is a double click or greater
@scheglov

tweak the preview click behavior

---

src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/actions/OpenInXcodeAction.java
src/io/flutter/run/daemon/FlutterAppListener.java
src/io/flutter/run/daemon/ProgressHelper.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/utils/ProgressHelper.java

Checks for `build/ios` and in it's absence kicks off a `flutter build --debug`, showing progress in the status line.
Otherwise, simply opens.
Fixes: #1373
@devoncarew

Smarts to run `flutter build` before trying open Xcode (#1373).

---

src/io/flutter/preview/PreviewView.java

Scrolling the node of the enclosing top-level declaration to the top of the tree has one not quite ideal consequence - the tree jumps us you click it.

Navigate from source to Preview view.

---

src/io/flutter/preview/PreviewView.java

So, when you open the view for the first time, or switch between editors, the item that corresponds to the current caret position is selected in the tree.

Select the outline under caret in the tree on a new outline notification.

---

src/io/flutter/preview/PreviewView.java

- handle the general tree selection event (sync the editor position with tree selection changes, like those from key events)
- elide `icon` param names - this makes `Icon` nodes look better
- don't show the parent association label; this is generally `child:` or `children:`. There's a little less noise in the tree w/o the labels, and the tree looks a bit more like a hierarchical representation of the widgets. @scheglov, I'm happy to discuss more in the office if you have concerns about this change
@scheglov

handle tree selection event

---

src/io/flutter/dart/DartAnalysisServerServiceEx.java

This solves a problem with restarting the analysis server, or the case when the view is open when you start IDE.

Unpack BlockingRequestSink to get the actual ByteRequestSink.

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/JumpToSourceActionBase.java
src/io/flutter/utils/AsyncRateLimiter.java
src/io/flutter/utils/AsyncUtils.java
src/io/flutter/view/InspectorPanel.java
testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java

For the full benefit a small matching change is required on the flutter side as there is some caching of property values that gets in the way.
Tests for the rate limiter code are a bit clumsy as I didn't see an obvious way to plumb through mock time objects. This rate limiter has the advantage over more simple approaches of ensuring the first update happens immediately and only subsequent updates are rate limited to avoid overtaxing the device. This means that after a hot reload you will see new properties immediately but you won't try to get property value updates at 60fps while scrolling.
Integration with completable future is also quite nice so we won't schedule a new update until at least after the previous update is complete ensuring we avoid denial of service level attacks on a slow …

Live update of property values triggered each time a flutter frame is drawn

---

src/io/flutter/utils/ColorIconMaker.java
src/io/flutter/view/InspectorPanel.java

Showing the name in grey even when the name was supposed to be hidden was confusing.
Add todo that icons are the wrong size when the font size is changed.

Property display cleanup.

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/JumpToSourceActionBase.java
src/io/flutter/utils/AsyncRateLimiter.java
src/io/flutter/utils/AsyncUtils.java
src/io/flutter/view/InspectorPanel.java
testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java

Avoid using keySet API on JsonObject as it is not supported by the version
of com.google.gson.JsonObject used on all platforms we support.
Change from the previously approved CL is just in the second hash part of this CL.

Reapply property value cl

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/preview/PreviewView.java
src/io/flutter/preview/PreviewViewState.java
src/io/flutter/utils/CustomIconMaker.java
src/org/dartlang/analysis/server/protocol/FlutterOutlineAttribute.java

Several misc changes:
- shorter closures in the preview view in order to reduce the amount of horiz. scrolling
- collect some common code for creating icons
- update the code to handle saving / restoring the Preview view state
@scheglov

shorter closures in the preview view

---

src/io/flutter/preview/ModelUtils.java
src/io/flutter/preview/PreviewAreaPanel.java
src/io/flutter/preview/PreviewView.java
src/io/flutter/preview/PreviewViewState.java

- add a splitter to the Preview view, and, when a file with a Flutter build() method is active, shows a JPanel there with the name of the currently selected Widget
- have a compile time flag to enable the panel; the panel doesn't do anything useful currently
- remember the splitter position in the view's persisted state
- render build() methods in bold, in order to highlight them in the UI
@scheglov, in the future, we use this to show a live preview of the current widget. That would likely be a ways out; we can choose to land the parts of this PR that are immediately useful, hold off on the PR, or commit it w/ the understanding that the panel might be refactored away if we don't go this direction.

Add preview area to the Preview view

---

src/io/flutter/preview/PreviewView.java

Address an NPE:
```
at io.flutter.preview.PreviewView.getOutlineOfPath(PreviewView.java:436)
at io.flutter.preview.PreviewView.lambda$updateActionsForOutline$2(PreviewView.java:326)
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
```
@scheglov

fix an npe in path selection

---

src/io/flutter/preview/PreviewView.java

It might be `null` if the file does not have any top-level declarations, e.g. a library that just reexports other libraries.

Check top-level outline getChildren() for null.

---

src/io/flutter/preview/PreviewView.java

These labels are long though.
We could shorten them on the client, e.g. leave first and last 50 characters.
Or we could shorten them on the server, e.g. omit long arguments.

Render generic label for outline items.

---

src/io/flutter/preview/PreviewView.java

This is for a dart sdk that does not have support for flutter outlines.
```
at io.flutter.preview.PreviewView.addOutlinesCoveredByRange(PreviewView.java:487)
at io.flutter.preview.PreviewView.applyEditorSelectionToTree(PreviewView.java:549)
```
@scheglov

fix an npe in preview

---

resources/META-INF/plugin.xml
src/io/flutter/actions/FlutterExternalIdeActionGroup.java
src/io/flutter/actions/OpenInAndroidStudioAction.java
src/io/flutter/actions/OpenInXcodeAction.java

Some changes to `Open Project in Android Studio/Xcode`
- Format, sort code; resolve warnings
- Disallow on project root (does not work for Xcode anyway)
- Do not allow opening *_android.iml in Xcode
- Allow opening Android project in Android Studio even if currently using Android Studio
The last one is significant because it is the only way to properly support editing of Java/Kotlin code within the Android module.

Improve Open In action

---

src/io/flutter/preview/PreviewView.java

- rename 'Add widget padding' assist to 'Add padding'
- this may conflict with https://github.com/flutter/flutter-intellij/pull/1769; I'll want to land this until after that lands
@scheglov

rename 'Add widget padding' assist to 'Add padding'

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorTreeActionBase.java
src/io/flutter/inspector/JumpToSourceAction.java
src/io/flutter/inspector/JumpToSourceActionBase.java
src/io/flutter/inspector/JumpToTypeSourceAction.java
src/io/flutter/inspector/Location.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/utils/JsonUtils.java
src/io/flutter/view/InspectorPanel.java

This CL is fine to land before the corresponding changes in Flutter or
Flutter Engine as without those changes source locations just show
up as missing. The source location menu item shows up as disabled
for widgets or render objects without a source location.
Note that RenderObjects will not have source locations even after the
Flutter change as there isn't a clear benefit in tracking them.

Track creation locations.

---

src/io/flutter/view/InspectorPanel.java

Fixes: #1697
This gets us simple search using Widget `toString()`s.  The Preview View takes it further (supporting path searches and more).  If we want to do that, we should consider adding something like a `getSpeedSearch()` method to `DiagnosticNode`.  Happy to follow-up some refinements if there's interest!
@jacob314 @scheglov

Basic speed search for the Inspector Tree.

---

src/io/flutter/project/FlutterIconProvider.java

- update when we use the flutter icon for modules
I noticed in some situations the icons was not showing for flutter modules, and was instead showing for non-flutter ones. Before this change:
(perf_tool is a web module, and conference_app is a flutter one); after this change:
@pq

update when we use the flutter icon for modules

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewAction.java
src/io/flutter/view/FlutterViewFactory.java
src/io/flutter/view/FlutterViewToggleableAction.java
src/io/flutter/view/InspectorPanel.java

Now each running app gets its own inspector tabs and clicking the toolbar buttons in the tab only impact that app.
Previously, the toolbar buttons would only impact the last running app leaving the other apps surprisingly unresponsive.
The design is now that inspector tabs close automatically when the apps stop making the lifecycles a bit easier resulting in removing some of the stopped events.

Inspector support for multiple running applications.

---

flutter-intellij-community.iml
flutter-studio/src/io/flutter/FlutterStudioInitializer.java
flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterProjectSystemProvider.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/FlutterWelcomeFrameFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/FlutterProjectStepFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/FlutterSettingsStepFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/NewFlutterModuleWizardFixture.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/NewFlutterProjectWizardFixture.java
flutter-studio/testSrc/io/flutter/tests/gui/NewModuleTest.java
product-matrix.json

Fix compile errors to run in debug mode.
Compile cleanly with AS 3.1 beta 3.
Upload binaries for plugin build cmd.
Do NOT add new target to travis because it isn't tested yet at all.
If you want to test it you should be able to make a local copy via:
```bash
./bin/plugin build -o3.1
```

Compile against 3.1 beta 3

---

src/io/flutter/view/FlutterView.java

- don't close the inspector when empty; this closes the right-hand tool window, even if the user had it open before the inspector ran; instead, we restore the previously active tool window
- move where we contribute the feedback toolbar button so that its visible even if an app has not yet been run
@jacob314

don't close the inspector when empty

---

.travis.yml
product-matrix.json

- compile against AS 3.1 when building 2017.3 (follow up from https://github.com/flutter/flutter-intellij/pull/1785)
- rename the `3.0` artifact directory to `2017.1` (for similarity with the 2017.3 and 2018.1 directories)
w/ this change, we now build:
- 2017.1 (IntelliJ and Android Studio)
- 2017.3 (IntelliJ and Android Studio)
- 2018.1 (IntelliJ)
@stevemessick

compile against AS 3.1 when building 2017.3

---

flutter-intellij-community.iml
flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/FlutterStudioInitializer.java
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
src/io/flutter/module/FlutterSmallIDEProjectGenerator.java

AS 3.1 and later require creating a write-safe context to make model modifications. This changes the explicit (simple) thread management to use TransactionGuard, which does the right thing.
Also runs the migrate-to-gradle converter immediately after creating an Android Studio project to eliminate the AS-specific prompt to do so. (Does not address IJ-specific prompt, which I did investigate w/o resolution.)
Tested in 2017.3, 3.0.1, 3.1.
Even so, do not cherry-pick into M22. AS 3.1 still has a number of problems.

Write safe

---

docs/android.md

@devoncarew @pq @mit-mit 
Add instructions for editing native Android code in a plugin. The main concepts are:
1. Use Flutter to build the example app.
2. Edit all native code through the example app with Android Studio.
Item 6 contains is a list with three items. `Gradle Scripts` is intentionally not emphasized, to match the appearance of the Project view.

Document editing native plugin code

---

tool/plugin/test/plugin_test.dart

Skipped as the `provision` test can (and mostly will) take longer than the 30 second test timeout.
@stevemessick

skip a test on travis

---

flutter-studio/src/io/flutter/project/FlutterProjectStep.java
src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterInitializer.java
src/io/flutter/FlutterUtils.java
src/io/flutter/module/FlutterGeneratorPeer.form
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
src/io/flutter/utils/FlutterModuleUtils.java
testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java

- if we see a WEB_MODULE module type on project open, convert it to a JAVA_MODULE; display a notification when we do this
- no long check to try and convert the older FLUTTER_MODULE_TYPE module types
- when opening or creating projects, disable the `show.migrate.to.gradle.popup` toast notification (fix https://github.com/flutter/flutter-intellij/issues/1807)
Changing the module type means that we get a bit more (automatic UI) in the project wizard, in the page where we ask people for the path to the flutter sdk. They'll now also see a combo box for selecting the Java SDK to use for this project. From experimenting, it's ok if this field is not populating - we can still create Flutter projects that work.
@stevemessick for review; @jwren for FYI re: the module type change

move to using JAVA_MODULE for our module types

---

src/io/flutter/preview/PreviewView.java

- move the extract action to before the up/down actions
- don't show the icons in the context menu (they're larger than the normal menu icons)
@scheglov

move the extract action to before the up/down actions

---

src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/OpenFlutterViewAction.java

This makes the multiple app case look much better compared to having a
confusing single list of Widgets and Render Tree tabs for all the running
apps.
Any ideas on the right way to add a separator between the words Flutter Inspector and the device name?
I tried to add the Flutter icon but it doesn't show unless the icon is clicked so doesn't help.
Here I want a separator between the words
`Flutter Inspector` and `Pixel 2 XL`
The multi tab case works well. The problem is the IntelliJ UI is clever and doesn't show a single tab like a tab which looks bad as I can't see how to give the content an icon... Probably there is something obvious I'm just missing or maybe someone has a better idea than showing redundant Flutter icons.
Note that if you had multiple devices with the same name I am …

Make the Flutter Inspector use two levels of nested tabs.

---

src/io/flutter/FlutterMessages.java
src/io/flutter/run/FlutterRunNotifications.java
src/io/flutter/run/daemon/DeviceService.java

- unify some of our IntelliJ notifications under the name 'Flutter Messages' (visible in the notifications prefs)
- remove a log.error() when the flutter daemon terminates (instead, choose to notify the user)
This addresses an exception seen in analytics (instead of sending an exception to analytics, show a notification to the user).

notify the user if the flutter daemon dies

---

.travis.yml.template
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

- fix some issues were we'd manually edited the (generated) .travis.yml file
- rename `plugin gen` to `plugin generate`
- put verbiage in to make manual edits of .travis.yml slightly less likely
@stevemessick 
We should likely have a step on travis that runs `plugin generate`, and fails if there are any git diffs to `.travis.yml`. This would help prevent manual edits in the future. (this would also help with plugin.xml + plugin.xml.template)

work on regenerating .travis.yml

---

flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml
src/io/flutter/actions/OpenInAndroidStudioAction.java

This replace a previous PR after fixing a merge problem.
I think Open in Android Studio has been broken for a while. Attempting to open the .iml file as a project does not work they way you'd expect. The parent directory gets opened, not the modules defined by the .iml file.
Making this work from within Android Studio requires replacing the action object with one that does not try to spawn a new Android Studio.

Fix Open Module in AS

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/run/bazelTest/BazelTestConfig.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/bazelTest/BazelTestRunner.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.form
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationType.java

New initial "Flutter Test (Bazel)" run configuration boiler plate code; currently this new configuration is commented out in the plugin.xml and in a work-in-progress state; currently running a test works, debugging does not; by landing this initial CL follow on CLs can be smaller and incremental.

New initial "Flutter Test (Bazel)" run configuration boiler plate code

---

src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationType.java

Refactoring and cleanup in Flutter Bazel configurations: have all Flutter Bazel run configurations use the same method to determine the isApplicable return value.

Refactoring and cleanup in Flutter Bazel configurations

---

src/io/flutter/run/FlutterRunConfigurationType.java
src/io/flutter/run/test/TestConfigType.java

Refactoring and cleanup in Flutter run configurations: have all Flutter run configurations use the same method to determine the isApplicable return value.

Refactoring and cleanup in Flutter run configurations

---

src/io/flutter/view/FlutterView.java

A fix for:
```
Already disposed: Project (Disposed) conference_app
java.lang.AssertionError: Already disposed: Project (Disposed) conference_app
at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$getComponent$1(ComponentManagerImpl.java:166)
at com.intellij.openapi.application.ReadAction.run(ReadAction.java:37)
at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:164)
at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:37)
at io.flutter.view.FlutterView.lambda$restorePreviousToolWindow$1(FlutterView.java:376)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java …
```

fix a project use after dispose

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/InspectorPanel.java

This CL doesn't do much on its own but will enable efficient filtering on the device of widgets based on their creation locations.
Depends on 
https://github.com/flutter/flutter/pull/15041

Track the pub root directories on the device so that Flutter code knows which widgets were actually created on the device.

---

src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/PreviewView.java

Also performs lock/unlock when rendering starts/ends, so that changing text does not blink selection.

Select the widget under the caret after rendering is done

---

flutter-intellij-community.iml
flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterStudioProjectOpenProcessor.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml
src/io/flutter/FlutterUtils.java
src/io/flutter/project/FlutterProjectOpenProcessor.java

For Flutter projects created with Android Studio, project creation should be quiet:
- Android framework is not detected, so there is no notification to configure it
- Constant 2-sec refresh is disabled
- "Migrate to Gradle" is not suggested
Opening a Flutter project created in IntelliJ:
- Constant 2-sec refresh is disabled
- "Migrate to Gradle" is suggested only first time the first time a project is opened -- `FlutterUtils.disableGradleProjectMigrationNotification()` is not run until after the notification is displayed, but does work for subsequent openings
That last item needs further work. The user won't see the prompt twice, even if no action is taken, but they should not even see it once. I think it is a problem that needs to be solved in IntelliJ.

Index less

---

src/io/flutter/run/bazel/BazelFields.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- flip the meaning of the preview dart 2 flag (fix https://github.com/flutter/flutter-intellij/issues/1910)
- change the name to `Don't run applications in Dart 2.0 mode`
- some UI refactoring in the settings page

flip the meaning of the preview dart 2 flag

---

src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/RenderHelper.java

- experiment with different colors for the preview
- use the classname as a label in the widget preview
- rotate colors for different depths in the tree; sibling nodes will share the same color
- add a border to help separate adjacent widgets
Happy to iterate on this, or remove portions of the PR.

experiment with different colors for the preview

---

src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/perf/HeapMonitor.java
src/io/flutter/perf/PerfService.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewMessages.java

A work in progress but ready for iteration.
Currently enabled with a compile time flag (`PerfService. DISPLAY_HEAP_USE`) but will be promoted to a preference or menu enablement down the road.  Lots of TODOs captured in the source.
Disabled state:
Enabled:
(This is the sample app and so not a lot of heap use; nonetheless, scaling needs work and that dip is odd.)
Lots of next steps documented in the source but a few immediate ones include:
* tweaking scaling
* refactoring value caching
* adding a label for current/total heap
* handling GCs
* consolidating observatory actions into the panel (maybe into one combined over-flow style action)
@devoncarew

Heap use display initial implementation.

---

src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/perf/HeapMonitor.java
src/io/flutter/perf/PerfService.java

A follow up to https://github.com/flutter/flutter-intellij/pull/1921, some tweaks to the memory usage view:
- track and graph samples by sample time (setting us up to be able to record GC events)
- dock the view samples to the right, so the samples always grow out of the right hand side
- switch the y axis (to account for the swing coordinate system)
- add a tooltip for the memory used
@pq

some tweaks to the memory usage view

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

Tweaks to the settings page:
- rename the heap usage setting to `Display application memory usage in the Flutter Inspector`
- some re-organization of the settings page (to move more important settings higher up)
@Pq

tweaks to the settings page

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
src/io/flutter/run/bazelTest/BazelTestConfig.java
src/io/flutter/run/bazelTest/BazelTestDebugProcess.java
src/io/flutter/run/bazelTest/BazelTestFields.java
src/io/flutter/run/bazelTest/BazelTestLaunchState.java
src/io/flutter/run/bazelTest/BazelTestRunner.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationType.java

More boiler plate changes to create the FlutterBazelTest* run configuration.  The new run configuration is still disabled in the plugin.xml.

More boiler plate changes to create the FlutterBazelTest* run config

---

src/io/flutter/inspector/HeapDisplay.java

Currently defaulting to off.  When we dock on the bottom this can default to on, and/or we can be smart about available horizontal space.
@devoncarew

Add a memory use summary label to the heap display.

---

src/io/flutter/run/bazelTest/BazelTestFields.java

Pass the new flag --enable-debugging as the last parameter, after the target, in the Flutter Test (Bazel) run configuration

More incremental work for commented out Bazel test run config, new --enable-debugging flag

---

src/io/flutter/run/bazelTest/BazelTestRunner.java

BazelTestRunner$Connector JSON keys are now stored in private static final variables

More incremental work for commented out Bazel test run config, have JSON keys in final variables

---

src/io/flutter/inspector/HeapDisplay.java

Just show the the consumed heap size when displaying the label in-line:

make the heap view label more terse

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewFactory.java

- display an empty content message in the inspector if there are no apps running (`No running applications`)
- remove the behavior to restore a previous view when the last flutter app terminates
- fix an issue with the live icon badge not being removed when the last flutter app terminates

display an empty content message in the inspector

---

src/io/flutter/preview/MoveHandle.java

I tried several colors, including list/tree selection background.
Unfortunately list/tree selection colors look well for large rectangles, but not for thin lines - they are hardly distinguishable from the color we use for colors rectangle borders.

Use Color.BLUE for selection feedback.

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
flutter-studio/src/io/flutter/project/FlutterProjectModel.java
src/io/flutter/actions/OpenInAndroidStudioAction.java

`Open Android module in Android Studio` needs special handling when working with plugins. There are two Android modules, one for the plugin and another for the example app. However, opening the plugin's module directly is not useful since class paths are not set correctly. Therefore, always open the module defined by the example app when editing Android modules in plugins.
There are some side-issues here. We don't want to display the Gradle project-import dialog, which asks for the location of Gradle. That's solved. What isn't solved is the way the importer changes the default project creation location. After opening a module, new Flutter projects default to that modules's location for their default directory. Fixing that problem will come later.
Fixes …

Open plugin modules in AS

---

src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/PreviewView.java
src/io/flutter/preview/RenderHelper.java

It seems that users are confused otherwise, and selection in the tree is not enough, so we decided to spend some vertical space for explanation. OTOH, this header might eventually host some additional action buttons (which don't fit / not appropriate for the main view toolbar?).

Show header with the widget name above the preview area.

---

src/io/flutter/editor/FlutterCompletionContributor.java
src/io/flutter/editor/FlutterMaterialIcons.java

* adds reflective smarts for 2018.1+ APIs
* displays an empty node when Icons are not cached (rather than displaying the IconData type)

Icon completion improvements.

---

.gitignore
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

- update the various versions we build against
- build releases into a new `releases/` dir, instead of the `artifacts/` dir (which has downloaded artifacts as well)
@stevemessick

update our build versions

---

src/io/flutter/preview/render_server_template.txt

This prevents thin gaps between adjacent widgets.

Trancate each side of widget bounds separately before computing size.

---

src/io/flutter/run/daemon/DaemonConsoleView.java
src/io/flutter/utils/StdoutJsonParser.java
testSrc/unit/io/flutter/utils/StdoutJsonParserTest.java

The downside of this approach is we will not display a line until a \n occurs but that appears to be fine.
An alternate robust approach would be to use an actual streaming JSON parser to track when the JSON blocks are complete.
The previous approach failed if the JSON had an }] too early in the block and failed on json responses larger than a single call to appendOutput.

Fix bugs in StdoutJsonParser when a line spanned multiple calls to appendOutput.

---

src/io/flutter/run/bazel/BazelFields.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- add a ternary setting for the preview dart 2 flag; user's can take the sdk default, can explicitly enable it, or can explicitly disable it
- fixes https://github.com/flutter/flutter-intellij/issues/1963

add a ternary setting for the preview dart 2 flag

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewMessages.java
src/io/flutter/view/InspectorPanel.java

This avoids problematic cases where the observatory protocol allowed
requests to issue at surprising times such as right in the middle of
a flutter method call.
It is expected this fixes many hard or impossible to reproduce inspector
bugs.
To simplify the code I have also changed the semantics so that
the supportedServiceMethods set is computed before an InspectorService
is considered ready. This reduces the number of future.thenCompose
calls within the InspectorService code dealing with functionality only
exposed by the latest version.

Make InspectorService supporting issuing most of its requests over the Flutter Daemon instead of observatory.

---

src/io/flutter/preview/PreviewArea.java

@scheglov, some UI adjustments to the preview area:
- don't have a border for the area
- give the panels for widgets a left-bottom shadow
- change the label color based on the container background color
- use new colors for the panels
Let's talk in person re: the colors. I'm not committed to these ones, but want to iterate a bit on what's currently in master.

add shadows to the panels in the preview view

---

docs/testing.md

Add instructions to the test script to exercise "Open in Android Studio" and "Project Structure".

Add Project Structure to test script

---

src/io/flutter/preview/PreviewArea.java

I don't fully understand why, but otherwise the blue selection line disappears as you type in the widget.

Register the outer panel as the widget component.

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
flutter-studio/src/io/flutter/actions/FlutterShowStructureSettingsAction.java

Allow the Project Structure menu item to show up in Android Studio. Tested by building a 3.0 plugin and installing it into AS 3.0.1, and by running debuggable AS from sources.
It still uses the one that comes with IntelliJ, so needs some work, but at least it can be used to add (non-Dart) dependencies to Flutter modules. There is some code that is commented-out that will be useful in fixing up support for the new one (I hope).

Restore Project Structure editor

---

flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java

Ensure actions are only replaced for Flutter projects. Tested with 3.0.1 and 3.1 RC 3.

Add guard clause

---

src/io/flutter/editor/FlutterCompletionContributor.java

After getting the Dart sources straightened out, IntelliJ started complaining about a missing @Override. Here it is.

Add missing @Override

---

src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/PreviewView.java

- always have text in the title: `Preview` - so that title area doesn't look empty
- slight tweaks to some error messages for consistency and so they display in more narrow layouts
@scheglov

some tweaks to the preview area title

---

src/io/flutter/inspector/FPSDisplay.java
src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/perf/FlutterFramesMonitor.java
src/io/flutter/perf/HeapMonitor.java
src/io/flutter/perf/PerfService.java
src/io/flutter/view/FlutterView.java

- add a larger version of the memory view at the bottom of the inspector
- implement an FPS view
- both memory and fps views show in the toolbar if the inspector tool window is in a horizontal orientation, and at the bottom of the view if in a vertical orientation
Still left to do (likely in a follow-up) is to make the preference to show opt-out, and move it to the overflow menu of the inspector view (or similar location).

add an fps view; implement a larger memory view

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/actions/FlutterAppAction.java
src/io/flutter/actions/RunFlutterAction.java
src/io/flutter/actions/RunProfileFlutterApp.java
src/io/flutter/actions/RunReleaseFlutterApp.java
src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/perf/PerfService.java
src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/run/FlutterLaunchMode.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/OpenTimelineViewAction.java
src/io/flutter/run/SdkRunner.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/run/daemon/RunMode.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewToggleableAction.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

We're going to want to recommend that users primarily view the memory and frame perf info in the profile builds of their apps. This improves the support for `--profile` in the plugin:
- add an action to open the timeline page to the run and debug views
- support the use of the Android plugins 'profile' launch type; this allows us to use their profile button to launch (contributed next to the regular run and debug buttons). User's can still launch using the 'Run' top-level menu contributiom
- some fixes to allow us to get notifications when the debugger connection connects in profile builds
- swizzle the inspector UI so that the service extension toolbar items show up when the inspector view is shown in profile mode; also, don't contribute the regular inspector panels, and do contribute …

improve our support of --profile mode

---

src/io/flutter/run/daemon/FlutterApp.java

- add local history labels on reloads and restarts
This makes is easier for users to experiment and revert speculative changes.

add local history labels on reloads and restarts

---

src/io/flutter/preview/PreviewArea.java
src/io/flutter/preview/render_server_template.txt

Sort children outlines by their RenderObject.depth during preview.

---

src/io/flutter/run/test/TestFields.java
src/io/flutter/run/test/TestLaunchState.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterCommandStartResult.java
src/io/flutter/sdk/FlutterCommandStartResultStatus.java

This fixes https://github.com/flutter/flutter-intellij/issues/1622 by showing a meaningful error instead of `@NotNull` failure.

Make FlutterCommand.startProcess() return details to handle specific issues in clients.

---

src/io/flutter/preview/PreviewView.java

Make the text a bit shorter (so its less likely to be truncated in narrow layouts); @scheglov.

tweak the message for non-renderable widgets

---

src/io/flutter/view/MultiIconSimpleColoredComponent.java

The commit has two commits. First is a baseline forking the SimpleColoredComponent class from
IntelliJ and the second commit customizes it to support icons interleaved with text.
Interleaving icons with text is needed to show flutter properties where the description contains icon(s) where the icons are interleaved with text as in the case of the color icons shown here.

MultiIconSimpleColoredComponent

---

src/io/flutter/run/PositionMapper.java
src/io/flutter/run/bazelTest/BazelTestRunner.java

This change opens the io.flutter.run.PositionMapper for the subclass, PositionMapper.findLocalFile() is now overridable and there is not an accessor for the Project.

Re-implement the BazelPositionMapper

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/perf/PerfService.java
src/io/flutter/view/FlutterView.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

- add logic in `PerfService` (as a singleton that already has knowledge of the service protocol and events) to track the current flutter isolate (at app startup, and during full retarts)
- have it fire events for when the isolate id for the flutter app's isolate changes
- have the inspector listen to those events; fix https://github.com/flutter/flutter-intellij/issues/1806 - the inspector would assert for apps that started isolates
@jacob314, I know you have a big refactor out. If this would conflict, I can roll back the inspector portions, land the rest, and re-apply once your work lands. We will want to get your changes in soon however, so we can resolve this issue as well as https://github.com/flutter/flutter-intellij/issues/2016 (which will require some UI work in the inspector view).

handle apps with multiple isolates in the inspector

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/perf/PerfService.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/utils/EventStream.java
src/io/flutter/utils/StreamSubscription.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewToggleableAction.java
src/io/flutter/view/InspectorPanel.java
testSrc/unit/io/flutter/utils/EventStreamTest.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

Also fix race condition determining what Flutter extensions are available resulting in 
inspector toolbar buttons typically being disabled.
Also add code to be a bit paranoid about ensuring all updates to PerfService occur on the UI thread.
We could optimize that code a bit and only switch to the UI thread when about to update fields.
fixes https://github.com/flutter/flutter-intellij/issues/2071

Fix race condition in DartVmServiceDebugProcessZ

---

flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
src/io/flutter/FlutterInitializer.java
src/io/flutter/FlutterUtils.java
src/io/flutter/ProjectOpenActivity.java
src/io/flutter/actions/FlutterToolsActionGroup.java
src/io/flutter/inspections/FlutterDependencyInspection.java
src/io/flutter/preview/RenderHelper.java
src/io/flutter/project/FlutterIconProvider.java
src/io/flutter/project/FlutterProjectOpenProcessor.java
src/io/flutter/pub/PubRoot.java
src/io/flutter/sdk/FlutterPluginsLibraryManager.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/FlutterModuleUtils.java

Some follow up to https://github.com/flutter/flutter-intellij/pull/2070 - remove uses of the singleForProject* calls. These would explicitly not handle the case of multiple flutter modules per project, or multiple pub roots per module. This removes the methods, and re-writes their previous call sites to handle multiple modules/pub roots.
Also, remove some older init code in `ProjectOpenActivity.java`.
@pq

remove uses of the singleForProject/singleForModule calls

---

flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
product-matrix.json
src/io/flutter/module/InstallSdkAction.java
tool/travis.sh

Update the sources (and travis) to build all supported platforms (assuming 3.0 is no longer supported).
If you want to try this at home, be aware that the sed command on MacOS is different from linux. You need to give an empty value to the in-place option:
```bash
sed -i '' 's/npw\.model\.NewModuleModel/npw.module.NewModuleModel/' flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
```
I chose to edit the file in-place because we do a fresh check-out for each build.
An exception is thrown during project creation in Android Studio 3.2 but since that also happens when creating plain Android projects I'm ignoring it.

Update for Canary 10

---

src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
src/io/flutter/module/settings/FlutterCreateParams.form
src/io/flutter/module/settings/FlutterCreateParams.java

Checks to see if pub (the website) is reachable as a proxy for "are we online and should we expect flutter create online to work".  If it's not, it auto-toggles the offline option and adds a label decoration to make it hopefully not too subtle.
with a tooltip:
Online defaults to:
See: #1923.
@scheglov @devoncarew

Auto-toggle offline mode if we’re obviously offline (#1923).

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/DiagnosticsPathNode.java
src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/inspector/InspectorInstanceRef.java
src/io/flutter/inspector/InspectorObjectGroupManager.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/JumpToSourceActionBase.java
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/view/DiagnosticsTreeCellRenderer.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/InspectorTreeMouseListener.java
testSrc/unit/io/flutter/inspector/FlutterWidgetTest.java

My apologies on the size of this commit. The changes to InspectorPanel escalated to the point where the diff is not very readable at points.
To test locally, patch https://github.com/flutter/flutter/pull/16638 into your flutter build.
If you don't do that, everything will work and you will see the custom tree line drawing but you won't see a details-summary view.
TLDR for InspectorService is all methods that were on InspectorService are now on the InspectorService.ObjectGroup class so that lifecycles of object references can be managed and there are now tons of checks to make sure we stop chaining futures as soon as the ObjectGroup is disposed. 
The code should now never leak memory on the device instead of leaking all the objects referenced by the inspector. This is important as the …

Details subtree review

---

src/io/flutter/view/FlutterView.java

The reported issue is percolating up from the platform and *may* be fixed in the latest platform releases but this extra check should give us a little more security.
Fixes: #2103.
@scheglov @devoncarew

Fix race condition when tool window is disposed.

---

src/io/flutter/inspector/InspectorTree.java
src/io/flutter/view/InspectorPanel.java

- use the normal intellij background color for the inspector trees (otherwise we get a strange looking artifact with smaller panes that the scrollable area)
- remove the tab for "Details"
- remove a small overscroll area - I think visually this didn't pay for itself

use the normal intellij background color

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/view/InspectorPanel.java

hasServiceExstension to ensure setPubRootDirectories is called
each time an isolate is available that supports setPubRootDirectories.
There was a bug where this method wasn't called on full restart of the app.

Simplify logic calling setPubRootDirectories using

---

third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/VmOpenSourceLocationListener.java

If an flutter app dies during the process of connecting to the debugger port, the underlying websocket library we're using can throw an ArrayIndexOutOfBoundsException; this gets surfaced to the user as a crash in the plugin.
Instead, we convert the runtime error to an IOException and report that (as a failure to connect to the app instance, rather than as a plugin crash).

fix an issue with an ArrayIndexOutOfBoundsException at connect time

---

.travis.yml
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart
tool/travis.sh

build against android studio 3.2 canary 11:
- move the 3.1 import re-writing logic to dart code (from the shell script) - this let's the local build progress
- just build two products (down from three); we were building two products compatible with 2018.1
- update to the latest version of AS and the dart plugin versions they resolve against
We don't compile against the version of the Dart plugin that resolves in AS 3.2; we'll need to backport Dat plugin changes to that version, or add back in some reflection code to the Flutter plugin.
@stevemessick @alexander-doroshko

build against android studio 3.2 canary 11

---

src/io/flutter/inspector/FPSDisplay.java
src/io/flutter/inspector/HeapDisplay.java
src/io/flutter/perf/HeapMonitor.java
src/io/flutter/perf/PerfService.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/InspectorPerfTab.java
src/io/flutter/view/InspectorTabPanel.java

add a 'performance' tab to the inspector:
- add a performance tab to the inspector
- due to the number of tabs, move the toolbar to the line above the inspector tabs (otherwise we run out of horizontal space)
- in debug mode runs, have a warning in the tab about preferring to profile in profile mode
- in profile mode, show the regular inspector tabs as disabled, and have the performance tab selected by default (but keep the widgets/render/perf tab order the same)
- only poll for memory usage when the tab is active
- remove the user preference in the experimental section of the preferences UI
- fix https://github.com/flutter/flutter-intellij/issues/2016
@jacob314 @pq

add a 'performance' tab to the inspector

---

product-matrix.json

This creates a locally-built plugin that will install into IJ 2018.1 but not AS Canary 12.

Set version constraint to 2018.1 after any Android Studio canary build

---

product-matrix.json

Allow the built plugin to install into Canary 12 for testing.
@devoncarew @scheglov

Try installing into AS canary 12

---

src/io/flutter/view/DiagnosticsTreeCellRenderer.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewState.java
src/io/flutter/view/InspectorPanel.java

The highlighting of nodes shown in both trees doesn't currently provide much value.
It is now behind an option which is unchecked by default.
Maybe I should just give up and remove it completely but I think there is a good feature hiding in this highlighting. My next step is to only highlight nodes that are actually scrolled into view in the details tree. I suspect it will become much more valuable in that case but I may just be overly attached to the highlighting.
Highlighting off looks much less busy.

Make highlight nodes shown in both trees optional.

---

src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

and
"Default to Track Widget Creation (requires Dart 2.0)"
checkbox to FlutterSettingsConfigurable.
Logic is that if you create an new FlutterConfiguration you get the value
from FlutterSettings as the default.
By default both are off so users won't be forced into running the transform.
Next step is to warn users at the bottom of the inspector that it is more awesome if they check the option.

Add "Track Widget Creation" checkbox to FlutterConfigurationEditorForm

---

src/io/flutter/inspector/FPSDisplay.java

- add double buffering to the FPS display
This had been removed as part of a refactor, but the display is too flashy when frames come in from flutter.

add double buffering to the FPS display

---

src/io/flutter/actions/RunFlutterAction.java
src/io/flutter/run/FlutterLaunchMode.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkFields.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterSdk.java
third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java

some improvements to how we pass --profile and --release info to launches:
- no longer piggy-back on the  `additionalArgs` field
- instead, make sure the `FlutterLaunchMode` field is properly populated on the ExecutionEnvironment
- use that info when creating the params to `flutter run`
- and - now that that info is properly populated - don't pass in flags like `--track-widget-creation` when not run in `--debug` launches

some improvements to how we pass --profile and --release info to launches

---

src/io/flutter/run/FlutterLaunchMode.java
src/io/flutter/view/InspectorPerfTab.java

This had always been showing as 'debug' mode, even for profile runs.

fix the label for the performance view

---

src/io/flutter/console/FlutterConsoleFilter.java

- fix a StringIndexOutOfBoundsException
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967)
at io.flutter.console.FlutterConsoleFilter.applyFilter(FlutterConsoleFilter.java:124)
at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:75)
... 22 more
```

fix a StringIndexOutOfBoundsException

---

src/io/flutter/view/DiagnosticsTreeCellRenderer.java
src/io/flutter/view/InspectorColoredTreeCellRenderer.java

minor changes to the inspector label provider:
- don't bold nodes anymore - when `--track-widget-creation` is the default, all the nodes in the main inspector tree will be from user code
- in the render tree, don't show the `child: ` prefix - most nodes have this prefix, so it doesn't add much. We still show `child 1:`, `child 2:`, ...
Also, added a todo: - when using the inspector on an app, one thing I really wanted was to have a suffix on the nodes for the widgets that were defined in user code. So, `MaterialApp` - while created in my build() method - wouldn't have a suffix. But `MyCustomPage` would, and would give me an indication for where it was defined (`lib/pages/foo_page.dart`).
@jacob314

minor changes to the inspector label provider

---

src/io/flutter/editor/FlutterSaveActionsManager.java

- check for project dispose in save actions
There's some latency between when a save action is invoked and when its applied; check for project dispose during the process.
```
Project Project (Disposed) untitled_foo_123 already disposed
java.lang.Throwable: Project Project (Disposed) untitled_foo_123 already disposed
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:118)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:105)
at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:216)
at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:172)
at …
```

check for project dispose in save actions

---

src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/FlutterApp.java

- fix an issue where reload on save would stop working
If a reload-in-save was occurring when an app shut down, the bit that indicated that we were in a reload on save wouldn't get cleared. We now properly pass the exception back through the reload result Future (by terminating all outstanding daemon calls), allowing the reload bit to be cleared.

fix an issue where reload on save would stop working

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorSourceLocation.java
src/io/flutter/view/InspectorPanel.java

https://github.com/flutter/flutter-intellij/issues/2205
There were two separate bugs in how we handled windows file paths. This isn't the ideal fix but fixes the issue without requiring a fix on the flutter engine side.

Fix track-widget-creation on Windows.

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorSourceLocation.java
src/io/flutter/view/InspectorPanel.java

https://github.com/flutter/flutter-intellij/issues/2205
There were two bugs in how we handled windows file paths that were converted to URIs.
This change was already reviewed and merged into m24.

Fix track-widget-creation on Windows. (#2219)

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/editor/NativeEditorNotificationProvider.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorSourceLocation.java
src/io/flutter/view/InspectorPanel.java

Add "Flutter commands" at the top of an editor when it can be opened in a native code editor like Xcode or Android Studio. This reuses the menu actions to do all the heavy lifting, which is nice since the Android Studio version does not try (and fail) to re-launch itself.
It would be nice to make the just-opened file open for editing in the new window but I haven't figured out how to do that with either Xcode or IntelliJ yet. I'm pretty sure I can do it in the case where Android Studio opens a new Android Studio project, but I have less confidence when IntelliJ launches Android Studio or when either fires up Xcode.

Add a command bar to editors that can open in a native-code editor

---

src/io/flutter/preview/PreviewView.java
src/io/flutter/preview/RenderHelper.java
src/io/flutter/preview/RenderProblemKind.java

1. Distinction between initial start timeout and render timeout.
2. Set `FLUTTER_TEST` to `true` (required on Windows).
3. Don't call render listener for requests that were made inactive be another request.
There are still two issues on Windows.
1. The current beta does not have required `--run-forever`.
2. Hot reload does not really work - `flutter_tester.exe` (I think) keeps the `build\app.dill` file locked, so you cannot write into it during first hot reload.

Improve work of preview on Windows.

---

src/io/flutter/actions/OpenSimulatorAction.java
src/io/flutter/sdk/XcodeUtils.java

Updated to do a pre-run with `-n` as suggested by @DanTup 👍 
---
No longer relevant:
> Displays a message when the Xcode simulator is running but there are no booted devices.
> 
> 
> ![image](https://user-images.githubusercontent.com/67586/39842320-dbbc3974-539a-11e8-81cf-d135b990f5ff.png)
> 
> (**EDIT:** updated w/ word-smithed final text.)
See: #2234
@devoncarew

Launch a simulator device if none is running (#2234)

---

flutter-intellij-community.iml
flutter-intellij.iml
src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/OpenInAndroidStudioAction.java
src/io/flutter/editor/NativeEditorNotificationProvider.java

Update the label (and hover-text description) of the action for "Open in Android Studio" based on whether a file is selected (or open for editing) or not. This implements the suggestion made by @mit-mit in #2216.
Also added the dep for jsr305. It is distributed with IJ/AS so we might as well use it.
@devoncarew

Update the action label depending on selection

---

src/io/flutter/actions/ExtractWidgetAction.java

Hide's refactoring for non-dart files.
TODO: improve this further to exclude non-flutter Dart files
Fixes: #2251 
/cc @scheglov

Update extract widget refactoring visibility (#2251)

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogEntryParser.java

Follow-up from https://github.com/flutter/flutter-intellij/pull/2257#discussion_r189962211.
Stores a parser in each logger.
There's a larger refactoring we could consider that gets rid of the duplicated JSON parsing but that will take some doing.  Note that the `DaemonConsoleView` currently duplicates this parsing as well so at least this is no worse than if that option is toggled... 🙁 
Happy to chat about a bigger refactoring but this will at least solve the immediate problem in case there are multiple apps and event streams.

One parser per logger.

---

src/io/flutter/run/daemon/FlutterDevice.java

The OpenSimulatorAction passes extra args (`-n`) which isn't right for device restarts; ` XcodeUtils.openSimulator()` (with no additional args) is what we want.

Fix isOS bringToFront() on device restart.

---

src/io/flutter/logging/FlutterLogView.java

Adds a popup menu to the logging tree.
Implements a clear entry action.
(FWIW: on the fence about Clear vs. Cut vs. Delete.  "Clear all" is implemented in the default console view.)
A few more to come (`Copy` to clipboard probably up next).

Log Tree popup (and clear entry action)

---

src/io/flutter/logging/FlutterLogTree.java

Prevents cell borders from rendering on selection.
Subtle but gives the rows better continuity.
Before:
After:

Logger: no borders for selected cells.

---

src/io/flutter/settings/FlutterSettings.java

- fix an issue where the setting for `--track-widget-creation` was not persisted
@jacob314

persist the track-widget-creation setting

---

resources/liveTemplates/flutter_miscellaneous.xml

- remove the `stanim` template (generally, I suspect that this one is not used in comparison to our two others)
@scheglov, /cc @stevemessick

remove the stanim template

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java

In the spirit of starting with the simplest possible thing, this migrates logger updates to prefer full reloads on update (leading to eventual consistency) rather than smart appends.
Still a WIP and some tuning and experimenting to do but in the meantime, this paves the way for some filtering UX prototyping.
/cc @scheglov

Migrate logger updates to a model of eventual consistency.

---

src/io/flutter/run/FlutterReloadManager.java

We're seeing lots of unhandled errors from daemon protocol commands (https://github.com/flutter/flutter-intellij/issues/2319). I can't tell if they are all from a certain command, or general errors in the protocol encoding. In any case, this PR adds better error handling for the reload/restart commands.

handle reload errors

---

flutter-studio/README.md
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/NewFlutterModuleWizardFixture.java
flutter-studio/testSrc/io/flutter/tests/gui/NewModuleTest.java

@devoncarew Canary 18 introduces more API changes. This fixes all known issues for that, in a way that continues to work in 3.1.
Hopefully, the `@SuppressWarnings("override")` will let us easily find all those places that need annotations once 3.2 goes stable.

Clean up the quick fixes in build-17

---

src/io/flutter/preview/PreviewView.java

Fixes https://github.com/flutter/flutter-intellij/issues/2330

Ignore non-Dart files completely in setSelectedFile().

---

src/io/flutter/logging/FlutterLogFilterPanel.form

The hardcoded background color introduced in #2361 doesn't play nice w/ darcula:
These returns us to the default, which fixes it.
/cc @stevemessick  @quangson91

Fix log filter background

---

src/io/flutter/inspector/FlutterWidget.java
src/io/flutter/utils/AsyncRateLimiter.java
src/io/flutter/utils/AsyncUtils.java
src/io/flutter/utils/animation/Curve.java
testSrc/unit/io/flutter/testing/Testing.java
testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java
testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java

4 actual test failures were hiding behind the 21 tests that failed to run.
All the existing changes to test files I believe reflect cases where we legitimately had broken tests and just didn't know because they weren't really running.
The two MainFileTests still fail but I am hoping that now that the complete failure at test startup is gone, someone else with more context on how these two tests are trying to work will be able to fix them quickly.
Stack trace for those two failing tests which may indicate a logic issue or may just indicate more configuration we need to do to get a fully functional test fixture:
```
com.intellij.openapi.util.TraceableDisposable$DisposalException: Virtual pointer 'file:///private/var/folders/n5/d160x2xj2095jng193ptjjl00025bq/T/unitTest835/root' hasn't been …
```

Fix 19 of the 21 failing unittests.

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java

Largely a structural refactoring to set us up for controlling row theming (e.g., foreground and background colors) in a rational way.  It did turn out that the way that renderers were getting mapped to active columns after a hide was incorrect so this does in fact fix that.
(Previous to this fix the hyperlink support was missing because the message row was wrongly getting rendered as simple text.)
Apologies for the churn in review; this is largely mechanical.  My hope is to land this one and put the more interesting changes in a follow-up where they'll be more obvious.

Log tree rendering refactor

---

src/io/flutter/logging/FlutterLogFilterPanel.form
src/io/flutter/logging/FlutterLogFilterPanel.java

Sort log level first.
I *think* it looks a bit better and makes semantic sense... it's also consistent w/ logcat (for what that's worth).
/cc @quangson91

Reorder level and text filters

---

src/io/flutter/logging/FlutterLogFilterPanel.java

Improves default rendering by padding items.
Before:
After:
Also leaves the door open for styling.  (Possibly using the level colors?)
/cc @quangson91 @scheglov

Add level combo renderer

---

src/io/flutter/logging/FlutterLogFilterPanel.java

Makes NONE less loud.
* lowercases
* presents no label when selected
Fixes: #2392 
/cc @devoncarew @quangson91

Mute “none” log level presentation

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
resources/colorSchemes/FlutterLogColorSchemeDefault.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/logging/FlutterLogColorPage.java
src/io/flutter/logging/FlutterLogConstants.java
src/io/flutter/logging/FlutterLogView.java

Issue: https://github.com/flutter/flutter-intellij/issues/2200
add flutter log color setting page
**TODO**
Screenshot

add flutter log color setting page

---

src/io/flutter/console/FlutterConsoleFilter.java

Before:
After:
/cc @scheglov @stevemessick

Fix console external file links w/ leading spaces

---

resources/liveTemplates/flutter_miscellaneous.xml

Howdy, y'all! I've been doing more and more animations, and thought the `stanim` snippet from VSCode was pretty cool. Same kinda thing with InheritedWidgets...
I've added two new live templates to quickly stub out the boilerplate for these classes.
They will produce the following code.
```dart
class Anim extends StatefulWidget {
@override
_AnimState createState() => _AnimState();
}
class _AnimState extends State<Anim> with SingleTickerProviderStateMixin {
AnimationController _controller;
@override
void initState() {
_controller = AnimationController(vsync: this);
super.initState();
}
@override
void dispose() {
_controller.dispose();
super.dispose();
}
@override
Widget build(BuildContext context) {
return Container();
}
}
```
```dart
class Inher extends InheritedWidget {
const Inher({
Key …
```

Add InheritedWidget and Stateful Widget with Animation live templates

---

src/io/flutter/sdk/FlutterLibraryManager.java
src/io/flutter/sdk/FlutterPluginsLibraryManager.java

Moves the pure library management code out of FlutterPluginsLibraryManager into an abstract superclass. The intent is to define a new subclass, specific to Android Studio, to manage discovered Android Libraries.
Lots of copy-paste-delete going on. Lightly tested.

Refactor FlutterPluginsLibraryManager

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java

Issue: https://github.com/flutter/flutter-intellij/issues/2431
+ apply other attributes for log color from setting page
Notes: some attributes are not working.
// cc @pq for review.
**Screenshots.**
----------
----------

apply other attributes for log color from setting page

---

src/io/flutter/logging/FlutterLogTree.java

Issue: https://github.com/flutter/flutter-intellij/issues/2402
+ support hyperlinks in flutter console log
Use `DartConsoleFilter` & `UrlFilter` to support hyper link stacktrace & url in log console.
Notes: stack trace can clickable, but `url` can't click to open in the browser.
Screenshot:
// cc @pq please take a look in next week :)

support hyperlinks in flutter console log

---

src/io/flutter/logging/FlutterLogPreferences.java

Following up on this question from @quangson91:
> @pq, I have a question. Why don't we enable show color by default?
(For me, if the log levels like warning/shout => we should be coloring them. It is better for eyes to recognize).
I tend to agree.  Especially since, like logcat, we only color severe and shout out of the box:
Related to: #2457.
/cc @quangson91 @devoncarew

Default log coloring to on

---

src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/utils/AndroidUtils.java

Further validation of android package names.
Bad package names spell trouble and are winnowed out in standard Android project creation.
Follow-up from #2468. 

Port ADT package name validation logic.

---

src/io/flutter/FlutterInitializer.java

When running from sources, like in a debugger, there's no reason to warn that Canary versions are not supported.
@devoncarew @pq @terrylucas

Stop complaining about Canary versions while debugging

---

tool/plugin/lib/plugin.dart

Aside from a couple reformatter lines, this just adds an import for the IconUtil class. Apparently, when the references to that class were removed its import was left behind. It was deleted in the latest reformat.

Add import for IconUtil

---

src/io/flutter/logging/FlutterLogTree.java

as for suggestions of @jacob314, I removed `volatile` as it unnecessary.
Ref: https://github.com/flutter/flutter-intellij/commit/6c968f95ac54511d9deffdb244733d9946065941#r29766875
// @jacob314 please take a look!

remove unnecessary volatile keyword

---

src/io/flutter/server/vmService/frame/DartVmServiceEvaluator.java

Fix race condition that sometimes occurs when the app is restarted resulting an easily avoidable error in the IntelliJ console.

Handle the device being disconnected more gracefully.

---

src/io/flutter/module/FlutterProjectType.java
src/io/flutter/module/settings/ProjectType.java

To add back when add-top-app is more fully baked.
Note this was showing up in the project creation UI.
Before:
After:

remove “module” project type

---

src/io/flutter/module/settings/ProjectType.java

@devoncarew @jwren 
The new 'Import Module' item should not appear in the Project type list for project creation.

Remove import from project type list

---

src/io/flutter/logging/FlutterLogTree.java

Reason: after apply row filter, the selected path will not correct. (because, some row is hidden by row-filter).
Screenshot:
**Before fix:**
**After fixed:**
// cc @pq, @devoncarew  for review.
Thanks!

correct get selected log for row filter

---

src/io/flutter/logging/FlutterLogTree.java

Assuming clear entries is not set for reloads and/or restarts, add a marker in the log view to delineate reloads and restarts.
This is maybe a bit subtle but could serve as a jumping off point for future iteration.
See: #2458

visuals for reload/restart entries

---

src/io/flutter/logging/FlutterLogEntry.java

Fixes the case where reloads / restarts are "Initializing" (vs. "Performing").
(Should have cleared the log -- and with this fix will!)

improve restart/reload detection

---

product-matrix.json
tool/plugin/lib/plugin.dart

Needed to fix a few places where dynamic was causing problems. Also changed the "filesToSkip" list to accept directories, and to allow its entities to be nonexistent. That means it (hopefully) works both before and after Terry's profiler code is in. For good measure, added the "filesToSkip" for his PR.
@pq @devoncarew @jacob314 @terrylucas (gee, did I omit anyone?)

Plugin dart2

---

src/io/flutter/inspector/HeapDisplay.java

Without this tweak you get a bunch of errors in IntelliJ debug mode about concurrent list modification.

Fix threading bug in HeapDisplay

---

src/io/flutter/sdk/FlutterCommand.java

Turns out saving files before running a Flutter command is more complicated than I thought.
Need to revert that change and push another build.

Revert save files before command

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/logging/LoggingChannel.java
src/io/flutter/run/daemon/FlutterApp.java

Conditionally (if `ENABLE_LOGGING_CHANNELS` is toggled) contributes a simple UI for querying, enabling and disabling log channels as contributed by the [logs package](https://github.com/pq/logs).
/cc @devoncarew @jacob314

[experimental] logging channel UI

---

.idea/runConfigurations/Flutter_Plugin.xml

Adding this means we can use the Swing UI Inspector which is very handy.
Thanks @terrylucas  for pointing this out.

add -Didea.is.internal=true flag so that the Swing UI inspector can be used to debug the plugin

---

src/io/flutter/run/ObservatoryFile.java
src/io/flutter/server/vmService/VMServiceManager.java
src/io/flutter/server/vmService/frame/DartVmServiceStackFrame.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/InvokeConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/BoundVariable.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Breakpoint.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/ClassObj.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Context.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/ErrorObj.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Event.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Field.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Flag.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Frame.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Func.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Instance.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceRef.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Isolate.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Message.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Obj.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Script.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/SourceLocation.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/SourceReportRange.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Stack.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/UnresolvedSourceLocation.java

- commit the latest version of the service protocol library (this version returns nulls for some fields, and documents which ones)
- update to some signature changes from the new library version
- be tolerant of nulls from Isolate.extensionRPCs
(fix https://github.com/dart-lang/vm_service_drivers/issues/185)
- handle cases where `Script.source` is null (this is new behavior in the VM, and happens for some `dart:` sources); fix https://github.com/flutter/flutter-intellij/issues/2617
The bulk of these changes are from the auto-generated protocol library.
@jacob314 @stevemessick

handle nulls from the service protocol

---

flutter-studio/src/io/flutter/actions/ConnectAndroidDebuggerAction.java
resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml
src/io/flutter/actions/AttachDebuggerAction.java
src/io/flutter/actions/FlutterCleanAction.java
src/io/flutter/actions/FlutterDoctorAction.java
src/io/flutter/actions/FlutterPackagesGetAction.java
src/io/flutter/actions/FlutterPackagesUpgradeAction.java
src/io/flutter/actions/FlutterSdkAction.java
src/io/flutter/actions/FlutterUpgradeAction.java

- Add the attach button to the toolbar in IntelliJ (and AS). (We promised to do this.)
- Change the AS-specific action class to hide the Android attach button in Flutter projects.
- Change the name of the button to `Attach debugger to embedded Flutter process`
- API change: add DataContext parameter
/cc @matthew-carroll

Attach debugger button for IntelliJ

---

.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/test/plugin_test.dart

- drop support for 2017.3 (and AS 3.1)
I believe it's ok to drop support for these two platforms now.
@jwren @stevemessick @DaveShuckerow

drop support for 2017.3 (and AS 3.1)

---

src/io/flutter/server/vmService/VmServiceWrapper.java

Fixes #2693 
As the comment at the top of this code block says, there are two paths to this code. One of them already has a read context. The other didn't.

Use read context to init debugger

---

src/io/flutter/logging/FlutterLogTree.java

Missed this on the last pass... (`clearEntries` clears the model and clears selections too).
Sorry for the noise!
/cc @jacob314

clear selections on reload

---

src/io/flutter/inspector/EvalOnDartLibrary.java
src/io/flutter/server/vmService/VmServiceConsumers.java
src/io/flutter/server/vmService/VmServiceWrapper.java
src/io/flutter/server/vmService/frame/DartVmServiceValue.java

- remove an older (and not needed, since consolidating the debugging library into the Flutter plugin) use of reflection for vmService.evaluate()
- switch from calling `evaluate` to get the toString() value of objects when debugging to `invoke`
@jacob314

remove older uses of reflection

---

.travis.yml
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

Had to re-create this four day old PR because it was too out of date to manage.
@pq @devoncarew @terrylucas @jacob314 @keertip 
- Update the plugin tool to build for AS 3.3 beta.
- Patch sources to match API changes in FlutterProjectSystem and FlutterStudioMonitorStageView
- Generate new build files
- Delete dead code for building AS 3.1
After merging this PR you'll need to update your Android Studio dependency to use 3.3; the 3.2 version won't compile anymore unless using the plugin tool.
You won't be able to build using the plugin tool until the new Android Studio artifact is uploaded to the cloud. I'll do that next week, but if someone wants to do it sooner, the file name is android-studio-ide-182.5073496-linux.zip and can be downloaded from the Android Studio preview site.
@terrylucas …

Build 3.3beta for M30 release

---

tool/plugin/lib/plugin.dart

Following up a review comment from @jacob314, this changes the way edited files are managed during a build. It is less likely that a file will be left in its edited state.

Keep edited files in a Map

---

src/io/flutter/utils/EventStream.java
src/io/flutter/view/BoolServiceExtensionCheckbox.java

The main problem was addChangeListener was used to listen for checkbox
changes instead of addActionListener.
The problem with using addChangeListener is it fired on mouse-over
and programatic value changes as value changes triggered by user interaction which
is all we care about.
Added some defensive changes to EventStream as well to prevent possible race
conditions for cases of many repeated value changes.

Fix flickering bug for BoolServiceExtensionCheckbox.

---

flutter-intellij-community.iml
flutter-intellij.iml
flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
product-matrix.json
tool/plugin/lib/plugin.dart
tool/plugin/test/plugin_test.dart

Update build to produce a single zip that works in IJ EAP and AS Canary IDEs.
After this is merged source builds need to use Dart plugin sources on branch 183.2153 of intellij-plugins. The Android Studio sources are sync'd to build 5081642.
@terry @jacob314 @devoncarew

Build for EAP and Canary

---

README.md
docs/testing.md
src/io/flutter/actions/InstallSdkAction.java

Flutter setup page url is changed to "get-started".
Please review this below. Is it right?
https://github.com/flutter/flutter-intellij/compare/master...ChangJoo-Park:master#diff-5a61e9f9f0b3221e1b12f6e24cf94ed4R153

Fix flutter setup links

---

resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml
src/io/flutter/FlutterInitializer.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterPerfViewFactory.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorMemoryTab.java

- move the memory tab into its own tool window
This splits the memory tab out of the Inspector and moves it into its own tool window. It also makes it only available contributed in Android Studio; we can adjust that once the charting lib is available in IntelliJ. The functionality of the memory view should be unaffected.
The tool window is named `Flutter Performance`, but we can noodle on alternative names (once we ship it however we should stay consistent). Note that this work is not for the current (M30) release.

move the memory tab into its own tool window

---

src/io/flutter/dart/DartSyntax.java
src/io/flutter/editor/FlutterEditorAnnotator.java
testSrc/unit/io/flutter/bazel/WorkspaceTest.java
testSrc/unit/io/flutter/editor/FlutterEditorAnnotatorTest.java
tool/colors/colors.dart

- update the colors icon provider to the latest from package:flutter
- fix some regressions in identifying in-line colors and icons due to optional `const`
- add tests for the editor annotation provider (for icons and colors)

update the color icon provider, and fix some regressions due to opt. const

---

src/io/flutter/run/FlutterDebugProcess.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/ToolbarComboBoxAction.java

The existing toolbar combobox was throwing an exception when not under darkula as a null border wasn't supported and using an empty border resulted in button ui we didn't want.
I couldn't figure out a way to fix this without forking the base ComboBoxAction class so we could customize things a bit. The first patch in the CL is the baseline for the ComboBox class. The second patch is the actual change.
As a bonus reduced the space between the icon and the text and changed the arrow icon so it is black instead of grey which matches other similar ui in intellij better.
We should test this under windows 10 at some point to make sure it looks ok.
Here is what the new UI looks like both dark, light, and when disabled.

Fix buttons

---

flutter-studio/src/io/flutter/module/FlutterModuleImporter.java

The module project template is not going away anytime soon. The app template does not work for importing into an Android app so don't allow it to be selected.
@pq

Disallow importing app templates into Android apps

---

src/io/flutter/logging/FlutterLogColors.java

It's on my short-list to make the category colors theme better.  This cooling off of the runtime magenta is just a first (and interim) step while I'm thinking of it...
/cc @jacob314

cool runtime label under light theme

---

src/io/flutter/sdk/FlutterSdk.java

Fixes: #2763.
I can't track down why it would happen but in at least this reported case the JSON coming back from the call to `flutter config --machine` is invalid.  In the absence of a fix on the flutter tools side, this guards against it.

guard against bad config json (#2763)

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/utils/JsonUtils.java

Adds a badge to log entries that have associated data.
**Note:** this is not currently user facing since only logging events produced by `package:logs` will associate JSON data with entries.
(Also: this is certainly not pressing to land; just playing around over ☕️.)

badge log entries w/ associated data

---

src/io/flutter/view/FlutterView.java

Fixes: #2762.
Confirmed this works in 2018.3 and AS 3.2.1.
Happy to add a check for earlier versions if you all think it's prudent?

Restore ‘no app running’ inspector message (#2762)

---

src/io/flutter/inspector/WidgetPerfPanel.java

Prevents perf tips from being clipped:
Now the layout can extend as much as it needs to (see exaggerated example):

Remove size specification from WidgetPerfPanel. 

---

src/io/flutter/FlutterConstants.java
src/io/flutter/FlutterErrorReportSubmitter.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/actions/RestartFlutterApp.java
src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/preview/RenderHelper.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/utils/JsonUtils.java
testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java

Recognize Dart stack traces. Send error reports to the Flutter repo when they are recognized as such. If we can't be sure what we have, but we think it is a Dart stack trace, send it to this repo. Unfortunately, DaemonApi was not properly arranged so the methods got moved around when it was reformatted. The main change in it was fetching the Dart stack trace at line 188.
Fixes #2657
Sample report (with simulated error):
[bug-report.txt](https://github.com/flutter/flutter-intellij/files/2567831/bug-report.txt)
@devoncarew

Report dart errors

---

src/io/flutter/inspector/FPSDisplay.java
src/io/flutter/inspector/FrameRenderingDisplay.java
src/io/flutter/view/InspectorPerfTab.java

- Rename chart to more accurately reflect functionality.
- Label target line
- Improve existing tooltips and new ones
- Move FPS calculation outside of chart

Improve UI for Frame Rendering Graph (formerly called FPS).

---

src/io/flutter/view/FlutterView.java

Perhaps you are running canary IntelliJ? Either way, the version without underlines is fine so lets just use it everrywhere.

I'm seeing this bug in IntelliJ as well as Android Studio on my machine.

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/InspectorSourceLocation.java
src/io/flutter/perf/DocumentFileLocationMapper.java
src/io/flutter/perf/EditorPerfDecorations.java
src/io/flutter/perf/EditorPerfModel.java
src/io/flutter/perf/FileLocationMapperFactory.java
src/io/flutter/perf/FilePerfInfo.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/perf/FlutterWidgetPerfManager.java
src/io/flutter/perf/Location.java
src/io/flutter/perf/PerfMetric.java
src/io/flutter/perf/PerfModel.java
src/io/flutter/perf/PerfTipRule.java
src/io/flutter/perf/SlidingWindowStats.java
src/io/flutter/perf/SlidingWindowStatsSummary.java
src/io/flutter/perf/SummaryStats.java
src/io/flutter/perf/WidgetPerfLinter.java
src/io/flutter/perf/WidgetPerfListener.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

Refactor of FlutterWidgetPerf so that widget names are always available instead
of only available when displaying gutter icons. The problem was we were calculating widget names for given offsets
when generating the EditorPerfDecorations instead of keeping a global cache
of widget names. The new approach is more efficient and needed for
work to display a table of the most frequent widget rebuilds.

Refactor of how metrics are calculated to make adding additional metics easier.

---

src/io/flutter/view/InspectorMemoryTab.java

- also handle `NoClassDefFoundError` in the memory view (for the case when it's opened in IntelliJ)
- fix https://github.com/flutter/flutter-intellij/issues/2774
@terrylucas @jacob314

handle NoClassDefFoundError in the memory view

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/FlutterBundle.properties
src/io/flutter/sdk/FlutterSearchableOptionContributor.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

Makes Flutter settings appear when a search term is entered in Settings/Preferences. As a side-effect it also moves strings from a form into a bundle.
Thanks to @alexander-doroshko for finding SearchableOptionContributor.
Fixes #2309

Make Flutter settings searchable

---

flutter-studio/src/io/flutter/profiler/FilterLibraryDialog.java
flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
flutter-studio/src/io/flutter/profiler/FlutterStudioProfilersView.java

Added grouping of all package:flutter to one entry in the filter dialog "package:flutter/*".
Fixed bug initial selections didn't include all libraries (some libraries have an empty name only URI).
Fixed allLibraries to include non-name libraries.
Fixed bogus error that dart:* not a library (it isn't and was skipped (re-mapped to all dart:* libraries).

Added package:flutter/* for filter dialog and fixed a few bugs.

---

src/io/flutter/inspector/WidgetPerfTipsPanel.java
src/io/flutter/perf/SlidingWindowStatsSummary.java
src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/InspectorPerfTab.java
src/io/flutter/view/WidgetPerfSummaryView.java
src/io/flutter/view/WidgetPerfTable.java

Several and various UI and layout tweaks to the perf tab. A few of these changes could probably use discussion; happy to have feedback about them.
- have the `profile mode` text extend across the full with of the tool window (instead of just across the left hand component)
- have the splitter default to a 50/50 split (instead of 60/40)
- re-order and re-group the toolbar actions
- the FPS display now consistently displays one decimal point (`60.0`)
- change to always having the rebuild stats area displayed; I think this will facilitate discovery of the feature, and won't really negatively impact the area available to the other UI (FPS display)
- unify the use of titled borders around the various areas
- move the enablement of the rebuild stats table into the rebuild stats panel
- remove …

various UI and layout tweaks to the perf tab

---

src/io/flutter/perf/EditorPerfDecorations.java
src/io/flutter/perf/EditorPerfModel.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/view/WidgetPerfTable.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

Add spinning icons to table indicating which rebuilds are actively occurring.
Show icons in source file when mousing over table.
Fix bugs in logic navigating to source location of the selected row.

Add spinning icons to table.

---

src/io/flutter/server/vmService/VMServiceManager.java

Prevents a crash in the framework. 
Crash was occurring if the Performance Overlay or Hide Debug Mode Banner settings were enabled before performing a hot restart.

Add service extensions after first frame event received.

---

docs/testing.md

We probably need to add even more.
Note that the instructions for testing modules don't work right now because module support needs work.
@devoncarew @jacob314 @pq

Add instructions to test modules and inspector

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

- adjust the order of the Flutter `Run` menu items
@stevemessick

re-order the Flutter Run menu items

---

pubspec.yaml
src/io/flutter/FlutterBundle.properties
src/io/flutter/FlutterConstants.java
tool/grind.dart
tool/travis.sh

add url checking to the build
* moves action URLs into bundle
* adds grind task that checks URLs in bundle
* adds grinder call to travis build
Fixes: #2819 
a few things to consider:
* I’m using a heuristic to grab URL bundle properties; we could be more eager
* where in the build this happens is open to debate — perhaps we ultimately should have a separate bot that does this and `./bin/plugin lint` ? dunno.

add url checking to the build

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/InspectorPerfTab.java
src/io/flutter/view/WidgetPerfTable.java

Polish InspectorPerfTab UI moving warning about debug mode closer to the FPS
display. Added description of what widget rebuild indicators are and moved some text around and made the fps warning a bit scarier.
The NPE fixes are targeting an error seen in a usability study but I haven't been able to reproduce the issue locally with either a device or an emulator so I am not 100% confident in the fix.
Tweaked UI:

Fix a couple NPE edge cases.

---

src/io/flutter/view/InspectorPerfTab.java

The UI isn't that useable when a small vertical width is set and could use some polish but is good enough for now.

Fix Split Mode resize issue.

---

src/io/flutter/FlutterUtils.java
src/io/flutter/run/SdkRunner.java
src/io/flutter/run/bazel/BazelRunner.java

A band-aid to address the re-run behavior regression in 2018.3.  
Additionally I wonder if this couldn't be fixed when we create our initial launch configs?  (Although that doesn't help with migration.)
Fixes: #2875.

force "allow running in parallel"

---

src/io/flutter/sdk/FlutterSearchableOptionContributor.java

Adds the Preference search strings to the database searched by `Help > Find Action`.
I didn't include this in M31 because I wasn't comfortable with it, but it looks safe enough. We'll have some time to check it out before M32.

Make Find Action search prefs

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
src/io/flutter/view/FlutterPerfView.java

Added checkbox "Disable Memory Profiler" to the Flutter Settings General group box.  By default memory profiling is enabled.  If this checkbox is enabled then memory profiling will not startup (in case there's any problems).

Added ability to turn off Memory Profiling, by default its enabled.

---

src/io/flutter/module/FlutterGeneratorPeer.java

(Note that **Next** is only enabled; it will not advance or throw errors.)
Fixes: #2913.

require sdk for project creation (#2913)

---

src/io/flutter/server/vmService/VMServiceManager.java
src/io/flutter/server/vmService/VmServiceWrapper.java

not show up as available on Flutter attach.
Fix race condition causing the profile rebuild extension not to be
reported when calling attach.
We now query the flutter framework directly to verify that a frame
has been drawn in the case of attach.
Also cleaned up locking logic for existingExtensions and
firstFrameEventReceived to be paranoid.

Fix bug where the profile widget rebuilds service extension does

---

src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/server/vmService/frame/DartVmServiceStackFrame.java

- trim prefix text on dart stack frames (`[Unoptimized] `)
- move to using a non-deprecated icon; I'll need to see whether this compiles on our oldest IDEs before committing this PR
- unrelated, but remove the check for `supports.pausePostRequest` - this has been in VMs for a very long time now
@stevemessick for review

trim unoptimized text from stack frame names

---

flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
src/io/flutter/sdk/AbstractLibraryManager.java

Enables code completion for Java and Kotlin. This is ready for review now.
- Gradle sync on start-up and whenever project roots are modified
- After sync, get Android libraries and add to Flutter project
- Add library dep to Android module for each library
- Add dep from Android module to Flutter module so the libraries can be found
Still has a couple TODOs, which I'll work on next. Some are noted in the code. Also:
- Make the Gradle sync run in the background
- See if other Android-like facets should be included (AndroidModuleLibraryManager line 153)
@devoncarew I had to refactor some of the library management code you added a while back.

Add Android libraries to Flutter project

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
src/io/flutter/module/settings/ProjectType.form
src/io/flutter/module/settings/ProjectType.java
src/io/flutter/samples/FlutterSample.java
src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/index.json
src/io/flutter/sdk/FlutterCreateAdditionalSettings.java

Adds support for specifying sample content in new project creation in IDEA.
Note that index format (and location) is still under development (see https://github.com/flutter/flutter/issues/25461 and https://github.com/flutter/flutter/pull/25515) so this works from a local copy that reflects the stable samples in 1.0.
Fixes: #2974
@stevemessick 
fyi @DanTup

Support for creating projects w/ sample content.

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogEntry.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/logging/util/LineInfo.java
src/io/flutter/logging/util/LineParser.java
src/io/flutter/logging/util/StyledText.java
src/io/flutter/run/daemon/FlutterApp.java
testSrc/unit/io/flutter/logging/util/LineParserTest.java

Adds basic ANSI color escape handling and generally reworks when/how we calculate styles for log entry rendering.
High points:
* supports 8 bit colors and styles that correspond to the error reporting presentation improvements being exploring w/ @InMatrix (fixes: #2552)
* disables auto-scroll on widget errors (fixes: #3033)
* parses style information on entry receipt once (and not on every rendering)
Example output (w/ a version of Flutter patched to include ansi colors):
While the render fixes are a definite performance improvement, there's still some more work there (see #2776 for example) and the styling will evolve to track requirements driven by framework changes but this is complete enough I think to not hide behind a flag.  Happy to reconsider if anyone feels differently though.  👍 …

Log entry ansi color support (and styling re-work)

---

flutter-intellij-community.iml

Fix a compilation error in FlutterSampleManager.

Add org.apache.commons.io.IOUtils to the classpath for the source build

---

src/io/flutter/logging/FlutterLogFilterPanel.form
src/io/flutter/logging/FlutterLogFilterPanel.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterTreeTableModel.java

Restores work from @quangson91 based on user feedback.
(Level checking has been updated to prefer ordinal value checking over regexps for performance reasons but otherwise this is substantially the same as what was reverted in https://github.com/flutter/flutter-intellij/pull/2686.)
/cc @jacob314  @quangson91 
Fixes: #3039

restore log level combo

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml

Make sense to have it ```⌥⌘W``` since all extracting methods starts with ```⌥⌘```

add keyboard shortcut for widget extraction

---

src/io/flutter/run/ObservatoryFile.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Element.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Script.java

- handle situations where `Script.tokenPosTable` can be null (now possible w/ the VM sending null for dart: sdk sources)
- fix https://github.com/flutter/flutter-intellij/issues/2938
This in includes some upstream null handling changes in the vm_service_drivers repo.

handle cases where script.tokenPosTable is null

---

src/io/flutter/utils/FlutterModuleUtils.java

- guard against disposed when querying project type
- fix https://github.com/flutter/flutter-intellij/issues/3046
This could happen when opening multiple windows when first trying Flutter out, closing one, and then agreeing to report analytics info.

guard against disposed when querying project type

---

src/io/flutter/run/test/FlutterTestLineMarkerContributor.java
src/io/flutter/run/test/TestConfigUtils.java

- fix an issue with escaped test names; we unescape them now (the test execution later re-escapes any necessary chars, like double quotes)
- fix https://github.com/flutter/flutter-intellij/issues/3058
@pq

fix an issue with escaped test names

---

src/io/flutter/inspector/InspectorService.java
src/io/flutter/logging/FlutterLog.java
src/io/flutter/perf/FlutterWidgetPerfManager.java
src/io/flutter/preview/RenderHelper.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/server/vmService/ServiceExtensions.java
src/io/flutter/server/vmService/ToggleableServiceExtensionDescription.java
src/io/flutter/server/vmService/VMServiceManager.java
src/io/flutter/view/BoolServiceExtensionCheckbox.java
src/io/flutter/view/DebugPaintAction.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewToggleableAction.java
src/io/flutter/view/InspectorPerfTab.java
src/io/flutter/view/PerformanceOverlayAction.java
src/io/flutter/view/ShowPaintBaselinesAction.java
src/io/flutter/view/TimeDilationAction.java
src/io/flutter/view/TogglePlatformAction.java

Service extension data is now stored in ServiceExtensions.java. Button text now reflects extension state.
Performance overlay example:
When the extension is enabled, the tooltip will now read "Hide Performance Overlay".
When the extension is disabled, the tooltip will now read "Show Performance Overlay".
This applies to all the service extension buttons, including those with visible text in the inspector dropdown menu.

Refactor service extensions and set button text based on extension state.

---

src/io/flutter/view/InspectorPerfTab.java

- shorten message for debug mode perf disclaimer (it was very long long and didn't lay out well in the UI)
- fix a likely bug in terms of when to show the perf table
older UI:
update:

shorten message for debug mode perf disclaimer

---

src/io/flutter/server/vmService/VMServiceManager.java

Set service extension states accordingly upon event received. This keeps service extension states in sync with other debugging tools.

Listen for ServiceExtensionStateChanged events.

---

src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/inspector/JumpToSourceActionBase.java
src/io/flutter/view/InspectorPanel.java
src/io/flutter/view/InspectorTreeMouseListener.java

and add a convenience method to InspectorService to create a
Future<ObjectGroup> directly.
This unblocks letting the logging view display DiagnosticsNode structured
errors before the InspectorService is available.
With async await and FutureOr, this would have taken 20 lines of code and 10 minutes instead of an hour and 100 lines of code.

Refactor DiagnosticsNode to accept a Future<ObjectGroup>

---

README.md

Following up from https://github.com/flutter/flutter/issues/16930#issuecomment-450203835, `flutter doctor` now does the correct reporting so this issue is stale and should be removed.
Cheers @neiljaywarner for the catch!

remove stale cocoapods issue from "known issues"

---

src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogColors.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/run/daemon/FlutterApp.java
testSrc/unit/io/flutter/logging/text/LineParserTest.java
testSrc/unit/io/flutter/logging/text/StyledTextTestUtils.java

Basic Flutter Error extension event handling.
As a next step we'll want to do something sensible w/ the parsed `DiagnosticsNode` pending UI exploration in the devtools version.  In the meantime this proves out inspector service initialization and interaction.
/cc @jacob314

Basic Flutter Error extension event handling.

---

.travis.yml
CHANGELOG.md
flutter-studio/flutter-studio.iml
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/profiler/FlutterStudioProfilers.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart
tool/plugin/pubspec.yaml
tool/plugin/test/plugin_test.dart

@devoncarew @pq @jacob314 @terrylucas @kenzieschmoll @DaveShuckerow
/cc @DanTup @keertip 
This gets us ready for building M32 for AS 3.3 stable, AS 3.4 beta, AS 3.5 canary, and IJ 2018.3. (IJ 2019.1 is still to come.)
The change log is a bit excessive. I was unfamiliar with most of the work so I just added a line for every commit in the git log. We ought to have a convention to identify user-facing changes so we don't need to call out every commit.
I changed the versioning to hopefully make it more intuitive. '3.3' and '3.4' are for Android Studio. '2018.3' is for IJ and AS 3.5. These become the build directories that you download and install the plugin from during testing. (You are planning to help with testing, right? :)
`ProfilerAspect.DEVICES` was removed. Not sure if my fix is right. …

Update the build for M32

---

src/io/flutter/logging/tree/MessageCellRenderer.java

Swaps out the overloaded info icon.
Before:
After:

update log entry data badge

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/samples/FlutterSample.java
src/io/flutter/samples/FlutterSampleActionsPanel.java
src/io/flutter/samples/FlutterSampleComboBox.java
src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/FlutterSampleNotificationProvider.java
testSrc/unit/io/flutter/samples/FlutterSampleTest.java

Adds a sample creation banner to framework files w/ samples.
In the common (and current case), presents a simple label for the active sample.
In case there is more than one sample (promised for the future), provides a chooser.
(Note this example above is showing more IDs than are appropriate for this file in order to demo the chooser behavior.)
**NOTE:** not for landing in M32 since we'll need to shore up the implementation in Android Studio.
/cc @stevemessick 
Fixes: #2976.

sample creation banner

---

src/io/flutter/inspector/DiagnosticLevel.java
src/io/flutter/inspector/DiagnosticsTreeStyle.java
src/io/flutter/logging/FlutterLogEntry.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/logging/tree/DataPanel.java
src/io/flutter/logging/tree/MessageCellRenderer.java
src/io/flutter/utils/HtmlBuilder.java
src/io/flutter/view/InspectorColoredTreeCellRenderer.java

An error data UI corresponding to the devtools prototype (https://github.com/flutter/devtools/pull/144).
Still a bunch to do but this proves us out end to end.
On the short-list:
* add hyperlink support to stack traces
* link node selections to inspector
* auto scroll-to-top of error pane
* dark-theme improvements / awareness
* styling in general
/cc @jacob314

structured error log data ui

---

src/io/flutter/run/FlutterRunConfigurationProducer.java

`ProjectFileIndex.isInContent()` is effectively the same, and it's enough. I'd like to remove `DartWritingAccessProvider.isInDartSdkOrDartPackagesFolder()` method from the Dart plugin completely.

Remove DartWritingAccessProvider.isInDartSdkOrDartPackagesFolder() usage

---

flutter-studio/testSrc/io/flutter/tests/gui/NewModuleTest.java
flutter-studio/testSrc/io/flutter/tests/util/WizardUtils.java

@pq @devoncarew @jacob314 
The test framework requires the runner to be named GuiTestRemoteRunner, which is why there is a strange class definition.
Tests run but do not pass. Apparently, we need to have some react native stuff on the path to create a default run config. Still investigating that.

UI test update

---

src/io/flutter/utils/StdoutJsonParser.java
testSrc/unit/io/flutter/utils/StdoutJsonParserTest.java

- handle a corner case of daemon protocol parsing
This is to properly handle messages we occasionally receive where the eol terminating the daemon json packet comes out of sequence later.
```json
[{"event":"app.progress","params":{"appId":"363879f2-74d7-46e5-bfa9-1654a8c69923","id":"12","progressId":"hot.restart","message":"Performing hot restart..."}}]Performing hot restart…
```

handle a corner case of daemon protocol parsing

---

src/io/flutter/view/ShowPaintBaselinesAction.java

- change the icon used for paint baselines

change the icon used for paint baselines

---

src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/perf/FlutterWidgetPerfManager.java
src/io/flutter/perf/WidgetPerfListener.java
src/io/flutter/view/WidgetPerfSummaryView.java
testSrc/unit/io/flutter/perf/FlutterWidgetPerfTest.java

This should fix
https://github.com/flutter/flutter-intellij/issues/3173

Avoid NPE if addPerfListener is called out of order with creating perfManager.getCurrentStats()

---

src/io/flutter/run/SdkAttachConfig.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/daemon/DaemonConsoleView.java

Reorder console filters to ensure that generic URL handling is last. If it is placed too early in the list it overrides alternative handlers that recognize specific forms of URL.
Fixes #3106
@pq

Reorder console filters

---

docs/testing.md
product-matrix.json

New beta and canary builds were released today. I also added a small change to the test script to exercise banners.

Update for Valentine's Day releases

---

src/io/flutter/samples/FlutterSampleActionsPanel.java

work around link rendering issues

---

.travis.yml
product-matrix.json
resources/META-INF/plugin.xml
tool/plugin/test/plugin_test.dart

- update the product matrix
@stevemessick, I noticed that we were shipping nearly the same version ranges for `IntelliJ 2018.2.5` and `AS 3.3.1` (`182.5107.7` - `182.*`). I don't know that the jetbrains plugin server would know which version to distribute, and assume that we no longer need to support IntelliJ 2018.2. I assume this change is correct, but would like your eyes on it.
We may want to add some automation to the bots here - perhaps a dart script which will parse this file, and fail with error if there are any overlapping ranges, or unintentional gaps in ranges.

update the product matrix

---

resources/META-INF/pluginIcon.svg

Fixes #3211 
No reason this can't be added to 33.1 -- it only affects the 2019.1 version and only shows up in the plugin management page of preferences.

Add plugin icon

---

CHANGELOG.md
product-matrix.json
resources/META-INF/plugin.xml

- support 2018.3.3
@stevemessick, @DaveShuckerow

support 2018.3.3

---

docs/building.md

While reading through the docs, I thought this would be a nice convenience.

Link to the plugins readme file from the building instructions.

---

CHANGELOG.md
resources/META-INF/plugin.xml
src/io/flutter/run/daemon/FlutterApp.java

- make a newer daemon protocol field optional
- fix https://github.com/flutter/flutter-intellij/issues/3228
@stevemessick @DaveShuckerow

make a newer daemon protocol field optional

---

tool/plugin/lib/lint.dart

- add org.apache.commons.io. to the list of imports to avoid
@pq - this is not yet something we can land - I don't know how to circumlocute around `org.apache.commons.io.IOUtils`.

add org.apache.commons.io. to the list of imports to avoid

---

src/io/flutter/devtools/DevToolsManager.java

Doing this the same way we do it in VSCode, via a query param. Fixes https://github.com/flutter/devtools/issues/383

Hide DevTools debugger when launching from IntelliJ.

---

src/io/flutter/settings/FlutterSettings.java

We've seen no instability in it in g3, so we'll turn it on by default for new users.

Turn the new bazel test runner to enabled-by-default

---

.idea/codeStyles/Project.xml
src/io/flutter/dart/DartSyntax.java
src/io/flutter/run/common/CommonTestConfigUtils.java
src/io/flutter/run/common/TestType.java
src/io/flutter/run/test/FlutterTestLocationProvider.java
testSrc/unit/io/flutter/dart/DartSyntaxTest.java
testSrc/unit/io/flutter/run/common/TestTypeTest.java

Add support for detecting test call sites matching `test([A-Z][A-Za-z0-9]*)?Widgets`, eg test patterns that start with `test`, are followed by a capital letter and the rest of a target name, then end with Widgets.
Justification: some g3 customers are introducing their own shims on top of `testWidgets()`.  Message me for additional context here.

Add support for matching customized Widget tests.

---

src/io/flutter/logging/FlutterLogTree.java
src/io/flutter/logging/FlutterLogView.java

Fixes: #3219.
* puts logging view updates on a throttled timer (updates limited to once per 100ms)
* simplifies append
* unifies UI exec calls and adds guards
Show's liveness using a version of @jaumard's stress test.
(Previously this would have hung the UI.)
/cc @stevemessick @jacob314

throttle logger updates

---

tool/plugin/lib/plugin.dart

- fix a dart2 type issue
- fix https://github.com/flutter/flutter-intellij/issues/3282
There are then follow-on issues running the command - I believe it's regressed:
```
testSrc/integration/io/flutter/testing/FlutterTestUtils.java:18: error: cannot find symbol
import io.flutter.dart.DartPlugin;
^
symbol:   class DartPlugin
location: package io.flutter.dart
```
Likely the compile paths are not longer up-to-date?
We should either fix the command, if we'd like to use it, and run it continuously on travis, or remove it.
@stevemessick @DaveShuckerow

fix a dart2 type issue

---

.idea/inspectionProfiles/profiles_settings.xml
src/io/flutter/FlutterUtils.java
src/io/flutter/run/daemon/DeviceDaemon.java

The testing device shows in the device list when integrations tests are running but not otherwise.
I don't know why profiles_settings.xml gets deleted but 2019.1 has been doing that every time it gets focus. I've been ignoring that change, but it slipped in this time and the file might as well go away.

Detect when integrations tests are running

---

src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterPerfViewFactory.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/FlutterViewFactory.java

If the views were open and the flutter app is closed and then reopened,
the views are also automatically reopened.
Consistent with before, neither view is opened by default unless the users
opts to.
This fixes.
https://github.com/flutter/flutter-intellij/issues/3096

Make Perf and Inspector views only display when a Flutter app is being debugged.

---

src/io/flutter/server/vmService/frame/DartVmServiceEvaluator.java
src/io/flutter/utils/FlutterModuleUtils.java

This should fix
https://github.com/flutter/flutter-intellij/issues/2984
Some of the utils in this class already handled this sort of case robustly so I went ahead and made all the helper methods graceful in the presence of disposed projects.

Make FlutterModuleUtils consistently robust to disposed projects.

---

src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkFields.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

This reverts commit 2595b1bee1600bc20b989d23c0d03443878c804d.
Unfortunately this change breaks regular Flutter support in the plugin with apps failing on startup.
Rolling back for now to unblock.
Likely just a small fix is required to make regular Flutter apps work again.

Revert "Some initial work for FlutterWeb apps (#3315)"

---

src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/FlutterSampleNotificationProvider.java

- disables samples until creation issue is fixed
see https://github.com/flutter/flutter-intellij/issues/3330
From my understanding of the issue, the data about avialable samples we have in the flutter-intellij repo is out of date with the actual samples in the flutter/flutter repo.
@pq @stevemessick @jacob314

disables samples until creation issue is fixed

---

resources/META-INF/plugin.xml
resources/META-INF/plugin_template.xml
resources/colorSchemes/FlutterCodeColorSchemeDefault.xml

Constructors are already nicely visible in Darkula mode.
Having this separate color style format will be handy for future additional UI as Code related
color tweaks. Here are screenshots of what this looks like in action. The Dark theme isn't
impacted but the light theme is.

Make Dart constructor calls pop out in light mode. 

---

flutter-gui-tests/build.gradle
flutter-gui-tests/res/META-INF/plugin.xml
flutter-gui-tests/testSrc/io/flutter/tests/gui/InspectorTest.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterInspectorFixture.kt
resources/META-INF/plugin.xml
tool/plugin/lib/plugin.dart

With these changes the integration test now is able to work with classes defined by the Flutter plugin.
- Refactor InspectorTest
- Add functionality to FlutterInspectorFixture and allow it to refer to plugin classes
- Change plugin architecture to use the Flutter plugin as a plugin (to enable above)
- Change plugin tool to create a valid plugin for testing (needs version tag)
There is a manual set-up step that is documented in build.gradle. It would be easy to add to the plugin tool, or just use a shell script.

Add inspector dependency to test

---

src/io/flutter/run/LaunchState.java
src/io/flutter/run/SdkFields.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java

The fix to the `flutter run` regression is in DartVmServiceDebugProcess.java
Original, reverted, PR: https://github.com/flutter/flutter-intellij/pull/3315
Tracking issue: https://github.com/flutter/flutter-intellij/issues/3293

Take 2 on "Some initial work for FlutterWeb apps" change

---

src/io/flutter/run/OpenDevToolsAction.java
src/io/flutter/run/bazelTest/BazelTestRunner.java
src/io/flutter/run/common/CommonTestConfigUtils.java
src/io/flutter/run/daemon/DaemonEvent.java
src/io/flutter/run/test/FlutterTestRunner.java
src/io/flutter/run/test/TestConfigUtils.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java
testSrc/integration/io/flutter/testing/FlutterTestUtils.java

- update how we manipulate the service protocol url
- this is in prep for handling urls in the form `http://xxx:yyy/token/` (and `ws://xxx:yyy/token/ws`)
- fix https://github.com/flutter/flutter-intellij/issues/3341

update how we manipulate the service protocol url

---

src/io/flutter/dart/DartSyntax.java

- address an NPE
```
class_name: "io.flutter.dart.DartSyntax",
method_name: "isCallToFunctionMatching",
filename: "DartSyntax.java",
line_number: 135
```

address an NPE

---

product-matrix.json

Adjust build to produce a plugin suitable for integration testing.

Adjust build to make plugin for testing

---

flutter-gui-tests/testSrc/io/flutter/tests/gui/InspectorTest.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/ProjectCreator.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/SmokeTest.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/TestSuite.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterInspectorFixture.kt
flutter-gui-tests/testSrc/io/flutter/tests/gui/fixtures/FlutterMessagesToolWindowFixture.kt

This includes a test for hot reload that uses the inspector to verify it actually worked. Pretty cool, I think :)
I added a bunch of `step` calls that wrap a block and log a message. Generally, if the first line of the diff starts with "step" then the only change is indentation.
@pq @jacob314

Integration test update

---

testSrc/unit/io/flutter/utils/EventStreamTest.java

@jacob314 
This makes `EventStreamTest` runnable, although two tests fail. Previously, the two tests would cause it to hang, so I added a timer to fail the test.
I think the two failing tests (`duplicateValues()` and `nullInitialValue()`) don't run correctly because in unit test mode `AsyncUtils.invokeLater()` uses the UI thread. That is called by `EventStream.setValue()`.

Event test

---

testSrc/unit/io/flutter/project/ProjectWatchTest.java

Fix ProjectWatchTest

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/module/FlutterModuleBuilder.java
src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
src/io/flutter/module/settings/ProjectType.java
src/io/flutter/samples/FlutterSample.java
src/io/flutter/samples/FlutterSampleComboBox.java
src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/FlutterSampleNotificationProvider.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java

read sample index from flutter_tool call

---

testSrc/unit/io/flutter/testing/AdaptedFixture.java

@pq 
This is a hack. But the test runs. The failure had nothing to do with any test code we have control over. I think it is due to something that was added to the Kotlin test framework, but I don't know for sure.

Fix MainFileTest

---

src/io/flutter/FlutterUtils.java
src/io/flutter/actions/ReloadFlutterApp.java
src/io/flutter/console/FlutterConsoleFilter.java
src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/inspector/DiagnosticsNode.java
src/io/flutter/inspector/InspectorService.java
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/OpenDevToolsAction.java
src/io/flutter/run/SdkAttachConfig.java
src/io/flutter/run/SdkRunConfig.java
src/io/flutter/run/bazel/BazelRunConfig.java
src/io/flutter/run/daemon/DaemonApi.java
src/io/flutter/run/daemon/DaemonEvent.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterWebCommand.java
src/io/flutter/server/vmService/DartVmServiceDebugProcess.java
src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterView.java
testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java

Various work in support of https://github.com/flutter/flutter-intellij/issues/3293:
- ensure that the hot reload action is disabled for flutter web app runs
- disable hot reload on save for flutter web app runs
- fix a bug where some text (like `"Build: Running build completed, took 191ms"`) was erroneously hyperlinked to in the run console
- change to connecting to service protocol apps via urls (not ports)
- remove no longer used 'restart recommended...' text
- fix an issue where a device was being associated with a flutter web launch; this would cause the iOS simulator to be brought to the front when launching flutter web apps
- fix an issue where already running flutter web apps weren't reloaded when the run button was hit
- add support for a new `daemon.log` event, to better support …

more work to support running Flutter web apps

---

src/io/flutter/inspector/InspectorInstanceRef.java
src/io/flutter/logging/text/LineParser.java
src/io/flutter/run/bazelTest/BazelTestFields.java
testSrc/unit/io/flutter/testing/AdaptedFixture.java

- misc. java analysis lints cleanup

java analysis lints cleanup

---

src/io/flutter/samples/FlutterSample.java
src/io/flutter/samples/FlutterSampleActionsPanel.java

Simplification and hooks for easy future iteration.

sample panel layout improvements

---

src/io/flutter/run/LaunchState.java

Refactor the logic out to a helper method and add a safety check before the typecast.

Make flutter web logic not cause bazel runs to crash

---

src/io/flutter/editor/IndentsPass.java

This CL is a straight copy of IndentsPass from the main IntelliJ repo.
There are absolutely zero modifications. I'm sending this out as a separate CL
so that nobody wastes time reviewing this file as part of the follow on CL.
We have to change this class a little bit to add functionality to hide indent guide lines that overlap with guide lines showing widgets.

BASELINE_OF_INDENTS_PASS

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/FlutterReloadManager.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

Currently, if the analysis server detects any errors in the project, it will not perform a hot reload.
This can cause hot reload to stop working needlessly when, eg, there is an analysis error in a test file.
Take two on #3181.

Add flag to skip the dart analyzer error check before a hot reload

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form

Moved the UI Guides settings to this section along with the format on save settings.
This lets us use the shorter "UI Guides" name while still making it clear they are an Editor feature instead of some separate tool window. The UI Guides are still unchecked by default for this release with a plan to turn them on by default next release.

Create "Editor" section of Flutter Settings

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

ui refactor of the settings dialog:
- re-order the sections (now: SDK, App Execution, Editor, Experimental)
- make the 'Reload with analysis errors' pref indented under the 'reload on save pref', and have it be enabled conditionally on that pref
- tweak the names of two of the settings
@jacob314 @DaveShuckerow

ui refactor of the settings dialog

---

src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

The option is enabled by default as UI Guides serve a lot of the same purpose as the closing tags.
We have analytics for when users turn the closing labels back on so we will be able to see how many users actually want both options at the same time. With very large build methods it could definitely make sense to want both options.
Settings dialog with one additional option:
When "Turn off closing labels in Dart source code when UI guides are on" is checked, checking the "UI Guides" checkbox toggles the closing labels checkbox in the separate settings panel. When the box is unchecked, checking the UI Guides checkbox has no impact.

Add an option to turn off closing labels in Dart source code when UI guides are on.

---

tool/plugin/lib/plugin.dart

- remove a no longer used 'PROJECTSYSTEM' case switch
@stevemessick; it looks like this is no longer necessary (and I verified that we can build the releases after this change)

remove a no longer used 'PROJECTSYSTEM' case switch

---

src/io/flutter/editor/FliteredIndentsHighlightingPass.java
src/io/flutter/editor/WidgetIndentsHighlightingPass.java

There was one legitimate case where the regular indent guides could be a bit stale when we accessed them and a couple other cases where we are calling this just to be safe and avoid any other edge case bugs like.
https://github.com/flutter/flutter-intellij/issues/3443

Defensively ensure all offsets are within the document length before calling getLineNumber.

---

flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
flutter-studio/src/io/flutter/android/AndroidModuleLibraryManager.java
flutter-studio/src/io/flutter/project/FlutterProjectStep.java
flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
resources/META-INF/studio-contribs.xml
resources/META-INF/studio-contribs_template.xml
tool/plugin/lib/plugin.dart

This fixes a number of problems that surfaced with Android Studio 3.5 beta 1.
1. The third page of the new project wizard is visible now.
2. The File menu has _New Flutter Project_ next to _New Project_ again.
3. The Welcome screen has the proper label for creating Flutter projects.
4. The Welcome screen has a spiffy new icon for Flutter.
5. The plugin tool allows resource files to be editing during the build (for # 2).
Here's the new icon, in context:
Fixes #3473 

Fix errors in AS 3.5 beta 1

---

src/io/flutter/run/daemon/FlutterApp.java

- limit the amount of time we wait for a graceful app shutdown
- fix https://github.com/flutter/flutter-intellij/issues/3319
Only block on the UI thread for a brief period when asking for a graceful shutdown when terminating flutter app runs.

limit the amount of time we wait for a graceful app shutdown

---

src/io/flutter/editor/NativeEditorNotificationProvider.java

Fixes: #3514.
(Still trying to figure out why the basedir would be `null` but crashing on banner creation isn't good regardless 😬)

guard against null project basedir

---

src/io/flutter/bazel/PluginConfig.java
src/io/flutter/bazel/Workspace.java
src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSdk.java
src/io/flutter/sdk/FlutterSdkVersion.java
testSrc/unit/io/flutter/bazel/FakeWorkspaceFactory.java
testSrc/unit/io/flutter/run/bazel/LaunchCommandsTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigProducerTest.java
testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java

Involves setting up a Bazel-compatible FlutterSDK and delegating to it.
Because the Bazel SDK does not surface the same behavior as the pub-based SDK, I made this an explicit step that we have to take when it is necessary.

Enable devtools launching from Bazel

---

src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- don't disable closing labels as part of UI Guides
- fix https://github.com/flutter/flutter-intellij/issues/3502
- rename the 'UI Guides' pref to 'Show UI Guides for build methods'
- add a small bit of padding to the left of some preference items
- fix an issue where we would request info from `flutter --version` twice in a very brief time, and the text in the preference page would often show `waiting for another flutter to release the lock`

don't disable closing labels as part of UI Guides

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java

- add a preference to toggle closing labels (duplicate the existing one from the Dart plugin, but expose it in the Flutter prefs UI)
- fix https://github.com/flutter/flutter-intellij/issues/3526

add in a preference to toggle closing labels

---

product-matrix.json

The AS beta release wasn't showing up in the plugin manager.

Resolve load conflict for beta

---

.travis.yml
.travis_template.yml
build.gradle
tool/travis.sh

There are too many failing tests to allow the build to fail due to failed tests. We''ll need to get those fixed first.
To find the failing tests, go to the travis build log, select the third job (UNIT_TEST_BOT) and scroll through for redness. We may want to improve reporting, but that's probably going to be a Q3 task.
To run the tests locally, open a terminal and cd to your plugin project directory. Then do:
```bash
export JAVA_HOME=<path-to-java-home>
./gradlew test
```
@devoncarew @pq @jacob314 @DaveShuckerow @terrylucas @kenzieschmoll

Run unit tests on travis

---

build.gradle
testSrc/unit/io/flutter/run/bazelTest/LaunchCommandsTest.java

Removing the setting to enable/disable the new bazel test runner (#3371) regressed these tests.
They may have been turned off on Travis, or some other thing happened that led to not seeing them fail.

Make the Bazel-specific tests work again

---

src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterView.java

@jacob314 @terrylucas 
IJ 2019.2 EAP has a new implementation of editor tabs. It requires a focus manager. This shouldn't affect builds for older versions, where that arg was nullable.
This changes makes the integration tests work again.
In 2019.2 EAP we get this exception when run without these changes:
```java
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.intellij.ui.tabs.newImpl.SameHeightTabs.<init>, parameter focusManager
at com.intellij.ui.tabs.newImpl.SameHeightTabs.<init>(SameHeightTabs.kt)
at com.intellij.execution.ui.layout.impl.JBRunnerTabs.<init>(JBRunnerTabs.java:40)
at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:218)
at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:440)
```

Add focus manager to JBRunnerTabs constructor call

---

build.gradle
flutter-intellij.iml
src/io/flutter/devtools/DevToolsManager.java
src/io/flutter/devtools/DevToolsUtils.java
testSrc/unit/io/flutter/devtools/DevToolsUtilsTest.java
tool/plugin/lib/plugin.dart

Adds "ide=IntelliJ" or "ide=AndroidStudio" to the DevTools url upon launch. Fixes https://github.com/flutter/flutter-intellij/issues/3591.
Also removed the `hide=debugger` param from the `serviceProtocolUrl == null` case to be consistent with what we do when the vm service uri is not null (the else path in this if statement). Discussion for this [here](https://github.com/flutter/devtools/issues/731). 
@jacob314 @terry @DanTup

Add IDE query param to DevTools url.

---

src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/utils/MostlySilentOsProcessHandler.java

- switch it to a mostly silent process
- refactor the mostly silent process handler into a shared util
Justification: Flutter apps that take a long time to start up in debug mode (for example, they have native logic that they invoke before the Flutter app itself starts) can make IntelliJ upset.

Treat FlutterApp as a long-running process

---

testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java

From the class docs:
```java
* Rate limiter that issues requests asynchronously on the ui thread
* ensuring framesPerSecond rate is not exceeded and that no more than 1
* request is issued at a time.
```
The test would fail with `requestsPerSecond` at 10, which is what the rate limited was told to not exceed. So, change `<` to `<=` to make the test not flakey.

Fix test to match class docs

---

CONTRIBUTING.md

Unit tests can now use mockito through the PowerMock libraries. The instructions are updated to include installation of them.
You'll need to do this if you haven't already.
@kenzieschmoll @jacob314 @terrylucas @pq @devoncarew

Update installation for libraries

---

src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java

- reduce the screen area we use to display the Flutter version in the preferences view. We've added several new preferences recently - this change will make it less likely for the Flutter preference page to need to scroll.
- also, add a 'copy tp clipboard' button for the version text

make the area for the flutter version smaller

---

flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
flutter-studio/src/io/flutter/project/FlutterProjectModel.java
flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
src/io/flutter/module/settings/ProjectType.form
src/io/flutter/module/settings/ProjectType.java
src/io/flutter/samples/FlutterSampleManager.java
src/io/flutter/samples/FlutterSampleNotificationProvider.java
src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
src/io/flutter/sdk/FlutterSdk.java

- simplify the sample creation workflow
- this PR removes the ability to create the dartdoc defined samples from the project wizards
- some work towards https://github.com/flutter/flutter-intellij/issues/3562
After this PR, users can continue to create sample projects via the in-line editor contributions. I think this better matches the flow of how we expect this to be used - when looking at specific widgets, rather than ahead of time, when considering creating a new project.
@pq

simplify the sample creation workflow

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/actions/DeviceSelectorAction.java
src/io/flutter/run/daemon/DaemonEvent.java
src/io/flutter/run/daemon/DeviceDaemon.java
src/io/flutter/run/daemon/DeviceSelection.java
src/io/flutter/run/daemon/FlutterDevice.java
src/io/flutter/sdk/FlutterCommand.java
src/io/flutter/sdk/FlutterSettingsConfigurable.form
src/io/flutter/sdk/FlutterSettingsConfigurable.java
src/io/flutter/settings/FlutterSettings.java
testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java

- show web and desktop devices in the device selector
- add a user preference to enable showing the above devices
- fix https://github.com/flutter/flutter-intellij/issues/3508
Note that running with those devices won’t work unless the projects have been created with the rightt support (flutter web, or desktop).

support showing desktop and web devices

---

src/io/flutter/preview/PreviewView.java

Ideally we should use `id` for matching Quick Assists and actions.
I think we postponed because at that time IDs were added only recently.
fix https://github.com/flutter/flutter-intellij/issues/3615

Issue 3615. Fix message for 'Remove widget'.

---

src/io/flutter/inspector/HeapState.java
src/io/flutter/vmService/HeapMonitor.java

Handle null JSON entries more gracefully.  This happens, for example, if we ask an Isolate for it's heap data (as for a web app in https://github.com/flutter/flutter-intellij/issues/3590) and there isn't any.

guard against null json heap entries

---

src/io/flutter/logging/FlutterConsoleLogManager.java
src/io/flutter/logging/FlutterLog.java
src/io/flutter/logging/FlutterLogEntryParser.java
src/io/flutter/run/LaunchState.java
src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/vmService/ServiceExtensions.java
src/io/flutter/vmService/VMServiceManager.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmService.java
third_party/vmServiceDrivers/org/dartlang/vm/service/VmServiceBase.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/GetMemoryUsageConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/InstanceSetConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/TimelineConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/consumer/TimelineFlagsConsumer.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/AllocationProfile.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/ClassHeapStats.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Event.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/EventKind.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceSet.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Isolate.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/LogRecord.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/MemoryUsage.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Script.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/Timeline.java
third_party/vmServiceDrivers/org/dartlang/vm/service/element/TimelineFlags.java

- upgrade the vm service library
- show service protocol logging events in the console view
- simplify and consolidate some code around 'Logging' events in the existing logging view
- fix https://github.com/flutter/flutter-intellij/issues/3421
This PR shows service protocol `'Logging'` events in the run and debug consoles. I bumped the vm service protocol library classes for this - done as a separate commit for easier reviewability.
There's a small bit of code in here related to `'Flutter.Error'` events; it's all disabled behind a compile time flag however.

show service protocol logging events in the console view

---

src/io/flutter/editor/OutlineLocation.java
src/io/flutter/editor/WidgetIndentsHighlightingPass.java
src/io/flutter/editor/WidgetIndentsHighlightingPassFactory.java

Only use the converted offsets when the file and the converted
offsets disagree. This avoids bugs where we sometimes converted
offsets that shouldn't be converted on windows.
This fixes https://github.com/flutter/flutter-intellij/issues/3561

Make logic dealing with converting offsets more robust.

---

tool/grind.dart
tool/icons/update_icons.dart
tool/plugin/lib/plugin.dart

This updates call sites with forward-compatible fixes for
a recent Dart SDK change that changed the following APIs
to be `Stream<Uint8List>` rather than `Stream<List<int>>`:
* HttpClientResponse
* File.openRead()
https://github.com/dart-lang/sdk/issues/36900

Fix per SDK Stream<Uint8List> breaking changes

---

src/io/flutter/view/MultiIconSimpleColoredComponent.java

- fix an NPE in the inspector
This NPE is caused by getting a null value from a Map (`Map<Integer, Integer>`), and trying to use it as an `int`. The NPE happens during the unboxing.
We should either land this fix, or roll back the portion of the PR that removed the gnu int hashmap.
```
at io.flutter.view.MultiIconSimpleColoredComponent.doPaintTextAndIcons(MultiIconSimpleColoredComponent.java:834)
at io.flutter.view.MultiIconSimpleColoredComponent.doPaint(MultiIconSimpleColoredComponent.java:752)
at io.flutter.view.MultiIconSimpleColoredComponent._doPaint(MultiIconSimpleColoredComponent.java:747)
at io.flutter.view.MultiIconSimpleColoredComponent.paintComponent(MultiIconSimpleColoredComponent.java:737)
at javax.swing.JComponent.paint(JComponent.java:1056)
```

fix an NPE in the inspector

---

src/io/flutter/FlutterBundle.properties
src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationType.java
testSrc/unit/io/flutter/run/bazel/BazelConfigurationFactoryTest.java
testSrc/unit/io/flutter/run/bazelTest/BazelTestConfigurationFactoryTest.java

There is a regression currently where saved bazel test configurations aren't loading properly.
Add tests to prevent future regressions.

Name the Bazel test config factories to match assumed names in g3

---

src/io/flutter/inspections/FlutterDependencyInspection.java
src/io/flutter/inspector/TreeScrollAnimator.java
src/io/flutter/logging/FlutterLogView.java
src/io/flutter/perf/FlutterWidgetPerf.java
src/io/flutter/run/ObservatoryFile.java
src/io/flutter/run/PositionMapper.java
src/io/flutter/test/DartTestEventsConverterZ.java
src/io/flutter/view/WidgetPerfTable.java
src/io/flutter/vmService/DartVmServiceBreakpointHandler.java
src/io/flutter/vmService/DartVmServiceDebugProcess.java
src/io/flutter/vmService/IsolatesInfo.java
src/io/flutter/vmService/VMServiceManager.java
src/io/flutter/vmService/frame/DartVmServiceEvaluator.java
tool/plugin/lib/lint.dart

This reverts gnu.trove import removal from commit fb50615d6eaceac70830ead0c783be65a3673dc6.
The io.netty imports will remain proscribed after merging this.
Fixes #3647.

Partial revert of "Remove netty and gnu.trove imports (#3623)"

---

flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
src/io/flutter/run/daemon/DaemonConsoleView.java
src/io/flutter/sdk/FlutterSdkUtil.java
src/io/flutter/utils/StdoutJsonParser.java
src/io/flutter/utils/SystemUtils.java
testSrc/unit/io/flutter/utils/StdoutJsonParserTest.java

- fix an issue with some daemon json output appearing in the console
- unrelated, rename a `System` class to `SystemUtils` so it doesn't have the same name as `java.lang.System`
```
[{"event":"app.progress","params":{"appId":"3afb1f88-db66-490d-bce7-f30050cb5d2a","id":"7","progressId":"hot.reload","message":"Performing hot reload..."}}]Performing hot reload...
```

fix an issue with some daemon json output appearing in the console

---

src/io/flutter/utils/StdoutJsonParser.java

- remove extra console whitespace
A minor follow up to https://github.com/flutter/flutter-intellij/pull/3658 - make sure we don't emit too many eol's (we shouldn't show the eols after a daemon output line).

remove extra console whitespace

---

src/io/flutter/FlutterInitializer.java
src/io/flutter/logging/FlutterConsoleLogManager.java

- init default settings for the run console text wrapping
`Flutter.Error` events will render better with text wrapping enabled for the Run and Debug consoles. We turn that setting on for the user (once).

init default settings for the run console text wrapping

---

build.gradle
testSrc/unit/io/flutter/utils/EventStreamTest.java

If we're shipping with the event stream's current behavior, then it seems to me the Event Stream is working the way we intend it to.
If that's the case, the best fix is to update the test and merge.
If that's not the case and we actually want to the behavior to match the tests, I think the best fix is to add a TODO for fixing the behavior and then merge these tests in a working state.  There are 9 tests in the file, and only 2 seem to be failing.  So long as this test is off, we aren't getting the value of the test cases that do work.

Make the event stream tests pass and re-enable them.

---

src/io/flutter/FlutterErrorReportSubmitter.java
src/io/flutter/analytics/Analytics.java
testSrc/unit/io/flutter/analytics/AnalyticsTest.java

- use getThrowableText() from IdeaLoggingEvents
At some point, the `Throwable` reported from IdeaLoggingEvents became a synthetic throwable: `IdeaReportingEvent$TextBasedThrowable`. In order to get the stack trace, we need to call `getThrowableText()` on it.
We should also plan to move to a more featureful crash reporting mechanism. With the current mechanism, we're not able to log crash exception names or messages, only traces.

use getThrowableText() from IdeaLoggingEvents

---

src/io/flutter/run/daemon/FlutterApp.java
src/io/flutter/view/FlutterPerfView.java
src/io/flutter/view/FlutterView.java
src/io/flutter/view/TogglePlatformAction.java
src/io/flutter/vmService/ServiceExtensionDescription.java
src/io/flutter/vmService/ServiceExtensions.java
src/io/flutter/vmService/ToggleableServiceExtensionDescription.java
src/io/flutter/vmService/VMServiceManager.java

Removes the toggle platform button from the service extension button bars (Inspector View and Performance View), and replaces it with a dropdown selector. We now include Fuchsia as an option and can add additional platforms in the future.
Confirmed that states stay synchronized between IntelliJ and DevTools.
Matching CL from DevTools is here: https://github.com/flutter/devtools/pull/783.
cc: @sfshaza2 in case this changes any docs or screenshots.

Add target platform selector for togglePlatform service extension.
