- README.md
> Added Contributing link.

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Adds version details to the SDK preference page.
Fixes: https://github.com/flutter/flutter-intellij/issues/83.
> Add version text details (#83).

- src/io/flutter/console/FlutterConsole.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/sdk/FlutterSdk.java
Fixes: https://github.com/flutter/flutter-intellij/issues/94
> Hyperlink support for `flutter doctor` in flutter console (#94).

- src/io/flutter/console/FlutterConsoleFilter.java
Follow-up from: https://github.com/flutter/flutter-intellij/pull/95/files/06360b26d70e319b253e2867b345bec079c17ddb#r77681848
> Fixed copyright.

- README.md
> Add build badge.

- build.gradle
- flutter-intellij-community.iml
- testSrc/io/flutter/FlutterCodeInsightFixtureTestCase.java
- third_party/intellij-plugins-dart/README.md
- third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
@stevemessick, refactor the location of the DartTestUtils class.
> refactor location of the DartTestUtils class

- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Fixes: https://github.com/flutter/flutter-intellij/issues/98
> Fix bad UI thread access (#98).

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceBreakpointHandlerZ.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcess.java
@devoncarew See if this fixes your class loader problem with the built plugin.
> Work around bad constructor decl

- CONTRIBUTING.md
- building.md
update the contributing and build docs; change build/libs/flutter-intellij-0.0.1.jar to build/distributions/Flutter-0.0.1.zip
> update the contributing and build docs

- src/io/flutter/sdk/FlutterSdk.java
- pass `--no-color` into `flutter create`; this causes the pub get step to not try and draw using ansi codes
> don't run create with ansi drawing

- .idea/misc.xml
- CONTRIBUTING.md
- flutter-intellij.iml
Follow up to https://github.com/flutter/flutter-intellij/pull/118, update the getting started docs for the flutter intellij plugin.
@stevemessick, @pq
> update the getting started instructions

- CONTRIBUTING.md
> Tweak install notes.

- .gitignore
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/FlutterConfigurationEditorForm.java
@stevemessick, remove unused fields in the launch config dialog.
> remove unused fields in the launch config dialog

- src/io/flutter/console/FlutterConsoleFolding.java
Taking a cue from `flutter run` folding...
> Console folding for `flutter create`.

- CONTRIBUTING.md
Instructions for getting platform sourcepaths wired up.
> Add source path details to the CONTRIBUTING docs.

- .idea/codeStyleSettings.xml
- src/io/flutter/console/FlutterConsoleFolding.java
- commit intellij formatting settings
- fix https://github.com/flutter/flutter-intellij/issues/144
- suppress one unused variable warning
> commit intellij formatting settings

- src/io/flutter/FlutterBundle.properties
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
Minor tweaks to the i18n file:
- sort the entries
- change a raw string to a FlutterBundle.message
> tweaks to the i18n file

- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/console/FlutterConsoleFolding.java
- third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
A lambda and some warnings suppressed.
> Wee bit of cleanup.

- src/io/flutter/run/FlutterAppState.java
- fix an npe when no devices are connected
> fix an npe when no devices are connected

- gradle.properties
- resources/META-INF/plugin.xml
- rev the plugin version
- adjust the plugin description text
- add a placeholder for a changelog (commented out f0r now)
> rev the plugin version

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
👯 
/cc @stevemessick @devoncarew 
Obviously we can think about whether this is how we want to cache selected devices and there's some error handling to fill out but it's a step in the right direction!
> Hookup discovered devices to device menu.

- src/io/flutter/run/daemon/FlutterDaemonController.java
- fix an npe at shutdown (not user facing, but I did see it in the logs)
> fix an npe at shutdown

- resources/META-INF/plugin.xml
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/run/daemon/FlutterDaemonController.java
Migrates initialization to a startup activity.  The `ApplicationTable` should be reliably available then.
Fixes: #157 
> Fix Daemon initialization issue (#157).

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
@pq @devoncarew This adds Restart and Reload buttons, which were dropped from the commit yesterday.
> Restore the buttons for reload and restart

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
@pq @devoncarew Just following through on IntelliJ suggestions. I tried to ignore it but every time I read this code I get distracted.
> Eliminate distracting yellow background

- src/io/flutter/run/FlutterRunner.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/DartRunner.java
@pq @devoncarew I had to re-read these classes to remember what's special about them so I thought it was time to add comments.
> Debugcomment

- src/io/flutter/actions/ReloadFlutterApp.java
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/daemon/FlutterAppManager.java
> Un-reverse reload/restart actions.

- gradle.properties
- resources/META-INF/plugin.xml
> Bump plugin to `0.0.3`.

- docs/alpha/updatePlugins.xml
> Update release to `0.0.3`.

- CONTRIBUTING.md
- resources/META-INF/plugin.xml
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/daemon/DaemonJsonInputFilterProvider.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/daemon/FlutterAppManager.java
@pq @devoncarew Makes the console output more readable. I also added a note about configuring sources for Dart.
> Filter out json formatting

- src/io/flutter/actions/DeviceSelectorAction.java
Fixes: https://github.com/flutter/flutter-intellij/issues/181
becomes:
> Add “no devices” menu placeholder (#181).

- src/io/flutter/run/daemon/DaemonJsonInputFilterProvider.java
@stevemessick - catch all daemon messages in the filter; a few were slipping by before.
> filter all daemon messages

- resources/META-INF/plugin.xml
> Fix debug action toolbar rogue appearance.

- src/io/flutter/actions/FlutterAppAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/actions/HotReloadFlutterAppKeyAction.java
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/actions/RestartFlutterAppKeyAction.java
- src/io/flutter/run/FlutterRunner.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
@pq @devoncarew Here's a rewrite of today's earlier branch that I gave up trying to merge.
I didn't preserve everything, but the user-facing bits are all there.
> Better enablement for toolbar buttons

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
@pq @devoncarew To alleviate the problem in #201
> Ignore sentinal msg

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.0.4` [TBR].

- src/io/flutter/run/daemon/FlutterAppManager.java
@stevemessick, for `app.stop`, use a shorter timeout when waiting for a response (1s instead of 10s).
> wait a shorter time for the stop timeout

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/run/daemon/ConnectedDevice.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
- have the device selector listen to device notifications
- auto-select a device if we find one and there is no current selection
- on the mac, show a menu item for opening the ios simulator
> device selector listens to device notifications

- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterRunConfigurationProducer.java
- src/io/flutter/run/FlutterRunnerParameters.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
- use the path and cwd info from the launch config (so we can launch things other than `lib/main.dart`)
> use the path and cwd info from the launch config

- resources/META-INF/plugin.xml
- remap hot reload shortcuts
- fix https://github.com/flutter/flutter-intellij/issues/189
> remap hot reload shortcuts

- gradle.properties
- resources/META-INF/plugin.xml
> Bumping to `0.0.5` [TBR].

- docs/alpha/updatePlugins.xml
> Bump to `0.0.5` [TBR].

- .travis.yml
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterRunnerParameters.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- src/io/flutter/run/daemon/ProgressHandler.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- tool/travis.sh
- address some intellij inspection warnings
- move the travis build to its own script
> Inspections

- .gitignore
- .travis.yml
- flutter-intellij.iml
- pubspec.yaml
- src/io/flutter/actions/OpenComputedUrlAction.java
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- tool/grind.dart
- tool/travis.sh
- print an API report for uses of the Dart plugin API
- remove some unused imports
- print the api report as part of travis
- fix https://github.com/flutter/flutter-intellij/issues/190
> Print api report

- tool/grind.dart
Tweak the grep search we use so that grep doesn't match grind.dart.
> Tweak grep

- src/io/flutter/console/FlutterConsoleFilter.java
Adds path hyperlinks to `flutter create` output.
> Console file path hyperlinks for `flutter create`.

- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
> Fix IDEA API calls.

- src/io/flutter/sdk/FlutterSdk.java
Fixes: https://github.com/flutter/flutter-intellij/issues/231
> Hoist Dart module config out of `flutter create` process wait (#231).

- src/io/flutter/sdk/FlutterSdk.java
> Ensure that a run config doesn’t exist before auto-creation (#245)

- src/io/flutter/run/daemon/FlutterDaemonService.java
> Set hot=false for release runs

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.0.6` [TBR].

- docs/alpha/updatePlugins.xml
> Update update site to point to `0.0.6` [TBR].

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- fix https://github.com/flutter/flutter-intellij/issues/256
- fix an issue w/ slow launches; after a timeout, the 2nd launch would NPE
@stevemessick
> fix an exception on launch

- docs/readme.md
Fixes: https://github.com/flutter/flutter-intellij/issues/255
/cc @devoncarew @mit-mit @stevemessick  
Word-smithing welcome!
> Install notes (#255).

- src/io/flutter/run/daemon/FlutterAppManager.java
@pq @devoncarew Gracefully recover from the flutter daemon process being killed (eg: kill -9 ...), or any other form of unplanned exit.
> Quietly recover from OS process exit

- resources/META-INF/plugin.xml
Adds:
* URL
* category
Fixes: #217 (Changelog can come later.)
> Plugin metadata tweaks (#217).

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.0.7` [TBR].

- docs/alpha/updatePlugins.xml
> Bump alpha to `0.0.7` [TBR].

- docs/alpha/updatePlugins.xml
> Bump to `0.1.0` [TBR].

- getting_started.md
> Getting started tweaks (#287, #288).

- src/io/flutter/run/daemon/FlutterAppManager.java
@pq @devoncarew Fixes #292. Probably temporary, but does no harm if not changed once the daemon code is patched.
> Stop hanging when the Stop button is clicked

- .gitignore
- .idea/copyright/chromium.xml
- .idea/copyright/profiles_settings.xml
- .idea/libraries/Dart.xml
- .idea/libraries/Dart_162_2017.xml
- .idea/libraries/Flutter_0_0_1.xml
- .idea/libraries/flutter_intellij_0_0_1.xml
- .idea/libraries/lib1.xml
- .idea/uiDesigner.xml
- .idea/workspace.xml
As per Alex's suggestion this morning, add `.idea` to versioning so that we have consistency across developers.  (This is part of _the Jetbrains way_...)
To be fair, these files may benefit from some tweaking but once we get it right we'll all have the same settings which I agree is a good thing.
> Version `.idea/` contents.

- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/sdk/FlutterSdkUtil.java
See: https://github.com/flutter/flutter-intellij/issues/300
Addresses the SDK and module config logging levels; debugging for a follow up (maybe @stevemessick could take a pass?)
> Logging level cleanup (#300).

- build.gradle
> Do not mark src as resources root

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
> Only show device selector for Flutter projects (#267).

- src/io/flutter/run/daemon/ProgressHandler.java
@pq @devoncarew @alexander-doroshko This is the first step towards fixing #230 
Tested manually, like most of the debug stuff.
> Fix inspections in ProgressHandler

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.1.1` [TBR].

- docs/alpha/updatePlugins.xml
> Bump update site to `0.1.1` [TBR].

- src/io/flutter/actions/DeviceSelectorAction.java
Fixes #330 
/cc @alexander-doroshko @stevemessick
> Fix device selector filtering (#330).

- gradle.properties
- resources/META-INF/plugin.xml
* fixed device selector filtering
* adds change notes (fixes #338)
> Version `0.1.2` [TBR].

- docs/alpha/updatePlugins.xml
> Publish `0.1.2` [TBR].

- resources/META-INF/plugin.xml
Fixes: #328
/cc @alexander-doroshko @devoncarew
> Add IDEA version constraints to plugin.xml (#328).

- .gitignore
- flutter-intellij.iml
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
I see a compile error locally for a missing abstract method - adding one here.
> implement a missing method

- .gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/inspectionProfiles/profiles_settings.xml
- update our .gitignores and committed files to include `.idea/inspectionProfiles` (see https://github.com/flutter/flutter-intellij/pull/353)
@alexander-doroshko
> include inspectionProfiles in committed files

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.1.3` [TBR].

- docs/alpha/updatePlugins.xml
> Publish `0.1.3` [TBR].

- src/io/flutter/run/daemon/DaemonJsonInputFilterProvider.java
- src/io/flutter/run/daemon/FlutterAppManager.java
Two minor changes:
- add a VERBOSE flag for controlling debug time output for the daemon protocol
- add some TODO:s and comments in `FlutterAppManager.java` (added while working on flutter_tools)
> add debugging aides

- build.gradle
- flutter-intellij.iml
- commit the 162.2485 dart plugin
@pq, @stevemessick
> commit the 162.2485 dart plugin

- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- expose pause after restart (currently we don't use this parameter, but will when we move to restoring breakpoints after a restart)
@pq, @stevemessick
> expose pause after restart

- resources/META-INF/plugin.xml
> Relax version constraint to work with current Dart plugin sources

- testing.md
> Smoke testing doc first steps (#114).

- resources/META-INF/plugin.xml
Fixes: #378 
/cc @alexander-doroshko
> Update plugin deps to specify CE and UE (#378).

- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/FlutterConfigurationEditorForm.java
See: #403 
/cc @alexander-doroshko @devoncarew
> Remove checked mode Flutter Run option (#403).

- src/io/flutter/run/daemon/FlutterAppManager.java
- update IntelliJ for flutter tools progress notification changes
@pq, @danrubel
> update IntelliJ for flutter tools progress notification changes

- resources/META-INF/plugin.xml
- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/settings/FlutterSettings.java
Fixes #429.
/cc @alexander-doroshko @devoncarew
> Cache version for dismissed SDK checks (#429).

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/FlutterGeneratorPeer.form
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Address #415.
Ideas about better wording are welcome.
> Suggest user to run 'flutter doctor' if Flutter SDK installation is not complete (#415)

- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/run/FlutterAppState.java
Adds missing hyperlinks for run targets.
/cc @devoncarew @alexander-doroshko
> Add console filters to `flutter run`s.

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.1.5`.

- testing.md
> Test script tweaks

- src/io/flutter/actions/FlutterAppAction.java
- src/io/flutter/actions/FlutterKeyAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/actions/HotReloadFlutterAppKeyAction.java
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/actions/RestartFlutterAppKeyAction.java
> Fix keymap assignments (#442).

- src/io/flutter/run/daemon/FlutterAppManager.java
- improve the output for reloading and restarting
- fix https://github.com/flutter/flutter-intellij/issues/441
@pq
```
Reloaded in 1015ms.
Reloaded 309 of 389 libraries.
Reloaded in 387ms.
Reloaded 0 of 389 libraries.
Restarted in 587ms.
Restart complete.
```
> improve the output for reloading and restarting

- testing.md
> Add sequence of debugging sessions.

- src/io/flutter/run/README.md
> Package overview doc (WIP).

- src/io/flutter/run/daemon/ConnectedDevice.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
For whatever reason, recent `.iml` changes have borked my ability to see the guava classes on my home machine.
- prefer java 7 classes to guava
@pq
> prefer java 7 classes to guava

- build.gradle
- flutter-intellij.iml
- remove old jars; add the latest Dart plugin jar
- fix https://github.com/flutter/flutter-intellij/issues/468
@pq @alexander-doroshko
> remove old jars; add the latest Dart plugin jar

- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/run/FlutterRunnerBase.java
- src/io/flutter/run/README.md
- src/io/flutter/run/daemon/FlutterAppManager.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
- src/io/flutter/run/daemon/RunMode.java
Essentially treats run like debug without breakpoints (as described in #445).
Far from an ideal solution but enough to get us experimenting with a new UX.
> Run mode behavior re-work (#445).

- src/io/flutter/run/README.md
- update the debugger arch doc
(TBR)
> update the debugger arch doc

- README.md
Removed two fixed issues
Not sure if I can remove https://github.com/flutter/flutter-intellij/issues/371 -- that was fixed but was it pushed by JetBrains?
> Remove fixed issues from known issues list

- src/io/flutter/FlutterErrors.java
- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterUpgradeAction.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/sdk/FlutterSdk.java
- add a common class for showing error notifications (fix https://github.com/flutter/flutter-intellij/issues/477)
@pq
> centralize error dialogs

- src/io/flutter/console/FlutterConsoleHelper.java
- src/io/flutter/sdk/FlutterSdk.java
- recycle Flutter consoles (fix https://github.com/flutter/flutter-intellij/issues/478)
@pq
> recycle flutter consoles

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/FlutterKeyAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/actions/OpenComputedUrlAction.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/console/FlutterConsoleFolding.java
- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/inspections/FlutterYamlNotificationProvider.java
- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterAppStateBase.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- src/io/flutter/run/daemon/FlutterDaemonController.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- testSrc/io/flutter/FlutterCodeInsightFixtureTestCase.java
- testSrc/io/flutter/sdk/FlutterSdkUtilTest.java
- testSrc/io/flutter/util/FlutterTestUtils.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
> Make locals and fields `final` where possible.

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterUpgradeAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/console/FlutterConsoleHelper.java
- src/io/flutter/run/FlutterAppStateBase.java
- src/io/flutter/run/daemon/FlutterAppManager.java
- src/io/flutter/run/daemon/FlutterDaemonController.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
* repaired mis-declaration of `FlutterJsonObject` fields as `final` (they’re not)
* NPE guards
* dead code cleanout
> Final `final` fixes; guards; cleanup.

- src/io/flutter/console/FlutterConsoleHelper.java
- src/io/flutter/module/FlutterModuleBuilder.java
Guard the console code behind a `runWhenInitialized()` call (fix an npe on project creation).
@pq
> fix an npe on new project creation

- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/vcs.xml
- update IntelliJ project meta-data
(TBR)
> update IntelliJ project meta-data

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/console/FlutterConsoleHelper.java
- src/io/flutter/run/FlutterRunner.java
> NPE guard; misc. cleanup.

- src/io/flutter/actions/DeviceSelectorAction.java
> Fix missing open IOS simulator menu action (#498).

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- fix an issue with debugging snapshot based apps
- fix https://github.com/flutter/flutter-intellij/issues/499
@pq
> fix an issue with debugging snapshot based apps

- .idea/inspectionProfiles/Project_Default.xml
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/sdk/FlutterSdk.java
- fix some intellij warnings in the codebase
@pq
> fix some intellij warnings in the codebase

- src/io/flutter/run/daemon/DaemonJsonInputFilterProvider.java
Follow up to https://github.com/flutter/flutter-intellij/pull/505, add some additional filtering to the console output.
> additional filtering for console output

- ISSUE_TEMPLATE.md
- resources/META-INF/plugin.xml
- src/io/flutter/actions/FlutterGettingStarted.java
- src/io/flutter/actions/FlutterSubmitFeedback.java
- on the shiny new `Tools` menu, add `Getting Started` and `Submit Feedback` items
- add a new issue template for the repo
fix https://github.com/flutter/flutter-intellij/issues/519, fix https://github.com/flutter/flutter-intellij/issues/352
@pq, @mit-mit
> add feedback and getting started menu items

- src/io/flutter/console/FlutterConsoleFolding.java
@pq, update the console folding text. We're running more flutter commands now, so remove the special-casing for `create` and `run`.
> update the console folding

- src/io/flutter/run/FlutterAppState.java
- improve the code for locating modules
reviewed in https://github.com/flutter/flutter-intellij/pull/522; landing as that PR may not make it
> improve the code for locating modules

- resources/META-INF/plugin.xml
- src/io/flutter/actions/FlutterPackageAction.java
- src/io/flutter/actions/FlutterPackagesGetAction.java
- src/io/flutter/actions/FlutterPackagesUpgradeAction.java
- src/io/flutter/inspections/FlutterYamlNotificationProvider.java
> Context menu for `flutter.yaml` files (#516)

- src/io/flutter/FlutterBundle.properties
address a nit with the `Process finished with exit code` message (TBR)
> add a newline

- resources/META-INF/plugin.xml
- src/io/flutter/actions/FlutterPackagesExplorerActionGroup.java
* contributes a new Flutter group to the Project View popup menu.
Fixes #537
> Context menu for flutter.yaml files (#537).

- src/io/flutter/console/FlutterConsoleFolding.java
- improve console folding for iOS
This is _a lot_ less verbose when running an iOS app, and the info is still there if you want to see it.
@pq (also @tvolkert, who's worked on the verbosity of the console logging)
> improve console folding for iOS

- gradle.properties
- resources/META-INF/plugin.xml
> Bump to `0.1.7`.

- src/io/flutter/sdk/FlutterSdk.java
Fix an NPE found during smoke testing; an NPE can be thrown on project creation. This is racy, so likely wasn't a regression.
@pq
> fix an npe on project creation

- src/io/flutter/console/FlutterConsoleFolding.java
- improve the console folding for iOS (also fold native stack traces)
@pq
> improve the console folding for iOS

- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/actions/OpenObservatoryAction.java
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/editor/FlutterIconRenderer.java
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterRunConfigurationProducer.java
- src/io/flutter/run/FlutterRunnerParameters.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- fix some warnings
- remove use of some dart plugin apis
@pq
> fix some warnings; remove use of some dart plugin apis

- src/io/flutter/sdk/FlutterSdk.java
- don't log process exit when run with no module
@pq (TBR)
> don't log process exit when run with no module

- build.gradle
- flutter-intellij.iml
> Add latest Dart plugin jar (163.10154.19).

- gradle.properties
- resources/flutter/colors.properties
- resources/flutter/icons.properties
- src/io/flutter/FlutterBundle.properties
- testing.md
- tool/colors/colors_main.dart
- tool/icons/icons_main.dart
- whitespace changes to a few files, and
- suppress some analysis warnings in properties files
(TBR)
> some whitespace changes, and suppress some analysis warnings

- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- tweak the ui for the flutter settings page (remove the default icon for the LinkLabel class)
TBR
> tweak the ui for the flutter settings page

- src/io/flutter/actions/FlutterRetargetAction.java
- src/io/flutter/actions/HotReloadFlutterAppRetarget.java
- src/io/flutter/actions/RestartFlutterAppRetarget.java
> Add place filtering to retargetable actions (#587).

- src/io/flutter/FlutterUtils.java
- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
- src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java
> Make version check occur on all fluttery files

- .idea/misc.xml
- src/io/flutter/FlutterUtils.java
- src/io/flutter/actions/OpenObservatoryAction.java
- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
- src/io/flutter/inspections/WrongModuleTypeNotificationProvider.java
- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/run/FlutterRunner.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
> Null checks, misc. cleanup.

- src/io/flutter/actions/FlutterRetargetAction.java
- src/io/flutter/actions/HotReloadFlutterApp.java
- src/io/flutter/actions/HotReloadFlutterAppRetarget.java
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/actions/RestartFlutterAppRetarget.java
* adds text and description to retargeted actions
@devoncarew
> Fix tooltips for restart/reload actions.

- resources/META-INF/plugin.xml
- src/io/flutter/run/daemon/FlutterDaemonController.java
- enable the bazel launch config
- pass the `--machine` and `--start-paused` flags to the flutter tool when launching
@pq
> enable the bazel launch config

- src/io/flutter/console/FlutterConsoleHelper.java
- src/io/flutter/sdk/FlutterSdk.java
> Fix race condition in console write on project creation (#514).

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- suppress a user-facing npe
- fix https://github.com/flutter/flutter-intellij/issues/603
@pq
> suppress a user-facing npe

- resources/META-INF/plugin.xml
> Flutter Plugin `0.1.8`.

- src/io/flutter/actions/HotReloadFlutterAppRetarget.java
- src/io/flutter/actions/RestartFlutterAppRetarget.java
- add reload actions to the nav toolbar (fix https://github.com/flutter/flutter-intellij/issues/605)
@pq
> add reload actions to the nav toolbar

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/analytics/Analytics.java
Follow up to https://github.com/flutter/flutter-intellij/pull/578, change the analytics toast to a sticky toast.
@pq
> change the analytics toast to a sticky toast

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/actions/OpenSimulatorAction.java
- src/io/flutter/run/FlutterAppState.java
> Bring simulator to front on run/debug (#611).

- .idea/copyright/chromium.xml
Follow-up from https://github.com/flutter/flutter-intellij/pull/623.
@devoncarew
> Update copyright profile.

- .idea/copyright/chromium.xml
As per https://github.com/flutter/flutter-intellij/pull/627#issuecomment-272286059...
> Copyright template tweak.

- .travis.yml
- rev the version of android studio we build against (`2.3 beta 2` was released)
@pq
> rev the version of android studio we build against

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/analytics/Analytics.java
- testSrc/unit/io/flutter/analytics/AnalyticsTest.java
- track the idea platform and api version
@pq, @mit-mit
> track the idea platform and api version

- .idea/misc.xml
Follow-up from https://github.com/flutter/flutter-intellij/pull/595.
* adds `"BorderFactoryClass"` config to client properties.
* does not remove border factories on save
One less place we need to post-process! 🤘 
@devoncarew @alexander-doroshko
> Allow for border factory editing in the forms UI.

- src/io/flutter/project/FlutterProjectOpenProcessor.java
More improvement to address #621.
On project open, if a pubspec exists and is fresher than `.packages`, pop a toast.
If they choose to update, `flutter packages upgrade` is run.
@devoncarew
> Add check on project open for out of date .packages (#621).

- src/io/flutter/project/FlutterProjectOpenProcessor.java
* ensures Flutter post-processing only occurs on projects with a Flutter module
@devoncarew 
(FWIW still working out how to add the Flutter module type in this flow...)
> Fix flutter project open to not be so greedy.

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/view/FlutterViewMessages.java
- testSrc/unit/io/flutter/analytics/AnalyticsTest.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- various and sundry intellij suggested cleanups
@pq, @skybrian
> various intellij suggested cleanups

- src/io/flutter/project/FlutterProjectOpenProcessor.java
Follow up to https://github.com/flutter/flutter-intellij/pull/652 - tweaks to the project open processor notification. This changes the notification over to use a button on the bottom instead of a hyperlink (similar to our analytics notification).
@pq
> tweaks to the project open processor notification

- src/io/flutter/utils/CollectionUtils.java
- src/io/flutter/utils/FlutterModuleUtils.java
Some collection utilities to make working with streams a little easier.
> Collection utilities.

- src/io/flutter/actions/OpenSimulatorAction.java
- src/io/flutter/project/FlutterProjectOpenProcessor.java
> minor formatting

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/analytics/ThrottlingBucket.java
- src/io/flutter/run/bazel/FlutterBazelAppState.java
- src/io/flutter/run/daemon/FlutterDaemonController.java
- src/io/flutter/run/daemon/FlutterDaemonService.java
- src/io/flutter/run/daemon/FlutterDevice.java
- fix https://github.com/flutter/flutter-intellij/issues/641
- send in platform arch info for the bazel launch config based on the selected device
@pq, @skybrian
> send in platform arch info for the bazel launch configs

- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/run/FlutterRunner.java
- src/io/flutter/run/FlutterRunnerParameters.java
- src/io/flutter/run/bazel/FlutterBazelRunner.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/utils/FlutterModuleUtils.java
- testSrc/integration/io/flutter/sdk/FlutterSdkUtilTest.java
- testSrc/integration/io/flutter/util/FlutterTestUtils.java
- third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
Round up of Dart Plugin API calls.
On-going.
This (and another I've got stashed) will make integrating with `HEAD` a bit easier.
@devoncarew
> Dart Plugin API dependency round-up.

- src/io/flutter/actions/DeviceSelectorAction.java
> Remove unused import.

- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/sdk/FlutterSdk.java
> Cleanup/consolidate Dart Plugin pub API interactions.

- src/io/flutter/actions/FlutterToolsActionGroup.java
> Fix Tools Menu visibility check (#678).

- CONTRIBUTING.md
These settings were a red herring and unneeded.
> Back out unneeded internal setup instructions.

- src/io/flutter/run/FlutterAppState.java
- src/io/flutter/sdk/FlutterSdk.java
> Unused import cleanup.

- src/io/flutter/view/FlutterViewFactory.java
> Disable auto-enable of the Flutter View (#691).

- src/io/flutter/console/FlutterConsoleHelper.java
> Fix 'flutter doctor' to work the second time it's run

- src/io/flutter/view/FlutterViewFactory.java
> Fix Flutter View initialization.

- resources/META-INF/plugin.xml
- src/io/flutter/actions/FlutterRetargetAppAction.java
- src/io/flutter/view/FlutterViewFactory.java
* fix button enablement in the Flutter View
* fix the reload action for apps launched from 'run'
@devoncarew
> 0.1.9.1 patch release.

- testing.md
> Instructions for verifying project open (#690)

- src/io/flutter/editor/FlutterPubspecNotificationProvider.java
> Improve module type testing for pubspec banner (#713).

- README.md
Remove fixed issue (Fixes #316)
Add two new issues
> Update known issues

- resources/META-INF/plugin.xml
- src/io/flutter/actions/ReloadFlutterAppRetarget.java
- src/io/flutter/actions/RestartFlutterAppRetarget.java
- add reload actions to the run menu
@pq, @skybrian
> add reload actions to the run menu

- src/io/flutter/run/daemon/FlutterDaemonControllerHelper.java
> Work around incorrectly reported device platform

- resources/META-INF/plugin.xml
- improve the location of the reload actions in the Run menu
@pq @skybrian
> improve the location of the reload actions in the Run menu

- src/io/flutter/view/FlutterView.java
- fix https://github.com/flutter/flutter-intellij/issues/772
@pq @skybrian
> fix a use after dispose exception

- resources/META-INF/plugin.xml
- src/io/flutter/view/FlutterView.java
* fix to a use after dispose exception in the Flutter View
> 0.1.11.1 patch release

- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/DaemonEvent.java
- testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java
- testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java
- testSrc/unit/io/flutter/testing/JsonTesting.java
This is a rewrite of the code to interact with an external process
using the Flutter Daemon protocol [1].
The classes aren't hooked up to anything yet. (Migration will happen
in a separate patch.)
[1] https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode
> Introduce DaemonApi and DaemonEvent

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/DeviceSelectorAction.java
> Display "Loading..." in device menu when loading

- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/run/FlutterRunConfigurationProducer.java
> Should run Flutter app by right-clicking on main.dart

- src/io/flutter/project/FlutterProjectOpenProcessor.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/utils/FlutterModuleUtils.java
> Auto create a run config on project open (#739).

- .gitignore
> Ignore vscode metatdata.

- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/FlutterConfigurationEditorForm.java
- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/daemon/FlutterAppService.java
- testSrc/unit/io/flutter/run/SdkFieldsTest.java
> Program arg support for run configs (799).

- resources/META-INF/plugin.xml
As per our conversation, whole numbers FTW.
Fixes: #738.
> Migrate version to whole numbers (#738).

- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/Launcher.java
- src/io/flutter/run/ObservatoryFile.java
- src/io/flutter/run/PositionMapper.java
- testSrc/unit/io/flutter/run/PositionMapperTest.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
No user-visible changes expected; this is for easier understanding
and testing.
- Added a couple basic unit tests
> Move source position mapping logic to PositionMapper

- resources/META-INF/plugin.xml
@devoncarew @skybrian @mit-mit
> `0.12.0` change notes.

- .travis.yml
- build.xml
- resources/META-INF/plugin.xml
- src/io/flutter/dart/DartPlugin.java
- src/io/flutter/dart/DartSdkLibUtilDelegate.java
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/FlutterSmallIDEGeneratorPeer.java
- src/io/flutter/run/PositionMapper.java
- src/io/flutter/run/daemon/DeviceService.java
- src/io/flutter/run/daemon/FlutterAppService.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkManager.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- testSrc/integration/io/flutter/testing/FlutterTestUtils.java
- testSrc/unit/io/flutter/dart/DartSdkLibUtilDelegateTest.java
- testSrc/unit/io/flutter/utils/FileWatchTest.java
- third_party/intellij-plugins-dart/testSrc/com/jetbrains/lang/dart/util/DartTestUtils.java
- tool/travis.sh
- update our product build matrix
- support 2017.1
- initial support for separate sdks per project
fix https://github.com/flutter/flutter-intellij/issues/823
> update our product build matrix

- .gitignore
- resources/META-INF/plugin.xml
> update changelog version

- src/io/flutter/sdk/FlutterSdk.java
> Fix to check for disposal before project access (#848).

- src/io/flutter/dart/DartSdkLibUtilDelegate.java
- testSrc/unit/io/flutter/dart/DartSdkLibUtilDelegateTest.java
(I believe the test broke when I upgraded the Dart plugin.)
> Fix a unit test to work again

- resources/META-INF/plugin.xml
@devoncarew Added bullet items for assists.
> Update release notes with assists

- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/run/daemon/FlutterAppService.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- pass in a FLUTTER_ENVIRONMENT env var when shelling out to the flutter cli
- fix https://github.com/flutter/flutter-intellij/issues/840
@skybrian
> pass in a FLUTTER_ENVIRONMENT env var when shelling out to the flutter cli

- testing.md
@devoncarew 
I changed File > Import to File > Open as that is the main flow. But should we still have File > Import in the test script?
> Add a few more testing steps

- resources/META-INF/plugin.xml
- remove the full restart keybinding (we just have a key binding got hot reload now)
@skybrian
> remove the full restart keybinding

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/view/FlutterView.java
- expose an additional toggle in the Flutter view to switch the device's platform rendering between iOS and Android
@pq @skybrian
> expose a toggle for switching the platform OS

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.java
- testSrc/unit/io/flutter/run/bazel/BazelFieldsTest.java
Depends on #887 (ignore the first commit until that lands).
> replace working directory in Bazel run config

- .idea/inspectionProfiles/Project_Default.xml
- src/io/flutter/console/FlutterConsoleFolding.java
- src/io/flutter/run/FlutterRunConfigurationProducer.java
- src/io/flutter/run/FlutterRunNotifications.java
- testSrc/unit/io/flutter/testing/Testing.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
Address a few IntelliJ warnings; @pq, @skybrian.
> address some IntelliJ warnings

- src/io/flutter/actions/RunFlutterAction.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/daemon/FlutterApp.java
> Update profile/release run enablement to track running Flutter app.

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/RunFlutterAction.java
- src/io/flutter/actions/RunProfileFlutterApp.java
- src/io/flutter/actions/RunReleaseFlutterApp.java
Updates menu text with selected run config (in keeping w/ other run menu items).
Message is a bit long...  Ideas welcome!
> Improve Flutter run menu item messaging.

- resources/META-INF/plugin.xml
> Remove defunct plugin version data.

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/FlutterPopFrameAction.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/OpenObservatoryAction.java
- src/io/flutter/view/FlutterView.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- implement drop frame for flutter apps
@skybrian
> Add flutter drop frame

- resources/META-INF/plugin.xml
- testSrc/unit/io/flutter/testing/Testing.java
- Jetbrains warning about unnecessary type inference seems to be incorrect?
- Registering the same action id twice causes tests to fail
> fix build and fix unit tests to work again

- src/io/flutter/project/FlutterIconProvider.java
cc @alexander-doroshko @devoncarew
> Limit Flutter Icon customizations to Flutter projects.

- build.xml
- resources/META-INF/idea-contribs.xml
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/run/SdkFields.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/utils/FileWatch.java
- testSrc/unit/io/flutter/analytics/AnalyticsTest.java
- testSrc/unit/io/flutter/testing/TestDir.java
- testSrc/unit/io/flutter/utils/RefreshableTest.java
* suppressed empty method warnings
* suppressed same return value warnings
* removed unnecessary (empty) overrides
* removed unneeded `throws`
* removed stale `version` plugin id
* suppressed ant resolutions warnings
> Misc. cleanups.

- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/utils/FlutterModuleUtils.java
> Fix setting of Flutter metadata in imported projects (#927).

- resources/META-INF/plugin.xml
> Remove defunct SdkService references.

- src/io/flutter/analytics/Analytics.java
- change user agent to better handle analytics on windows
- fix https://github.com/flutter/flutter-intellij/issues/879
This fix is a bit of a shot in the dark, as we have a long latency between a change here and knowing if it's correctly handled by google analytics. This change does bring our synthetic user agent in-line with the dart package:usage, which does correctly identify the platform.
@skybrian
> change user agent to better handle analytics on windows

- resources/META-INF/plugin.xml
See: #930.
@skybrian @devoncarew 
FYI: @mit-mit
> Disable profile and release run modes pending fixes (#930).

- src/io/flutter/actions/FlutterSdkAction.java
- save dirty documents before running flutter actions
- fix https://github.com/flutter/flutter-intellij/issues/947
@pq @skybrian
> save all before running flutter actions

- src/io/flutter/FlutterConstants.java
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterPackagesGetAction.java
- src/io/flutter/actions/FlutterPackagesUpgradeAction.java
- src/io/flutter/actions/FlutterSdkAction.java
- src/io/flutter/actions/FlutterUpgradeAction.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/project/FlutterProjectOpenProcessor.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/sdk/FlutterSdk.java
Probably no user-visible changes.
> Simplify FlutterSdkAction and subclasses

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/analytics/Analytics.java
- src/io/flutter/analytics/ToolWindowTracker.java
- add analytics for tool window usage
@pq, @skybrian
> add analytics for tool window usage

- .travis.yml
- build.xml
@skybrian, rev to the latest intellij versions (some prep work before looking at getting tests running on the bots)
> rev to the latest intellij versions

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/sdk/FlutterSdk.java
> Show lib/main.dart after creating a new project

- src/io/flutter/actions/DeviceSelectorAction.java
- display 'no devices' when there are not devices connected
- some work towards https://github.com/flutter/flutter-intellij/issues/971
@skybrian
> display 'no devices' when there are not devices connected

- src/io/flutter/actions/DeviceSelectorAction.java
- fix an issue w/ displaying 'no devices' text
@skybrian
> fix an issue w/ displaying 'no devices' text

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/pub/PubRoot.java
@pq, @skybrian - quiet a few IntelliJ inspections
> cleanup from IntelliJ inspections

- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkUtil.java
- src/io/flutter/sdk/FlutterSdkVersion.java
- gracefully handle if the flutter sdk has no VERSION file
@pq
> gracefully handle if the flutter sdk has no VERSION file

- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterUpgradeAction.java
- src/io/flutter/console/FlutterConsole.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/console/FlutterConsoles.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Introduced FlutterCommand and moved the low-level details of launching
processes there.
Also, somewhat better error reporting in a few places.
> clean up API for starting Flutter commands

- src/io/flutter/FlutterMessages.java
- src/io/flutter/run/daemon/DaemonEvent.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- testSrc/unit/io/flutter/run/daemon/DaemonEventTest.java
- handle the daemon showMessage event
- added docs for the event here: https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode#showmessage
- fix https://github.com/flutter/flutter-intellij/issues/980
@skybrian (/cc @tvolkert)
> handle the daemon showMessage event

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/android/AndroidSdk.java
- src/io/flutter/pub/PubRoot.java
(This only happens if the Android SDK already exists and the project's Java SDK is unset.)
Fixes #1001
> On project open, set the Java SDK based on ANDROID_HOME

- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/FlutterModuleBuilder.java
- testSrc/unit/io/flutter/FlutterUtilsTest.java
> Add package_name validation (#1009)

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- Removed an unnecessary retry loop.
- Started reporting the URL that we failed to connect to.
- Untangled the code.
> clean up error handling for Observatory connection failure

- src/io/flutter/view/OpenFlutterViewAction.java
See https://github.com/flutter/flutter-intellij/issues/1028.
@devoncarew
> Null check on Flutter View open (#1028).

- src/io/flutter/module/FlutterModuleBuilder.java
Look in the new location first.
See: https://github.com/flutter/flutter/pull/10163
> Prepare for renaming Android module

- src/io/flutter/module/FlutterModuleBuilder.java
(Please look at the second commit.)
Fixes https://github.com/flutter/flutter-intellij/issues/1014
> Fix File->New->Module to work for Flutter

- README.md
@mit-mit  @devoncarew 
Not sure if there's a good bug to link to?
FYI @tvolkert
> Doc Observatory timeouts in known issues.

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
> change the option name for verbose logging

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/view/FlutterView.java
- re-organize the flutter view toolbar
- fix https://github.com/flutter/flutter-intellij/issues/1024, fix https://github.com/flutter/flutter-intellij/issues/1025
@pq, @skybrian, /cc @jacob314
> re-organize the flutter view toolbar

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/FlutterModuleType.java
this commit doesn't break compilation against 2017.1
> Fix compilation against IntelliJ IDEA 2017.2

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
Fixes: #1064.
@devoncarew @skybrian 
This is a little inelegant but expedient (and I didn't see a better way that wouldn't involve a bunch of swizzling of bits around).
Happy to revisit.
> Capture and report `flutter create` error details (#1064).

- src/io/flutter/actions/FlutterExternalIdeActionGroup.java
Allows for opening from:
* project dir
* `ios` dir
Follow-up on #880
@devoncarew
> Improve “Open in Xcode” filtering (#880)

- src/io/flutter/pub/PubRoot.java
- src/io/flutter/run/test/TestConfig.java
- src/io/flutter/run/test/TestConfigProducer.java
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/run/test/TestForm.form
- src/io/flutter/run/test/TestForm.java
- src/io/flutter/sdk/FlutterSdk.java
The directory can be the pub root, the "test" directory, or any
subdirectory of "test".
If it's the pub root, we just run "flutter test".
Also, simplify PubRoot.fromPsiFile() slightly (remove fallback).
> Add support for running all tests in a directory

- src/io/flutter/run/test/TestForm.form
- src/io/flutter/run/test/TestForm.java
- testSrc/unit/io/flutter/run/test/TestFieldsTest.java
- set a default value so the field doesn't become blank
- increase margin so the fields don't move
> Test configs: make switching between scopes smoother

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/analytics/ToolWindowTracker.java
- only init analytics for flutter projects (fix https://github.com/flutter/flutter-intellij/issues/1084)
@pq
> only start analytics for flutter projects

- src/io/flutter/actions/InstallSdkAction.java
- src/io/flutter/module/FlutterGeneratorPeer.form
- src/io/flutter/module/FlutterGeneratorPeer.java
First cut: opens `flutter.io` setup URL.  Next step, add git workflow.
See: #764.
@devoncarew
> SDK “Install…” action link (#764).

- resources/META-INF/plugin.xml
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/daemon/DaemonConsoleView.java
- src/io/flutter/run/test/DebugTestRunner.java
- src/io/flutter/run/test/TestConfig.java
- src/io/flutter/run/test/TestDebugProcess.java
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/run/test/TestLaunchState.java
- src/io/flutter/sdk/FlutterSdk.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
The debug button is only activated when running all the tests in a file
(not a directory).
> Add support for running a Flutter test in the debugger

- src/io/flutter/sdk/FlutterSdkUtil.java
- change the env var name for flutter_host
- fix https://github.com/flutter/flutter-intellij/issues/1113
@skybrian
> change the env var name for flutter_host

- src/io/flutter/run/daemon/DaemonConsoleView.java
- src/io/flutter/run/test/DebugTestRunner.java
- src/io/flutter/run/test/TestConfig.java
- src/io/flutter/run/test/TestLaunchState.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkVersion.java
Depends on: https://github.com/flutter/flutter/pull/10848
> Display a proper UI for test progress

- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/bazel/WorkspaceCache.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/DaemonConsoleView.java
- src/io/flutter/run/daemon/DaemonEvent.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/run/daemon/DeviceSelection.java
- src/io/flutter/run/daemon/DeviceService.java
Also, reorder assertions to be before declarations and signatures to be consistent with other JetBrains plugin source.
> Add missing guaranteed assertions about nullability

- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
> Change the SDK configuration notification provider to exit if the project is configured as a Bazel-Flutter project.

- src/io/flutter/actions/InstallSdkAction.java
- src/io/flutter/module/FlutterGeneratorPeer.form
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/module/FlutterModuleBuilder.java
Still some noodling to do but this gets us a bit further...
* adds cancel UI
* hooks up errors to wizard status line
* filters unfriendly progress details
* automatically advances to project configuration page on successful installation
* adds install action link icons
@devoncarew 
See: #764
> SDK install flow improvements (#764).

- src/io/flutter/FlutterUtils.java
- src/io/flutter/actions/InstallSdkAction.java
- src/io/flutter/module/FlutterModuleBuilder.java
* implement `hasGit` and flip the bit
* fix local filesystem refresh issues w/ newly cloned SDKs
See: #764.
@devoncarew
> SDK install flow fixes and bit flip (#764).

- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/module/InstallSdkAction.java
@pq, for your consideration: move InstallSdkAction.java into flutter/module
> refactor - move InstallSdkAction.java into flutter/module

- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/InstallSdkAction.java
Prefer testing for clean execution over mere PATH presence check.
@devoncarew
> Harden git existence check.

- src/io/flutter/module/InstallSdkAction.java
> SDK install workflow analytics.

- src/io/flutter/module/InstallSdkAction.java
> `flutter precache` commandline setup improvements.

- README.md
> Update min IntelliJ version.

- src/io/flutter/module/InstallSdkAction.java
Fixes: #1149 
@devoncarew @mit-mit
> Clone `alpha` in git install action (#1149).

- src/io/flutter/module/FlutterSmallIDEGeneratorPeer.java
- src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
- src/io/flutter/sdk/FlutterCommand.java
- fix https://github.com/flutter/flutter-intellij/issues/1146
- fix an issue with the flutter sdk field not showing in the webstorm new project wizard
- fix an npe after project creation (after flutter create), trying to refresh the file system
@pq
> fix issues w/ project creation in small IDEs

- src/io/flutter/module/FlutterGeneratorPeer.java
> Fix progress font (#1148).

- src/io/flutter/module/InstallSdkAction.java
Refactoring for clarity.
Functionally the same but I hope a little easier to follow.
@devoncarew @jwren
> Install Action cleanup.

- src/io/flutter/module/FlutterSmallIDEGeneratorPeer.java
- src/io/flutter/module/FlutterSmallIDEProjectGenerator.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- update some todos
- no longer disable logging debugger traffic (the NPE we were hitting is long since fixed)
@pq @jwren
> update our logging

- src/io/flutter/run/test/TestConfigProducer.java
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/run/test/TestForm.form
- src/io/flutter/run/test/TestForm.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSdkVersion.java
- testSrc/unit/io/flutter/run/test/TestFieldsTest.java
Depends on:
https://github.com/flutter/flutter/pull/11020
> Add support for running a single Flutter test, by name

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterPackagesGetAction.java
- src/io/flutter/actions/FlutterPackagesUpgradeAction.java
- src/io/flutter/actions/FlutterSdkAction.java
- src/io/flutter/actions/FlutterUpgradeAction.java
- src/io/flutter/inspections/FlutterDependencyInspection.java
- src/io/flutter/run/test/TestLaunchState.java
> Exception cleanup.

- src/io/flutter/run/test/DebugTestRunner.java
- src/io/flutter/run/test/TestConfigProducer.java
- src/io/flutter/run/test/TestFields.java
- Allow running it in the debugger.
- Allow user to run a single test by right-clicking, either in
source code or on a test in the test tree widget.
> Improvements to running a single Flutter test

- src/io/flutter/dart/DartSyntax.java
- src/io/flutter/run/test/TestConfigProducer.java
- testSrc/unit/io/flutter/dart/DartSyntaxTest.java
(They just cover the happy path, but more could be written.)
> Cleanup: move AST queries to a separate class and write basic tests.

- src/io/flutter/sdk/FlutterSdkVersion.java
> Inspection cleanup.

- src/io/flutter/run/FlutterRunConfigurationProducer.java
- src/io/flutter/run/test/TestConfigProducer.java
- allow running flutter tests in //packages/flutter/
- fix https://github.com/flutter/flutter-intellij/issues/1177
@skybrian @pq
> allow running flutter tests in //packages/flutter/

- resources/META-INF/plugin.xml
- src/io/flutter/actions/FlutterGettingStartedAction.java
- src/io/flutter/actions/RestartFlutterDaemonAction.java
- src/io/flutter/run/daemon/DeviceService.java
- add an action to restart the flutter daemon (fix https://github.com/flutter/flutter-intellij/issues/1143)
@pq
> add a restart flutter daemon action

- flutter-intellij-community.iml
Does making this change cause any problems for HEAD?
It fixes 22 compile errors for my experimental branch.
I'm not sure why this change wasn't required to implement the test UI.
> Add module deps

- src/io/flutter/dart/DartSyntax.java
- src/io/flutter/run/test/FlutterTestLineMarkerContributor.java
- src/io/flutter/run/test/TestConfigProducer.java
- src/io/flutter/run/test/TestConfigUtils.java
- testSrc/unit/io/flutter/dart/DartSyntaxTest.java
* adds support for group config discovery
* adds markers for groups and main
* cleans up tooltips
@devoncarew
> Support for test groups.

- src/io/flutter/editor/FlutterEditorAnnotator.java
- src/io/flutter/utils/FlutterModuleUtils.java
> Move the static FlutterEditorAnnotator.isInFlutterModule into FlutterModuleUtils

- src/io/flutter/run/test/TestConfigUtils.java
Centralizes mapping of function names to test types (to ease adding `testWidgets` support once location issues are resolved).
@stevemessick @jwren
> Centralized test function mapping.

- src/io/flutter/project/FlutterIconProvider.java
Identifies test files (w/ a simple heuristic) in the project view and editor tabs.
@stevemessick
> Icon annotations for test files.

- src/io/flutter/actions/FlutterDoctorAction.java
- src/io/flutter/actions/FlutterSdkAction.java
- src/io/flutter/bazel/PluginConfig.java
- src/io/flutter/bazel/Workspace.java
- testSrc/unit/io/flutter/bazel/WorkspaceTest.java
> Bazel workspace configuration support for running a flutter doctor script

- src/io/flutter/FlutterUtils.java
- src/io/flutter/dart/DartSyntax.java
- src/io/flutter/run/FlutterRunConfigurationProducer.java
- src/io/flutter/run/test/TestConfigUtils.java
- testSrc/unit/io/flutter/dart/DartSyntaxTest.java
* test call check short-circuiting to avoid needless Psi Element traversals
* minor cleanup
@stevemessick @jwren
> Test discovery optimization.

- src/io/flutter/run/test/TestConfigProducer.java
Follow up on https://github.com/flutter/flutter-intellij/commit/435a43b1f5b9dd04e06beeda6694c2d0087d3186#comments, improves Flutter test scoping to handle projects that contain multiple modules (both Flutter and plain Dart).
@devoncarew
> Improve Flutter test context detection.

- src/io/flutter/run/test/TestLaunchState.java
> Add relative path hyperlinks to the Flutter Test console view.

- src/io/flutter/run/test/TestLaunchState.java
> Test console filters for URLs and Flutter Doctor output.

- src/io/flutter/android/AndroidSdk.java
- src/io/flutter/android/IntelliJAndroidSdk.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
- pull the android sdk location from flutter tools (flutter config --machine)
- fix https://github.com/flutter/flutter-intellij/issues/1150
- related cleanup to `FlutterCommand.java` and notifying the dart plugin when we're running pub related commands
@pq
> pull the android sdk location from flutter tools

- .travis.yml
- rev versions we build against
- re-add android studio (fix https://github.com/flutter/flutter-intellij/issues/1209)
> rev versions we build against; re-add android studio

- CONTRIBUTING.md
- README.md
- flutter-intellij.iml
- move the android studio docs to the contributing page
@stevemessick
> move the android studio docs to the contributing page

- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/run/daemon/DeviceService.java
One half of fixing an issue when upgrading the dart sdk in use by the flutter sdk (work towards https://github.com/flutter/flutter-intellij/issues/1155). This PR changes errors from the device daemon to not be hard errors - things that we show to users in dialogs.
@stevemessick
> work towards fixing an sdk upgrade issue

- src/io/flutter/FlutterStudioInitializer.java
- src/io/flutter/actions/FlutterSdkAction.java
- src/io/flutter/bazel/Workspace.java
- src/io/flutter/inspections/SdkConfigurationNotificationProvider.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/run/daemon/DeviceService.java
> Cleanup unused imports.

- src/io/flutter/run/daemon/DeviceSelection.java
- src/io/flutter/run/daemon/DeviceService.java
- ensure that a device is selected (if any have been discovered)
> always select a device

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/android/IntelliJAndroidSdk.java
- src/io/flutter/sdk/FlutterSdk.java
- cache the value of the android sdk returned from flutter_tools; make device switching faster (fix https://github.com/flutter/flutter-intellij/issues/1240)
There is still a delay in redrawing the device selector combo box (which I wasn't able to suss out), but we're no longer blocking the UI thread.
@pq
> faster device switching

- src/io/flutter/actions/DeviceSelectorAction.java
- src/io/flutter/sdk/FlutterSdk.java
- improve the speed of the device pulldown (fix https://github.com/flutter/flutter-intellij/issues/1240); we now remember FlutterSdk instances for project:sdk_path combos
- when the device menu is open, show the currently selected device's menu as selected
@pq
> improve the speed of the device pulldown

- src/io/flutter/project/FlutterIconProvider.java
> Restore lost project icons (#1245)

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/settings/FlutterCreateAddtionalSettingsFields.java
- src/io/flutter/module/settings/ProjectType.form
- src/io/flutter/module/settings/ProjectType.java
- src/io/flutter/module/settings/SettingsHelpForm.form
* migrate to a combo for project type
* remove driver creation option
* improve help form alignment
@devoncarew 
Fixes: #1262.
> Project Wizard UI iteration (#1262)

- src/io/flutter/run/LaunchState.java
- when we launch an app, check for analysis errors, and display a tool window tooltip on the analysis view if there are any
- fix https://github.com/flutter/flutter-intellij/issues/729
@pq 
We're using reflection for now - we can move to using at compile time when we rev to 2017.2,
> display any analysis issues on run

- src/io/flutter/actions/FlutterAppAction.java
- src/io/flutter/run/LaunchState.java
Follow up from https://github.com/flutter/flutter-intellij/pull/1272; @pq.
> review follow up

- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/test/TestForm.java
- src/io/flutter/sdk/FlutterSdkManager.java
Fixes a few possible NPEs and updates API contracts.
> Null checks and API updates.

- src/io/flutter/run/LaunchState.java
> use StringUtil from com.intellij.openapi.util.text

- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/LaunchState.java
- show the memory page when running in profile mode
This adds the memory page action when we're running a flutter app in profile mode.
@B3rn475
> show the memory page when running in profile mode

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- move the experimental settings into their own group
- rename the accessor method for `isMemoryDashboard` => `isMemoryDashboardEnabled()`
@pq @B3rn475
> refactor the prefs ui screen

- build.xml
@devoncarew @pq Changes to the build script to conditionally compile the flutter-studio module for AS and produce a ZIP file in that case only.
> Build zip file for AS, jar for others

- src/io/flutter/view/FlutterView.java
update the flutter view toolbar:
- use a different toolbar component. The icons have color now, and they can show enablement and disablement
- use a sub-menu as the action overflow (for less common actions)
- fix the method call for enabling the inspector (/cc @jacob314)
@stevemessick
> redo the flutter toolbar

- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
@devoncarew As requested, switch to the Project view after creating a new Flutter project in AS.
It would be nice, I think, to autoscroll the project tree and select the file that is open in the editor. Haven't figured out how to do that yet.
> Switch to Project view after creating a Flutter project

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/FlutterProjectType.java
- src/io/flutter/module/settings/FlutterCreateAddtionalSettingsFields.java
- src/io/flutter/module/settings/ProjectType.java
- src/io/flutter/module/settings/SettingsHelpForm.form
- src/io/flutter/module/settings/SettingsHelpForm.java
- src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
- testSrc/unit/io/flutter/sdk/FlutterCreateAddtionalSettingsTest.java
Add an option to create packages, in addition to apps and plugins.
The help text could be improved (in another PR).
fix https://github.com/flutter/flutter-intellij/issues/1291
> Add Package option

- resources/META-INF/plugin.xml
- rev to M17 (https://github.com/flutter/flutter-intellij/issues/1248)
- update the changelog
@stevemessick @mit-mit @pq
> rev to M17; update the changelog

- .travis.yml
- build.xml
@devoncarew For after the new file has been uploaded.
> Update build script for AS beta 3

- src/io/flutter/actions/RunFlutterAction.java
- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/FlutterConfigurationEditorForm.java
- src/io/flutter/run/SdkFields.java
- add a text field for the `--flavor` arg to flutter run (fix https://github.com/flutter/flutter-intellij/issues/1289)
@stevemessick
> support the --flavor flutter run arg

- src/io/flutter/actions/OpenInXcodeAction.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/utils/FlutterModuleUtils.java
- add the ability to open XCode for plugin projects (fix https://github.com/flutter/flutter-intellij/issues/1117)
@pq
> open xcode projects for plugins

- .travis.yml
- build.xml
> Build for AS beta 5

- src/io/flutter/settings/FlutterSettings.java
- src/io/flutter/view/FlutterView.java
- make reload on save be the default (address much of https://github.com/flutter/flutter-intellij/issues/1331)
- (also, update an icon in the flutter view to be more consistent w/ other IntelliJ icons)
> make reload on save be the default

- src/io/flutter/run/FlutterReloadManager.java
- fix an issue where we could issue a reload (on save) while another reload was in progress (fix https://github.com/flutter/flutter-intellij/issues/1333)
> make sure we don't issue two reloads in parallel

- src/io/flutter/FlutterUtils.java
- src/io/flutter/actions/FlutterExternalIdeActionGroup.java
- src/io/flutter/actions/OpenInAndroidStudioAction.java
fix https://github.com/flutter/flutter-intellij/issues/1334
> hide the 'open in android studio' menu item in android studio

- .travis.yml
- build.xml
Updates the build scripts to compile against Android Studio 3.0 beta 6.
> Build for AS beta 6

- src/io/flutter/pub/PubRoot.java
@pq Declare vars final, for consistency.
> Make vars final

- flutter-intellij-community.iml
- src/io/flutter/pub/PubRoot.java
This shouldn't hurt anything, but let's see if the travis build passes.
@devoncarew
> Add dep on snakeyaml

- src/io/flutter/run/FlutterReloadManager.java
- add a hyperlink to open the analysis view from the reload-on-save notification (fix https://github.com/flutter/flutter-intellij/issues/1309)
- some clean up in the FlutterReloadManager class - some lints found by IntelliJ, and an inadvertent `if (true)` that was committed (after the last release)
> add a hyperlink to the reload notification

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
@pq @devoncarew This fixes a problem that caused the SDK path text to be cleared if the `Install SDK` button was clicked, then the file chooser was cancelled.
> Initialize the SDK path cache

- flutter-studio/src/io/flutter/project/FlutterProjectModel.java
@pq @devoncarew The default domain should not be reversed.
> Set the default domain correctly

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
@devoncarew Add a TODO, as promised to @pq
> Add a TODO

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/InstallSdkAction.java
Reduce the complexity of the labels on the check boxes to make them easier to read.
> Shorten labels to improve readability

- src/io/flutter/FlutterBundle.properties
@pq @devoncarew @mit-mit Uses more conservative default names for projects. They still illustrate the snake_case naming convention.
> Change default names

- src/io/flutter/module/InstallSdkAction.java
@pq @devoncarew Refresh files in the SDK directory after installing the SDK. Tested with both AS and IJ wizards.
> Refresh files

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
@pq @devoncarew @mit-mit 
This depends on https://github.com/flutter/flutter/pull/12391
Rather than allowing Android Studio to open a newly created project, this forces a reload so the files written by Flutter are used. AS writes a few files that just confuse its world before running `flutter create`. This gets rid of them before running flutter since flutter won't overwrite them.
This also adds an Android facet to apps and plugins.
Fixes: #1347, #1370
> Create projects to open as they would when created from the cmd line

- src/io/flutter/run/OpenMemoryDashboardAction.java
- src/io/flutter/run/OpenObservatoryAction.java
- src/io/flutter/view/FlutterView.java
- use the default BrowserLauncher to open a url (fix https://github.com/flutter/flutter-intellij/issues/1308)
> use the default BrowserLauncher to open a url

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
> Address review comment

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- fix an issue with disabling reload on save - we need to specify the default value when using PropertiesComponent (fix https://github.com/flutter/flutter-intellij/issues/1388)
> fix an issue with disabling reload on save

- src/io/flutter/module/settings/FlutterCreateAddtionalSettingsFields.java
- testSrc/unit/io/flutter/utils/FlutterModuleUtilsTest.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
> Clean up: lambdas, method refs and redundant throws.

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- src/io/flutter/FlutterUtils.java
- src/io/flutter/module/FlutterModuleBuilder.java
> Fix method name typo

- .travis.yml
- resources/META-INF/plugin.xml
Trial run of 2017.3 EAP (fix https://github.com/flutter/flutter-intellij/issues/1348).
> 2017.3 EAP

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
> Make punctuation consistent in wizard error messages

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
> Remove extra quote

- flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
Also adds toString() which makes testing easier.
> Make coverage easier to understand

- flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
Ensure events get triggered when the combo box selection is changed.
> Combo select

- resources/META-INF/plugin.xml
- src/io/flutter/inspector/DiagnosticLevel.java
- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/DiagnosticsPathNode.java
- src/io/flutter/inspector/DiagnosticsTreeStyle.java
- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorActions.java
- src/io/flutter/inspector/InspectorInstanceRef.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/inspector/InspectorTreeActionBase.java
- src/io/flutter/inspector/JumpToSourceAction.java
- src/io/flutter/inspector/JumpToSourceActionBase.java
- src/io/flutter/inspector/JumpToTypeSourceAction.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/FlutterViewMessages.java
- src/io/flutter/view/InspectorPanel.java
I'm still cleaning up InspectorPanel and FlutterView. All other files are generally ready for review.
> Inspect functionality

- src/io/flutter/pub/PubRoots.java
- src/io/flutter/run/FlutterReloadManager.java
> Exclude errors in tests from blocking Reload on Save (#1437).

- flutter-intellij-community.iml
Add xdebugger-impl to the module deps.
Am I the first to compile with the new inspector?
> Fix compile errors

- src/io/flutter/project/FlutterIconProvider.java
> Limit Flutter project icon contributions to Flutter projects.

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/ProjectOpenActivity.java
- src/io/flutter/project/FlutterProjectOpenProcessor.java
Net-net:  limit extra initialization to Flutter-declaring projects.
Fixes: #1441 
@devoncarew
> Scope Flutter Project initialization smarts.

- src/io/flutter/FlutterInitializer.java
Follow-up from: https://github.com/flutter/flutter-intellij/pull/1446#pullrequestreview-72354578
> Only auto open main if no other editors are open.

- src/io/flutter/FlutterUtils.java
- testSrc/unit/io/flutter/FlutterUtilsTest.java
Migrated to possessive quantifiers to get a big speed boost.
Fixes: #1421 
@stevemessick
> Speed up package ID regexp (#1421).

- src/io/flutter/FlutterUtils.java
Cleanup a wee bit of duplication.
@stevemessick
> Tidy up “is in flutter project” check.

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/FlutterUtils.java
- fix an npe in android studio
- compile the plugin source with line number to aid future debugging
The NPE we were seeing was:
```
at io.flutter.FlutterInitializer.getAnalytics(FlutterInitializer.java:67)
at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:205)
at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:143)
at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:346)
at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:161)
at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:305)
```
@stevemessick
> fix an npe in android studio

- src/io/flutter/sdk/FlutterPluginsLibraryManager.java
- src/io/flutter/utils/FlutterModuleUtils.java
- make sure we don't create entries for non-flutter projects (fix https://github.com/flutter/flutter-intellij/issues/1459)
> make sure we don't create entries for non-flutter projects

- src/io/flutter/run/test/TestConfigUtils.java
> Fix running flutter tests nested in groups (#1439).

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorInstanceRef.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/inspector/JumpToSourceActionBase.java
- src/io/flutter/view/InspectorPanel.java
@jacob314, minor tweaks to the inspector code - reformat, and add `final` and other to address some analysis hints.
> fmt and some analysis hints

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
#1436 asks for some way to inform the user that a valid Flutter SDK path has been entered.
With this change the SDK field has a normal background color when the path is correct. Otherwise, it changes as shown in the screen shots. This is only for the Android Studio version. Once we determine this is viable it (or whatever it morphs into) can be applied to the other.
> Change SDK background

- resources/META-INF/plugin.xml.template
Follow-up from: https://github.com/flutter/flutter-intellij/pull/1473#discussion_r149150345
@stevemessick
> Suppress PluginXmlValidity issue.

- flutter-intellij-community.iml
This is the iml file I use for AS dev.
> Add Dart dep

- src/io/flutter/view/InspectorPanel.java
Nothing substantial but arguably a little tidier.
Feel free to ignore! 😄 
@jacob314
> Java8 lambda cleanups.

- .travis.yml
- docs/testing.md
- reduce the product matrix
@mit-mit @stevemessick @pq
> reduce the product matrix

- .travis.yml
- build.xml
- drop one bot from travis (test android studio, and IntelliJ 2017.1, 2017.2, and 2017.3 eap)
- update the versions in the build+travis scripts
> update the versions in the build+travis scripts

- src/io/flutter/inspector/FlutterWidget.java
- src/io/flutter/inspector/widgets.json
- src/io/flutter/utils/JsonUtils.java
- testSrc/unit/io/flutter/inspector/FlutterWidgetTest.java
Widget catalog derived from `widgets.json` for use in the inspector for widget categorization.
Babysteps.
I'm looking at icons and the way we do that may change some of the details but this at least gets the basic categories handy.
@jacob314 @devoncarew
> Widget Catalog first cut.

- .gitignore
- update the gitignore to ignore .idea files not explicitly added to git
@pq @mess
> update the gitignore to ignore .idea files not explicitly added to git

- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- src/io/flutter/FlutterBundle.properties
Fixes the label on the project location directory picker.
This label doesn't even show up on the Mac when the plugin is installed. It does show up when launched from sources.
> Fix location label

- src/io/flutter/inspector/FlutterWidget.java
- src/io/flutter/utils/JsonUtils.java
@jacob314 
I just changed the import statement to use JetBrains Nullable. I got compile errors from the javax one.
> Use the other Nullable

- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Introduced a small refactoring to make it possible to write tests that check interesting things.
Made one new test work.
> Refactor for testability

- src/io/flutter/run/FlutterReloadManager.java
- fix an exception on reload on save
```
cannot share data context between Swing events; initial event count = 661100; current event count = 661223
java.lang.Throwable
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:363)
at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:59)
at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:165)
at com.intellij.openapi.actionSystem.AnActionEvent.getProject(AnActionEvent.java:120)
at io.flutter.run.FlutterReloadManager$1.afterActionPerformed(FlutterReloadManager.java:114)
```
The issue seems to be that we can have a new event created and sent before we receive the `afterActionPerformed` notification, and …
> fix an exception in reload on save

- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Implement `plugin --release=NN deploy`. The argument is required. The current git branch should be named "release_NN" -- but that is not being enforced yet.
The `upload()` method has not been tested yet.
There are some formatting changes from running it through dartfmt.
> plugin deploy

- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Sort file contents. No other changes.
> Sort file content

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/run/bazel/BazelFields.java
Bazel run configuration changes: Remove assistance around appending_run_hot; additional message to assert that Bazel targets start with //
> Bazel run configuration changes

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/FlutterWidget.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- testSrc/unit/io/flutter/inspector/FlutterWidgetTest.java
A little hacky but gets us into a place to start experimenting in earnest.
@devoncarew @stevemessick 
FYI: @jacob314
> Inspector View widget filtering basics.

- CONTRIBUTING.md
> Update current CE version.

- .idea/misc.xml
Reverts change that (mistakenly) snuck into: https://github.com/flutter/flutter-intellij/pull/1468.
@stevemessick @jwren
> Fix project SDK.

- src/io/flutter/module/FlutterModuleBuilder.java
> Fix project creation to respect custom options.

- src/io/flutter/utils/FlutterModuleUtils.java
> Prefer opening xcode workspace files (#1526).

- product-matrix.json
- resources/META-INF/plugin.xml
- tool/plugin/lib/plugin.dart
Finish `plugin build`; implement `plugin gen`. Most of .travis.yml is embedded in the code but that's easy to change if needed. I just didn't find a better place to put it.
I plan to work on `plugin test` after getting some GUI tests running.
> Plugin tool progress

- src/io/flutter/inspector/InspectorService.java
- use `VmServiceConsumers.EMPTY_SUCCESS_CONSUMER` in two places
@jacob314 @pq
> misc cleanups to the InspectorService.java

- tool/plugin/analysis_options.yaml
- tool/plugin/bin/main.dart
- tool/plugin/lib/plugin.dart
- tool/plugin/lib/src/lint.dart
- tool/plugin/test/plugin_test.dart
As promised, code clean-up driven by additional lint rules.
I'm a bit conflicted about "type_annotate_public_apis". It caused addition of types where I had actually not wanted them. Oh well...perhaps the style guide suggests them -- I don't have it memorized.
> Add some lint rules and clean up the code

- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/utils/VmServiceListenerAdapter.java
- src/io/flutter/view/FlutterView.java
> add an abstract VmServiceListenerAdapter.java

- src/io/flutter/run/daemon/DaemonConsoleView.java
@pq @stevemessick, fix an issue with the recently introduced console filtering. My last PR didn't take into account the different types of console output (`NORMAL_OUTPUT`, `SYSTEM_OUTPUT`, ...).
> fix an issue with the recently introduced console filtering

- src/io/flutter/inspections/IncompatibleDartPluginNotificationProvider.java
>  Stop complaining about Dart version when run from sources

- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/view/InspectorPanel.java
Created this change to match code review comments from the flutter repo CL but forgot to send it out.
> Change method name to match Flutter side of Inspector changes.

- src/io/flutter/view/InspectorPanel.java
Fixes https://github.com/flutter/flutter-intellij/issues/1542
> Handle edge cases when an isolate is stopped or selection is null.

- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
> Download files

- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- enable the inspector pref setting
@jacob314
> enable the inspector pref setting

- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
- flutter-studio/testSrc/io/flutter/tests/util/WizardUtils.java
- tool/plugin/lib/plugin.dart
@devoncarew @jacob314 
Also, a small refactoring for readability.
> Add comments suggested by reviewers

- src/io/flutter/inspector/FlutterWidget.java
Thanks Steve for identifying the issue!
Problem was multiple jars in Android Studio mean that only some ways of loading resources will work.
> Make loading Widget Catalog work in Android Studio.

- tool/plugin/README.md
@devoncarew @pq @jacob314 @jwren
> Add remote debugging instructions

- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/utils/FlutterModuleUtils.java
- select an existing config at launch
- fix https://github.com/flutter/flutter-intellij/issues/1565
@pq
> select an existing config at launch

- product-matrix.json
> Change since build id

- tool/plugin/test/plugin_test.dart
> Update tests to work with revised provisioning

- tool/plugin/lib/plugin.dart
> Add -ide for AS file name

- src/io/flutter/FlutterUtils.java
- src/io/flutter/run/test/TestConfigProducer.java
> Fix test discovery for plugin example tests (#1572).

- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Implements the decisions we made on release branch names and release option values. See the new tests for examples.
> Tighten checks for release values and branch names

- src/io/flutter/pub/PubRoot.java
- src/io/flutter/run/test/TestFields.java
> Improve pub root detection for flutter tests (#1575).

- src/io/flutter/FlutterUtils.java
Fixes: #1583.
@stevemessick @devoncarew 
FYI @brianegan
And thanks to #1575, they can even run too! 👍
> Fix discovery of tests in example subdirs (#1583)

- src/io/flutter/console/FlutterConsoleFilter.java
More hyperlinks!
* adds links to files in restart messages
* adds links to stack trace path elements
Fixes: #1571
cc @stevemessick @devoncarew 
￼￼
￼
> Improve console hyperlinking for local files.

- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/run/daemon/FlutterApp.java
Adds a hyperlink to the restart message.
> Actionable “restart” debugging console output.

- src/io/flutter/FlutterInitializer.java
- src/io/flutter/utils/FlutterModuleUtils.java
> Fix run config autoselection for plugin projects (#1591).

- src/io/flutter/inspector/FlutterWidget.java
> Disable category widgets.

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- src/io/flutter/view/FlutterView.java
> Remove Inspector Preference (#1617)

- src/io/flutter/editor/FlutterEditorAnnotator.java
- src/io/flutter/editor/FlutterMaterialIcons.java
- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/view/InspectorPanel.java
- refactor the code to create flutter material icons out of the editor annotations and into a common class
- show flutter material icons in the inspector
@jacob314
> show flutter material icons in the inspector

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- update release notes for M21
(TBR)
> update release notes for M21

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- src/io/flutter/run/bazel/BazelFields.java
- update android_cpu type from armeabi to armeabi-v7a
@jwren, @tvolkert
> update android_cpu type from armeabi to armeabi-v7a

- src/io/flutter/dart/DartAnalysisServerServiceEx.java
- src/io/flutter/dart/DartAnalysisServerServiceExResponseListener.java
- src/io/flutter/utils/ThreadUtil.java
- testSrc/unit/io/flutter/utils/ThreadUtilTest.java
- tool/plugin/plugin.iml
…and allows sending arbitrary requests and listen for all responses.
> Add DartAnalysisServerServiceEx that wraps the Dart Analysis Service.

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- update the changelog to mention the npe fix
(TBR)
> update the changelog to mention the npe fix

- tool/plugin/analysis_options.yaml
- tool/plugin/bin/main.dart
- tool/plugin/lib/lint.dart
- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
some misc build system changes:
- make the `abuild` command hidden (when you run `bin/plugin -h`)
- change the directory names the release artifacts are written to from `artifacts/release_21.0` to `artifacts/release_21` (open use the major version number)
@stevemessick
> some misc build system changes

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
> add a changelog entry for 21.2

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- src/io/flutter/preview/DartElementPresentationUtil.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/PreviewViewCondition.java
- src/io/flutter/preview/PreviewViewFactory.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/view/preview/DartElementPresentationUtil.java
- src/org/dartlang/analysis/server/protocol/FlutterOutline.java
- src/org/dartlang/analysis/server/protocol/FlutterOutlineAttribute.java
- format some java files
- move the preview related files to their own java package
@scheglov
> Format and move files

- src/io/flutter/FlutterBundle.properties
- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/view/InspectorPanel.java
Hide property name when getShowName was false as graying the name was confusing.
> Enum property support and tweaks to property display.

- src/io/flutter/preview/PreviewViewCondition.java
- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- add a preference flag to opt into `--preview-dart-2`; fix https://github.com/flutter/flutter-intellij/issues/1667
@pq
> add a flag to enable --preview-dart-2

- src/io/flutter/preview/DartElementPresentationUtil.java
- src/io/flutter/preview/PreviewView.java
- src/org/dartlang/analysis/server/protocol/FlutterOutline.java
- src/org/dartlang/analysis/server/protocol/FlutterOutlineAttribute.java
- show build() methods in bold; this helps identify the areas of the tree that are related to widget creation
@scheglov
> show build() methods in bold

- src/io/flutter/preview/PreviewView.java
Bind `Add widget padding` assist to the action.
Show tooltips with the same text as the assist message.
> Update actions on both caret and tree selection.

- src/io/flutter/preview/PreviewView.java
I forgot to upload these changes before landing the patch :-(
> Update messages for wrapping with Column/Row.

- src/io/flutter/preview/PreviewView.java
So, action to wrap into `Column` or `Row` do the same in the editor and in the tree.
And you can see what is selected.
> Select in the tree outlines selected in the editor.

- src/io/flutter/run/bazel/FlutterBazelRunConfigurationType.java
This is a cleanup nit, the string name does not change with this PR.
> Use the FlutterBundle.message(...) instead of the same hard-coded string.

- src/io/flutter/preview/PreviewView.java
Corresponding Analysis Server change.
https://dart-review.googlesource.com/c/sdk/+/41023
> Bind actions to move widget down/up.

- src/io/flutter/preview/PreviewView.java
closes https://github.com/flutter/flutter-intellij/issues/1716
> Add analytics for opening the view, executing actions, and navigation.

- src/io/flutter/editor/FlutterEditorAnnotator.java
- add support for color shades (`Colors.blue.shade200`)
- fix https://github.com/flutter/flutter-intellij/issues/1639
@pq
> add support for color shades

- src/io/flutter/module/FlutterModuleBuilder.java
Fixes: #1761.
Not pretty or ideal but consistent with the name validation UX and is another nudge to keep folks on the rails.
> Validate descriptions

- tool/plugin/lib/plugin.dart
Fixes #1556 
@pq 
```bash
$ ./bin/plugin build -o3.0
Getting artifacts:
artifacts/intellij-javac2.zip exists in cache
artifacts/android-studio-ide-171.4408382-linux.zip exists in cache
artifacts/Dart-171.4424.10.zip exists in cache
Building flutter-intellij.jar:
rm -rf build
ant -f tool/plugin/compile.xml -Didea.product=android-studio -Didea.version=171.4408382 -Dbasedir=/Users/messick/src/flutter/flutter-intellij compile
The build command requires ant to be installed.
Please ensure ant is on your $PATH.
$ echo $?
2
```
> Print a message if ant is not installed

- gen/icons/FlutterIcons.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
Closes https://github.com/flutter/flutter-intellij/issues/1789
> Rename 'Flutter Preview' to 'Flutter Outline'.

- src/io/flutter/preview/PreviewView.java
> Prefix icons of Flutter items with the Flutter icon.

- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/InspectorPanel.java
> address a few analysis warnings

- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/PreviewViewState.java
So, its value stays the same between IntelliJ restarts.
https://github.com/flutter/flutter-intellij/issues/1790
> Move the 'showOnlyWidgets' flag into PreviewViewState.

- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/FlutterViewAction.java
- src/io/flutter/view/FlutterViewToggleableAction.java
Follow-up from: https://github.com/flutter/flutter-intellij/pull/1788#pullrequestreview-97972127.
Instruments all flutter view actions (not just toggleable ones).
@devoncarew
> Flutter View Action analytics.

- src/io/flutter/preview/PreviewView.java
So, the Undo action works in `Flutter Outline`.
> Add OutlineComponent that provides PlatformDataKeys.FILE_EDITOR for undo

- src/io/flutter/preview/PreviewView.java
> Show assist actions also in Outline popup.

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
> Make Outline feedback text consistent.

- resources/META-INF/plugin.xml
- resources/META-INF/plugin.xml.template
- src/io/flutter/module/InstallSdkAction.java
- src/io/flutter/settings/FlutterSettings.java
- install the flutter sdk using the beta channel by default
- restore some analytics for experimental flags
(TBR)
> install the flutter sdk using the beta channel by default

- resources/META-INF/plugin.xml.template
See #1842 -- once implemented it should prevent this kind of problem in the future.
> Add changes to template that were omitted during #1758

- src/io/flutter/analytics/Analytics.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
- fix an exception discovered via analytics
- do some very slight compression of stack traces to fit a few more stackes into the google analytics limit
@stevemessick
> fix an exception

- flutter-studio/src/io/flutter/project/FlutterProjectStep.form
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/module/FlutterGeneratorPeer.form
- src/io/flutter/module/FlutterGeneratorPeer.java
- src/io/flutter/module/InstallSdkAction.java
- src/io/flutter/view/FlutterView.java
- testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java
- address a few misc. IntelliJ analyzer lints
> address some IntelliJ analyzer lints

- src/io/flutter/settings/FlutterSettings.java
- fix a typo in the settings analytics
- oops
> fix a typo in the settings analytics

- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/run/daemon/DeviceDaemon.java
- src/io/flutter/run/daemon/DeviceService.java
- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/InspectorPanel.java
- testSrc/unit/io/flutter/utils/AsyncRateLimiterTest.java
Some Java7/8 cleanups and a few little nits.
@jacob314
> Cleanup; annotations, => lambda expressions, etc.

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/Location.java
- src/io/flutter/view/InspectorPanel.java
A baby-step along the way to doc hovers but useful in and of itself. 🎁 
See: #1847 
Depends on: https://github.com/flutter/flutter/pull/14993
@jacob314
> Present names for user-defined properties in BOLD.

- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
- flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
Add comments to the tricky AS code for "Open in Android Studio".
> Add comments for opening module

- src/io/flutter/run/SdkFields.java
- src/io/flutter/utils/FlutterModuleUtils.java
Actually two issues:
* failure to copy additional fields
* overly zealous config auto creation 
Fixes: #1867 
@jacob314 @devoncarew
> Fix run config persistence (#1867)

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/editor/FlutterSaveActionsManager.java
- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- implement format on save
- also, implement organize imports on save
- fix https://github.com/flutter/flutter-intellij/issues/1205
This might be a bit twitchy, so I added it in the experimental section.
@scheglov
> implement format on save

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/Location.java
- src/io/flutter/view/InspectorPanel.java
Jump to source for properties in the Inspector View.
Next up: Jump to property definition 👍 
@jacob314
> “Jump to Source” for properties.

- src/io/flutter/preview/PreviewView.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
> Make 'Show preview area' a setting instead of a compile time constant.

- src/io/flutter/preview/Handle.java
- src/io/flutter/preview/MoveHandle.java
- src/io/flutter/preview/PreviewArea.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/SelectionEditPolicy.java
- src/io/flutter/preview/SquareHandle.java
- src/io/flutter/preview/SquareHandlePosition.java
> Show selection handles for the selected component on the preview area.

- src/io/flutter/preview/PreviewArea.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/RenderHelper.java
- src/io/flutter/preview/render_server_template.txt
> Use the bottom area size as the size for the widget to render.

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/run/FlutterDebugProcess.java
- src/io/flutter/view/InspectorPanel.java
Fixes: #1847
TODO:
* consider hovers for values
* consider rich navigation hovers (w/ styling and navigable docs) 
@jacob314
> Property description tooltips (#1847)

- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
Use reflection to resolve potential compile problems.
> Remove hard dependency on deprecated method

- .gitignore
See: https://github.com/dart-lang/sdk/issues/32030
> Ignore new `dart_tool` pub cache  directory

- src/io/flutter/preview/RenderHelper.java
- src/io/flutter/preview/render_server_template.txt
When we can, we render about `10x` faster.
Without hot reload - about `1000ms`.
With hot reload - about `60-80ms` for reload and `20-60ms` for rendering, depending on complexity of the widget. Edits, switching between widgets in the same file, and even in the same package should be hot realoadable.
> Use hot reload for rendering when possible.

- src/io/flutter/utils/FlutterModuleUtils.java
- dial back our module auto-conversion a bit; only perform this for Android Studio
- fix https://github.com/flutter/flutter-intellij/issues/1920
@jwren
> dial back our module auto-conversion a bit

- src/io/flutter/inspector/HeapDisplay.java
- src/io/flutter/perf/HeapMonitor.java
- src/io/flutter/perf/PerfService.java
Some misc work on the memory view:
- add samples for GC events
- fix an issue where the display values wouldn't update after a full restart
- ensure that the foreground color works in dark themes
@pq
> handle GC events

- src/io/flutter/perf/PerfService.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- src/io/flutter/view/FlutterView.java
Migrates static compile time constant to user visible preference.
See: #1927
@devoncarew
> Add a preference to toggle heap use display.

- src/io/flutter/run/FlutterReloadManager.java
- remove the feedback link for reload on save - it's been shipped for a while
@pq
> remove the feedback link for reload on save

- src/io/flutter/run/bazelTest/BazelTestFields.java
- src/io/flutter/run/daemon/RunMode.java
- src/io/flutter/run/test/TestFields.java
This is a follow up on https://github.com/flutter/flutter-intellij/pull/1928
> Additional @NotNull annotations in BazelTestFields and TestFields

- src/io/flutter/run/bazelTest/BazelTestRunner.java
Override getSourcePosition() in BazelPositionMapper to open the correct file when a breakpoint is hit.
> More incremental work for commented out Bazel test run config.

- src/io/flutter/view/FlutterView.java
IMO feels more consistent with where similar menus are rendered for views and plays a bit nicer with resizing.
> Move Inspector View toolbar overflow to the East.

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/inspector/InspectorSourceLocation.java
- src/io/flutter/inspector/SourceLocation.java
- src/io/flutter/view/InspectorPanel.java
- add padding to the bottom of the inspector scroll area (the magic constant here is `JBUI.scale(14)`)
- fix https://github.com/flutter/flutter-intellij/issues/1607
- also, a rename of `Location` to `InspectorSourceLocation`
@pq, @jacob314
> add padding to the bottom of the inspector scroll area

- src/io/flutter/dart/FlutterOutlineListener.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/view/InspectorPanel.java
* removed some unused imports
* migrated warning color to be more explicitly darcula-friendly
* added null awareness in some places
@jacob314 @scheglov
> Miscellaneous housekeeping.

- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
> Improvements to the Flutter (Bazel) launch configuration UI.

- src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.form
> Improvements to the Flutter Test (Bazel) launch configuration UI.

- src/io/flutter/run/test/TestForm.form
- src/io/flutter/run/test/TestForm.java
> Improvements to the Flutter Test launch configuration UI

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
- src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.form
- This includes a nit in the Flutter Bazel Test config too
> Change order and message for additional arguments in the Flutter Bazel run configurations

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazelTest/BazelTestFields.java
- Removes all the commented out references and TODOs around additionalArgs
- And refactors the two definitions of checkRunnable into one shared definition
> Cleanup in BazelTestFields (and BazelFields).

- src/io/flutter/inspector/DiagnosticsNode.java
- src/io/flutter/run/test/TestConfigUtils.java
- src/io/flutter/view/InspectorPanel.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/VmOpenSourceLocationListener.java
Update a few `String.isEmpty()` tests to use `StringUtils`.
Follow-up from https://github.com/flutter/flutter-intellij/pull/1977#discussion_r176480429.
@jacob314
> Wee cleanup (StringUtils edition).

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
- src/io/flutter/run/bazelTest/BazelTestConfig.java
- src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.java
A few cleanup actions are also in this PR
> Enable the Bazel test run configuration

- src/io/flutter/run/daemon/DaemonApi.java
- src/io/flutter/run/daemon/DaemonConsoleView.java
- src/io/flutter/run/daemon/DaemonEvent.java
- testSrc/unit/io/flutter/run/daemon/DaemonApiTest.java
- fix https://github.com/flutter/flutter-intellij/issues/1879, fix https://github.com/flutter/flutter-intellij/issues/1615
- harden the daemon protocol against user printed `[{...}]` json blocks
> handle user printed json output in stdout

- src/io/flutter/run/bazelTest/BazelTestLaunchState.java
- src/io/flutter/run/bazelTest/BazelTestRunner.java
- Enable the DaemonConsoleView for the run config
- Implement BazelTestRunner.canRun() for the runner
> Address 2 TODOs in the Flutter Test Bazel run config.

- src/io/flutter/run/FlutterConfigurationEditorForm.form
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
- src/io/flutter/run/bazelTest/FlutterBazelTestConfigurationEditorForm.form
- src/io/flutter/run/test/TestForm.form
> some tweaks to our launch config UIs

- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- remove a timeout on app launch
- fix https://github.com/flutter/flutter-intellij/issues/1988
> remove a timeout on app launch

- product-matrix.json
We'll want this for M23, fixes #454.
> Fix build to include completion contributions in 3.1+

- src/io/flutter/view/FlutterView.java
Note: I opted not to rename the action since that would impact analytics...  Happy to do so though.
@jacob314 @devoncarew
> “Slow Mode” => “Debug Mode” label update.

- src/io/flutter/preview/PreviewArea.java
> Use lighter colors for default UI theme.

- src/io/flutter/preview/PreviewArea.java
Follow up to https://github.com/flutter/flutter-intellij/pull/1987; @scheglov.
> add a new shadow border

- CHANGELOG.md
- resources/META-INF/plugin.xml
- update the changelog for M23
> update the changelog for M23

- src/io/flutter/preview/PreviewArea.java
- src/org/dartlang/analysis/server/protocol/FlutterOutline.java
https://github.com/flutter/flutter-intellij/issues/1986
> Show widget class name + optional state class name.

- src/io/flutter/preview/PreviewArea.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/RenderHelper.java
- src/io/flutter/preview/RenderProblemKind.java
> Distinguish 'no widget' and 'not renderable widget'.

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/actions/ExtractWidgetAction.java
- src/io/flutter/dart/FlutterDartAnalysisServer.java
- src/io/flutter/refactoring/ExtractWidgetRefactoring.java
- src/org/dartlang/analysis/server/protocol/ExtractWidgetFeedback.java
- src/org/dartlang/analysis/server/protocol/ExtractWidgetOptions.java
- src/org/dartlang/analysis/server/protocol/RefactoringKind.java
https://github.com/flutter/flutter-intellij/issues/1250
> Integrate 'Extract Widget' refactoring.

- src/io/flutter/preview/PreviewArea.java
https://github.com/flutter/flutter-intellij/issues/1986
> Tweaks for the preview area title.

- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
Set the 'disable user config' flag at start up.
@devoncarew
> Disable user config

- CHANGELOG.md
- resources/META-INF/plugin.xml
update release notes to capture https://github.com/flutter/flutter-intellij/pull/2022
> release notes for 23.1

- src/io/flutter/run/FlutterReloadManager.java
- have the 'reloading...' notification timeout after the reload completes (work around an issue with the IntelliJ Notification.expire() implementation - this does not remove notifications displayed for tool windows)
This addresses an issue there the `Reloading...` tool window notification will continue to show after the reload is complete (until the next time the user interacts with the IDE).
> have the reloading... notification timeout after the reload completes

- src/io/flutter/view/FlutterView.java
fix https://github.com/flutter/flutter-intellij/issues/2040
> Check if the toolWindow has been disposed.

- .travis.yml
- flutter-intellij-community.iml
- flutter-studio/src/io/flutter/FlutterStudioStartupActivity.java
- product-matrix.json
- resources/META-INF/plugin.xml
- resources/META-INF/studio-contribs.xml
- resources/META-INF/studio-contribs_template.xml
- tool/plugin/lib/plugin.dart
- tool/plugin/test/plugin_test.dart
Drop 3.0.1; update 3.1; add 3.2.
@devoncarew
> Update build artifacts

- src/io/flutter/dart/DartAnalysisServerServiceEx.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/preview/DartElementPresentationUtil.java
- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/sdk/FlutterSdkManager.java
- remove some 2017.1 and 2017.2 based reflection
@scheglov @stevemessick
> remove some 2017.1 and 2017.2 based reflection

- src/io/flutter/preview/MoveHandle.java
Fixes https://github.com/flutter/flutter-intellij/issues/2000
> Fix painting for MoveHandle.

- src/io/flutter/preview/DartElementPresentationUtil.java
@scheglov; this matches what we show in the Structure view
> show test icons in the outline view

- tool/plugin/bin/main.dart
- tool/plugin/pubspec.yaml
- tool/plugin/test/plugin_test.dart
- upgrade package:git
- a test PR to see if this fixes travis
> upgrade package:git

- flutter-studio/src/io/flutter/actions/FlutterNewProjectAction.java
- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/run/test/TestFields.java
- src/io/flutter/view/FlutterViewMessages.java
- src/io/flutter/view/MultiIconSimpleColoredComponent.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- some unused imports
- a few LOG statements changed to match our other uses
> address a few nits

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
> Append project name to location to get project directory

- flutter-studio/flutter-studio.iml
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/FlutterGuiTestRule.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/FlutterProjectStepFixture.java
Tweaking the GUI test framework. Still needs work for 3.2.
> Additional updates; still not runnable

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterInitializer.java
- src/io/flutter/module/FlutterModuleBuilder.java
- src/io/flutter/project/FlutterProjectStructureDetector.java
- src/io/flutter/utils/FlutterModuleUtils.java
Importing Flutter (and vanilla Dart) projects "just work". 🤘 
Also makes initialization a little more multi-module friendly.
Fixes: #1889.
> Project Import Support (#1889)

- src/io/flutter/actions/OpenInXcodeAction.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
* prefers building for the simulator which avoids provisioning issues
* adds console logging
Fixes: #1914
> Improve “Open in XCode…” auto-build (#1914).

- src/io/flutter/view/FlutterView.java
> Disposed window check in FlutterView initialization (#2076).

- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/RenderHelper.java
- src/io/flutter/preview/render_server_template.txt
- src/io/flutter/sdk/FlutterSdk.java
> Fixes to make outline preview working on Windows.

- src/io/flutter/perf/PerfService.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
- address an NPE in DartVmServiceDebugProcessZ.java (found when testing launching in profile mode)
> fix an NPE in DartVmServiceDebugProcessZ.java

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.form
- src/io/flutter/run/bazel/FlutterBazelConfigurationEditorForm.java
- testSrc/unit/io/flutter/run/bazel/BazelFieldsTest.java
> Additional launch configuration for release mode in the Flutter (Bazel) launch configuration

- src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java
- src/io/flutter/module/settings/FlutterCreateParams.form
- src/io/flutter/module/settings/FlutterCreateParams.java
- src/io/flutter/module/settings/ProjectType.form
- src/io/flutter/module/settings/SettingsHelpForm.form
- src/io/flutter/module/settings/SettingsHelpForm.java
- src/io/flutter/sdk/FlutterCreateAdditionalSettings.java
Adds an option to create projects "offline".
To make room for the options, the help is trimmed a bit too.  Previously:
To follow are some smarts to auto-select based on the reachability of pub.
See: #1923
@scheglov @devoncarew
> Option to create projects in “offline” mode (#1923).

- src/io/flutter/actions/OpenInAndroidStudioAction.java
> Fix “Open in AS” action to not show for the ios dir.

- src/io/flutter/project/ProjectWatch.java
- src/io/flutter/sdk/FlutterPluginLibraryType.java
- src/io/flutter/sdk/FlutterSdkManager.java
> Some deprecated API call cleanup.

- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/view/FlutterView.java
- src/io/flutter/view/InspectorPanel.java
- disable the refresh button during a refresh
I unintentionally formatted `InspectorService.java` as part of this PR - I'm happy to revert, and reapply just my changes.
> disable the refresh button during a refresh

- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/SdkRunConfig.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/daemon/FlutterApp.java
Now you can turn the flag on and off and click the debug or run button
and have the app relaunch correctly.
Work around https://github.com/flutter/flutter/issues/16766
with horrible hacks to delete the build directory if the config
change.
> Fix issues turning --track-widget-creation on and off.

- product-matrix.json
- tool/plugin/test/plugin_test.dart
- update to the latest AS 3.2 canary
@stevemessick
> update to the latest AS 3.2 canary

- src/io/flutter/run/SdkRunConfig.java
> Remove unused import

- src/io/flutter/inspector/TreeScrollAnimator.java
- src/io/flutter/utils/animation/Cubic.java
- src/io/flutter/utils/animation/Curve.java
- src/io/flutter/utils/animation/Curves.java
- src/io/flutter/utils/animation/FlippedCurve.java
- src/io/flutter/utils/animation/Threshold.java
- testSrc/unit/io/flutter/utils/animation/CurvesTest.java
javafx dependency which makes building the plugin on some environments
hard.
> Port Curve classes from Flutter along with their tests to avoid

- README.md
In lieu of a fix landing to `flutter doctor` for IO, this update our known issues.
Fixes: #2134 
@devoncarew
> Add cocoapod version known issue.

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- slight UI tweak to the inspector preferences
This changes the indent for the pref to one matching the organize imports on save pref further down.
@jacob314
> slight UI tweak to the inspector preferences

- flutter-studio/src/io/flutter/FlutterStudioInitializer.java
> Warning about Canary

- product-matrix.json
- fix code completion in AS 3.1
- fix https://github.com/flutter/flutter-intellij/issues/2153
It looks like the Dart plugin in 2017.3 now supports the necessary completion interface.
@stevemessick
> fix code completion in AS 3.1

- src/io/flutter/console/FlutterConsoles.java
- src/io/flutter/preview/PreviewView.java
- src/io/flutter/preview/RenderHelper.java
- src/io/flutter/preview/RenderProblemKind.java
- src/io/flutter/preview/render_server_template.txt
> Show local and remote exceptions during preview.

- src/io/flutter/actions/ExtractWidgetAction.java
https://github.com/flutter/flutter-intellij/issues/2165
> Run ExtractWidgetAction in transaction.

- src/io/flutter/preview/PreviewArea.java
Closes https://github.com/flutter/flutter-intellij/issues/2176
> When clearing the preview area, clear also maps.

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/actions/FlutterCleanAction.java
- src/io/flutter/sdk/FlutterCommand.java
- src/io/flutter/sdk/FlutterSdk.java
Adds top-level action.
Shows results in console:
> Add `flutter clean` top-level action.

- CHANGELOG.md
- flutter-studio/src/io/flutter/FlutterStudioInitializer.java
- resources/META-INF/plugin.xml
- src/io/flutter/FlutterInitializer.java
- remove AS Canary from changelog
- change the UI for the AS Canary warning to using the toast style notifications
@stevemessick
> remove AS Canary from changelog; update check

- src/io/flutter/actions/ExtractWidgetAction.java
https://github.com/flutter/flutter-intellij/issues/2182
> Check initial status for 'Extract Widget' refactoring.

- src/io/flutter/actions/ReloadFlutterApp.java
- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/daemon/DeviceSelection.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/run/test/TestForm.java
- src/io/flutter/utils/FileWatch.java
- src/io/flutter/utils/Refreshable.java
- src/io/flutter/utils/animation/FlippedCurve.java
- remove unused fields and params (orphaned from a refactoring)
- organize imports for the project
> remove unused fields and params

- src/io/flutter/run/FlutterReloadManager.java
- don't reload on save for profile runs (addresses one aspect of https://github.com/flutter/flutter-intellij/issues/2185#issuecomment-386162456)
> don't reload on save for profile runs

- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- re-org the prefs page (move some items out of the experimental section)
> re-org the prefs

- src/io/flutter/logging/FlutterLogEntry.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogView.java
Follow-up from: #2187.
@devoncarew
> Make timestamps long.

- src/io/flutter/FlutterUtils.java
- src/io/flutter/view/FlutterView.java
- work around https://github.com/flutter/flutter-intellij/issues/2029
closes https://github.com/flutter/flutter-intellij/issues/2029
> remove the empty content message for 2017.3

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogView.java
>  Logger View auto-scroll.

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogView.java
- src/io/flutter/perf/HeapMonitor.java
- log gc events
- show the full name for categories in the log
@pq
> log gc events

- gen/icons/FlutterIcons.java
- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/actions/RestartFlutterApp.java
- src/io/flutter/perf/PerfService.java
- src/io/flutter/run/FlutterReloadManager.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/daemon/FlutterApp.java
- fix https://github.com/flutter/flutter-intellij/issues/2221
> rename full restart to hot restart

- src/io/flutter/logging/FlutterLogView.java
Toggle-able scroll-to-end.
Down the road we can consider smarts to disable/reenable based on scrollbar interactions.
> Logger: scroll-to-end toggle action.

- CHANGELOG.md
- resources/META-INF/plugin.xml
- fix a typo in the changelog
@pq
> fix a typo in the changelog

- src/io/flutter/actions/OpenInAndroidStudioAction.java
@pq 
If the "Open in Android Studio" action is invoked on a file (not directory) in IntelliJ then Android Studio will open that file for editing when it is launched.
Have not looked at AS -> AS yet.
Tried to do IJ -> Xcode but that didn't work.
> Open selected file when launching Android Studio

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
> log view opt-in preference

- flutter-studio/src/io/flutter/actions/OpenAndroidModule.java
Similar to #2230, open an editor for the selected file in the AS -> AS case. (Another tweak to "Open in Android Studio")
[Deleted previous PR due to git branch error]
> Open the selected file for editing when opening a new project

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogView.java
- src/io/flutter/run/daemon/DaemonApi.java
Still a work in progress but this improves logging output significantly by properly parsing daemon API events (no more observatory spam! 🎉 ).
Work on the TODOs to follow.
/cc @jacob314
> Improve logger daemon event handling.

- src/io/flutter/logging/FlutterLogView.java
Adds basic hyperlink support to log message cells.
* adds mouse event handling to the log tree
* adds flutter console hyperlink handling
> Hyperlink support for log messages.

- src/io/flutter/logging/FlutterLogView.java
Follow-up from #2259.
* migrates rendering awareness to column info objects
* removes (now) needless overrides
There's still a bit of logic that manually delegates the renderer lookup.  This is done magically by some base classes so it's maybe just a matter of extending the right one (or if this is all they do, maybe not bother).  Anyway, there's a TODO about that...
> Refactor log tree to use preferred columinfos.

- .travis.yml
- .travis_template.yml
- only build travis PRs (and the master branch)
> only build PRs

- src/io/flutter/run/bazel/BazelFields.java
- src/io/flutter/sdk/FlutterSdk.java
- src/io/flutter/sdk/FlutterSettingsConfigurable.form
- src/io/flutter/sdk/FlutterSettingsConfigurable.java
- src/io/flutter/settings/FlutterSettings.java
- remove the option to configure the preview-dart-2 setting (fix https://github.com/flutter/flutter-intellij/issues/2263);
- flip the track-widget-creation flag to be on by default
- tweak the text for the flutter logging view preference
> various updates to the settings view

- flutter-studio/src/io/flutter/android/GradleDependencyFetcher.java
- flutter-studio/testSrc/io/flutter/GradleDependencyFetcherTest.java
@devoncarew 
Not quite sure how this will be used yet. It takes a while to run, so we'll need to design around that. I'd say it is comparable to analyzing a Dart project.
> Gradle deps

- resources/liveTemplates/flutter_miscellaneous.xml
Fixes https://github.com/flutter/flutter-intellij/issues/2282
> Don't use 'new' for stless, stfull, stanim.

- src/io/flutter/editor/NativeEditorNotificationProvider.java
> Fix native editor banner presentation (#2291).

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
work to support filtering.
* stores events in the log (not just the tree model)
* migrates the clear action to empty the log (and view)
/cc @scheglov
> Log model refactoring.

- src/io/flutter/actions/ExtractWidgetAction.java
https://github.com/flutter/flutter-intellij/issues/2283
https://dart-review.googlesource.com/c/sdk/+/57704
> Provide bath offset and length to 'Extract Widget' refactoring.

- src/io/flutter/logging/FlutterLog.java
> => ImmutableList

- resources/META-INF/plugin.xml
- tool/plugin/lib/plugin.dart
- tool/plugin/pubspec.yaml
> pretty print the changelog

- .github/move.yml
- .github/no-response.yml
- add no-response and move issues bots configs
- fix https://github.com/flutter/flutter-intellij/issues/2315
> add no-response and move issues bots configs

- src/io/flutter/logging/FlutterLogView.java
Simple log event filtering.
Still WIP.
/cc @scheglov
> Log view filtering WIP

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
> Log tree tuning

- src/io/flutter/logging/FlutterLogTree.java
**MUCH** smoother now.
/cc @scheglov
> Fix log model updates.

- product-matrix.json
- build for AS 3.2 Canary 16
@stevemessick
> build for AS 3.2 Canary 16

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Subject to move as toolbar contributions get finalized but a good starting point (and handy in the meantime).
/cc @scheglov
> Filter count labels.

- src/io/flutter/logging/FlutterLog.java
🎉 
Couldn't resist now that I know about it...
/cc @scheglov
> Event dispatching cleanup.

- src/io/flutter/actions/InstallSdkAction.java
- src/io/flutter/console/FlutterConsoleFilter.java
- src/io/flutter/run/LaunchState.java
- src/io/flutter/run/bazel/BazelRunConfig.java
- src/io/flutter/run/bazelTest/BazelTestConfig.java
- src/io/flutter/run/bazelTest/BazelTestRunner.java
- src/io/flutter/run/test/DebugTestRunner.java
- src/io/flutter/run/test/TestConfig.java
- src/io/flutter/utils/System.java
- src/io/flutter/utils/animation/Curves.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java
Quick sweep of some missing annotations, unnecessary code, etc.
> Misc. fixups

- src/io/flutter/settings/FlutterSettings.java
- third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/VmOpenSourceLocationListener.java
This should be all of 'em.
Cheers for the find @scheglov ! 🎉 
> Event Dispatcher migrations.

- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogView.java
- use the log category name from the dart:developer event
@pq
> use the log category name from the dart:developer event

- flutter-studio/README.md
- flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/newProjectWizard/NewFlutterModuleWizardFixture.java
- flutter-studio/testSrc/io/flutter/tests/gui/NewModuleTest.java
- flutter-studio/testSrc/io/flutter/tests/gui/NewProjectTest.java
- flutter-studio/testSrc/io/flutter/tests/gui/ProjectWizardTest.java
- product-matrix.json
This still needs some work. The correct value for one new method will have to be retrieved via reflection until Canary 18 is published. (It is commented for now.)
If travis stays green then it is good enough for now.
@devoncarew (ya, we just did 16)
> Build for Canary 17

- src/io/flutter/logging/FlutterLogTree.java
> Fix auto-scroll to catch up to fully rendered log tree.

- src/io/flutter/logging/FlutterLogView.java
> Live log tree filtering 🤘 

- src/io/flutter/logging/FlutterLogTree.java
- when filtering in the Logging view, also look at the category field
@pq
> also filter on the category

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
- src/io/flutter/view/FlutterView.java
Some UI-smithing to come as we settle on final configurable bits, but this lands the basic functionality.
See: #2340.
> Logger view support for hiding timestamps

- product-matrix.json
> Build for Canary 18

- src/io/flutter/logging/FlutterLogFilterPanel.form
- src/io/flutter/logging/FlutterLogFilterPanel.java
Issue: https://github.com/flutter/flutter-intellij/issues/2353
+ Improve logging layout.
Here is the record of how it works.
I'm not good for swing/layout much.
=> please give me a suggestion to make it better.
Notes:
Actually, I want to make log layout still keep visible while user resizes window like this one:
> fix log layout problem.

- AUTHORS
@quangson91 : is this a good attribution?
> Add QuangSon to AUTHORS.

- src/io/flutter/run/daemon/FlutterApp.java
> Harden isSessionActive

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntry.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Playing w/ sequence numbers as per: #2200. 
> Log entry sequence numbering.

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntry.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
- testSrc/unit/io/flutter/logging/FlutterLogTest.java
See: #2340 
/cc @scheglov @stevemessick
> Support for log entry levels.

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Basic entry coloring (WIP).
As discussed in #2200, this will ultimately benefit from user configurability; this plumbs in the back-end for that.
> Log entry coloring.

- src/io/flutter/logging/FlutterLogView.java
Relate: https://github.com/flutter/flutter-intellij/pull/2361
Fix the filter panel is hidden when the window is narrow.
Reason:
It seems all actions will automatically hide when the window is narrow & auto visible when the mouse hover.
Solution
Keep the filter panel is just a Panel. (we don't wrap it in the action).
Demo:
/cc @pq
> fix flutter log view while resizing

- src/io/flutter/logging/FlutterLogFilterPanel.form
- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
- testSrc/unit/io/flutter/logging/FlutterLogTreeTest.java
Issue: https://github.com/flutter/flutter-intellij/issues/2377
+ add feature filter by log level
Demo
While testing, It seems the generate log level is not correct.
So I think we should double check after the issue for log level fixed.
/cc @pq what do you think?
> add feature filter by log level

- src/io/flutter/android/AndroidSdk.java
- look for the emulator tool in the `emulator/` directory first
- fix https://github.com/flutter/flutter-intellij/issues/2351
> look for the emulator tool in the emulator/ directory first

- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Before:
After:
(This reapplies the fix in https://github.com/flutter/flutter-intellij/pull/2274/commits/01e492eaa94706774739ac5f30d7d870ead00c9b that I dropped in a recent refactoring.)
Also: a bit of re-org, centralizing all toolbar creation logic in one method.
> Remove selected cell borders (tk 2)

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Ensures clearing log entries updates event count.
> Fix log event count update on clear

- src/io/flutter/logging/FlutterLogTree.java
Greatly improves performance w/ busy event streams and long entry lists.
May address: #2403.
/cc @scheglov @devoncarew @quangson91
> Remove gratuitous logger model updates.

- src/io/flutter/logging/FlutterLogView.java
Issue: https://github.com/flutter/flutter-intellij/issues/2396
setting log color by taking value from flutter log color setting page.
Demo
/ cc @pq
> setting log color from flutter log setting page

- src/io/flutter/coverage/EditorCoverageDecorations.java
- fix an exception when using the live coverage feature
- fix https://github.com/flutter/flutter-intellij/issues/2407
> fix an exception when using the live coverage feature

- src/io/flutter/view/FlutterView.java
- remove the Inspector's empty content message
I hit another issue where an app was running, but the inspector was not displaying info about the current app (rather, no tab was selected - you had to manually click on the app's tab). I'm removing the empty content message so user's don't run into this issue.
> remove the Inspector's empty content message

- src/io/flutter/logging/FlutterLogTree.java
> Guard against (possible) null module in filtering.

- product-matrix.json
> Update build for AS 3.2 beta

- resources/META-INF/plugin.xml
- resources/META-INF/plugin_template.xml
- src/io/flutter/logging/FlutterLogPreferences.java
Create a class to store flutter log setting.
// cc @pq, please take a look in next week!
> create flutter log preferences

- src/io/flutter/logging/FlutterLogTree.java
Follow-up from: https://github.com/flutter/flutter-intellij/pull/2413#issuecomment-400318578
/cc @quangson91 @scheglov
> extract renderers

- CHANGELOG.md
- resources/META-INF/plugin.xml
> update the changelog for m26

- src/io/flutter/logging/FlutterLogView.java
We were being too smart.  No reason to limit config to active sessions.
Fixes:  #2434
> Fix config menu enablement

- src/io/flutter/logging/FlutterLogView.java
> Update cursor on log entry link hover.

- src/io/flutter/logging/FlutterLogTree.java
Refactoring:
+ use flutter log constant for the column name
// cc @pq a small refactoring.
> use flutter log constant for column name

- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogPreferences.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
https://github.com/flutter/flutter-intellij/issues/2340
+ Save & Load flutter log filter preferences.
So the user can keep filtering option between session.
// cc @pq for review
> Save & Load flutter log filter preferences.

- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntry.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogTree.java
- display the log level names in lower case
- default the filter level to `config`
- do display the log filter level all the time (previously, we didn't display for the `none` level)
@pq @quangson91
> lower case the log level names

- AUTHORS
@brianegan : confirm this mail?  (cribbed from your GH profile 👍 )
Thanks again for the contribution!
/cc @brianegan @devoncarew @stevemessick
> Add Brian to AUTHORS.

- src/io/flutter/sdk/AbstractLibraryManager.java
- src/io/flutter/sdk/FlutterPluginsLibraryManager.java
Rename the abstract class; add some javadoc.
> Changes requested during review.

- src/io/flutter/logging/FlutterLogView.java
Fixes: #2463.
/cc @devoncarew @quangson91
> Fix log entry browser links (#2463)

- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogPreferences.java
Update logger defaults 
Fixes: #2457
/cc @devoncarew @quangson91
> Update logger defaults (#2457)

- src/io/flutter/logging/FlutterLogView.java
I make some small refactoring flutter log view
// cc @pq for review.
> a small refactoring flutter log view

- src/io/flutter/module/FlutterModuleBuilder.java
> Validate package org in project creation (#2468)

- src/io/flutter/logging/FlutterLogPopup.java
- src/io/flutter/logging/FlutterLogTree.java
Issue: https://github.com/flutter/flutter-intellij/issues/2452
+ support copy a part of the log.
+ support search with google.
**Note**
To show selected log popup -> user have to double-click to the row.
// @pq, please review when you have time.
Demo:
> support copy a part of the log

- src/io/flutter/logging/FlutterLogEntryPopup.java
- src/io/flutter/logging/FlutterLogTree.java
* class rename
* title tweak "Selected log" => "Log Entry"
/cc @quangson91
> Log Entry popup tweaks

- src/io/flutter/logging/FlutterLogEntry.java
- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Issue: https://github.com/flutter/flutter-intellij/issues/2452
This PR fix problem when user copy log by shortcut (eg: `Ctrl + C` / `CMD + C`)
I fix by register copy shortcut & handle it.
(By default, the system will automatically copy the value of each cell - com.intellij.ui.treeStructure.treetable.ListTreeTableModelOnColumns#getValueAt then passing to the clipboard).
**NOTE**
Currently, when user copy we still copy `invisible` columns.
We should improve that.
See my comments for more detail.
// cc @pq please review on next week!
> Improve Copy / Paste on new Logging View

- analysis_options.yaml
- tool/plugin/analysis_options.yaml
The build is failing. I think this will fix it, but not sure why this causes failure.
> Fix analysis options

- flutter-intellij-community.iml
Minor change to add a new module dependency that resolves compilation errors in AndroidUtils.
@pq
> Update module definition

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
Issue: https://github.com/flutter/flutter-intellij/issues/2487
+ auto-disable scroll to end when user manual scroll log up
// cc @pq, @zoechi 
Screenshot
> auto-disable scroll to end when user manual scroll log up

- cloudbuild.yaml
- tool/cloudbuild.sh
> experiment with cloudbuild

- README.md
- cloudbuild.yaml
- tool/cloudbuild.sh
Experimenting with the new [Cloud Build](https://cloud.google.com/cloud-build/) CI.
> readme and cloudbuild updates

- CHANGELOG.md
- resources/META-INF/plugin.xml
- tool/plugin/pubspec.yaml
- update changelog
- update some dart deps for Dart 2.0.0
> rev to M27

- src/io/flutter/console/FlutterConsoleFilter.java
> Resolve files in `example` dir (#2518).

- src/io/flutter/run/daemon/DaemonApi.java
This doesn't address https://github.com/flutter/flutter-intellij/issues/2332, but does add some more logging details to help us track down the issue the next time its reported.
> add more details to logging output

- src/io/flutter/settings/FlutterSettings.java
This reverts commit b43d9f7fd9d289b65663a2ea2c5ed0efd7120dc5.
> Revert "Enable track widget creation by default. (#2515)"

- flutter-intellij-community.iml
- flutter-studio/src/io/flutter/module/FlutterDescriptionProvider.java
- flutter-studio/src/io/flutter/module/FlutterModuleImporter.java
- flutter-studio/src/io/flutter/module/FlutterModuleModel.java
- flutter-studio/src/io/flutter/module/ImportFlutterModuleStep.form
- flutter-studio/src/io/flutter/module/ImportFlutterModuleStep.java
- flutter-studio/src/io/flutter/project/FlutterProjectSystem.java
- flutter-studio/testSrc/com/android/tools/idea/tests/gui/framework/fixture/IdeaFrameFixture.java
- src/io/flutter/FlutterBundle.properties
- src/io/flutter/module/FlutterProjectType.java
- src/io/flutter/pub/PubRoot.java
- src/io/flutter/utils/System.java
- tool/plugin/lib/plugin.dart
- tool/plugin/pubspec.yaml
Adds UI support for importing Flutter modules into Android apps.
Fixes build issues that arise with AS canary 7 (or maybe 5, not sure when it started).
Fixes plugin tool to work with AS canary 7 and Dart 2.0.
@devoncarew @pq @jwren
> Import module

- flutter-studio/src/io/flutter/project/FlutterProjectCreator.java
- flutter-studio/src/io/flutter/project/FlutterProjectModel.java
- flutter-studio/src/io/flutter/project/FlutterProjectStep.java
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.form
- flutter-studio/src/io/flutter/project/FlutterSettingsStep.java
Fixes a couple issues found by @mravn-google 
1. There should be language choice
2. The package name cannot contain underscores
And one I discovered during testing
1. Existing directories were only detected for apps
> Fix issues in new module UI

- CHANGELOG.md
- resources/META-INF/plugin.xml
> Release 28

- flutter-studio/flutter-studio.iml
@devoncarew @pq @terrylucas
A couple modules were renamed but nothing else affects else.
> Update flutter-studio to Canary 10 sources

- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Code.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/CodeRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/ErrorObj.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/ErrorRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Event.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Frame.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Instance.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/InstanceRef.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Isolate.java
- third_party/vmServiceDrivers/org/dartlang/vm/service/element/Sentinel.java
- fix an issue with an NPE on InstanceRef.getKind()
- fix https://github.com/flutter/flutter-intellij/issues/2578
@jwren
> fix an issue with an NPE on InstanceRef.getKind()

- src/io/flutter/logging/FlutterLogFilterPanel.java
- src/io/flutter/logging/FlutterLogView.java
fixes https://github.com/flutter/flutter-intellij/issues/2576
+ set default filter from preference
@devoncarew please review this PR.
Thanks!
> fix 2576 - set default filter from preference

- src/io/flutter/logging/FlutterLogTree.java
- src/io/flutter/logging/FlutterLogView.java
- src/io/flutter/logging/FlutterTreeTableModel.java
Issue: https://github.com/flutter/flutter-intellij/issues/2403
I implement filtering by `TableRowSorter`.
Demo
See my comments for more detail.
// cc @pq, please take a look!.
> improve flutter logging

- src/io/flutter/logging/FlutterTreeTableModel.java
Follow-up from https://github.com/flutter/flutter-intellij/pull/2416.
/cc @quangson91 @devoncarew
> table model cleanup (nits)

- src/io/flutter/server/vmService/IsolatesInfo.java
- src/io/flutter/server/vmService/frame/DartVmServiceEvaluator.java
Fixes https://github.com/flutter/flutter-intellij/issues/2595
> Avoid NPE when restarting Flutter app.

- src/io/flutter/test/DartTestEventsConverterZ.java
Fixes: #2597.
🤘 
See related PR: https://github.com/dart-lang/test/pull/853/
/cc @jacob314 @DanTup
> Fix flutter test navigation (#2597).

- src/io/flutter/logging/FlutterLogTree.java
Fixes: #2601
/cc @devoncarew @stevemessick 
FYI @quangson91
> fix update counter (#2601).

- src/io/flutter/server/vmService/DartVmServiceDebugProcess.java
- src/io/flutter/server/vmService/VmServiceWrapper.java
- tool/plugin/test/plugin_test.dart
@jacob314 @devoncarew @pq 
- Adds a TODO as a follow-up to a review comment from @jacob314 
- Pops the project window to the top when a breakpoint is hit
> Minor changes to attach debugger

- flutter-studio/src/io/flutter/actions/ConnectAndroidDebuggerAction.java
- src/io/flutter/server/vmService/DartVmServiceDebugProcess.java
- src/io/flutter/server/vmService/VmServiceWrapper.java
- tool/plugin/test/plugin_test.dart
This is a serious bug that needs to be cherry-picked into M29. The original code broke the Attach to Android button for Android projects :(
> Fix attach button for Android projects

- src/io/flutter/sdk/FlutterCommand.java
@pq @jacob314 @devoncarew 
Fixes #2493
> Save files before spawning process

- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/FPSDisplay.java
- src/io/flutter/inspector/HeapDisplay.java
- src/io/flutter/inspector/HeapState.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/perf/VmServiceWidgetPerfProvider.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/server/vmService/FlutterFramesMonitor.java
- src/io/flutter/server/vmService/HeapMonitor.java
- src/io/flutter/server/vmService/VMServiceManager.java
- src/io/flutter/server/vmService/VmServiceWrapper.java
- src/io/flutter/view/FlutterViewMessages.java
- src/io/flutter/view/InspectorMemoryTab.java
- src/io/flutter/view/InspectorPanel.java
- src/io/flutter/view/InspectorPerfTab.java
> Rename perf service

- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/FPSDisplay.java
- src/io/flutter/inspector/HeapDisplay.java
- src/io/flutter/inspector/HeapState.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/perf/FlutterFramesMonitor.java
- src/io/flutter/perf/HeapMonitor.java
- src/io/flutter/perf/PerfService.java
- src/io/flutter/perf/VmServiceWidgetPerfProvider.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/server/vmService/VmServiceWrapper.java
- src/io/flutter/view/FlutterViewMessages.java
- src/io/flutter/view/InspectorMemoryTab.java
- src/io/flutter/view/InspectorPanel.java
- src/io/flutter/view/InspectorPerfTab.java
Need to fix that CL to hit some Android Studio specific files.
This reverts commit 8865a98a93711fa3af6e1599408916be7b0d3ada.
> Revert "Cleanup: rename VMService VMServiceManager and move to io.flutter.server.vmService

- flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java
- flutter-studio/src/io/flutter/profiler/FlutterStudioProfilers.java
- src/io/flutter/inspector/EvalOnDartLibrary.java
- src/io/flutter/inspector/FPSDisplay.java
- src/io/flutter/inspector/HeapDisplay.java
- src/io/flutter/inspector/HeapState.java
- src/io/flutter/inspector/InspectorService.java
- src/io/flutter/logging/FlutterLog.java
- src/io/flutter/logging/FlutterLogEntryParser.java
- src/io/flutter/perf/VmServiceWidgetPerfProvider.java
- src/io/flutter/run/daemon/FlutterApp.java
- src/io/flutter/server/vmService/FlutterFramesMonitor.java
- src/io/flutter/server/vmService/HeapMonitor.java
- src/io/flutter/server/vmService/VMServiceManager.java
- src/io/flutter/server/vmService/VmServiceWrapper.java
- src/io/flutter/view/FlutterViewMessages.java
- src/io/flutter/view/InspectorMemoryTab.java
- src/io/flutter/view/InspectorPanel.java
- src/io/flutter/view/InspectorPerfTab.java
Re-land with trivial refactors in the android studio codebase added.
> Rename perf service 2

- flutter-studio/src/io/flutter/profiler/FlutterAllMemoryData.java
- flutter-studio/src/io/flutter/profiler/FlutterStudioMonitorStageView.java
Fixed redraw of chart on screen to appear smooth as updating and scrolling left on timeline.
Added selection support in preparation of list of memory objects.
Added legend.
Re-organized UI panels for proper Z-order and support for tabular for selection and tooltips (need to be top-most).
> Fixed redraw flicker and added more functionality.
